// ============================================
// Seed ELA Unit 4 — "Perspectives and Justice" (Lessons 1–4)
// ============================================
// Perspective-taking, bias, argument building, communication.
// Run: npx tsx prisma/seed-ela-u4-l1-l4.ts

import { config } from 'dotenv';
config({ path: '.env.local' });
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('⚖️ Seeding ELA Unit 4 "Perspectives and Justice" — L1–L4');

  const lessonDefs = [
    { id: 'g6-ela-u4-l1', title: 'Walking in Others\' Shoes', order: 1, learningGoal: 'Analyze how authors use fiction to develop empathy and explore perspectives different from our own.', successCriteria: 'I can identify the perspective from which a story is told.\nI can explain how a character\'s background shapes their perspective.\nI can compare my perspective with a character\'s to understand a different point of view.', reflectionPrompt: 'Have you ever had an experience where you realized your perspective was different from someone else\'s? What did you learn from it?' },
    { id: 'g6-ela-u4-l2', title: 'Whose Voice Is Missing?', order: 2, learningGoal: 'Identify whose perspectives are included and excluded in texts and media, and analyze how bias and representation shape understanding.', successCriteria: 'I can identify which perspectives are represented in a text and which are missing.\nI can explain how missing perspectives affect the reader\'s understanding.\nI can describe how audience and context influence the way information is presented.', reflectionPrompt: 'Think about a news story or social media post you saw recently. Whose perspective was centered? Whose voice was missing? How might the story change if told from a different viewpoint?' },
    { id: 'g6-ela-u4-l3', title: 'Building Arguments', order: 3, learningGoal: 'Construct a persuasive argument using claims, evidence, and reasoning in a multi-paragraph format.', successCriteria: 'I can write a clear claim statement.\nI can support my claim with at least 2 pieces of evidence.\nI can explain my reasoning — HOW the evidence supports my claim.\nI can organize my argument with an introduction, body, and conclusion.', reflectionPrompt: 'What makes an argument persuasive? Is it the evidence, the reasoning, or the way it\'s delivered? Why?' },
    { id: 'g6-ela-u4-l4', title: 'Effective Communication', order: 4, learningGoal: 'Analyze verbal, non-verbal, and paraverbal communication and understand how these elements affect message delivery.', successCriteria: 'I can define verbal, non-verbal, and paraverbal communication.\nI can identify how body language, tone, and eye contact affect a message.\nI can analyze how communication choices can change the meaning of the same words.', reflectionPrompt: 'Think about a time when HOW something was said mattered more than WHAT was said. What non-verbal or paraverbal cues made the difference?' },
  ];

  for (const l of lessonDefs) {
    await prisma.lesson.upsert({
      where: { id: l.id },
      update: { title: l.title, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
      create: { id: l.id, unitId: 'g6-ela-u4', title: l.title, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
    });
  }
  console.log('✅ Lessons 1–4 upserted');

  for (const l of lessonDefs) {
    await prisma.lessonBlock.deleteMany({ where: { lessonId: l.id } });
    await prisma.quizQuestion.deleteMany({ where: { lessonId: l.id } });
  }

  // L1: Walking in Others' Shoes — TR.2, Review: RC.1, TF.1
  const L1 = 'g6-ela-u4-l1';
  const l1Blocks = [
    { id: 'u4-l1-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Why Perspective Matters</h3><p>Every story is told from a <strong>perspective</strong> — a specific point of view shaped by the character\'s or narrator\'s background, experiences, beliefs, and position in the world.</p><p>When we read from a perspective different from our own, we practice <strong>empathy</strong> — the ability to understand and share the feelings of another person, even if we disagree with them.</p>' } },
    { id: 'u4-l1-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Anchor Text: Two Sides</h3><blockquote style="border-left:3px solid #f59e0b;padding:12px 16px;margin:12px 0;color:#475569"><strong>Jade\'s Perspective</strong><br>"I couldn\'t believe they picked Malik for team captain. I\'ve been on this team for three years. Three years of showing up early, staying late, running extra drills. Malik joined last semester. He\'s athletic, sure — but he doesn\'t know our plays. He doesn\'t know our team. How is it fair that popularity wins over dedication?"</blockquote><blockquote style="border-left:3px solid #3b82f6;padding:12px 16px;margin:12px 0;color:#475569"><strong>Malik\'s Perspective</strong><br>"I didn\'t ask to be captain. When Coach asked me, I almost said no. I know Jade wanted it — I could see it in her face. But Coach said the team voted, and the truth is, I\'ve been trying hard to learn every play, every position. I stay after practice too, but nobody seems to notice. They just see \'the new kid.\' I want to prove I earned this — not just for me, but for the whole team."</blockquote>' } },
    { id: 'u4-l1-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: 'Both Jade and Malik feel:', options: [{ label: 'That the situation is completely fair', value: 'a' }, { label: 'That they have worked hard and their effort isn\'t being recognized', value: 'b', correct: true }, { label: 'Angry at each other', value: 'c' }], explanation: 'Both characters share a core feeling: they want their hard work to be seen. Jade feels overlooked for her dedication; Malik feels reduced to "the new kid." Understanding both perspectives reveals more of the truth than either one alone.' } },
    { id: 'u4-l1-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: '1. How is Jade\'s perspective DIFFERENT from Malik\'s?\n2. How are their perspectives SIMILAR?\n3. Write 3–4 sentences from COACH\'S perspective on this situation. What might Coach be thinking and feeling?\n4. Does understanding BOTH perspectives change how you see the fairness of the decision? Why or why not?', minLength: 50 } },
    { id: 'u4-l1-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Have you ever had an experience where you realized your perspective was very different from someone else\'s? What did you learn from seeing the situation from their side?', minLength: 30 } },
  ];
  for (const b of l1Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L1, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L1: ${l1Blocks.length} blocks`);

  const l1Qs = [
    { id: 'u4-l1-q1', questionText: 'EMPATHY means:', options: [{ label: 'Agreeing with everyone', value: 'a' }, { label: 'The ability to understand and share the feelings of another person', value: 'b', correct: true }, { label: 'Feeling sorry for someone', value: 'c' }, { label: 'Ignoring other people\'s feelings', value: 'd' }], correctAnswer: 'b', explanation: 'Empathy is understanding HOW someone else feels and WHY — even if you don\'t share their experience. It\'s deeper than sympathy (feeling sorry for someone).', outcomeCode: 'ELA.6.TR.2', difficulty: 1 },
    { id: 'u4-l1-q2', questionText: 'A character\'s PERSPECTIVE is shaped by:', options: [{ label: 'Only their age', value: 'a' }, { label: 'Their background, experiences, beliefs, culture, and position in the situation', value: 'b', correct: true }, { label: 'Only their opinion on one topic', value: 'c' }, { label: 'What other characters tell them', value: 'd' }], correctAnswer: 'b', explanation: 'Perspective comes from the whole person — their history, identity, relationships, and context all shape how they see the world.', outcomeCode: 'ELA.6.TR.2', difficulty: 1 },
    { id: 'u4-l1-q3', questionText: 'In the anchor text, Jade says "popularity wins over dedication." You can INFER that Jade believes:', options: [{ label: 'Malik is not athletic', value: 'a' }, { label: 'The team chose Malik because he is likeable, not because of effort or experience', value: 'b', correct: true }, { label: 'She doesn\'t care about being captain', value: 'c' }, { label: 'Coach made the wrong decision for safety reasons', value: 'd' }], correctAnswer: 'b', explanation: 'Jade\'s use of "popularity" vs "dedication" reveals she believes the election was a popularity contest, not a merit-based decision.', outcomeCode: 'ELA.6.RC.1', difficulty: 2 },
    { id: 'u4-l1-q4', questionText: 'Malik says "They just see the new kid." This reveals that:', options: [{ label: 'He is proud of being new', value: 'a' }, { label: 'He feels reduced to a label and wants to be seen for his effort, not just his newness', value: 'b', correct: true }, { label: 'He thinks being new is an advantage', value: 'c' }, { label: 'He wants to leave the team', value: 'd' }], correctAnswer: 'b', explanation: 'Malik wants to be recognized for his hard work, not dismissed with a label. This mirrors Jade\'s feeling of being unseen — both want recognition.', outcomeCode: 'ELA.6.TR.2', difficulty: 2 },
    { id: 'u4-l1-q5', questionText: 'Reading the SAME EVENT from two different perspectives helps readers:', options: [{ label: 'Pick which character is right', value: 'a' }, { label: 'Understand that situations are more complex than they appear from one side', value: 'b', correct: true }, { label: 'Decide the story is confusing', value: 'c' }, { label: 'Choose a favourite character', value: 'd' }], correctAnswer: 'b', explanation: 'Multiple perspectives reveal complexity. Neither Jade nor Malik is entirely "right" or "wrong" — understanding both gives a fuller picture of the truth.', outcomeCode: 'ELA.6.TR.2', difficulty: 1 },
    { id: 'u4-l1-q6', questionText: 'The conflict in the anchor text is primarily:', options: [{ label: 'Person vs Nature', value: 'a' }, { label: 'Person vs Person — two characters with different views on fairness', value: 'b', correct: true }, { label: 'Person vs Society', value: 'c' }, { label: 'There is no conflict', value: 'd' }], correctAnswer: 'b', explanation: 'The core conflict is between Jade and Malik\'s competing claims to the captaincy. Each feels their effort deserves recognition.', outcomeCode: 'ELA.6.TF.1', difficulty: 1 },
    { id: 'u4-l1-q7', questionText: 'If an author only told this story from Jade\'s perspective, the reader would likely:', options: [{ label: 'Have a complete understanding of the situation', value: 'a' }, { label: 'Side with Jade and not see Malik\'s effort or feelings', value: 'b', correct: true }, { label: 'Not care about either character', value: 'c' }, { label: 'Understand both characters equally', value: 'd' }], correctAnswer: 'b', explanation: 'A single perspective creates bias. Without Malik\'s side, readers would only see Jade\'s frustration and might assume Malik didn\'t deserve the role.', outcomeCode: 'ELA.6.TR.2', difficulty: 2 },
    { id: 'u4-l1-q8', questionText: 'The BEST reason to practice perspective-taking is:', options: [{ label: 'To always agree with others', value: 'a' }, { label: 'To develop deeper understanding of people and situations, even when we disagree', value: 'b', correct: true }, { label: 'To win arguments', value: 'c' }, { label: 'To change your own opinion', value: 'd' }], correctAnswer: 'b', explanation: 'Perspective-taking builds understanding and empathy. You don\'t have to agree with someone to understand WHY they feel the way they do.', outcomeCode: 'ELA.6.TR.2', difficulty: 1 },
  ];
  for (const q of l1Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L1, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L1: ${l1Qs.length} questions`);

  // L2: Whose Voice Is Missing? — TR.3, Review: RC.2, TF.3
  const L2 = 'g6-ela-u4-l2';
  const l2Blocks = [
    { id: 'u4-l2-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Representation and Missing Voices</h3><p>Every text, news story, or social media post makes choices about <strong>whose voice is heard</strong> and whose voice is <em>left out</em>.</p><p>When certain perspectives are consistently missing, it can:</p><ul><li>Create an incomplete or misleading picture</li><li>Make some groups feel invisible or unimportant</li><li>Reinforce stereotypes by only showing one version of a group\'s experience</li></ul><p>Critical readers ask: <strong>"Who is speaking? Who is not? What might change if we heard from the missing voices?"</strong></p>' } },
    { id: 'u4-l2-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>How Context and Audience Shape Information</h3><p>The same event can be reported very differently depending on:</p><ul><li><strong>Who is telling it</strong> (which publication, which person)</li><li><strong>Who they are telling it TO</strong> (the audience)</li><li><strong>What their purpose is</strong> (inform, persuade, entertain, sell)</li><li><strong>What context surrounds it</strong> (political climate, cultural moment)</li></ul><p>Example: A new school policy banning phones could be reported as:</p><ul><li>A parent-focused article: "Parents applaud phone-free classrooms"</li><li>A student-focused article: "Students protest new phone ban"</li><li>A teacher-focused article: "Teachers report improved focus after phone ban"</li></ul><p>Same event, three very different stories.</p>' } },
    { id: 'u4-l2-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: 'If a news article about a school phone ban ONLY interviews parents, the missing perspectives are:', options: [{ label: 'Parents', value: 'a' }, { label: 'Students, teachers, and administrators — their experiences are not represented', value: 'b', correct: true }, { label: 'Nobody is missing — parents are enough', value: 'c' }], explanation: 'Students experience the ban directly. Teachers implement it. Administrators designed it. Without these voices, the story shows only one perspective.' } },
    { id: 'u4-l2-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Choose a real topic (school dress codes, homework policies, social media age restrictions, etc.).\n\n1. Write 2–3 sentences from ONE perspective (e.g., a student)\n2. Write 2–3 sentences from a DIFFERENT perspective (e.g., a parent or teacher)\n3. Whose voice is OFTEN MISSING from this conversation? Why might their perspective matter?\n4. How does the AUDIENCE change what gets emphasized?', minLength: 50 } },
    { id: 'u4-l2-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Think about a news story or social media post you saw recently. Whose perspective was centered? Whose voice was missing? How might the story change if told from a different viewpoint?', minLength: 30 } },
  ];
  for (const b of l2Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L2, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L2: ${l2Blocks.length} blocks`);

  const l2Qs = [
    { id: 'u4-l2-q1', questionText: '"Representation" in texts and media refers to:', options: [{ label: 'How long the text is', value: 'a' }, { label: 'Whose voices, experiences, and perspectives are included or excluded', value: 'b', correct: true }, { label: 'How many pictures are included', value: 'c' }, { label: 'The font used', value: 'd' }], correctAnswer: 'b', explanation: 'Representation is about WHO is visible and heard. When groups are consistently excluded, it shapes how we understand the world.', outcomeCode: 'ELA.6.TR.3', difficulty: 1 },
    { id: 'u4-l2-q2', questionText: 'A "missing voice" in a text means:', options: [{ label: 'Someone who cannot speak', value: 'a' }, { label: 'A perspective or group that is not represented in the text', value: 'b', correct: true }, { label: 'A character who whispers', value: 'c' }, { label: 'An audio that doesn\'t play', value: 'd' }], correctAnswer: 'b', explanation: 'When a text discusses an issue but leaves out a key group\'s perspective, that is a "missing voice." Critical readers notice and question this.', outcomeCode: 'ELA.6.TR.3', difficulty: 1 },
    { id: 'u4-l2-q3', questionText: 'The same school phone ban reported differently for parents vs students shows that:', options: [{ label: 'One article is wrong', value: 'a' }, { label: 'Audience and context shape how information is presented', value: 'b', correct: true }, { label: 'The event happened twice', value: 'c' }, { label: 'All articles are the same', value: 'd' }], correctAnswer: 'b', explanation: 'The audience determines what the writer emphasizes. A parent audience gets parent-aligned framing; a student audience gets student concerns.', outcomeCode: 'ELA.6.TR.3', difficulty: 1 },
    { id: 'u4-l2-q4', questionText: 'When one group\'s perspective is consistently LEFT OUT of media, it can:', options: [{ label: 'Have no effect', value: 'a' }, { label: 'Reinforce stereotypes and make that group feel invisible', value: 'b', correct: true }, { label: 'Make the media more accurate', value: 'c' }, { label: 'Improve representation', value: 'd' }], correctAnswer: 'b', explanation: 'Consistent exclusion creates an incomplete picture of the world. People from excluded groups may feel unrepresented, and audiences may develop stereotyped understanding.', outcomeCode: 'ELA.6.TR.3', difficulty: 2 },
    { id: 'u4-l2-q5', questionText: 'Think about the soil article from Unit 3. A non-fiction analysis would note that the article INCLUDES the perspective of:', options: [{ label: 'Only farmers', value: 'a' }, { label: 'A soil scientist (Dr. Patel) — but does NOT include farmers\' or Indigenous perspectives on land', value: 'b', correct: true }, { label: 'All perspectives equally', value: 'c' }, { label: 'Only politicians', value: 'd' }], correctAnswer: 'b', explanation: 'The soil article quotes a scientist but doesn\'t include farmers who actually work the land, or Indigenous perspectives on soil relationships. Noticing what\'s missing is a critical reading skill.', outcomeCode: 'ELA.6.TF.3', difficulty: 2 },
    { id: 'u4-l2-q6', questionText: 'A critical reader should always ask:', options: [{ label: '"Is this text entertaining?"', value: 'a' }, { label: '"Who is speaking, who is not, and how might the story change with different perspectives?"', value: 'b', correct: true }, { label: '"Is the text long enough?"', value: 'c' }, { label: '"Do I agree with the text?"', value: 'd' }], correctAnswer: 'b', explanation: 'Critical reading means questioning representation, bias, missing voices, and how audience/context shape the message — not just whether you agree.', outcomeCode: 'ELA.6.TR.3', difficulty: 1 },
    { id: 'u4-l2-q7', questionText: 'A text-to-world connection involves:', options: [{ label: 'Connecting the text to your personal life', value: 'a' }, { label: 'Connecting the text to what you know about the world, society, or current events', value: 'b', correct: true }, { label: 'Connecting the text to another text', value: 'c' }, { label: 'Connecting the text to a movie', value: 'd' }], correctAnswer: 'b', explanation: 'Text-to-world connections link what you read to broader issues in society, politics, or the community — this is where perspective-taking meets real life.', outcomeCode: 'ELA.6.RC.2', difficulty: 1 },
    { id: 'u4-l2-q8', questionText: 'The AUTHOR\'S PURPOSE shapes a text because:', options: [{ label: 'It doesn\'t affect the text at all', value: 'a' }, { label: 'An author writing to persuade may select different evidence than one writing to inform', value: 'b', correct: true }, { label: 'All authors have the same purpose', value: 'c' }, { label: 'Purpose only matters in fiction', value: 'd' }], correctAnswer: 'b', explanation: 'Purpose determines what information is included, how it\'s framed, and what\'s emphasized. A persuasive text selectively includes evidence that supports its position.', outcomeCode: 'ELA.6.TR.3', difficulty: 2 },
  ];
  for (const q of l2Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L2, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L2: ${l2Qs.length} questions`);

  // L3: Building Arguments — WC.6, TF.4, Review: TR.1, WC.2
  const L3 = 'g6-ela-u4-l3';
  const l3Blocks = [
    { id: 'u4-l3-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>From Opinions to Arguments</h3><p>An <strong>opinion</strong> is how you feel about something. An <strong>argument</strong> is a structured position supported by <strong>evidence</strong> and <strong>reasoning</strong>.</p><ul><li>❌ Opinion: "Homework is stupid." (no evidence, no reasoning)</li><li>✅ Argument: "Schools should reduce homework for Grades 4–6 because research shows that excessive homework increases stress without improving academic outcomes for elementary students." (claim + evidence + reasoning)</li></ul>' } },
    { id: 'u4-l3-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Argument Structure</h3><ol><li><strong>Claim:</strong> Your position stated clearly. "Schools should [do this] because [reason]."</li><li><strong>Evidence:</strong> Facts, data, examples, or expert quotes that support your claim.</li><li><strong>Reasoning:</strong> Your explanation of WHY the evidence supports your claim.</li><li><strong>Counterargument (optional but strong):</strong> Acknowledge the opposing view and explain why your position is still stronger.</li></ol><p>This builds on the C-E-E model from Unit 3 — the difference is that now you are <em>persuading</em>, not just <em>informing</em>.</p>' } },
    { id: 'u4-l3-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: 'What makes an argument STRONGER than a simple opinion?', options: [{ label: 'Speaking louder', value: 'a' }, { label: 'Supporting the claim with evidence and explaining the reasoning', value: 'b', correct: true }, { label: 'Repeating the opinion more times', value: 'c' }], explanation: 'Arguments are structured: claim + evidence + reasoning. Opinions are unsupported preferences. The evidence and reasoning transform an opinion into a persuasive argument.' } },
    { id: 'u4-l3-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Choose ONE of these topics (or propose your own):\n- Should students have a say in school rules?\n- Should recess be longer for Grade 6?\n- Should schools teach coding as a core subject?\n\n1. Write a clear CLAIM (1 sentence)\n2. Provide 2 pieces of EVIDENCE (facts, examples, or reasoning)\n3. Write a 2–3 sentence EXPLANATION of why each piece of evidence supports your claim\n4. Write a COUNTERARGUMENT: What might someone who disagrees say? Why is your position still stronger?', minLength: 60 } },
    { id: 'u4-l3-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'What makes an argument persuasive? Is it the evidence, the reasoning, the way it\'s delivered, or something else? What did you learn about your own argument-building skills today?', minLength: 30 } },
  ];
  for (const b of l3Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L3, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L3: ${l3Blocks.length} blocks`);

  const l3Qs = [
    { id: 'u4-l3-q1', questionText: 'The difference between an OPINION and an ARGUMENT is:', options: [{ label: 'They are the same thing', value: 'a' }, { label: 'An argument is supported by evidence and reasoning; an opinion is a personal feeling without support', value: 'b', correct: true }, { label: 'Arguments are always about politics', value: 'c' }, { label: 'Opinions are stronger than arguments', value: 'd' }], correctAnswer: 'b', explanation: 'Arguments are structured (claim + evidence + reasoning). Opinions are personal preferences without evidence ("I think it\'s bad").', outcomeCode: 'ELA.6.WC.6', difficulty: 1 },
    { id: 'u4-l3-q2', questionText: 'A CLAIM in an argument is:', options: [{ label: 'Evidence from a source', value: 'a' }, { label: 'Your clear position or statement about the topic', value: 'b', correct: true }, { label: 'A question', value: 'c' }, { label: 'A counterargument', value: 'd' }], correctAnswer: 'b', explanation: 'The claim is your thesis — the clear statement of what you believe and will argue for, supported by evidence and reasoning.', outcomeCode: 'ELA.6.WC.6', difficulty: 1 },
    { id: 'u4-l3-q3', questionText: 'A COUNTERARGUMENT in a persuasive essay:', options: [{ label: 'Weakens your own argument', value: 'a' }, { label: 'Acknowledges the opposing view and then explains why your position is still stronger', value: 'b', correct: true }, { label: 'Should be avoided', value: 'c' }, { label: 'Agrees with the other side', value: 'd' }], correctAnswer: 'b', explanation: 'Addressing counterarguments STRENGTHENS your argument. It shows you understand the issue from multiple perspectives and can still defend your position.', outcomeCode: 'ELA.6.WC.6', difficulty: 2 },
    { id: 'u4-l3-q4', questionText: 'What type of organizational structure does a persuasive argument use?', options: [{ label: 'Chronological order', value: 'a' }, { label: 'Claim → Evidence → Reasoning → Counterargument → Conclusion', value: 'b', correct: true }, { label: 'Description only', value: 'c' }, { label: 'Random order', value: 'd' }], correctAnswer: 'b', explanation: 'Persuasive writing follows a specific structure: state your position → support it → address opposition → conclude with strength.', outcomeCode: 'ELA.6.TF.4', difficulty: 1 },
    { id: 'u4-l3-q5', questionText: '"Research shows that excessive homework increases stress without improving academic outcomes." This sentence provides:', options: [{ label: 'An opinion', value: 'a' }, { label: 'EVIDENCE — it references research findings that can be verified', value: 'b', correct: true }, { label: 'A counterargument', value: 'c' }, { label: 'A reflection', value: 'd' }], correctAnswer: 'b', explanation: 'This cites research as evidence. It\'s verifiable and specific, which gives the argument credibility.', outcomeCode: 'ELA.6.TR.1', difficulty: 1 },
    { id: 'u4-l3-q6', questionText: 'The REASONING in an argument serves to:', options: [{ label: 'Just repeat the evidence', value: 'a' }, { label: 'Explain WHY the evidence supports the claim — connecting proof to position', value: 'b', correct: true }, { label: 'Change the topic', value: 'c' }, { label: 'Introduce a new claim', value: 'd' }], correctAnswer: 'b', explanation: 'Reasoning is the bridge between evidence and claim. It answers: "So what? Why does this evidence matter for my position?"', outcomeCode: 'ELA.6.WC.6', difficulty: 2 },
    { id: 'u4-l3-q7', questionText: 'A multi-paragraph argument should be organized with:', options: [{ label: 'Only one long paragraph', value: 'a' }, { label: 'Introduction (claim), body paragraphs (evidence + reasoning), and conclusion', value: 'b', correct: true }, { label: 'Just bullet points', value: 'c' }, { label: 'Random thoughts in any order', value: 'd' }], correctAnswer: 'b', explanation: 'Like research reports, arguments follow intro → body → conclusion. Each body paragraph should have focused evidence that supports the overall claim.', outcomeCode: 'ELA.6.WC.2', difficulty: 1 },
    { id: 'u4-l3-q8', questionText: 'Which evidence is STRONGEST for the claim "Schools should offer more outdoor learning time"?', options: [{ label: '"I think being outside is fun."', value: 'a' }, { label: '"A 2023 study from the University of British Columbia found that students who spent 30+ minutes outdoors daily showed a 15% improvement in focus and a 20% reduction in reported stress."', value: 'b', correct: true }, { label: '"Everyone agrees outside is better."', value: 'c' }, { label: '"My friend likes it outside."', value: 'd' }], correctAnswer: 'b', explanation: 'Option B is strongest because it cites a specific study with measurable results. Personal opinions and vague generalizations are weak evidence.', outcomeCode: 'ELA.6.TR.1', difficulty: 2 },
  ];
  for (const q of l3Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L3, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L3: ${l3Qs.length} questions`);

  // L4: Effective Communication — OC.2, Review: OC.3
  const L4 = 'g6-ela-u4-l4';
  const l4Blocks = [
    { id: 'u4-l4-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Three Channels of Communication</h3><p>When we communicate, we use THREE channels at the same time, and they all carry meaning:</p><ul><li><strong>Verbal:</strong> The actual WORDS you say. "I\'m fine."</li><li><strong>Non-verbal:</strong> Your BODY LANGUAGE — gestures, posture, facial expressions, eye contact. Arms crossed, looking away.</li><li><strong>Paraverbal:</strong> HOW you say it — tone, pitch, volume, speed. Flat tone, sigh.</li></ul><p>The same words can mean completely different things depending on non-verbal and paraverbal cues:</p><ul><li>"I\'m <em>fine</em>." (warm smile, relaxed posture) = genuinely fine</li><li>"I\'m <em>fine</em>." (eye roll, arms crossed, flat voice) = definitely NOT fine</li></ul>' } },
    { id: 'u4-l4-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Why This Matters for Writing and Speaking</h3><p>In <strong>writing</strong>, you don\'t have non-verbal or paraverbal cues — which is why word choice, punctuation, and tone are so important. "Fine." vs "Fine!" vs "Fine..." all feel completely different.</p><p>In <strong>speaking</strong>, your body language and tone often carry MORE weight than your words. Research suggests that up to 93% of communication is non-verbal and paraverbal.</p><p>Effective communicators <strong>align</strong> all three channels — their words, body language, and tone all send the same message.</p>' } },
    { id: 'u4-l4-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: '"Thank you SO much." (said with a sigh and rolling eyes). The non-verbal and paraverbal cues suggest:', options: [{ label: 'Genuine gratitude', value: 'a' }, { label: 'Sarcasm — the speaker does NOT actually mean "thank you"', value: 'b', correct: true }, { label: 'Excitement', value: 'c' }], explanation: 'The words say "thank you" but the sigh (paraverbal) and eye roll (non-verbal) contradict the verbal message. This is sarcasm — the body and tone overrule the words.' } },
    { id: 'u4-l4-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: '1. Write the sentence "I didn\'t say she stole the book" THREE times, each time emphasizing a DIFFERENT word (use CAPS or bold). How does the meaning change each time?\n\n2. Describe a situation where someone\'s BODY LANGUAGE contradicted their WORDS. What happened? Which message was "true" — the words or the body language?\n\n3. How does understanding non-verbal communication make you a BETTER communicator?', minLength: 50 } },
    { id: 'u4-l4-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Think about a time when HOW something was said mattered more than WHAT was said. What non-verbal or paraverbal cues made the difference?', minLength: 30 } },
  ];
  for (const b of l4Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L4, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L4: ${l4Blocks.length} blocks`);

  const l4Qs = [
    { id: 'u4-l4-q1', questionText: 'PARAVERBAL communication refers to:', options: [{ label: 'The words you say', value: 'a' }, { label: 'HOW you say it — tone, pitch, volume, and speed', value: 'b', correct: true }, { label: 'Your body language', value: 'c' }, { label: 'Written text', value: 'd' }], correctAnswer: 'b', explanation: 'Paraverbal = alongside (para) the words (verbal). It\'s the way your voice delivers the words — tone, pitch, volume, speed, pauses.', outcomeCode: 'ELA.6.OC.2', difficulty: 1 },
    { id: 'u4-l4-q2', questionText: 'NON-VERBAL communication includes:', options: [{ label: 'The words you write', value: 'a' }, { label: 'Gestures, posture, facial expressions, and eye contact', value: 'b', correct: true }, { label: 'Your vocabulary choices', value: 'c' }, { label: 'Grammar rules', value: 'd' }], correctAnswer: 'b', explanation: 'Non-verbal communication is everything your BODY does: facial expressions, gestures, posture, proximity, eye contact.', outcomeCode: 'ELA.6.OC.2', difficulty: 1 },
    { id: 'u4-l4-q3', questionText: 'If someone says "I\'m fine" with crossed arms and a flat voice, the communication is:', options: [{ label: 'Consistent — all three channels agree', value: 'a' }, { label: 'Inconsistent — the non-verbal and paraverbal cues contradict the verbal message', value: 'b', correct: true }, { label: 'Only verbal', value: 'c' }, { label: 'Not communicating at all', value: 'd' }], correctAnswer: 'b', explanation: 'The words say "fine" but the body (crossed arms) and voice (flat tone) say "not fine." When channels conflict, people tend to trust non-verbal over verbal.', outcomeCode: 'ELA.6.OC.2', difficulty: 1 },
    { id: 'u4-l4-q4', questionText: 'Research suggests that up to 93% of communication is:', options: [{ label: 'Verbal — the words themselves', value: 'a' }, { label: 'Non-verbal and paraverbal — body language and tone', value: 'b', correct: true }, { label: 'Written text', value: 'c' }, { label: 'Digital (texting)', value: 'd' }], correctAnswer: 'b', explanation: 'Most communication is carried by HOW you say something (paraverbal) and what your BODY does (non-verbal). Words alone are only part of the message.', outcomeCode: 'ELA.6.OC.2', difficulty: 1 },
    { id: 'u4-l4-q5', questionText: 'In WRITING, we compensate for the lack of non-verbal and paraverbal cues by using:', options: [{ label: 'Nothing — writing needs no compensation', value: 'a' }, { label: 'Word choice, punctuation, and tone to convey meaning and emotion', value: 'b', correct: true }, { label: 'Only capital letters', value: 'c' }, { label: 'Emojis in all writing', value: 'd' }], correctAnswer: 'b', explanation: '"Fine." vs "Fine!" vs "Fine..." — punctuation creates different tones in writing. Word choice and sentence structure also convey emotion without body language.', outcomeCode: 'ELA.6.OC.2', difficulty: 2 },
    { id: 'u4-l4-q6', questionText: 'Emphasizing DIFFERENT words in the same sentence changes the meaning. "I didn\'t say SHE stole the book" implies:', options: [{ label: 'Nobody stole the book', value: 'a' }, { label: 'Someone else stole the book — not HER', value: 'b', correct: true }, { label: 'The speaker definitely said it', value: 'c' }, { label: 'The book was not stolen', value: 'd' }], correctAnswer: 'b', explanation: 'Emphasizing "SHE" shifts focus to the person — "I didn\'t say SHE stole it" implies it was someone else. Emphasis (a paraverbal tool) changes meaning entirely.', outcomeCode: 'ELA.6.OC.2', difficulty: 2 },
    { id: 'u4-l4-q7', questionText: 'Active listening in collaborative discussion requires:', options: [{ label: 'Thinking about what you will say next', value: 'a' }, { label: 'Making eye contact, nodding, asking follow-up questions, and giving the speaker your full attention', value: 'b', correct: true }, { label: 'Only hearing the words', value: 'c' }, { label: 'Interrupting with your ideas', value: 'd' }], correctAnswer: 'b', explanation: 'Active listening involves both verbal (follow-up questions) and non-verbal (eye contact, nodding) engagement. It shows respect and deepens understanding.', outcomeCode: 'ELA.6.OC.3', difficulty: 1 },
    { id: 'u4-l4-q8', questionText: 'SARCASM is an example of:', options: [{ label: 'All three channels being consistent', value: 'a' }, { label: 'Non-verbal and paraverbal cues intentionally CONTRADICTING the verbal message', value: 'b', correct: true }, { label: 'Strong communication', value: 'c' }, { label: 'The absence of communication', value: 'd' }], correctAnswer: 'b', explanation: 'Sarcasm relies on the listener recognizing that the tone/body language contradicts the words. "Great job!" (eye roll) = the verbal and non-verbal are deliberately mismatched.', outcomeCode: 'ELA.6.OC.2', difficulty: 2 },
  ];
  for (const q of l4Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L4, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L4: ${l4Qs.length} questions`);

  console.log(`\n╔═══════════════════════════════════════════════╗\n║   ELA UNIT 4 (L1–L4) SEED COMPLETE          ║\n╠═══════════════════════════════════════════════╣\n║ Lessons:    4                                ║\n║ Blocks:     ${String(l1Blocks.length + l2Blocks.length + l3Blocks.length + l4Blocks.length).padStart(2)}                               ║\n║ Questions:  ${String(l1Qs.length + l2Qs.length + l3Qs.length + l4Qs.length).padStart(2)}                               ║\n╚═══════════════════════════════════════════════╝`);
}

main()
  .catch((e) => { console.error('❌ Seed error:', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); pool.end(); });
