// ============================================
// Seed ELA Unit 5 — "Wonder, Discovery, and Imagination" (Lessons 5–8)
// ============================================
// Speaking with power, writing poetry, creative performance, wonder showcase.
// Run: npx tsx prisma/seed-ela-u5-l5-l8.ts

import { config } from 'dotenv';
config({ path: '.env.local' });
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🌿 Seeding ELA Unit 5 "Wonder, Discovery, and Imagination" — L5–L8');

  const lessonDefs = [
    { id: 'g6-ela-u5-l5', title: 'Speaking With Power', order: 5, learningGoal: 'Explore the elements of rhetoric and public speaking, including structure, delivery, and audience engagement.', successCriteria: 'I can identify the elements of effective rhetoric.\nI can analyze how a speaker engages an audience.\nI can practice delivery techniques (pacing, emphasis, pausing).', reflectionPrompt: 'What makes a speech memorable? Think of a speech or presentation you remember — what made it stick with you?' },
    { id: 'g6-ela-u5-l6', title: 'Writing Poetry', order: 6, learningGoal: 'Craft original poems using voice, imagery, figurative language, and intentional structure.', successCriteria: 'I can write an original poem using at least 3 figurative language techniques.\nI can make intentional choices about structure (line breaks, stanzas).\nI can develop my own poetic voice.', reflectionPrompt: 'How did writing your own poem change the way you think about reading poetry? What surprised you about the process?' },
    { id: 'g6-ela-u5-l7', title: 'Creative Performance', order: 7, learningGoal: 'Prepare a dramatic reading or spoken word performance, applying delivery skills to bring writing to life.', successCriteria: 'I can prepare a text for dramatic reading with appropriate emphasis and pacing.\nI can use voice, gesture, and eye contact to enhance performance.\nI can give and receive constructive feedback on creative performances.', reflectionPrompt: 'How does performing a poem or dramatic piece change the way you understand it? What is added by the human voice that reading silently cannot capture?' },
    { id: 'g6-ela-u5-l8', title: 'Wonder Showcase', order: 8, learningGoal: 'Perform original creative work for an audience and reflect on creative growth throughout the unit.', successCriteria: 'I can perform my original poem or creative piece with confidence and expression.\nI can give specific peer feedback using the Glow/Grow/Question protocol.\nI can reflect on my growth as a creative writer and speaker.', reflectionPrompt: 'How has your understanding of imagination, creativity, and expression grown during this unit? What will you take with you?' },
  ];

  for (const l of lessonDefs) {
    await prisma.lesson.upsert({
      where: { id: l.id },
      update: { title: l.title, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
      create: { id: l.id, unitId: 'g6-ela-u5', title: l.title, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
    });
  }
  console.log('✅ Lessons 5–8 upserted');

  for (const l of lessonDefs) {
    await prisma.lessonBlock.deleteMany({ where: { lessonId: l.id } });
    await prisma.quizQuestion.deleteMany({ where: { lessonId: l.id } });
  }

  // L5: Speaking With Power — OC.5, Review: OC.2, OC.4
  const L5 = 'g6-ela-u5-l5';
  const l5Blocks = [
    { id: 'u5-l5-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>The Art of Public Speaking</h3><p>Great speakers don\'t just say words — they <em>move</em> people. Whether it\'s a speech, a spoken word poem, or a classroom presentation, effective public speaking combines:</p><ul><li><strong>Content:</strong> What you say (your ideas, evidence, imagery)</li><li><strong>Structure:</strong> How you organize it (beginning, middle, end)</li><li><strong>Delivery:</strong> How you say it (voice, body, energy)</li></ul>' } },
    { id: 'u5-l5-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Rhetorical Techniques</h3><ul><li><strong>Rhetorical question:</strong> A question asked for effect, not expecting an answer. "Can we really afford to wait?"</li><li><strong>Rule of three:</strong> Grouping ideas in threes for impact. "Government of the people, by the people, for the people."</li><li><strong>Anaphora:</strong> Repeating a phrase at the start of consecutive sentences. "I have a dream..." (Martin Luther King Jr.)</li><li><strong>Pause:</strong> Strategic silence that lets an idea land. "We choose to go to the moon. [pause] Not because it is easy... but because it is hard."</li></ul>' } },
    { id: 'u5-l5-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: '"We came. We saw. We conquered." is an example of:', options: [{ label: 'A rhetorical question', value: 'a' }, { label: 'The RULE OF THREE — three short, powerful phrases for maximum impact', value: 'b', correct: true }, { label: 'A pause', value: 'c' }], explanation: 'Three parallel phrases create rhythm, memorability, and punch. This is one of the oldest and most effective rhetorical techniques.' } },
    { id: 'u5-l5-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: '1. Write a RHETORICAL QUESTION about a topic you care about.\n2. Write a RULE OF THREE sentence about why reading matters.\n3. Write 3 lines using ANAPHORA (repeating the same phrase at the start): "I believe..."\n4. Mark where you would add a PAUSE in this sentence for maximum effect: "Every child deserves to feel safe at school — every single one."', minLength: 40 } },
    { id: 'u5-l5-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'What makes a speech memorable? Think of a speech, presentation, or spoken word performance you remember — what made it stick with you?', minLength: 30 } },
  ];
  for (const b of l5Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L5, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L5: ${l5Blocks.length} blocks`);

  const l5Qs = [
    { id: 'u5-l5-q1', questionText: 'A RHETORICAL QUESTION is:', options: [{ label: 'A question that requires a written answer', value: 'a' }, { label: 'A question asked for effect, not expecting an actual answer', value: 'b', correct: true }, { label: 'A question on a quiz', value: 'c' }, { label: 'A question that has no answer', value: 'd' }], correctAnswer: 'b', explanation: 'Rhetorical questions engage the audience by making them think. "Can we really afford to wait?" implies "no" without saying it.', outcomeCode: 'ELA.6.OC.5', difficulty: 1 },
    { id: 'u5-l5-q2', questionText: 'The RULE OF THREE creates impact by:', options: [{ label: 'Using three paragraphs', value: 'a' }, { label: 'Grouping ideas, words, or phrases in threes for rhythm and memorability', value: 'b', correct: true }, { label: 'Repeating three times', value: 'c' }, { label: 'Speaking for three minutes', value: 'd' }], correctAnswer: 'b', explanation: '"Life, liberty, and the pursuit of happiness" — three concepts create a complete, satisfying rhythm that audiences remember.', outcomeCode: 'ELA.6.OC.5', difficulty: 1 },
    { id: 'u5-l5-q3', questionText: 'ANAPHORA is:', options: [{ label: 'A type of poem', value: 'a' }, { label: 'Repeating a phrase at the START of consecutive sentences for emphasis', value: 'b', correct: true }, { label: 'Speaking quietly', value: 'c' }, { label: 'A sound device', value: 'd' }], correctAnswer: 'b', explanation: '"I have a dream..." repeated creates building momentum. Each repetition adds a new idea while the phrase creates unity and rhythm.', outcomeCode: 'ELA.6.OC.5', difficulty: 1 },
    { id: 'u5-l5-q4', questionText: 'A strategic PAUSE in a speech:', options: [{ label: 'Shows the speaker forgot their lines', value: 'a' }, { label: 'Lets an important idea land and gives the audience time to absorb it', value: 'b', correct: true }, { label: 'Is always a mistake', value: 'c' }, { label: 'Should be avoided', value: 'd' }], correctAnswer: 'b', explanation: 'Pauses are powerful. Silence after a key point creates weight and emphasis. Great speakers use pauses intentionally.', outcomeCode: 'ELA.6.OC.5', difficulty: 2 },
    { id: 'u5-l5-q5', questionText: 'Effective public speaking combines:', options: [{ label: 'Only reading from notes', value: 'a' }, { label: 'Strong content, clear structure, and purposeful delivery (voice + body + energy)', value: 'b', correct: true }, { label: 'Speaking as fast as possible', value: 'c' }, { label: 'Only memorization', value: 'd' }], correctAnswer: 'b', explanation: 'All three elements work together: WHAT you say (content), HOW you organize it (structure), and HOW you deliver it (voice, body, connection).', outcomeCode: 'ELA.6.OC.5', difficulty: 1 },
    { id: 'u5-l5-q6', questionText: 'Understanding verbal, non-verbal, and paraverbal cues (from Unit 4) helps public speakers because:', options: [{ label: 'It doesn\'t help', value: 'a' }, { label: 'Aligning all three channels makes the message clear, credible, and emotionally engaging', value: 'b', correct: true }, { label: 'Only words matter', value: 'c' }, { label: 'Body language is distracting', value: 'd' }], correctAnswer: 'b', explanation: 'A speaker whose voice, body, and words all align is more believable and impactful than one who reads flatly from a paper.', outcomeCode: 'ELA.6.OC.2', difficulty: 2 },
    { id: 'u5-l5-q7', questionText: 'Adapting a speech for a specific audience requires:', options: [{ label: 'Using the same speech for everyone', value: 'a' }, { label: 'Choosing language, examples, and tone that connect with who you are speaking to', value: 'b', correct: true }, { label: 'Using the most complex vocabulary possible', value: 'c' }, { label: 'Ignoring the audience', value: 'd' }], correctAnswer: 'b', explanation: 'Audience awareness — a skill from Unit 4 — means tailoring your content and delivery to your specific listeners.', outcomeCode: 'ELA.6.OC.4', difficulty: 2 },
    { id: 'u5-l5-q8', questionText: '"Can we really stand by and do nothing? Can we look our children in the eye and say we didn\'t try?" These are examples of:', options: [{ label: 'Evidence from a study', value: 'a' }, { label: 'RHETORICAL QUESTIONS — asked for effect to engage the audience emotionally', value: 'b', correct: true }, { label: 'Stage directions', value: 'c' }, { label: 'Literal questions requiring answers', value: 'd' }], correctAnswer: 'b', explanation: 'These questions don\'t expect an answer — they provoke emotion and make the audience feel the urgency. That\'s pathos + rhetoric.', outcomeCode: 'ELA.6.OC.5', difficulty: 2 },
  ];
  for (const q of l5Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L5, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L5: ${l5Qs.length} questions`);

  // L6: Writing Poetry — TF.5, WC.4, Review: VL.2, WC.1
  const L6 = 'g6-ela-u5-l6';
  const l6Blocks = [
    { id: 'u5-l6-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>From Reader to Writer</h3><p>You\'ve read poetry, analyzed figurative language, and explored how structure creates meaning. Now it\'s your turn to WRITE.</p><p><strong>Writing poetry is about:</strong></p><ul><li>Saying something REAL in a way that is VIVID</li><li>Making intentional choices about every word, every line break, every image</li><li>Finding YOUR voice — not copying someone else\'s</li></ul>' } },
    { id: 'u5-l6-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Your Poetry Toolkit</h3><ol><li><strong>Imagery:</strong> Show, don\'t tell. Use sensory details (sight, sound, touch, taste, smell)</li><li><strong>Figurative language:</strong> Metaphor, simile, personification, symbolism</li><li><strong>Sound devices:</strong> Alliteration, onomatopoeia, repetition</li><li><strong>Line breaks:</strong> Where you end a line changes how the reader breathes and pauses</li><li><strong>Voice:</strong> Your unique way of seeing and saying things</li></ol>' } },
    { id: 'u5-l6-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: '"Show, don\'t tell" in poetry means:', options: [{ label: 'Include pictures', value: 'a' }, { label: 'Use vivid sensory details and imagery instead of just naming emotions directly', value: 'b', correct: true }, { label: 'Write as many words as possible', value: 'c' }], explanation: 'Instead of "I was sad," show sadness: "The world dimmed to gray, and the rain on the window matched the weight behind my eyes." SHOW the feeling.' } },
    { id: 'u5-l6-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Write an ORIGINAL POEM (at least 12 lines) on ANY topic.\n\nRequirements:\n- Use at least 3 different figurative language techniques (label them in the margin or below)\n- Include at least 2 examples of vivid imagery (sensory details)\n- Make intentional choices about line breaks and stanza organization\n- Find your own VOICE — write about something that matters to you\n\nAfter your poem, write 2–3 sentences explaining your choices.', minLength: 80 } },
    { id: 'u5-l6-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'How did writing your own poem change the way you think about reading poetry? What surprised you about the creative writing process?', minLength: 30 } },
  ];
  for (const b of l6Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L6, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L6: ${l6Blocks.length} blocks`);

  const l6Qs = [
    { id: 'u5-l6-q1', questionText: '"Show, don\'t tell" in poetry means:', options: [{ label: 'Write as many words as possible', value: 'a' }, { label: 'Use vivid sensory imagery to SHOW emotions and experiences instead of directly naming them', value: 'b', correct: true }, { label: 'Use only dialogue', value: 'c' }, { label: 'Include illustrations', value: 'd' }], correctAnswer: 'b', explanation: '"I was happy" (telling) vs "My feet barely touched the ground, and the sky opened up like a promise" (showing). Imagery creates experience.', outcomeCode: 'ELA.6.TF.5', difficulty: 1 },
    { id: 'u5-l6-q2', questionText: 'LINE BREAKS in poetry:', options: [{ label: 'Don\'t matter', value: 'a' }, { label: 'Create pauses, emphasis, and visual rhythm that affect how the reader experiences the poem', value: 'b', correct: true }, { label: 'Are random', value: 'c' }, { label: 'Only happen at the end of sentences', value: 'd' }], correctAnswer: 'b', explanation: 'Where you break a line changes the pace and emphasis. Breaking mid-phrase creates surprise or tension.', outcomeCode: 'ELA.6.TF.5', difficulty: 2 },
    { id: 'u5-l6-q3', questionText: 'Your POETIC VOICE is:', options: [{ label: 'Copying a famous poet\'s style', value: 'a' }, { label: 'Your unique way of seeing, thinking, and expressing — what makes YOUR writing sound like YOU', value: 'b', correct: true }, { label: 'Using as many big words as possible', value: 'c' }, { label: 'Only using rhyme', value: 'd' }], correctAnswer: 'b', explanation: 'Voice is what makes your writing distinctly yours. It comes from your word choices, rhythms, topics, and perspective on the world.', outcomeCode: 'ELA.6.WC.4', difficulty: 2 },
    { id: 'u5-l6-q4', questionText: 'Which line uses stronger IMAGERY?', options: [{ label: '"The sunset was nice."', value: 'a' }, { label: '"The horizon bled crimson and gold as the sun dissolved into the lake."', value: 'b', correct: true }, { label: '"I saw the sunset."', value: 'c' }, { label: '"Sunset: 7:42 PM."', value: 'd' }], correctAnswer: 'b', explanation: '"Bled crimson and gold" and "dissolved into the lake" create vivid visual imagery. You can SEE this sunset. The other options just name it.', outcomeCode: 'ELA.6.VL.2', difficulty: 1 },
    { id: 'u5-l6-q5', questionText: 'The writing process for poetry includes:', options: [{ label: 'Write once, never revise', value: 'a' }, { label: 'Brainstorm → Draft → Read aloud → Revise → Share', value: 'b', correct: true }, { label: 'Only typing', value: 'c' }, { label: 'Copying someone else\'s poem', value: 'd' }], correctAnswer: 'b', explanation: 'Poetry follows the writing process too. Reading aloud is especially important for poetry because rhythm and sound only emerge when spoken.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u5-l6-q6', questionText: 'Using at least 3 figurative language techniques in a poem:', options: [{ label: 'Makes the poem too long', value: 'a' }, { label: 'Creates layers of meaning, sensory experience, and emotional depth', value: 'b', correct: true }, { label: 'Is unnecessary', value: 'c' }, { label: 'Confuses the reader', value: 'd' }], correctAnswer: 'b', explanation: 'Multiple techniques create richness. A metaphor + imagery + personification can work together to build a complete sensory and emotional experience.', outcomeCode: 'ELA.6.VL.2', difficulty: 2 },
    { id: 'u5-l6-q7', questionText: 'Explaining your creative choices AFTER writing a poem demonstrates:', options: [{ label: 'That you didn\'t know what you were doing', value: 'a' }, { label: 'Metacognitive awareness — understanding WHY you made specific choices', value: 'b', correct: true }, { label: 'Nothing important', value: 'c' }, { label: 'That the poem failed', value: 'd' }], correctAnswer: 'b', explanation: 'Reflecting on your choices (why this metaphor? why this line break?) shows sophisticated thinking and deepens your craft.', outcomeCode: 'ELA.6.WC.4', difficulty: 2 },
    { id: 'u5-l6-q8', questionText: 'Intentional structure in poetry means:', options: [{ label: 'Random stanza breaks', value: 'a' }, { label: 'Making deliberate choices about line length, stanza organization, and spacing to support the poem\'s meaning', value: 'b', correct: true }, { label: 'Always using rhyme', value: 'c' }, { label: 'Writing in paragraphs', value: 'd' }], correctAnswer: 'b', explanation: 'Every structural choice should serve the poem\'s purpose. Short lines = urgency. Long stanzas = flowing thought. White space = pause.', outcomeCode: 'ELA.6.TF.5', difficulty: 2 },
  ];
  for (const q of l6Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L6, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L6: ${l6Qs.length} questions`);

  // L7: Creative Performance — TF.6, OC.5, Review: OC.1, WC.4
  const L7 = 'g6-ela-u5-l7';
  const l7Blocks = [
    { id: 'u5-l7-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Bringing Words to Life</h3><p>A poem or dramatic piece on the page is only half alive. When performed — spoken aloud with voice, gesture, and intention — it becomes a complete experience.</p><p><strong>Performance preparation checklist:</strong></p><ol><li><strong>Read aloud multiple times</strong> — find the natural rhythm</li><li><strong>Mark emphasis:</strong> Underline words to stress</li><li><strong>Mark pauses:</strong> Add // where you want to pause for impact</li><li><strong>Plan gestures:</strong> What natural movements support the meaning?</li><li><strong>Eye contact:</strong> Look up from your text regularly</li><li><strong>Practice with an audience</strong> (even one person) before the final performance</li></ol>' } },
    { id: 'u5-l7-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Choose your ORIGINAL POEM from L6 or a dramatic scene from L3.\n\n1. Mark your text for performance: underline 5 words to EMPHASIZE, add // for 3 PAUSES, and note 2 GESTURES.\n2. Practice reading it aloud at least 3 times.\n3. Describe in 3–4 sentences what CHANGES when you perform the piece vs. reading it silently.', minLength: 40 } },
    { id: 'u5-l7-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'How does performing a poem or dramatic piece change the way you understand it? What is added by the human voice that reading silently cannot capture?', minLength: 30 } },
  ];
  for (const b of l7Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L7, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L7: ${l7Blocks.length} blocks`);

  const l7Qs = [
    { id: 'u5-l7-q1', questionText: 'Preparing a text for performance includes:', options: [{ label: 'Just reading it once', value: 'a' }, { label: 'Marking emphasis, pauses, and gestures — then practicing aloud multiple times', value: 'b', correct: true }, { label: 'Memorizing every word perfectly', value: 'c' }, { label: 'Only reading silently', value: 'd' }], correctAnswer: 'b', explanation: 'Performance preparation transforms a text from words on a page to a lived experience. Marking and practicing builds confidence and intentionality.', outcomeCode: 'ELA.6.TF.6', difficulty: 1 },
    { id: 'u5-l7-q2', questionText: 'EMPHASIS in performance means:', options: [{ label: 'Speaking every word the same way', value: 'a' }, { label: 'Stressing certain words to highlight their importance and create meaning', value: 'b', correct: true }, { label: 'Speaking quietly', value: 'c' }, { label: 'Reading faster', value: 'd' }], correctAnswer: 'b', explanation: 'Emphasis changes meaning. "I didn\'t STEAL the book" vs "I didn\'t steal the BOOK" — the stressed word shifts the focus entirely.', outcomeCode: 'ELA.6.OC.5', difficulty: 1 },
    { id: 'u5-l7-q3', questionText: 'Performing a poem adds the element of:', options: [{ label: 'Nothing new', value: 'a' }, { label: 'The human voice — tone, rhythm, emotion, and physical presence that bring text to life', value: 'b', correct: true }, { label: 'Only volume', value: 'c' }, { label: 'Speed', value: 'd' }], correctAnswer: 'b', explanation: 'Performance adds paraverbal (tone, pacing) and non-verbal (gesture, eye contact) layers that written text alone cannot provide.', outcomeCode: 'ELA.6.OC.5', difficulty: 1 },
    { id: 'u5-l7-q4', questionText: 'Strategic PAUSES during performance:', options: [{ label: 'Show you forgot your lines', value: 'a' }, { label: 'Create tension, let ideas sink in, and give the audience time to feel the impact', value: 'b', correct: true }, { label: 'Should always be avoided', value: 'c' }, { label: 'Make the performance too long', value: 'd' }], correctAnswer: 'b', explanation: 'Pauses are one of the most powerful performance tools. Silence after an important line lets the audience absorb and respond emotionally.', outcomeCode: 'ELA.6.OC.5', difficulty: 2 },
    { id: 'u5-l7-q5', questionText: 'Giving PEER FEEDBACK on a creative performance should include:', options: [{ label: 'Only saying "good job"', value: 'a' }, { label: 'Specific Glows (strengths), Grows (improvements), and Questions — focused on delivery AND content', value: 'b', correct: true }, { label: 'Criticizing the person, not the performance', value: 'c' }, { label: 'Not saying anything', value: 'd' }], correctAnswer: 'b', explanation: 'Like all peer feedback, creative performance feedback should be specific, balanced, and constructive.', outcomeCode: 'ELA.6.OC.3', difficulty: 1 },
    { id: 'u5-l7-q6', questionText: 'Indigenous oral tradition teaches us that spoken words:', options: [{ label: 'Are less important than written words', value: 'a' }, { label: 'Carry unique power — stories, knowledge, and values that are transmitted through voice and presence', value: 'b', correct: true }, { label: 'Are only for entertainment', value: 'c' }, { label: 'Should be replaced by writing', value: 'd' }], correctAnswer: 'b', explanation: 'Oral tradition shows that spoken words carry layers of meaning — tone, context, relationship — that written text alone may not capture.', outcomeCode: 'ELA.6.OC.1', difficulty: 2 },
    { id: 'u5-l7-q7', questionText: 'Voice and gesture in performance are examples of:', options: [{ label: 'Only verbal communication', value: 'a' }, { label: 'Paraverbal (voice) and non-verbal (gesture) communication working together', value: 'b', correct: true }, { label: 'Written text', value: 'c' }, { label: 'Neither verbal nor non-verbal', value: 'd' }], correctAnswer: 'b', explanation: 'Voice quality = paraverbal. Gestures = non-verbal. Together, they create the full performance experience.', outcomeCode: 'ELA.6.OC.5', difficulty: 1 },
    { id: 'u5-l7-q8', questionText: 'Choosing to write and perform your OWN creative work develops:', options: [{ label: 'Nothing', value: 'a' }, { label: 'Creative expression, voice, confidence, and the ability to communicate ideas through original forms', value: 'b', correct: true }, { label: 'Only writing skills', value: 'c' }, { label: 'Only speaking skills', value: 'd' }], correctAnswer: 'b', explanation: 'Creating and performing your own work combines writing craft, oral communication, and personal expression — the full range of ELA skills.', outcomeCode: 'ELA.6.WC.4', difficulty: 1 },
  ];
  for (const q of l7Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L7, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L7: ${l7Qs.length} questions`);

  // L8: Wonder Showcase — OC.5, WC.1, Review: WC.3, OC.3
  const L8 = 'g6-ela-u5-l8';
  const l8Blocks = [
    { id: 'u5-l8-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>The Wonder Showcase</h3><p>This is your moment. You have explored poetry, figurative language, drama, Indigenous land literacy, rhetoric, and creative expression. Now you will share your original creative work with an audience.</p><p><strong>Final preparation:</strong></p><ul><li>Choose your strongest piece (poem, dramatic scene, or spoken word)</li><li>Revise it one more time for clarity and impact</li><li>Mark it for performance (emphasis, pauses, gestures)</li><li>Practice at least 3 times</li><li>Prepare to give AND receive peer feedback</li></ul>' } },
    { id: 'u5-l8-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Perform your original creative work.\n\nAfter performing and receiving peer feedback, write:\n\n1. What are you MOST proud of in your creative work?\n2. What specific FEEDBACK did you receive? What will you do with it?\n3. What did you learn from watching OTHER performances?\n4. How has your understanding of creativity, imagination, and expression GROWN during this unit?', minLength: 50 } },
    { id: 'u5-l8-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'How has your understanding of imagination, creativity, and expression grown during this unit? What will you carry with you as a reader, writer, and communicator?', minLength: 30 } },
  ];
  for (const b of l8Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L8, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L8: ${l8Blocks.length} blocks`);

  const l8Qs = [
    { id: 'u5-l8-q1', questionText: 'Before performing, a final revision should focus on:', options: [{ label: 'Only spelling', value: 'a' }, { label: 'Clarity, impact, word choice, and how the piece sounds when read aloud', value: 'b', correct: true }, { label: 'Making it longer', value: 'c' }, { label: 'Nothing — first drafts are fine', value: 'd' }], correctAnswer: 'b', explanation: 'Final revision for performance focuses on how the piece SOUNDS and FEELS to an audience, not just correctness on the page.', outcomeCode: 'ELA.6.WC.3', difficulty: 1 },
    { id: 'u5-l8-q2', questionText: 'Choosing your STRONGEST piece for the showcase shows:', options: [{ label: 'You only wrote one thing', value: 'a' }, { label: 'Self-evaluation — the ability to assess your own work and identify what represents your best effort', value: 'b', correct: true }, { label: 'You don\'t like the other pieces', value: 'c' }, { label: 'Nothing important', value: 'd' }], correctAnswer: 'b', explanation: 'Self-assessment is a key metacognitive skill. Choosing your strongest work requires honest evaluation of your own writing.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u5-l8-q3', questionText: 'Giving specific, constructive peer feedback:', options: [{ label: 'Is rude', value: 'a' }, { label: 'Helps the creator understand what works, what could improve, and provokes deeper thinking', value: 'b', correct: true }, { label: 'Is unnecessary', value: 'c' }, { label: 'Only involves saying "I liked it"', value: 'd' }], correctAnswer: 'b', explanation: '"Your use of personification in line 3 made the wind feel alive" is far more helpful than "good poem."', outcomeCode: 'ELA.6.OC.3', difficulty: 1 },
    { id: 'u5-l8-q4', questionText: 'Looking back at this unit, the skills of poetry, drama, rhetoric, and FNMI land literacy all share:', options: [{ label: 'Nothing in common', value: 'a' }, { label: 'A focus on how language, voice, and perspective create meaning and connection', value: 'b', correct: true }, { label: 'Only written skills', value: 'c' }, { label: 'Only oral skills', value: 'd' }], correctAnswer: 'b', explanation: 'All four areas explore how we use language (in different forms) to make meaning, express identity, and connect with others and the world.', outcomeCode: 'ELA.6.OC.5', difficulty: 2 },
    { id: 'u5-l8-q5', questionText: 'Practice before a performance builds:', options: [{ label: 'Nothing', value: 'a' }, { label: 'Confidence, fluency, and the ability to connect with the audience instead of reading from notes', value: 'b', correct: true }, { label: 'Only memory', value: 'c' }, { label: 'Anxiety', value: 'd' }], correctAnswer: 'b', explanation: 'Each practice run builds comfort and allows you to focus on delivery rather than just remembering words.', outcomeCode: 'ELA.6.OC.5', difficulty: 1 },
    { id: 'u5-l8-q6', questionText: 'The writing process applied to creative work is:', options: [{ label: 'Different from the writing process for research', value: 'a' }, { label: 'The same core process: brainstorm → draft → revise → edit → share/publish', value: 'b', correct: true }, { label: 'Not needed for poetry', value: 'c' }, { label: 'Only drafting', value: 'd' }], correctAnswer: 'b', explanation: 'The writing process is universal. Poetry especially benefits from revision — every word must earn its place.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u5-l8-q7', questionText: 'Reflecting on your growth as a creative writer helps you:', options: [{ label: 'Nothing — reflection is a waste of time', value: 'a' }, { label: 'Identify strengths, recognize growth, set goals, and build metacognitive awareness', value: 'b', correct: true }, { label: 'Only feel bad about mistakes', value: 'c' }, { label: 'Avoid writing in the future', value: 'd' }], correctAnswer: 'b', explanation: 'Reflection is how learning becomes conscious. Without reflection, growth happens slowly; with it, you can accelerate and direct your improvement.', outcomeCode: 'ELA.6.WC.1', difficulty: 2 },
    { id: 'u5-l8-q8', questionText: 'This unit shows that imagination and creativity:', options: [{ label: 'Are not real academic skills', value: 'a' }, { label: 'Are essential for expression, communication, empathy, and seeing the world in new ways', value: 'b', correct: true }, { label: 'Only belong in art class', value: 'c' }, { label: 'Cannot be learned', value: 'd' }], correctAnswer: 'b', explanation: 'Creativity is a core literacy skill. Poetry, drama, and rhetoric all require imaginative thinking, and they deepen every other ELA skill.', outcomeCode: 'ELA.6.WC.4', difficulty: 1 },
  ];
  for (const q of l8Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L8, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L8: ${l8Qs.length} questions`);

  console.log(`\n╔═══════════════════════════════════════════════╗\n║   ELA UNIT 5 (L5–L8) SEED COMPLETE          ║\n╠═══════════════════════════════════════════════╣\n║ Lessons:    4                                ║\n║ Blocks:     ${String(l5Blocks.length + l6Blocks.length + l7Blocks.length + l8Blocks.length).padStart(2)}                               ║\n║ Questions:  ${String(l5Qs.length + l6Qs.length + l7Qs.length + l8Qs.length).padStart(2)}                               ║\n╚═══════════════════════════════════════════════╝`);
}

main()
  .catch((e) => { console.error('❌ Seed error:', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); pool.end(); });
