// ============================================
// Seed Science Unit D L1-L3 — Structures & Forces
// ============================================
// Run: npx tsx prisma/seed-sci-ud-l1-l3.ts

import { config } from 'dotenv';
config({ path: '.env.local' });
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function seedLesson1() {
  const ID = 'g7-sci-ud-l1';
  console.log('\n🏛️ Seeding UD L1: Types of Structures...');
  await prisma.lesson.update({ where: { id: ID }, data: { subjectMode: 'SCIENCE', estimatedMinutes: 45, learningGoal: 'Describe and classify structures as shell, frame, or solid; identify materials used and explain choices; compare natural and human-made structures.', successCriteria: 'I can name 3 structure types with examples, explain material choices for structures, and match natural to human-made structures.', materials: 'Science notebook', reflectionPrompt: 'What type of structures are around you right now? If you could design one, what type would you choose?', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } } });
  await prisma.lessonBlock.deleteMany({ where: { lessonId: ID } });
  await prisma.quizQuestion.deleteMany({ where: { lessonId: ID } });

  const blocks = [
    { id: 'ud-l1-learn-1', section: 'LEARN' as const, blockType: 'VOCABULARY' as const, order: 1, content: { terms: [
      { term: 'Structure', definition: 'Something with a definite shape, designed to support a load.', example: 'Bridges, buildings, skeletons.' },
      { term: 'Shell Structure', definition: 'A hollow structure with a thin outer layer for both shape and strength.', example: 'Eggshell, helmet, dome.' },
      { term: 'Frame Structure', definition: 'A skeleton of connected parts (beams, bars) with open spaces.', example: 'Bicycle frame, crane, human skeleton.' },
      { term: 'Solid (Mass) Structure', definition: 'Made entirely of material throughout. Strength comes from bulk.', example: 'Dam, brick wall, mountain.' },
      { term: 'Load', definition: 'Forces acting on a structure. Dead load = own weight. Live load = additional forces.', example: 'People, wind, snow on a roof.' },
      { term: 'Compression', definition: 'A pushing force that squeezes a material.', example: 'Concrete pillars supporting a roof.' },
      { term: 'Tension', definition: 'A pulling force that stretches a material.', example: 'Steel cables on a suspension bridge.' },
    ] } },
    { id: 'ud-l1-learn-2', section: 'LEARN' as const, blockType: 'TEXT' as const, order: 2, content: { html: '<h3>📐 Three Types of Structures</h3><table><thead><tr><th>Type</th><th>Description</th><th>Examples</th></tr></thead><tbody><tr><td>🥚 <strong>Shell</strong></td><td>Hollow with a thin outer layer for shape and strength</td><td>Eggshell, igloo, helmet, airplane fuselage</td></tr><tr><td>🏗️ <strong>Frame</strong></td><td>Connected parts (beams, bars) with open spaces between</td><td>Bicycle, crane, spider web, skeleton</td></tr><tr><td>🧱 <strong>Solid</strong></td><td>Made of material throughout — strength from bulk</td><td>Brick wall, dam, mountain, sandcastle</td></tr></tbody></table><p>Many structures combine types. A house has a <strong>frame</strong> (wood studs), covered with a <strong>shell</strong> (drywall), on a <strong>solid</strong> foundation (concrete).</p>' } },
    { id: 'ud-l1-learn-3', section: 'LEARN' as const, blockType: 'VIDEO' as const, order: 3, content: { url: 'https://www.youtube.com/embed/sLfUDIRaPGU', title: 'Types of Structures: Shell, Frame, and Solid', transcript: 'Video explaining the three types of structures.' } },
    { id: 'ud-l1-learn-4', section: 'LEARN' as const, blockType: 'TEXT' as const, order: 4, content: { html: '<h3>🔩 Structural Materials & Properties</h3><ul><li>🪨 <strong>Concrete:</strong> Strong in compression. Heavy, durable, fireproof. Used for foundations and dams.</li><li>🔩 <strong>Steel:</strong> Strong in tension AND compression. Flexible, can rust. Used for bridges and skyscrapers.</li><li>🪵 <strong>Wood:</strong> Light and easy to shape. Burns, can rot. Used for houses and furniture.</li><li>🪟 <strong>Glass:</strong> Transparent, hard, brittle. Breaks under impact. Used for windows.</li><li>🧪 <strong>Plastic:</strong> Light, flexible, waterproof. Not heat-resistant. Used for containers.</li></ul>' } },
    { id: 'ud-l1-learn-5', section: 'LEARN' as const, blockType: 'TEXT' as const, order: 5, content: { html: '<h3>🌿 Natural vs Human-Made Structures</h3><table><thead><tr><th>Natural</th><th>Type</th><th>Human Equivalent</th></tr></thead><tbody><tr><td>🥚 Eggshell</td><td>Shell</td><td>🏟️ Dome stadium</td></tr><tr><td>🕷️ Spider web</td><td>Frame</td><td>🌉 Suspension bridge</td></tr><tr><td>🦴 Skeleton</td><td>Frame</td><td>🏗️ Steel building frame</td></tr><tr><td>🦫 Beaver dam</td><td>Solid</td><td>🫗 Hydroelectric dam</td></tr></tbody></table><p><strong>Alberta:</strong> Calgary\'s Peace Bridge is a helical frame structure that distributes weight evenly across the Bow River.</p>' } },
    { id: 'ud-l1-prac-1', section: 'PRACTICE' as const, blockType: 'MATCHING' as const, order: 1, content: { instruction: 'Classify each structure as Shell, Frame, or Solid:', pairs: [{ left: 'Eggshell', right: 'Shell' }, { left: 'Bicycle frame', right: 'Frame' }, { left: 'Brick wall', right: 'Solid' }, { left: 'Helmet', right: 'Shell' }, { left: 'Spider web', right: 'Frame' }, { left: 'Concrete dam', right: 'Solid' }] } },
    { id: 'ud-l1-prac-2', section: 'PRACTICE' as const, blockType: 'MATCHING' as const, order: 2, content: { instruction: 'Match each material to its best structural use:', pairs: [{ left: 'Steel', right: 'Bridges & skyscrapers' }, { left: 'Concrete', right: 'Foundations & dams' }, { left: 'Wood', right: 'Houses & furniture' }, { left: 'Glass', right: 'Windows & displays' }, { left: 'Plastic', right: 'Containers & bottles' }] } },
    { id: 'ud-l1-reflect-1', section: 'REFLECT' as const, blockType: 'CONSTRUCTED_RESPONSE' as const, order: 1, content: { prompt: 'Choose a structure you see every day. In 2-4 sentences, explain what type it is, what materials it\'s made from, and why those materials were chosen.', minLength: 60, rubricHint: 'Identifies structure type. Names materials and their properties. Connects material choice to function.', teacherReviewRequired: false } },
  ];
  for (const b of blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: ID, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`  ✅ ${blocks.length} blocks`);

  const questions = [
    { id: 'ud-l1-q1', questionText: 'A hollow structure with a thin outer layer is a:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Frame structure', value: 'a' }, { label: 'Solid structure', value: 'b' }, { label: 'Shell structure', value: 'c', correct: true }, { label: 'Combination', value: 'd' }], correctAnswer: 'c', explanation: 'Shell structures use a thin outer layer for both shape and strength.', outcomeCode: 'SCI.7.D.1.1', difficulty: 1 },
    { id: 'ud-l1-q2', questionText: 'A bicycle is an example of a:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Shell structure', value: 'a' }, { label: 'Frame structure', value: 'b', correct: true }, { label: 'Solid structure', value: 'c' }, { label: 'Natural structure', value: 'd' }], correctAnswer: 'b', explanation: 'A bicycle has connected bars forming a skeleton — it\'s a frame structure.', outcomeCode: 'SCI.7.D.1.1', difficulty: 1 },
    { id: 'ud-l1-q3', questionText: 'Steel is preferred for skyscrapers because:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'It\'s transparent', value: 'a' }, { label: 'It\'s light and brittle', value: 'b' }, { label: 'It\'s strong in both tension and compression', value: 'c', correct: true }, { label: 'It\'s waterproof only', value: 'd' }], correctAnswer: 'c', explanation: 'Steel can resist both pulling (tension) and pushing (compression) forces.', outcomeCode: 'SCI.7.D.1.2', difficulty: 1 },
    { id: 'ud-l1-q4', questionText: 'A solid structure gets its strength from:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Its thin outer shell', value: 'a' }, { label: 'Its connected framework', value: 'b' }, { label: 'The mass/bulk of its material', value: 'c', correct: true }, { label: 'Air inside it', value: 'd' }], correctAnswer: 'c', explanation: 'Solid structures rely on the sheer bulk of material for strength.', outcomeCode: 'SCI.7.D.1.1', difficulty: 1 },
    { id: 'ud-l1-q5', questionText: '\'Form follows function\' means:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'All structures look the same', value: 'a' }, { label: 'A structure\'s shape is determined by what it needs to do', value: 'b', correct: true }, { label: 'Function doesn\'t matter', value: 'c' }, { label: 'Only natural structures have form', value: 'd' }], correctAnswer: 'b', explanation: 'The shape (form) of a structure is designed to suit its purpose (function).', outcomeCode: 'SCI.7.D.1.1', difficulty: 1 },
    { id: 'ud-l1-q6', questionText: 'Concrete is strong in:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Tension (stretching)', value: 'a' }, { label: 'Compression (pushing)', value: 'b', correct: true }, { label: 'Both equally', value: 'c' }, { label: 'Neither', value: 'd' }], correctAnswer: 'b', explanation: 'Concrete excels at resisting compression but is weak in tension.', outcomeCode: 'SCI.7.D.1.2', difficulty: 1 },
    { id: 'ud-l1-q7', questionText: 'A human skeleton is most similar to:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'A steel building frame', value: 'a', correct: true }, { label: 'A concrete wall', value: 'b' }, { label: 'An eggshell', value: 'c' }, { label: 'A sandcastle', value: 'd' }], correctAnswer: 'a', explanation: 'Both are internal frame structures providing shape and support.', outcomeCode: 'SCI.7.D.1.1', difficulty: 2 },
    { id: 'ud-l1-q8', questionText: 'Which material is best for a bridge that must handle heavy traffic AND strong winds?', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Glass', value: 'a' }, { label: 'Wood', value: 'b' }, { label: 'Steel', value: 'c', correct: true }, { label: 'Plastic', value: 'd' }], correctAnswer: 'c', explanation: 'Steel\'s strength in both tension and compression makes it ideal for bridges under dynamic loads.', outcomeCode: 'SCI.7.D.1.2', difficulty: 2 },
  ];
  for (const q of questions) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: ID, questionText: q.questionText, questionType: q.questionType, options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`  ✅ ${questions.length} questions`);
}

async function seedLesson2() {
  const ID = 'g7-sci-ud-l2';
  console.log('\n⚖️ Seeding UD L2: Forces & Stability...');
  await prisma.lesson.update({ where: { id: ID }, data: { subjectMode: 'SCIENCE', estimatedMinutes: 45, learningGoal: 'Describe internal forces (tension, compression, shear, torsion), distinguish dead/live loads, explain centre of gravity and stability, and identify causes of structural failure.', successCriteria: 'I can classify 4 force types, explain dead vs. live loads, describe stability principles, and predict structural improvements.', materials: 'Science notebook', reflectionPrompt: 'What forces are acting on the structures around you right now?', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } } });
  await prisma.lessonBlock.deleteMany({ where: { lessonId: ID } });
  await prisma.quizQuestion.deleteMany({ where: { lessonId: ID } });

  const blocks = [
    { id: 'ud-l2-learn-1', section: 'LEARN' as const, blockType: 'VOCABULARY' as const, order: 1, content: { terms: [
      { term: 'Tension', definition: 'A pulling force that stretches a material.', example: 'Cables on a suspension bridge.' },
      { term: 'Compression', definition: 'A pushing/squeezing force that shortens a material.', example: 'Pillars supporting a roof.' },
      { term: 'Shear', definition: 'A sliding force pushing parts in opposite directions.', example: 'Scissors cutting paper.' },
      { term: 'Torsion', definition: 'A twisting force.', example: 'Wringing out a towel.' },
      { term: 'Centre of Gravity', definition: 'The point where an object\'s mass is balanced. Lowering it increases stability.', example: 'Race cars are low to the ground.' },
      { term: 'Dead Load', definition: 'The permanent weight of the structure itself.', example: 'Walls, floors, roof beams.' },
    ] } },
    { id: 'ud-l2-learn-2', section: 'LEARN' as const, blockType: 'TEXT' as const, order: 2, content: { html: '<h3>💪 Internal Forces</h3><ul><li>↗️ <strong>Tension:</strong> Pulling apart — cables on a suspension bridge</li><li>↙️ <strong>Compression:</strong> Squeezing together — pillars supporting a roof</li><li>↔️ <strong>Shear:</strong> Sliding in opposite directions — scissors cutting paper</li><li>🔄 <strong>Torsion:</strong> Twisting — wringing out a towel</li></ul>' } },
    { id: 'ud-l2-learn-3', section: 'LEARN' as const, blockType: 'TEXT' as const, order: 3, content: { html: '<h3>📦 Dead Load vs. Live Load</h3><table><thead><tr><th>Type</th><th>Description</th><th>Examples</th></tr></thead><tbody><tr><td><strong>Dead Load</strong></td><td>Permanent weight of the structure itself</td><td>Walls, floor, roof, beams</td></tr><tr><td><strong>Live Load</strong></td><td>Temporary forces that change</td><td>People, furniture, snow, wind, vehicles</td></tr></tbody></table><p><strong>Key:</strong> Engineers must calculate both to prevent collapse. A bridge must support its own weight PLUS the traffic crossing it.</p>' } },
    { id: 'ud-l2-learn-4', section: 'LEARN' as const, blockType: 'TEXT' as const, order: 4, content: { html: '<h3>⚖️ Stability & Centre of Gravity</h3><p>A structure is <strong>stable</strong> when it resists tipping. Stability depends on:</p><ul><li>⬇️ <strong>Low Centre of Gravity</strong> — harder to tip (race cars)</li><li>↔️ <strong>Wide Base</strong> — more support area (Eiffel Tower)</li><li>⚖️ <strong>Symmetry</strong> — balanced weight distribution</li></ul><p><strong>Alberta:</strong> Calgary\'s Bow Tower uses triangular bracing and weighted foundations to resist strong Chinook winds.</p>' } },
    { id: 'ud-l2-learn-5', section: 'LEARN' as const, blockType: 'VIDEO' as const, order: 5, content: { url: 'https://www.youtube.com/embed/d2Q0SU-S4A4', title: 'Structural Forces & Engineering', transcript: 'Video explaining internal forces on structures.' } },
    { id: 'ud-l2-prac-1', section: 'PRACTICE' as const, blockType: 'MATCHING' as const, order: 1, content: { instruction: 'Classify each scenario by force type:', pairs: [{ left: 'A rope pulled tight in tug-of-war', right: 'Tension' }, { left: 'A pillar supporting a heavy roof', right: 'Compression' }, { left: 'Scissors cutting cardboard', right: 'Shear' }, { left: 'Wringing water from a towel', right: 'Torsion' }, { left: 'A bridge cable holding the deck', right: 'Tension' }, { left: 'Standing on a sponge', right: 'Compression' }] } },
    { id: 'ud-l2-reflect-1', section: 'REFLECT' as const, blockType: 'CONSTRUCTED_RESPONSE' as const, order: 1, content: { prompt: 'A school wants to build an outdoor stage. Explain what forces the stage must resist, what loads it experiences, and how to make it stable. Use at least 3 vocabulary words.', minLength: 80, rubricHint: 'Names specific forces (tension, compression). Distinguishes dead/live loads. Suggests stability features.', teacherReviewRequired: false } },
  ];
  for (const b of blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: ID, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`  ✅ ${blocks.length} blocks`);

  const questions = [
    { id: 'ud-l2-q1', questionText: 'Tension is a force that:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Squeezes material together', value: 'a' }, { label: 'Pulls material apart', value: 'b', correct: true }, { label: 'Twists material', value: 'c' }, { label: 'Slides material', value: 'd' }], correctAnswer: 'b', explanation: 'Tension is a pulling force that stretches a material.', outcomeCode: 'SCI.7.D.2.1', difficulty: 1 },
    { id: 'ud-l2-q2', questionText: 'The permanent weight of a structure is called its:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Live load', value: 'a' }, { label: 'Dead load', value: 'b', correct: true }, { label: 'Shear force', value: 'c' }, { label: 'Torsion', value: 'd' }], correctAnswer: 'b', explanation: 'Dead load = the structure\'s own permanent weight.', outcomeCode: 'SCI.7.D.2.1', difficulty: 1 },
    { id: 'ud-l2-q3', questionText: 'Lowering the centre of gravity makes a structure:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Taller', value: 'a' }, { label: 'More stable', value: 'b', correct: true }, { label: 'Lighter', value: 'c' }, { label: 'Weaker', value: 'd' }], correctAnswer: 'b', explanation: 'A lower centre of gravity makes a structure harder to tip over.', outcomeCode: 'SCI.7.D.2.2', difficulty: 1 },
    { id: 'ud-l2-q4', questionText: 'Scissors cutting paper is an example of:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Tension', value: 'a' }, { label: 'Compression', value: 'b' }, { label: 'Shear', value: 'c', correct: true }, { label: 'Torsion', value: 'd' }], correctAnswer: 'c', explanation: 'Shear forces push parts of a material in opposite directions.', outcomeCode: 'SCI.7.D.2.1', difficulty: 1 },
    { id: 'ud-l2-q5', questionText: 'Snow on a roof is an example of:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Dead load', value: 'a' }, { label: 'Live load', value: 'b', correct: true }, { label: 'Tension', value: 'c' }, { label: 'Torsion', value: 'd' }], correctAnswer: 'b', explanation: 'Snow is a temporary changing force — a live load.', outcomeCode: 'SCI.7.D.2.1', difficulty: 1 },
    { id: 'ud-l2-q6', questionText: 'A wider base improves stability because:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'It looks better', value: 'a' }, { label: 'It provides more support area', value: 'b', correct: true }, { label: 'It adds more weight', value: 'c' }, { label: 'It uses less material', value: 'd' }], correctAnswer: 'b', explanation: 'A wider base spreads the load and makes tipping more difficult.', outcomeCode: 'SCI.7.D.2.2', difficulty: 1 },
    { id: 'ud-l2-q7', questionText: 'Material fatigue causes failure due to:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Single heavy impact', value: 'a' }, { label: 'Repeated stress over time', value: 'b', correct: true }, { label: 'Freezing temperatures', value: 'c' }, { label: 'Being too light', value: 'd' }], correctAnswer: 'b', explanation: 'Repeated bending/stress weakens materials over time until they break.', outcomeCode: 'SCI.7.D.2.1', difficulty: 2 },
    { id: 'ud-l2-q8', questionText: 'Pillars supporting a roof mainly experience:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Tension', value: 'a' }, { label: 'Compression', value: 'b', correct: true }, { label: 'Shear', value: 'c' }, { label: 'Torsion', value: 'd' }], correctAnswer: 'b', explanation: 'Pillars are squeezed under the weight of the roof — compression.', outcomeCode: 'SCI.7.D.2.1', difficulty: 1 },
  ];
  for (const q of questions) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: ID, questionText: q.questionText, questionType: q.questionType, options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`  ✅ ${questions.length} questions`);
}

async function seedLesson3() {
  const ID = 'g7-sci-ud-l3';
  console.log('\n🌪️ Seeding UD L3: External Forces...');
  await prisma.lesson.update({ where: { id: ID }, data: { subjectMode: 'SCIENCE', estimatedMinutes: 45, learningGoal: 'Identify external forces (wind, gravity, seismic, snow, water), explain how environmental factors influence design, and describe how friction helps and hinders structures.', successCriteria: 'I can name 4 external forces, explain Alberta-specific design challenges, and describe how friction affects structures.', materials: 'Science notebook', reflectionPrompt: 'What external forces act on your home? How is it designed to handle them?', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } } });
  await prisma.lessonBlock.deleteMany({ where: { lessonId: ID } });
  await prisma.quizQuestion.deleteMany({ where: { lessonId: ID } });

  const blocks = [
    { id: 'ud-l3-learn-1', section: 'LEARN' as const, blockType: 'VOCABULARY' as const, order: 1, content: { terms: [
      { term: 'External Force', definition: 'Forces from outside the structure — wind, gravity, earthquakes, snow, water.', example: 'A windstorm pushing against a building.' },
      { term: 'Dynamic Load', definition: 'Forces that change over time — wind gusts, traffic, earthquakes.', example: 'Cars driving over a bridge at different speeds.' },
      { term: 'Seismic Force', definition: 'Ground shaking from earthquakes that can topple structures.', example: 'The 1985 Rocky Mountain House earthquake (4.6 magnitude).' },
      { term: 'Friction', definition: 'Force that resists sliding between surfaces — can help (grip) or hinder (wear).', example: 'Tires gripping the road; sandpaper wearing down wood.' },
    ] } },
    { id: 'ud-l3-learn-2', section: 'LEARN' as const, blockType: 'VIDEO' as const, order: 2, content: { url: 'https://www.youtube.com/embed/340MmuY_osY', title: 'Forces on Structures', transcript: 'Video explaining external forces on structures.' } },
    { id: 'ud-l3-learn-3', section: 'LEARN' as const, blockType: 'TEXT' as const, order: 3, content: { html: '<h3>🌪️ External Forces in Alberta</h3><ul><li>❄️ <strong>Snow Load:</strong> Heavy snowfalls create massive roof loads. Steep roofs let snow slide off; flat roofs must handle the weight.</li><li>🌬️ <strong>Wind:</strong> Chinook winds can gust up to 160 km/h. Buildings need wind bracing and deep foundations.</li><li>🌍 <strong>Seismic:</strong> Western Alberta has moderate earthquake risk. The 1985 Rocky Mountain House quake was 4.6 magnitude.</li><li>💧 <strong>Water/Ice:</strong> Freeze-thaw cycles crack foundations and roads. Proper drainage and waterproofing are critical.</li></ul>' } },
    { id: 'ud-l3-prac-1', section: 'PRACTICE' as const, blockType: 'MATCHING' as const, order: 1, content: { instruction: 'Match each design feature to the external force it defends against:', pairs: [{ left: 'Steep pitched roof', right: 'Snow load' }, { left: 'Deep foundation with bracing', right: 'Wind' }, { left: 'Flexible building frame', right: 'Earthquake/Seismic' }, { left: 'Waterproof membrane and drainage', right: 'Water/Ice' }] } },
    { id: 'ud-l3-reflect-1', section: 'REFLECT' as const, blockType: 'CONSTRUCTED_RESPONSE' as const, order: 1, content: { prompt: 'Design a bus shelter for Lethbridge, Alberta (strong Chinook winds + heavy winter snow). What external forces must you consider and how would you design the shelter to resist them?', minLength: 80, rubricHint: 'Identifies wind and snow forces. Proposes specific solutions (angled roof, wind bracing, drainage). Uses vocabulary.', teacherReviewRequired: false } },
  ];
  for (const b of blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: ID, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`  ✅ ${blocks.length} blocks`);

  const questions = [
    { id: 'ud-l3-q1', questionText: 'Alberta\'s Chinook winds are a type of:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Dead load', value: 'a' }, { label: 'External dynamic force', value: 'b', correct: true }, { label: 'Internal force', value: 'c' }, { label: 'Compression', value: 'd' }], correctAnswer: 'b', explanation: 'Wind is an external, changing (dynamic) force acting on a structure.', outcomeCode: 'SCI.7.D.2.3', difficulty: 1 },
    { id: 'ud-l3-q2', questionText: 'Steep roofs in Alberta are designed to:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Look attractive', value: 'a' }, { label: 'Allow heavy snow to slide off', value: 'b', correct: true }, { label: 'Block sunlight', value: 'c' }, { label: 'Increase dead load', value: 'd' }], correctAnswer: 'b', explanation: 'Steep pitched roofs prevent dangerous snow buildup by letting snow slide off.', outcomeCode: 'SCI.7.D.2.3', difficulty: 1 },
    { id: 'ud-l3-q3', questionText: 'Freeze-thaw cycles damage structures by:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Making them too hot', value: 'a' }, { label: 'Water expanding when frozen, cracking materials', value: 'b', correct: true }, { label: 'Making wind stronger', value: 'c' }, { label: 'Adding shear force', value: 'd' }], correctAnswer: 'b', explanation: 'Water expands when frozen — repeated freezing/thawing cracks foundations and roads.', outcomeCode: 'SCI.7.D.2.3', difficulty: 1 },
    { id: 'ud-l3-q4', questionText: 'A dynamic load differs from a dead load because it:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Never changes', value: 'a' }, { label: 'Changes over time (wind, traffic, earthquakes)', value: 'b', correct: true }, { label: 'Is always heavier', value: 'c' }, { label: 'Only acts upward', value: 'd' }], correctAnswer: 'b', explanation: 'Dynamic loads are variable forces that change in magnitude and direction over time.', outcomeCode: 'SCI.7.D.2.3', difficulty: 2 },
    { id: 'ud-l3-q5', questionText: 'Earthquake-resistant buildings often use:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Rigid, unbending frames', value: 'a' }, { label: 'Flexible frames that can sway without collapsing', value: 'b', correct: true }, { label: 'No foundation', value: 'c' }, { label: 'Only glass walls', value: 'd' }], correctAnswer: 'b', explanation: 'Flexible structures absorb seismic energy by swaying rather than cracking.', outcomeCode: 'SCI.7.D.2.3', difficulty: 2 },
    { id: 'ud-l3-q6', questionText: 'Friction helps structures by:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Making them heavier', value: 'a' }, { label: 'Providing grip between surfaces (preventing sliding)', value: 'b', correct: true }, { label: 'Adding compression', value: 'c' }, { label: 'Reducing dead load', value: 'd' }], correctAnswer: 'b', explanation: 'Friction between surfaces prevents parts from sliding — like bolts gripping or tires on road.', outcomeCode: 'SCI.7.D.2.3', difficulty: 1 },
    { id: 'ud-l3-q7', questionText: 'Deep foundations help Alberta buildings resist:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Gravity only', value: 'a' }, { label: 'Strong wind forces by anchoring the building', value: 'b', correct: true }, { label: 'Sunlight', value: 'c' }, { label: 'Nothing', value: 'd' }], correctAnswer: 'b', explanation: 'Deep foundations anchor buildings to resist wind uplift and overturning forces.', outcomeCode: 'SCI.7.D.2.3', difficulty: 1 },
    { id: 'ud-l3-q8', questionText: 'Waterproofing a foundation prevents damage from:', questionType: 'MULTIPLE_CHOICE' as const, options: [{ label: 'Wind', value: 'a' }, { label: 'Water infiltration and freeze-thaw cracking', value: 'b', correct: true }, { label: 'Compression', value: 'c' }, { label: 'Live loads', value: 'd' }], correctAnswer: 'b', explanation: 'Waterproofing keeps water out, preventing freeze-thaw cycles from cracking the concrete.', outcomeCode: 'SCI.7.D.2.3', difficulty: 1 },
  ];
  for (const q of questions) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: ID, questionText: q.questionText, questionType: q.questionType, options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`  ✅ ${questions.length} questions`);
}

async function main() {
  console.log('🏗️ ═══ SCIENCE UNIT D: L1-L3 ═══');
  await seedLesson1();
  await seedLesson2();
  await seedLesson3();
  console.log('\n✅ Unit D L1-L3 complete!');
}
main().catch(console.error).finally(() => { pool.end(); });
