// ============================================
// Seed ELA Unit 2 — "Story Power" (Lessons 5–8)
// ============================================
// The writing/production half: drafting, conflict & character,
// editing conventions, and final revision/publishing.
// Run: npx tsx prisma/seed-ela-u2-l5-l8.ts

import { config } from 'dotenv';
config({ path: '.env.local' });

import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('📖 Seeding ELA Unit 2 "Story Power" — Lessons 5–8');
  console.log('===================================================\n');

  const lessonDefs = [
    { id: 'g6-ela-u2-l5', title: 'Building My Story', subtitle: 'Plan and draft a multi-paragraph short story using a story map.', order: 5, learningGoal: 'Plan and draft a multi-paragraph short story with clear conflict, characters, and plot structure.', successCriteria: 'I can use a story map to plan my narrative with protagonist, antagonist, conflict, and plot arc.\nI can write a multi-paragraph draft with a clear beginning, middle, and end.\nI can organize my writing around a central conflict.', reflectionPrompt: 'What was the hardest part of planning your story? What decision took the most thought?' },
    { id: 'g6-ela-u2-l6', title: 'Crafting Conflict & Character', subtitle: 'Create compelling conflict and develop round characters with motivation.', order: 6, learningGoal: 'Deepen a draft by creating compelling conflict and developing round characters with clear motivation.', successCriteria: 'I can explain the difference between a flat and round character.\nI can identify a character\'s motivation and explain how it drives the plot.\nI can revise my story to deepen conflict and character.', reflectionPrompt: 'Think about a character you\'ve read about that felt truly REAL. What made them feel that way? How can you bring that quality to your own characters?' },
    { id: 'g6-ela-u2-l7', title: 'Editing Lab', subtitle: 'Capitalization, colon usage, clause identification, and sentence variety.', order: 7, learningGoal: 'Apply conventions skills to improve the clarity and correctness of writing: capitalization, colon usage, clauses, and sentence variety.', successCriteria: 'I can apply capitalization rules correctly.\nI can use colons to introduce a list, example, or explanation.\nI can identify independent and dependent clauses.\nI can vary my sentence types (simple, compound) for better rhythm.', reflectionPrompt: 'How does fixing conventions errors change the way a reader experiences your writing? Why do conventions matter for communication?' },
    { id: 'g6-ela-u2-l8', title: 'Story Showcase', subtitle: 'Final revision, peer feedback, publish and share.', order: 8, learningGoal: 'Complete the writing process by revising, seeking peer feedback, and publishing a polished short story.', successCriteria: 'I can revise my story for clarity, voice, and impact.\nI can give and receive constructive peer feedback.\nI can publish a final version that I am proud of.', reflectionPrompt: 'Look back at your story from plan to final draft. What is the biggest improvement you made? What would you do differently next time?' },
  ];

  for (const l of lessonDefs) {
    await prisma.lesson.upsert({
      where: { id: l.id },
      update: { title: l.title, subtitle: l.subtitle, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
      create: { id: l.id, unitId: 'g6-ela-u2', title: l.title, subtitle: l.subtitle, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
    });
  }
  console.log('✅ Lessons 5–8 upserted');

  for (const l of lessonDefs) {
    await prisma.lessonBlock.deleteMany({ where: { lessonId: l.id } });
    await prisma.quizQuestion.deleteMany({ where: { lessonId: l.id } });
  }

  // ════════════════════════════════════════
  // LESSON 5: Building My Story
  // Target: ELA.6.WC.2 (multi-paragraph writing)
  // Secondary: ELA.6.WC.1 (writing process)
  // Review: ELA.6.TF.1 (fiction elements from L1-L2)
  // ════════════════════════════════════════
  const L5 = 'g6-ela-u2-l5';

  const l5Blocks = [
    { id: 'u2-l5-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>From Reader to Writer</h3><p>In Lessons 1–4, you analyzed how great stories work. Now it\'s time to <strong>build your own</strong>.</p><p>Every strong story starts with a <strong>plan</strong>. Professional authors don\'t just start writing — they map out their story first.</p>' } },
    { id: 'u2-l5-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Your Story Map</h3><p>Before drafting, complete this planning framework:</p><ol><li><strong>Protagonist:</strong> Who is your main character? What do they want?</li><li><strong>Antagonist/Obstacle:</strong> What force stands in their way?</li><li><strong>Conflict type:</strong> Person vs Person? Person vs Self? Person vs Nature? Person vs Society?</li><li><strong>Setting:</strong> Where and when does your story take place?</li><li><strong>Plot arc:</strong><ul><li>Exposition: What is the "normal world"?</li><li>Inciting incident: What changes everything?</li><li>Rising action: What makes things worse? (2–3 events)</li><li>Climax: What is the turning point?</li><li>Resolution: How does it end?</li></ul></li></ol>' } },
    { id: 'u2-l5-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Drafting Tips</h3><ul><li><strong>Start in the middle of the action</strong> — don\'t begin with "Once upon a time" or "My name is..."</li><li><strong>Each paragraph should serve a purpose</strong> — advance the plot, reveal character, or build tension</li><li><strong>Use what you learned in L4:</strong> show-don\'t-tell, sensory detail, and dialogue</li><li><strong>Don\'t worry about perfection</strong> — this is a FIRST DRAFT. You will revise later.</li></ul>' } },
    { id: 'u2-l5-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Complete your STORY MAP:\n\n1. Protagonist (name, age, one key trait):\n2. Antagonist or obstacle:\n3. Conflict type:\n4. Setting:\n5. Plot arc (exposition → inciting incident → 2 rising action events → climax → resolution):\n\nThen write the FIRST PARAGRAPH of your story (at least 4 sentences). Remember: start in the action!', minLength: 100 } },
    { id: 'u2-l5-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'What was the hardest part of planning your story? What decision took the most thought — the character, the conflict, or the plot structure?', minLength: 30 } },
  ];

  for (const b of l5Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L5, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L5: ${l5Blocks.length} blocks`);

  const l5Qs = [
    { id: 'u2-l5-q1', questionText: 'What is the FIRST step of the writing process?', options: [{ label: 'Publishing', value: 'a' }, { label: 'Editing for grammar', value: 'b' }, { label: 'Planning — organizing ideas before drafting', value: 'c', correct: true }, { label: 'Reading it aloud', value: 'd' }], correctAnswer: 'c', explanation: 'Planning comes first: organizing characters, conflict, and plot structure before you start drafting.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u2-l5-q2', questionText: 'A multi-paragraph story should be organized around:', options: [{ label: 'Random events that happen to the character', value: 'a' }, { label: 'A central conflict with a clear beginning, rising action, climax, and resolution', value: 'b', correct: true }, { label: 'As many characters as possible', value: 'c' }, { label: 'Only dialogue', value: 'd' }], correctAnswer: 'b', explanation: 'Multi-paragraph writing needs organizing structure — the conflict and plot arc give the story shape and direction.', outcomeCode: 'ELA.6.WC.2', difficulty: 1 },
    { id: 'u2-l5-q3', questionText: 'Which is the STRONGEST opening for a story?', options: [{ label: '"Hi, my name is Jake and I am going to tell you about my adventure."', value: 'a' }, { label: '"Once upon a time, there was a boy."', value: 'b' }, { label: '"The rope snapped. Jake grabbed for the ledge, but his fingers found only air."', value: 'c', correct: true }, { label: '"This story is about a boy who goes on an adventure."', value: 'd' }], correctAnswer: 'c', explanation: 'Starting in the action immediately creates tension and pulls the reader in. The other options are flat introductions that delay engagement.', outcomeCode: 'ELA.6.WC.2', difficulty: 1 },
    { id: 'u2-l5-q4', questionText: 'The "inciting incident" is:', options: [{ label: 'The final scene', value: 'a' }, { label: 'The event that disrupts the normal world and kicks off the conflict', value: 'b', correct: true }, { label: 'The introduction of the setting', value: 'c' }, { label: 'The subplot', value: 'd' }], correctAnswer: 'b', explanation: 'The inciting incident is the catalyst — it changes everything and sets the story\'s conflict in motion.', outcomeCode: 'ELA.6.TF.1', difficulty: 1 },
    { id: 'u2-l5-q5', questionText: 'Why should each paragraph in a story "serve a purpose"?', options: [{ label: 'To make the story longer', value: 'a' }, { label: 'Each paragraph should advance the plot, reveal character, or build tension — unnecessary paragraphs slow the reader down', value: 'b', correct: true }, { label: 'Teachers require a certain number of paragraphs', value: 'c' }, { label: 'It doesn\'t matter what each paragraph does', value: 'd' }], correctAnswer: 'b', explanation: 'Focused writing keeps the reader engaged. Every paragraph should move the story forward in some meaningful way.', outcomeCode: 'ELA.6.WC.2', difficulty: 2 },
    { id: 'u2-l5-q6', questionText: 'A story map helps a writer by:', options: [{ label: 'Showing where the story takes place on a real map', value: 'a' }, { label: 'Organizing the characters, conflict, and plot arc BEFORE drafting', value: 'b', correct: true }, { label: 'Replacing the need to write a draft', value: 'c' }, { label: 'Telling the writer exactly what to write word-for-word', value: 'd' }], correctAnswer: 'b', explanation: 'A story map is a planning tool — it outlines the key elements so the writer has a clear direction when drafting.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u2-l5-q7', questionText: 'In a story with "Person vs Society" conflict, the protagonist is struggling against:', options: [{ label: 'Another character', value: 'a' }, { label: 'A natural disaster', value: 'b' }, { label: 'Rules, traditions, or expectations of the community', value: 'c', correct: true }, { label: 'Their own feelings', value: 'd' }], correctAnswer: 'c', explanation: 'Person vs Society means the character challenges societal rules, norms, or expectations — like in The Giver or Divergent.', outcomeCode: 'ELA.6.TF.1', difficulty: 1 },
    { id: 'u2-l5-q8', questionText: 'What is the difference between a FIRST DRAFT and a FINAL DRAFT?', options: [{ label: 'A first draft is shorter', value: 'a' }, { label: 'A first draft captures ideas; a final draft has been revised for clarity, voice, and correctness', value: 'b', correct: true }, { label: 'There is no difference', value: 'c' }, { label: 'A first draft is always better', value: 'd' }], correctAnswer: 'b', explanation: 'First drafts are about getting ideas down. Final drafts are polished through revision, editing, and sometimes restructuring.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
  ];

  for (const q of l5Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L5, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L5: ${l5Qs.length} questions (target: WC.2, WC.1, review: TF.1)`);

  // ════════════════════════════════════════
  // LESSON 6: Crafting Conflict & Character
  // Target: ELA.6.TF.1 + ELA.6.WC.4
  // Review: ELA.6.RC.1 (inference)
  // ════════════════════════════════════════
  const L6 = 'g6-ela-u2-l6';

  const l6Blocks = [
    { id: 'u2-l6-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Flat vs Round Characters</h3><p>Not all characters are created equal:</p><ul><li><strong>Flat characters</strong> have one or two traits. They don\'t change much. Example: a villain who is simply "evil."</li><li><strong>Round characters</strong> are complex — they have multiple traits, internal conflicts, and they GROW or change during the story.</li></ul><p>The best protagonists are round characters. Readers connect with characters who feel real.</p>' } },
    { id: 'u2-l6-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Character Motivation</h3><p>Every character needs a <strong>motivation</strong> — a reason for their actions. Without motivation, characters feel robotic.</p><p>Ask: <em>What does my character WANT? What are they AFRAID of? What would they NEVER do?</em></p><blockquote style="border-left:3px solid #7c5cf5;padding:12px 16px;margin:12px 0;font-style:italic">"Amara didn\'t want the trophy. She wanted her father to see her in the audience and know — without being told — that she had become someone worth watching."<br><br>— Original example</blockquote><p>Amara\'s motivation isn\'t about winning — it\'s about being seen by her father. This makes her a round character with emotional depth.</p>' } },
    { id: 'u2-l6-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: 'A "round character" is one who:', options: [{ label: 'Is physically round', value: 'a' }, { label: 'Is complex, has internal conflicts, and changes during the story', value: 'b', correct: true }, { label: 'Appears in every scene', value: 'c' }], explanation: 'Round characters have depth — multiple traits, internal struggles, and they grow or change. This makes them feel real.' } },
    { id: 'u2-l6-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Look at the protagonist in YOUR story draft.\n\n1. Is your character currently flat or round? Why?\n2. What is your character\'s MOTIVATION? (What do they want? What are they afraid of?)\n3. Write 2–3 sentences that SHOW (don\'t tell) your character\'s motivation through their actions or internal thoughts.', minLength: 50 } },
    { id: 'u2-l6-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Think about a character from a book or movie that felt truly REAL. What made them feel that way? How can you bring that quality to your own characters?', minLength: 30 } },
  ];

  for (const b of l6Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L6, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L6: ${l6Blocks.length} blocks`);

  const l6Qs = [
    { id: 'u2-l6-q1', questionText: 'A FLAT character is one who:', options: [{ label: 'Is complex and grows throughout the story', value: 'a' }, { label: 'Has only one or two traits and does not change much', value: 'b', correct: true }, { label: 'Is the protagonist', value: 'c' }, { label: 'Appears only once', value: 'd' }], correctAnswer: 'b', explanation: 'Flat characters are simple — they represent one trait (the bully, the wise mentor) and don\'t grow or change significantly.', outcomeCode: 'ELA.6.TF.1', difficulty: 1 },
    { id: 'u2-l6-q2', questionText: 'Character MOTIVATION is:', options: [{ label: 'What the character looks like', value: 'a' }, { label: 'The reason behind a character\'s actions — what they want or fear', value: 'b', correct: true }, { label: 'Where the character lives', value: 'c' }, { label: 'The character\'s name', value: 'd' }], correctAnswer: 'b', explanation: 'Motivation drives the story — it\'s WHY a character does what they do. Without it, actions feel random and disconnected.', outcomeCode: 'ELA.6.TF.1', difficulty: 1 },
    { id: 'u2-l6-q3', questionText: 'In the example, Amara doesn\'t want the trophy — she wants her father to see her. This makes her conflict:', options: [{ label: 'Person vs Nature', value: 'a' }, { label: 'Person vs Self — an internal emotional struggle', value: 'b', correct: true }, { label: 'Person vs Person — fighting her father', value: 'c' }, { label: 'Person vs Society', value: 'd' }], correctAnswer: 'b', explanation: 'Amara\'s struggle is internal — she wants recognition and connection with her father. This is Person vs Self.', outcomeCode: 'ELA.6.TF.1', difficulty: 2 },
    { id: 'u2-l6-q4', questionText: '"She wanted her father to see her and know — without being told — that she had become someone worth watching." What can you INFER about Amara\'s relationship with her father?', options: [{ label: 'They are very close', value: 'a' }, { label: 'She feels he hasn\'t been paying attention or recognizing her growth', value: 'b', correct: true }, { label: 'He is a sports coach', value: 'c' }, { label: 'They live in different cities', value: 'd' }], correctAnswer: 'b', explanation: 'The phrase "without being told" suggests she wants him to notice naturally. "Become someone worth watching" implies she feels he hasn\'t been watching.', outcomeCode: 'ELA.6.RC.1', difficulty: 2 },
    { id: 'u2-l6-q5', questionText: 'Which technique best helps a writer develop a ROUND character?', options: [{ label: 'Describing their appearance in detail', value: 'a' }, { label: 'Giving them internal conflicts, clear motivations, and showing them change', value: 'b', correct: true }, { label: 'Making them the tallest character', value: 'c' }, { label: 'Having them appear in every scene', value: 'd' }], correctAnswer: 'b', explanation: 'Round characters need depth: internal struggles, clear reasons for their actions, and growth throughout the story.', outcomeCode: 'ELA.6.WC.4', difficulty: 1 },
    { id: 'u2-l6-q6', questionText: 'A good writing technique to reveal character motivation is:', options: [{ label: 'Having the narrator say "she was motivated by..."', value: 'a' }, { label: 'Showing the character\'s thoughts, choices, and reactions through actions and internal monologue', value: 'b', correct: true }, { label: 'Listing their traits at the beginning', value: 'c' }, { label: 'Having another character describe them', value: 'd' }], correctAnswer: 'b', explanation: 'Show-don\'t-tell applies to motivation too — reveal WHY through actions and thoughts, not statements.', outcomeCode: 'ELA.6.WC.4', difficulty: 2 },
    { id: 'u2-l6-q7', questionText: 'What makes a PROTAGONIST more interesting than a simple "hero"?', options: [{ label: 'Superpowers', value: 'a' }, { label: 'Flaws, doubts, and real struggles that make them relatable', value: 'b', correct: true }, { label: 'Always winning', value: 'c' }, { label: 'Being older than other characters', value: 'd' }], correctAnswer: 'b', explanation: 'Relatable flaws and genuine struggles make protagonists feel human. Perfection makes characters boring.', outcomeCode: 'ELA.6.TF.1', difficulty: 2 },
    { id: 'u2-l6-q8', questionText: '"He whispered the words, but his hands were fists." What two emotions might this SHOW?', options: [{ label: 'He is happy and excited', value: 'a' }, { label: 'He is trying to stay calm (whisper) but is actually angry or frustrated (fists)', value: 'b', correct: true }, { label: 'He is cold', value: 'c' }, { label: 'He is bored', value: 'd' }], correctAnswer: 'b', explanation: 'The contrast between whispering (control) and fists (anger) shows internal conflict — he\'s restraining himself. This is showing, not telling.', outcomeCode: 'ELA.6.WC.4', difficulty: 2 },
  ];

  for (const q of l6Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L6, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L6: ${l6Qs.length} questions (target: TF.1, WC.4, review: RC.1)`);

  // ════════════════════════════════════════
  // LESSON 7: Editing Lab
  // Target: ELA.6.CV.1 (caps), CV.2 (colons), CV.3 (grammar)
  // Review: ELA.6.WC.3 (revision)
  // ════════════════════════════════════════
  const L7 = 'g6-ela-u2-l7';

  const l7Blocks = [
    { id: 'u2-l7-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Why Conventions Matter</h3><p>Conventions (capitalization, punctuation, grammar) are the <strong>traffic signals</strong> of writing. Without them, even great ideas become confusing to read.</p><p>In this lesson, you will sharpen three specific conventions skills and apply them to your own story draft.</p>' } },
    { id: 'u2-l7-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Capitalization Rules</h3><ul><li>Sentence beginnings</li><li>Proper nouns: names, places, titles (Ms. Chen, Alberta, The Giver)</li><li>Titles of books, movies, songs (capitalize major words)</li><li>Days, months, holidays (but NOT seasons)</li><li>"I" is always capitalized</li></ul><p><strong>Creative use:</strong> Some authors use ALL CAPS for emphasis: <em>"DO NOT open that door."</em></p>' } },
    { id: 'u2-l7-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>The Colon (:)</h3><p>Use a colon to:</p><ol><li><strong>Introduce a list:</strong> She packed three things: a flashlight, a map, and her courage.</li><li><strong>Give an explanation:</strong> There was one problem: the bridge was gone.</li><li><strong>Give an example:</strong> She had a favourite word: resilience.</li></ol><p><strong>Rule:</strong> The part BEFORE the colon must be a complete sentence.</p>' } },
    { id: 'u2-l7-learn-4', section: 'LEARN', blockType: 'TEXT', order: 4, content: { html: '<h3>Clauses & Sentence Types</h3><ul><li><strong>Independent clause:</strong> Can stand alone as a complete sentence. <em>"Mara climbed the stairs."</em></li><li><strong>Dependent clause:</strong> Cannot stand alone — needs an independent clause. <em>"When the storm hit"</em> (what happened?)</li><li><strong>Simple sentence:</strong> One independent clause. <em>"The dog barked."</em></li><li><strong>Compound sentence:</strong> Two independent clauses joined by a comma + conjunction (and, but, so, or). <em>"The dog barked, and the cat hid."</em></li></ul><p><strong>Tip:</strong> Varying sentence types creates RHYTHM in your writing. Too many simple sentences = choppy. Too many compound = exhausting.</p>' } },
    { id: 'u2-l7-learn-5', section: 'LEARN', blockType: 'MICRO_CHECK', order: 5, content: { question: 'Which sentence uses a colon CORRECTLY?', options: [{ label: '"She went to: the store, the park, and home."', value: 'a' }, { label: '"She needed three things: a rope, a flashlight, and a plan."', value: 'b', correct: true }, { label: '"She: ran, jumped, and climbed."', value: 'c' }], explanation: 'A colon must follow a complete sentence. "She needed three things" is a complete sentence, so the colon correctly introduces the list.' } },
    { id: 'u2-l7-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Open your story draft from Lesson 5.\n\n1. Find and fix 3 capitalization errors (or confirm all caps are correct)\n2. Add at least ONE colon that introduces a list, explanation, or example\n3. Find 2 simple sentences that could be combined into a compound sentence. Rewrite them.\n\nPaste your corrected paragraph below.', minLength: 40 } },
    { id: 'u2-l7-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'How does fixing conventions errors change the way a reader experiences your writing? Why do conventions matter beyond "getting a good grade"?', minLength: 30 } },
  ];

  for (const b of l7Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L7, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L7: ${l7Blocks.length} blocks`);

  const l7Qs = [
    { id: 'u2-l7-q1', questionText: 'Which word should be capitalized? "we visited calgary in july."', options: [{ label: 'visited', value: 'a' }, { label: 'calgary and july', value: 'b', correct: true }, { label: 'in', value: 'c' }, { label: 'None — all is correct', value: 'd' }], correctAnswer: 'b', explanation: 'Calgary is a proper noun (place name) and July is a month — both require capitalization.', outcomeCode: 'ELA.6.CV.1', difficulty: 1 },
    { id: 'u2-l7-q2', questionText: 'Which sentence uses a colon CORRECTLY?', options: [{ label: '"The explorer packed: quickly and left."', value: 'a' }, { label: '"There was only one option: run."', value: 'b', correct: true }, { label: '"She was: tired, hungry, and cold."', value: 'c' }, { label: '"He: went home."', value: 'd' }], correctAnswer: 'b', explanation: '"There was only one option" is a complete sentence, so the colon correctly introduces the explanation "run."', outcomeCode: 'ELA.6.CV.2', difficulty: 1 },
    { id: 'u2-l7-q3', questionText: '"When the storm hit" is an example of:', options: [{ label: 'An independent clause — it can stand alone', value: 'a' }, { label: 'A dependent clause — it cannot stand alone as a sentence', value: 'b', correct: true }, { label: 'A compound sentence', value: 'c' }, { label: 'A complete thought', value: 'd' }], correctAnswer: 'b', explanation: '"When the storm hit" leaves us asking "what happened?" It depends on an independent clause to complete the thought.', outcomeCode: 'ELA.6.CV.3', difficulty: 1 },
    { id: 'u2-l7-q4', questionText: '"The dog barked, and the cat hid under the bed." This is:', options: [{ label: 'A simple sentence', value: 'a' }, { label: 'A compound sentence — two independent clauses joined by a comma + conjunction', value: 'b', correct: true }, { label: 'A sentence fragment', value: 'c' }, { label: 'A dependent clause', value: 'd' }], correctAnswer: 'b', explanation: '"The dog barked" and "the cat hid under the bed" are both independent clauses, joined by a comma + "and" = compound sentence.', outcomeCode: 'ELA.6.CV.3', difficulty: 1 },
    { id: 'u2-l7-q5', questionText: 'Seasons should NOT be capitalized UNLESS:', options: [{ label: 'They are always capitalized', value: 'a' }, { label: 'They begin a sentence or are part of a proper name (e.g., "Spring Festival")', value: 'b', correct: true }, { label: 'They are never capitalized', value: 'c' }, { label: 'You are writing about weather', value: 'd' }], correctAnswer: 'b', explanation: 'Seasons (spring, summer, fall, winter) are common nouns — lowercase unless they start a sentence or are part of a proper name like "Winter Olympics."', outcomeCode: 'ELA.6.CV.1', difficulty: 2 },
    { id: 'u2-l7-q6', questionText: 'Why is sentence variety important in writing?', options: [{ label: 'It makes the writing longer', value: 'a' }, { label: 'Mixing simple and compound sentences creates rhythm and keeps the reader engaged', value: 'b', correct: true }, { label: 'It is not important', value: 'c' }, { label: 'Only compound sentences are good', value: 'd' }], correctAnswer: 'b', explanation: 'Variety creates flow — short sentences create impact; longer sentences create detail and complexity. The mix produces rhythm.', outcomeCode: 'ELA.6.CV.3', difficulty: 2 },
    { id: 'u2-l7-q7', questionText: 'Which revision improves this passage? "She ran. She hid. She cried."', options: [{ label: 'Keep it — it is perfect', value: 'a' }, { label: 'Combine: "She ran and hid behind the door, tears already streaming down her face."', value: 'b', correct: true }, { label: 'Add more simple sentences', value: 'c' }, { label: 'Remove all sentences', value: 'd' }], correctAnswer: 'b', explanation: 'The revision combines choppy sentences into a compound structure and adds a sensory detail ("tears streaming"). This creates better flow and imagery.', outcomeCode: 'ELA.6.WC.3', difficulty: 2 },
    { id: 'u2-l7-q8', questionText: 'A colon introduces a list after a complete sentence. Which is INCORRECT?', options: [{ label: '"She needed: water, shelter, and fire."', value: 'b', correct: true }, { label: '"Three things mattered most: trust, loyalty, and honesty."', value: 'a' }, { label: '"There was one rule: never go alone."', value: 'c' }, { label: '"The ingredients are simple: flour, sugar, and eggs."', value: 'd' }], correctAnswer: 'b', explanation: '"She needed" is incomplete without the list — the colon incorrectly interrupts the sentence. The correct version: "She needed water, shelter, and fire."', outcomeCode: 'ELA.6.CV.2', difficulty: 2 },
  ];

  for (const q of l7Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L7, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L7: ${l7Qs.length} questions (target: CV.1, CV.2, CV.3, review: WC.3)`);

  // ════════════════════════════════════════
  // LESSON 8: Story Showcase
  // Target: ELA.6.WC.1 (writing process — publish)
  // Secondary: ELA.6.WC.3 (revision)
  // Review: ELA.6.OC.3 (collaborative dialogue)
  // ════════════════════════════════════════
  const L8 = 'g6-ela-u2-l8';

  const l8Blocks = [
    { id: 'u2-l8-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>The Final Stage: Publish</h3><p>You have planned, drafted, deepened characters, added craft, and edited for conventions. Now it\'s time to <strong>revise for impact</strong> and <strong>share your work</strong>.</p><p>Publishing does not mean printing a book. It means <em>making your writing available to an audience</em> — sharing it, presenting it, or submitting it.</p>' } },
    { id: 'u2-l8-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Final Revision Checklist</h3><p>Before publishing, read through your story one more time and check:</p><ul><li>✅ <strong>Opening:</strong> Does it hook the reader immediately?</li><li>✅ <strong>Conflict:</strong> Is certain, and does it build through rising action?</li><li>✅ <strong>Character:</strong> Is the protagonist round with clear motivation?</li><li>✅ <strong>Craft:</strong> Have I used show-don\'t-tell, sensory detail, and dialogue?</li><li>✅ <strong>Conventions:</strong> Capitalization, punctuation, grammar — all clean?</li><li>✅ <strong>Ending:</strong> Does the resolution feel earned and satisfying?</li><li>✅ <strong>Read aloud:</strong> Does it flow? Are there awkward spots?</li></ul>' } },
    { id: 'u2-l8-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Peer Feedback Protocol</h3><p>Before finalizing, exchange stories with a classmate. Use these guidelines:</p><ol><li><strong>Stars:</strong> Name 2 specific things the writer did well. Be precise: "Your dialogue in paragraph 3 really showed Maya\'s determination."</li><li><strong>Wish:</strong> Name 1 specific area for improvement. Be constructive: "I wish the ending gave more closure — I wanted to know what happened to the dog."</li><li><strong>Wonder:</strong> Ask 1 question about the story: "I wonder why the character chose NOT to tell her parents?"</li></ol>' } },
    { id: 'u2-l8-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Complete the FINAL revision of your story.\n\nAfter revising, paste your complete, polished story below. It should be at least 350 words with:\n- A hook opening (no "My name is..." or "Once upon a time...")\n- A clear protagonist with motivation\n- A conflict that builds through rising action to a climax\n- Show-don\'t-tell, sensory details, and dialogue\n- Correct capitalization, punctuation, and grammar\n- A satisfying resolution', minLength: 350 } },
    { id: 'u2-l8-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Look back at your complete writing journey for Unit 2:\n\n1. What is the biggest improvement between your first plan and your final story?\n2. Which writer\'s tool (show-don\'t-tell, sensory detail, dialogue, flashback, etc.) did you use MOST effectively? Give an example from your story.\n3. What would you do differently next time?', minLength: 40 } },
  ];

  for (const b of l8Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L8, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L8: ${l8Blocks.length} blocks`);

  const l8Qs = [
    { id: 'u2-l8-q1', questionText: 'The correct ORDER of the writing process is:', options: [{ label: 'Draft → Plan → Publish → Edit', value: 'a' }, { label: 'Plan → Draft → Revise → Edit → Publish', value: 'b', correct: true }, { label: 'Publish → Plan → Draft', value: 'c' }, { label: 'Edit → Draft → Plan → Publish', value: 'd' }], correctAnswer: 'b', explanation: 'The writing process follows: Plan (ideas) → Draft (write) → Revise (content changes) → Edit (conventions fixes) → Publish (share).', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u2-l8-q2', questionText: 'What is the difference between REVISING and EDITING?', options: [{ label: 'They are the same thing', value: 'a' }, { label: 'Revising focuses on content, clarity, and impact; editing fixes spelling, grammar, and conventions', value: 'b', correct: true }, { label: 'Editing comes first', value: 'c' }, { label: 'Revising means deleting the whole thing', value: 'd' }], correctAnswer: 'b', explanation: 'Revising = big-picture changes (improving ideas, structure, voice). Editing = surface-level corrections (spelling, grammar, punctuation).', outcomeCode: 'ELA.6.WC.3', difficulty: 1 },
    { id: 'u2-l8-q3', questionText: 'Constructive peer feedback should:', options: [{ label: 'Only point out negatives', value: 'a' }, { label: 'Identify specific strengths AND offer specific, actionable suggestions for improvement', value: 'b', correct: true }, { label: 'Say "it\'s good" or "it\'s bad"', value: 'c' }, { label: 'Rewrite the other person\'s story', value: 'd' }], correctAnswer: 'b', explanation: 'Good feedback is specific (not vague), balanced (strengths AND growth areas), and actionable (the writer can DO something with it).', outcomeCode: 'ELA.6.OC.3', difficulty: 1 },
    { id: 'u2-l8-q4', questionText: '"Publishing" in the writing process means:', options: [{ label: 'Printing a physical book', value: 'a' }, { label: 'Making your writing available to an audience — sharing it in any form', value: 'b', correct: true }, { label: 'Submitting it to a publishing company', value: 'c' }, { label: 'Posting it online', value: 'd' }], correctAnswer: 'b', explanation: 'Publishing simply means sharing your finished work with readers — reading aloud, displaying in class, submitting digitally, etc.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u2-l8-q5', questionText: 'When reading your story aloud to check it, you should listen for:', options: [{ label: 'How fast you can read it', value: 'a' }, { label: 'Awkward phrasing, choppy rhythm, and spots where the flow breaks', value: 'b', correct: true }, { label: 'Whether it rhymes', value: 'c' }, { label: 'How many big words you used', value: 'd' }], correctAnswer: 'b', explanation: 'Reading aloud reveals problems your eyes miss — awkward wording, unnatural rhythm, and places where sentences don\'t flow smoothly.', outcomeCode: 'ELA.6.WC.3', difficulty: 1 },
    { id: 'u2-l8-q6', questionText: 'A satisfying resolution should:', options: [{ label: 'Always be happy', value: 'a' }, { label: 'Feel earned — connected to the conflict, showing how the character has grown or changed', value: 'b', correct: true }, { label: 'Introduce a new character', value: 'c' }, { label: 'End with "The End"', value: 'd' }], correctAnswer: 'b', explanation: 'A resolution should feel like a natural outcome of the story\'s events — it resolves the conflict and shows how the protagonist has been affected.', outcomeCode: 'ELA.6.TF.1', difficulty: 2 },
    { id: 'u2-l8-q7', questionText: 'In the Stars/Wish/Wonder feedback model, a "Wish" should:', options: [{ label: 'Be a vague comment like "I wish it was better"', value: 'a' }, { label: 'Identify a specific area for improvement with a constructive suggestion', value: 'b', correct: true }, { label: 'Only name negative aspects', value: 'c' }, { label: 'Change the story\'s ending', value: 'd' }], correctAnswer: 'b', explanation: '"I wish the ending gave more closure — I wanted to know what happened to the dog" is specific and actionable. "Make it better" is not helpful.', outcomeCode: 'ELA.6.OC.3', difficulty: 2 },
    { id: 'u2-l8-q8', questionText: 'A writer notices their story has 10 simple sentences in a row. The BEST revision strategy is:', options: [{ label: 'Add 10 more simple sentences', value: 'a' }, { label: 'Combine some into compound sentences and vary the structure for rhythm', value: 'b', correct: true }, { label: 'Delete all of them', value: 'c' }, { label: 'Make all of them compound sentences', value: 'd' }], correctAnswer: 'b', explanation: 'Mixing sentence types (simple, compound, complex) creates rhythm and flow. Variety keeps the reader engaged.', outcomeCode: 'ELA.6.WC.3', difficulty: 2 },
  ];

  for (const q of l8Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L8, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L8: ${l8Qs.length} questions (target: WC.1, WC.3, review: OC.3, TF.1)`);

  // ── Summary ──
  console.log(`
╔═══════════════════════════════════════════════╗
║   ELA UNIT 2 (L5–L8) SEED COMPLETE          ║
╠═══════════════════════════════════════════════╣
║ Lessons:    4                                ║
║ Blocks:     ${String(l5Blocks.length + l6Blocks.length + l7Blocks.length + l8Blocks.length).padStart(2)}                               ║
║ Questions:  ${String(l5Qs.length + l6Qs.length + l7Qs.length + l8Qs.length).padStart(2)}                               ║
╚═══════════════════════════════════════════════╝`);
}

main()
  .catch((e) => { console.error('❌ Seed error:', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); pool.end(); });
