// ============================================
// Seed Science Unit E L4-L7 — Planet Earth
// ============================================
// Run: npx tsx prisma/seed-sci-ue-l4-l7.ts

import { config } from 'dotenv';
config({ path: '.env.local' });
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function seed(ID: string, title: string, data: { lesson: Record<string, unknown>, blocks: Array<Record<string, unknown>>, questions: Array<Record<string, unknown>> }) {
  console.log(`\n🌍 Seeding ${title}...`);
  await prisma.lesson.update({ where: { id: ID }, data: data.lesson as any });
  await prisma.lessonBlock.deleteMany({ where: { lessonId: ID } });
  await prisma.quizQuestion.deleteMany({ where: { lessonId: ID } });
  for (const b of data.blocks) { await prisma.lessonBlock.create({ data: { ...b, lessonId: ID } as any }); }
  console.log(`  ✅ ${data.blocks.length} blocks`);
  for (const q of data.questions) { await prisma.quizQuestion.create({ data: { ...q, lessonId: ID } as any }); }
  console.log(`  ✅ ${data.questions.length} questions`);
}

const L4 = {
  lesson: { subjectMode: 'SCIENCE', estimatedMinutes: 45, learningGoal: 'Distinguish mechanical and chemical weathering, identify agents of erosion, and explain how Alberta landforms formed through weathering and erosion.', successCriteria: 'I can classify weathering types, name 4 erosion agents, and explain how the Drumheller Badlands and hoodoos formed.', materials: 'Science notebook', reflectionPrompt: 'What evidence of weathering or erosion can you see in your own community?', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
  blocks: [
    { id: 'ue-l4-learn-1', section: 'LEARN', blockType: 'VOCABULARY', order: 1, content: { terms: [{ term: 'Mechanical Weathering', definition: 'Physical breakdown of rock without changing its chemistry — freeze-thaw, root growth, abrasion.', example: 'Water freezing in cracks breaks rock apart.' }, { term: 'Chemical Weathering', definition: 'Dissolving or altering minerals in rock — acid rain, oxidation, carbonation.', example: 'Acid rain dissolving limestone over centuries.' }, { term: 'Erosion', definition: 'Transport of broken rock and sediment by wind, water, ice, or gravity.', example: 'A river carrying sand downstream.' }, { term: 'Sedimentation', definition: 'When transported sediment settles and accumulates in layers.', example: 'River delta building up at a river mouth.' }] } },
    { id: 'ue-l4-learn-2', section: 'LEARN', blockType: 'VIDEO', order: 2, content: { url: 'https://www.youtube.com/embed/R-Iak3Wvh9c', title: 'Weathering & Erosion', transcript: 'Video explaining weathering and erosion processes.' } },
    { id: 'ue-l4-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>🌬️ Weathering Types</h3><table><thead><tr><th>Type</th><th>How It Works</th><th>Examples</th></tr></thead><tbody><tr><td>🔨 Mechanical</td><td>Physical force breaks rock (no chemical change)</td><td>Freeze-thaw, root growth, wind/water abrasion</td></tr><tr><td>🧪 Chemical</td><td>Chemical reactions dissolve or alter minerals</td><td>Acid rain on limestone, rust (oxidation), carbonation</td></tr></tbody></table><h3>Agents of Erosion</h3><ul><li>💧 <strong>Water:</strong> Rivers, rain, waves — the #1 erosion agent</li><li>🌬️ <strong>Wind:</strong> Carries sand particles that sandblast rock</li><li>🧊 <strong>Ice/Glaciers:</strong> Massive ice sheets carve valleys — shaped the Rockies!</li><li>⬇️ <strong>Gravity:</strong> Landslides, rockfalls, soil creep</li></ul><p><strong>Alberta:</strong> The Drumheller Badlands and hoodoos formed from millions of years of wind and water erosion on soft sedimentary rock. Harder cap rocks protected softer layers below, creating the mushroom-shaped hoodoos.</p>' } },
    { id: 'ue-l4-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Classify each scenario as mechanical or chemical weathering:', pairs: [{ left: 'Water freezes in a crack, expanding and splitting rock', right: 'Mechanical' }, { left: 'Acid rain dissolves limestone', right: 'Chemical' }, { left: 'Tree roots push through cracks in concrete', right: 'Mechanical' }, { left: 'Iron in rock turns to rust (oxidation)', right: 'Chemical' }, { left: 'Wind-blown sand smooths a cliff face', right: 'Mechanical' }, { left: 'Carbonic acid in groundwater dissolves caves', right: 'Chemical' }] } },
    { id: 'ue-l4-reflect-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Explain how weathering and erosion created the Drumheller Badlands and hoodoos over millions of years. Include both weathering types and identify the erosion agents.', minLength: 80, rubricHint: 'Names mechanical + chemical weathering. Identifies wind and water as agents. Explains cap rock/hoodoo formation.', teacherReviewRequired: false } },
  ],
  questions: [
    { id: 'ue-l4-q1', questionText: 'Freeze-thaw weathering is a type of:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Chemical weathering', value: 'a' }, { label: 'Mechanical weathering', value: 'b', correct: true }, { label: 'Erosion', value: 'c' }, { label: 'Sedimentation', value: 'd' }], correctAnswer: 'b', explanation: 'Water expanding as it freezes physically breaks rock — mechanical (no chemical change).', outcomeCode: 'SCI.7.E.3.1', difficulty: 1 },
    { id: 'ue-l4-q2', questionText: 'Acid rain dissolving limestone is an example of:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Mechanical weathering', value: 'a' }, { label: 'Chemical weathering', value: 'b', correct: true }, { label: 'Erosion', value: 'c' }, { label: 'Sedimentation', value: 'd' }], correctAnswer: 'b', explanation: 'The acid reacts with and dissolves the rock\'s minerals — a chemical change.', outcomeCode: 'SCI.7.E.3.1', difficulty: 1 },
    { id: 'ue-l4-q3', questionText: 'The #1 agent of erosion on Earth is:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Wind', value: 'a' }, { label: 'Water', value: 'b', correct: true }, { label: 'Ice', value: 'c' }, { label: 'Gravity', value: 'd' }], correctAnswer: 'b', explanation: 'Water (rivers, rain, waves, glacial melt) moves the most sediment worldwide.', outcomeCode: 'SCI.7.E.3.1', difficulty: 1 },
    { id: 'ue-l4-q4', questionText: 'The Drumheller hoodoos formed because:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Volcanic eruptions', value: 'a' }, { label: 'Hard cap rocks protected softer layers below from erosion', value: 'b', correct: true }, { label: 'Earthquakes split the ground', value: 'c' }, { label: 'Humans carved them', value: 'd' }], correctAnswer: 'b', explanation: 'Harder rock on top shields softer sedimentary rock below, creating mushroom shapes.', outcomeCode: 'SCI.7.E.3.1', difficulty: 2 },
    { id: 'ue-l4-q5', questionText: 'Erosion is different from weathering because:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'It\'s the same thing', value: 'a' }, { label: 'Erosion transports broken material; weathering breaks it down', value: 'b', correct: true }, { label: 'Erosion creates rocks', value: 'c' }, { label: 'Weathering moves rocks', value: 'd' }], correctAnswer: 'b', explanation: 'Weathering = breaking down. Erosion = moving the broken pieces somewhere else.', outcomeCode: 'SCI.7.E.3.1', difficulty: 1 },
    { id: 'ue-l4-q6', questionText: 'Glaciers shaped Alberta\'s landscape by:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Melting all rock', value: 'a' }, { label: 'Carving valleys and depositing sediment as they retreated', value: 'b', correct: true }, { label: 'Only causing earthquakes', value: 'c' }, { label: 'Creating volcanoes', value: 'd' }], correctAnswer: 'b', explanation: 'Massive ice sheets carved U-shaped valleys and left behind sediment deposits.', outcomeCode: 'SCI.7.E.3.1', difficulty: 2 },
    { id: 'ue-l4-q7', questionText: 'Sedimentation occurs when:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Rock melts', value: 'a' }, { label: 'Transported sediment settles and accumulates in layers', value: 'b', correct: true }, { label: 'Wind blows', value: 'c' }, { label: 'Rock gets harder', value: 'd' }], correctAnswer: 'b', explanation: 'When erosion slows, sediment particles settle and build up in layers.', outcomeCode: 'SCI.7.E.3.1', difficulty: 1 },
    { id: 'ue-l4-q8', questionText: 'Tree roots cracking pavement is:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Chemical weathering', value: 'a' }, { label: 'Mechanical weathering', value: 'b', correct: true }, { label: 'Erosion', value: 'c' }, { label: 'Sedimentation', value: 'd' }], correctAnswer: 'b', explanation: 'Physical force from growing roots breaks the surface — no chemical change.', outcomeCode: 'SCI.7.E.3.1', difficulty: 1 },
  ],
};

const L5 = {
  lesson: { subjectMode: 'SCIENCE', estimatedMinutes: 45, learningGoal: 'Explain how fossils form in sedimentary rock, use fossils to determine relative age of rock layers, and describe Alberta\'s significance in fossil science.', successCriteria: 'I can explain fossil formation, use superposition for relative dating, identify index fossils, and describe Drumheller\'s importance.', materials: 'Science notebook', reflectionPrompt: 'If you could visit the Royal Tyrrell Museum in Drumheller, what fossils would you most want to see?', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
  blocks: [
    { id: 'ue-l5-learn-1', section: 'LEARN', blockType: 'VOCABULARY', order: 1, content: { terms: [{ term: 'Fossil', definition: 'Preserved remains or traces of ancient life — bones, shells, footprints, leaf imprints.', example: 'Dinosaur bones in the Alberta Badlands.' }, { term: 'Relative Dating', definition: 'Determining which rock layers are older or younger by position — deeper = older.', example: 'The bottom layer of rock in a cliff is the oldest.' }, { term: 'Geological Time Scale', definition: 'Timeline dividing Earth\'s 4.6 billion year history into eons, eras, periods, and epochs.', example: 'Dinosaurs lived in the Mesozoic Era.' }, { term: 'Index Fossil', definition: 'Fossils from organisms that lived briefly but widely — useful for dating rock layers.', example: 'Trilobites are index fossils for the Paleozoic Era.' }] } },
    { id: 'ue-l5-learn-2', section: 'LEARN', blockType: 'VIDEO', order: 2, content: { url: 'https://www.youtube.com/embed/3LObb5WxMdw', title: 'Fossils & Deep Time', transcript: 'Video explaining fossil formation and geological time.' } },
    { id: 'ue-l5-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>🦕 How Fossils Form</h3><ol><li>An organism dies and is quickly buried by sediment</li><li>Soft parts decompose; hard parts (bones, shells) remain</li><li>Minerals replace original material over millions of years (mineralization)</li><li>Rock layers above compact and cement the remains</li><li>Erosion eventually exposes the fossil at the surface</li></ol><p><strong>Key Rule:</strong> Fossils are almost always found in <strong>sedimentary rock</strong> because igneous (melting) and metamorphic (heat/pressure) destroy organic remains.</p><h3>📏 Law of Superposition</h3><p>In undisturbed rock layers, the <strong>bottom layer is the oldest</strong> and the <strong>top layer is the youngest</strong>. This is how we determine relative age.</p><p><strong>Alberta:</strong> Drumheller\'s Royal Tyrrell Museum has over 160,000 specimens. Alberta\'s badlands are one of the world\'s richest dinosaur fossil sites, with species like Albertosaurus and Pachyrhinosaurus!</p>' } },
    { id: 'ue-l5-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Match each concept to its definition:', pairs: [{ left: 'Deeper rock layers are older', right: 'Law of Superposition' }, { left: 'Fossils from short-lived, widespread organisms', right: 'Index Fossils' }, { left: 'Minerals replace original bone material', right: 'Mineralization/Fossilization' }, { left: 'Determining which layer is older without exact dates', right: 'Relative Dating' }] } },
    { id: 'ue-l5-reflect-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Why are fossils almost never found in igneous or metamorphic rock? Explain using your knowledge of how these rocks form.', minLength: 60, rubricHint: 'Explains igneous = melting destroys fossils. Metamorphic = heat/pressure destroys them. Only sedimentary preserves.', teacherReviewRequired: false } },
  ],
  questions: [
    { id: 'ue-l5-q1', questionText: 'Fossils are most commonly found in:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Igneous rock', value: 'a' }, { label: 'Metamorphic rock', value: 'b' }, { label: 'Sedimentary rock', value: 'c', correct: true }, { label: 'All types equally', value: 'd' }], correctAnswer: 'c', explanation: 'Sedimentary layers gently bury and preserve remains; igneous and metamorphic destroy them.', outcomeCode: 'SCI.7.E.3.2', difficulty: 1 },
    { id: 'ue-l5-q2', questionText: 'The Law of Superposition states:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Top layers are oldest', value: 'a' }, { label: 'Bottom layers are oldest in undisturbed rock', value: 'b', correct: true }, { label: 'All layers are the same age', value: 'c' }, { label: 'Fossils determine layer position', value: 'd' }], correctAnswer: 'b', explanation: 'In undisturbed layers, the bottom was deposited first and is therefore oldest.', outcomeCode: 'SCI.7.E.3.2', difficulty: 1 },
    { id: 'ue-l5-q3', questionText: 'Index fossils are useful because:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'They are the biggest', value: 'a' }, { label: 'They lived briefly but widely, helping date specific time periods', value: 'b', correct: true }, { label: 'They are the prettiest', value: 'c' }, { label: 'They are always dinosaurs', value: 'd' }], correctAnswer: 'b', explanation: 'Short existence + wide distribution = great markers for specific time periods.', outcomeCode: 'SCI.7.E.3.2', difficulty: 2 },
    { id: 'ue-l5-q4', questionText: 'Alberta\'s Drumheller region is famous for:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Gold mining', value: 'a' }, { label: 'Being one of the world\'s richest dinosaur fossil sites', value: 'b', correct: true }, { label: 'Volcanic activity', value: 'c' }, { label: 'Glaciers', value: 'd' }], correctAnswer: 'b', explanation: 'Drumheller\'s badlands contain extraordinary dinosaur fossils, including Albertosaurus.', outcomeCode: 'SCI.7.E.3.2', difficulty: 1 },
    { id: 'ue-l5-q5', questionText: 'Fossils form when organisms are:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Exposed to sunlight', value: 'a' }, { label: 'Quickly buried by sediment before decomposing', value: 'b', correct: true }, { label: 'Melted by lava', value: 'c' }, { label: 'Washed away by rain', value: 'd' }], correctAnswer: 'b', explanation: 'Quick burial prevents decomposition and allows mineralization over millions of years.', outcomeCode: 'SCI.7.E.3.2', difficulty: 1 },
    { id: 'ue-l5-q6', questionText: 'Relative dating tells us:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'The exact age in years', value: 'a' }, { label: 'Which layers are older or younger relative to each other', value: 'b', correct: true }, { label: 'What colour rocks are', value: 'c' }, { label: 'Nothing useful', value: 'd' }], correctAnswer: 'b', explanation: 'Relative dating compares ages — this layer is older/younger than that one — without exact years.', outcomeCode: 'SCI.7.E.3.2', difficulty: 1 },
    { id: 'ue-l5-q7', questionText: 'Fossils are rarely found in igneous rock because:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Igneous rock is too heavy', value: 'a' }, { label: 'The heat of magma destroys organic remains', value: 'b', correct: true }, { label: 'Igneous rock is too old', value: 'c' }, { label: 'Animals avoid volcanoes', value: 'd' }], correctAnswer: 'b', explanation: 'Magma temperatures (700-1200°C) destroy any organic material completely.', outcomeCode: 'SCI.7.E.3.2', difficulty: 2 },
    { id: 'ue-l5-q8', questionText: 'Earth is approximately:', questionType: 'MULTIPLE_CHOICE', options: [{ label: '6,000 years old', value: 'a' }, { label: '4.6 billion years old', value: 'b', correct: true }, { label: '1 million years old', value: 'c' }, { label: '100 billion years old', value: 'd' }], correctAnswer: 'b', explanation: 'Radiometric dating of meteorites and Earth rocks shows ~4.6 billion years.', outcomeCode: 'SCI.7.E.3.2', difficulty: 1 },
  ],
};

const L6 = {
  lesson: { subjectMode: 'SCIENCE', estimatedMinutes: 45, learningGoal: 'Describe methods to explore for geological resources, explain environmental impacts of extraction, and discuss Alberta\'s role as a resource producer.', successCriteria: 'I can match exploration methods to resources, classify benefits vs costs of extraction, and discuss reclamation.', materials: 'Science notebook', reflectionPrompt: 'How do Alberta\'s geological resources affect your daily life? Think about energy, products, and jobs.', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
  blocks: [
    { id: 'ue-l6-learn-1', section: 'LEARN', blockType: 'VOCABULARY', order: 1, content: { terms: [{ term: 'Non-renewable Resource', definition: 'Resources that take millions of years to form — oil, gas, coal, minerals. Cannot be replaced in a human lifetime.', example: 'Alberta\'s oil sands.' }, { term: 'Geological Survey', definition: 'Systematic study of an area\'s rocks, minerals, and structures to find resources.', example: 'Seismic surveys that use sound waves to map underground formations.' }, { term: 'Reclamation', definition: 'Restoring land disturbed by mining back to a usable state.', example: 'Replanting trees on former mine sites.' }, { term: 'Oil Sands', definition: 'Naturally occurring mixture of sand, clay, water, and bitumen — Alberta\'s largest oil source.', example: 'The Athabasca Oil Sands near Fort McMurray.' }] } },
    { id: 'ue-l6-learn-2', section: 'LEARN', blockType: 'VIDEO', order: 2, content: { url: 'https://www.youtube.com/embed/wQhFQFeYdJU', title: 'Alberta\'s Geological Resources', transcript: 'Video exploring Alberta\'s resource economy.' } },
    { id: 'ue-l6-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>⛏️ Alberta\'s Key Geological Resources</h3><ul><li>🛢️ <strong>Oil & Gas:</strong> Alberta produces ~80% of Canada\'s oil. The Athabasca Oil Sands are one of the world\'s largest petroleum reserves.</li><li>⚫ <strong>Coal:</strong> Historically important for power generation. Alberta is transitioning to renewables.</li><li>💎 <strong>Minerals:</strong> Potash, limestone, gravel, and sand used in construction and agriculture.</li></ul><h3>Exploration Methods</h3><ul><li>🔊 <strong>Seismic Surveys:</strong> Sound waves map underground rock structures</li><li>🧲 <strong>Magnetic Surveys:</strong> Detect variations in Earth\'s magnetic field from mineral deposits</li><li>🛰️ <strong>Satellite Imagery:</strong> Identify surface features that indicate underground resources</li><li>🔩 <strong>Core Drilling:</strong> Extract cylindrical rock samples from underground</li></ul><h3>Environmental Balance</h3><p><strong>Benefits:</strong> Jobs, tax revenue, energy security, infrastructure. <strong>Costs:</strong> Habitat destruction, water pollution, CO₂ emissions, tailings ponds. <strong>Reclamation</strong> is required by Alberta law — companies must restore land after extraction.</p>' } },
    { id: 'ue-l6-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Classify each statement as a benefit or cost of resource extraction:', pairs: [{ left: 'Creates thousands of well-paying jobs', right: 'Benefit' }, { left: 'Produces tailings ponds with toxic water', right: 'Cost' }, { left: 'Generates tax revenue for schools and hospitals', right: 'Benefit' }, { left: 'Destroys wildlife habitat', right: 'Cost' }, { left: 'Provides energy for heating homes', right: 'Benefit' }, { left: 'Increases CO₂ emissions contributing to climate change', right: 'Cost' }] } },
    { id: 'ue-l6-reflect-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Alberta\'s oil sands are among the world\'s largest petroleum reserves. Discuss both economic benefits and environmental costs. What role should reclamation play?', minLength: 80, rubricHint: 'Names specific benefits and costs. Discusses reclamation. Shows balanced, evidence-based thinking.', teacherReviewRequired: false } },
  ],
  questions: [
    { id: 'ue-l6-q1', questionText: 'Alberta produces approximately what percentage of Canada\'s oil?', questionType: 'MULTIPLE_CHOICE', options: [{ label: '20%', value: 'a' }, { label: '50%', value: 'b' }, { label: '80%', value: 'c', correct: true }, { label: '10%', value: 'd' }], correctAnswer: 'c', explanation: 'Alberta is Canada\'s largest oil producer, accounting for about 80% of national production.', outcomeCode: 'SCI.7.E.4.1', difficulty: 1 },
    { id: 'ue-l6-q2', questionText: 'Oil sands are a mixture of:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Water only', value: 'a' }, { label: 'Sand, clay, water, and bitumen', value: 'b', correct: true }, { label: 'Pure oil', value: 'c' }, { label: 'Coal and gas', value: 'd' }], correctAnswer: 'b', explanation: 'Oil sands (or tar sands) contain bitumen mixed with sand, clay, and water.', outcomeCode: 'SCI.7.E.4.1', difficulty: 1 },
    { id: 'ue-l6-q3', questionText: 'Reclamation means:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Extracting more resources', value: 'a' }, { label: 'Restoring land disturbed by mining to a usable state', value: 'b', correct: true }, { label: 'Building new mines', value: 'c' }, { label: 'Finding new oil deposits', value: 'd' }], correctAnswer: 'b', explanation: 'Reclamation restores ecosystems — replanting, reshaping land, and cleaning water.', outcomeCode: 'SCI.7.E.4.1', difficulty: 1 },
    { id: 'ue-l6-q4', questionText: 'Seismic surveys help find resources by:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Digging holes', value: 'a' }, { label: 'Using sound waves to map underground rock structures', value: 'b', correct: true }, { label: 'Measuring temperature', value: 'c' }, { label: 'Looking at the sky', value: 'd' }], correctAnswer: 'b', explanation: 'Sound waves bounce off underground rock layers, revealing hidden structures and resources.', outcomeCode: 'SCI.7.E.4.1', difficulty: 1 },
    { id: 'ue-l6-q5', questionText: 'Non-renewable resources are problematic because:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'They are unlimited', value: 'a' }, { label: 'They take millions of years to form and will eventually be depleted', value: 'b', correct: true }, { label: 'They are cheap', value: 'c' }, { label: 'They have no environmental impact', value: 'd' }], correctAnswer: 'b', explanation: 'Oil, gas, and coal formed over millions of years — we use them far faster than they form.', outcomeCode: 'SCI.7.E.4.1', difficulty: 1 },
    { id: 'ue-l6-q6', questionText: 'A major environmental concern of oil sands extraction is:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Too much reclamation', value: 'a' }, { label: 'Tailings ponds containing toxic water', value: 'b', correct: true }, { label: 'Creating too many jobs', value: 'c' }, { label: 'Generating too much tax revenue', value: 'd' }], correctAnswer: 'b', explanation: 'Tailings ponds hold water contaminated with heavy metals and chemicals from extraction.', outcomeCode: 'SCI.7.E.4.1', difficulty: 2 },
    { id: 'ue-l6-q7', questionText: 'Core drilling is used to:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Build buildings', value: 'a' }, { label: 'Extract rock samples from underground for analysis', value: 'b', correct: true }, { label: 'Make tunnels', value: 'c' }, { label: 'Find water only', value: 'd' }], correctAnswer: 'b', explanation: 'Core drilling extracts cylindrical rock samples, revealing underground geology.', outcomeCode: 'SCI.7.E.4.1', difficulty: 1 },
    { id: 'ue-l6-q8', questionText: 'Alberta law requires mining companies to:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Abandon sites after extraction', value: 'a' }, { label: 'Reclaim and restore land after mining is complete', value: 'b', correct: true }, { label: 'Pay no taxes', value: 'c' }, { label: 'Only mine in summer', value: 'd' }], correctAnswer: 'b', explanation: 'Alberta requires reclamation — companies must restore disturbed land to a productive state.', outcomeCode: 'SCI.7.E.4.1', difficulty: 1 },
  ],
};

const L7 = {
  lesson: { subjectMode: 'SCIENCE', estimatedMinutes: 60, learningGoal: 'Interpret a geological cross-section by analyzing rock layers, fossil evidence, geological events, and resource potential at a site in the Alberta Badlands.', successCriteria: 'I can analyze rock layers, use fossils for dating, create a geological timeline, and evaluate resource potential with environmental considerations.', materials: 'Science notebook, coloured pencils', reflectionPrompt: 'How does understanding Earth\'s geological history help us make better decisions about resource use today?', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
  blocks: [
    { id: 'ue-l7-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h2>🏆 Geological Cross-Section Interpretation</h2><p>You are a geologist studying a site in the Alberta Badlands. A construction crew has uncovered a cliff face showing multiple rock layers, fossils, a fault line, and evidence of an ancient volcanic eruption. Complete all 4 sections:</p><ol><li><strong>Rock Layer Analysis</strong> — Describe layers (bottom to top). What types? How did each form?</li><li><strong>Fossil Evidence</strong> — What fossils in each sedimentary layer? How do they determine age?</li><li><strong>Geological Events Timeline</strong> — Create a timeline (oldest → newest) including sedimentation, volcanism, faulting, erosion.</li><li><strong>Resource Potential & Environment</strong> — What resources might exist? Environmental considerations for extraction?</li></ol>' } },
    { id: 'ue-l7-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Part 1: Rock Layer Analysis — Describe the rock layers you would expect to see (bottom to top). What rock types would be present and how did each form?', minLength: 80, rubricHint: 'Names 3+ rock types in correct order. Links each to formation process. Uses vocabulary.', teacherReviewRequired: true } },
    { id: 'ue-l7-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: 'Part 2: Fossil Evidence — What fossils might be found in each sedimentary layer? How do they help determine the age of the rocks?', minLength: 80, rubricHint: 'Names specific fossil types. Explains relative dating. References index fossils.', teacherReviewRequired: true } },
    { id: 'ue-l7-prac-3', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 3, content: { prompt: 'Part 3: Create a timeline of geological events at this site (oldest to newest). Include sedimentation, volcanic activity, faulting, and erosion.', minLength: 80, rubricHint: 'Events in correct order. Includes all 4 event types. Uses superposition logic.', teacherReviewRequired: true } },
    { id: 'ue-l7-prac-4', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 4, content: { prompt: 'Part 4: Based on the geology, what resources might exist at this site? If extraction were proposed, what environmental considerations would you recommend?', minLength: 80, rubricHint: 'Identifies potential resources. Names environmental concerns. Discusses reclamation. Shows balanced thinking.', teacherReviewRequired: true } },
    { id: 'ue-l7-reflect-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Reflect on the entire Planet Earth unit. What was the most important concept you learned? How does understanding Earth\'s geological history help us make better decisions about resources and the environment?', minLength: 60, rubricHint: 'Makes personal connection. References unit content. Connects to real-world decisions.', teacherReviewRequired: false } },
  ],
  questions: [
    { id: 'ue-l7-q1', questionText: 'In a geological cross-section, the oldest layer is:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'At the top', value: 'a' }, { label: 'At the bottom', value: 'b', correct: true }, { label: 'In the middle', value: 'c' }, { label: 'Random position', value: 'd' }], correctAnswer: 'b', explanation: 'Law of Superposition: bottom layers were deposited first and are oldest.', outcomeCode: 'SCI.7.E.3.2', difficulty: 1 },
    { id: 'ue-l7-q2', questionText: 'A layer of basalt between sedimentary layers indicates:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Erosion', value: 'a' }, { label: 'A volcanic eruption occurred between sediment deposits', value: 'b', correct: true }, { label: 'Weathering', value: 'c' }, { label: 'Nothing', value: 'd' }], correctAnswer: 'b', explanation: 'A basalt (igneous) layer between sedimentary layers shows lava flowed between deposition periods.', outcomeCode: 'SCI.7.E.1.2', difficulty: 2 },
    { id: 'ue-l7-q3', questionText: 'A fault line cutting through rock layers shows:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'The rocks are all the same age', value: 'a' }, { label: 'The fault is younger than the layers it cuts through', value: 'b', correct: true }, { label: 'The fault formed first', value: 'c' }, { label: 'Erosion only', value: 'd' }], correctAnswer: 'b', explanation: 'A fault must be younger than the rocks it cuts — the rocks existed before the fault formed.', outcomeCode: 'SCI.7.E.3.2', difficulty: 2 },
    { id: 'ue-l7-q4', questionText: 'If a site has ancient marine fossils, the area was once:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'A desert', value: 'a' }, { label: 'Covered by an ocean or sea', value: 'b', correct: true }, { label: 'A mountain top', value: 'c' }, { label: 'A volcano', value: 'd' }], correctAnswer: 'b', explanation: 'Marine fossils in rock layers = that land was once under an ocean or sea.', outcomeCode: 'SCI.7.E.3.2', difficulty: 1 },
    { id: 'ue-l7-q5', questionText: 'Before extracting resources from a geological site, you should:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Start digging immediately', value: 'a' }, { label: 'Assess environmental impact and plan for reclamation', value: 'b', correct: true }, { label: 'Ignore the environment', value: 'c' }, { label: 'Only look at profit', value: 'd' }], correctAnswer: 'b', explanation: 'Responsible extraction requires environmental impact assessment and reclamation planning.', outcomeCode: 'SCI.7.E.4.1', difficulty: 1 },
    { id: 'ue-l7-q6', questionText: 'A geologist uses fossils and rock layers to:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Build houses', value: 'a' }, { label: 'Reconstruct the geological history of an area', value: 'b', correct: true }, { label: 'Predict the weather', value: 'c' }, { label: 'Make jewelry', value: 'd' }], correctAnswer: 'b', explanation: 'Fossils and rock layers are clues that reveal millions of years of Earth\'s history.', outcomeCode: 'SCI.7.E.3.2', difficulty: 1 },
    { id: 'ue-l7-q7', questionText: 'Sedimentary rock at a site might contain:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Only minerals', value: 'a' }, { label: 'Fossils, coal, oil, and natural gas', value: 'b', correct: true }, { label: 'Only igneous rock', value: 'c' }, { label: 'Nothing useful', value: 'd' }], correctAnswer: 'b', explanation: 'Sedimentary rock can contain fossils and fossil fuels (coal, oil, gas) formed from ancient organisms.', outcomeCode: 'SCI.7.E.4.1', difficulty: 1 },
    { id: 'ue-l7-q8', questionText: 'Understanding geological history helps us:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Nothing practical', value: 'a' }, { label: 'Find resources, predict hazards, and make environmental decisions', value: 'b', correct: true }, { label: 'Only name rocks', value: 'c' }, { label: 'Only study fossils', value: 'd' }], correctAnswer: 'b', explanation: 'Geological knowledge is essential for resource extraction, hazard prediction, and environmental stewardship.', outcomeCode: 'SCI.7.E.4.1', difficulty: 1 },
  ],
};

async function main() {
  console.log('🌍 ═══ SCIENCE UNIT E: L4-L7 ═══');
  await seed('g7-sci-ue-l4', 'UE L4: Weathering & Erosion', L4);
  await seed('g7-sci-ue-l5', 'UE L5: Fossils & Geological Time', L5);
  await seed('g7-sci-ue-l6', 'UE L6: Geological Resources', L6);
  await seed('g7-sci-ue-l7', 'UE L7: Performance Task', L7);
  console.log('\n✅ Unit E L4-L7 complete!');
}
main().catch(console.error).finally(() => { pool.end(); });
