// ============================================
// Seed ELA Unit 2 — "Story Power" (Lessons 1–4)
// ============================================
// First fully normalized unit — all quiz questions use child skill codes.
// Run: npx tsx prisma/seed-ela-u2-l1-l4.ts

import { config } from 'dotenv';
config({ path: '.env.local' });

import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('📖 Seeding ELA Unit 2 "Story Power" — Lessons 1–4');
  console.log('===================================================\n');

  // ── Ensure Unit 2 exists ──
  await prisma.unit.upsert({
    where: { id: 'g6-ela-u2' },
    update: { title: 'Story Power', description: 'Study fiction as both a reader and writer. Analyze mentor texts for narrative craft, then create your own original short story.' },
    create: {
      id: 'g6-ela-u2',
      subjectId: 'g6-ela',
      title: 'Story Power',
      description: 'Study fiction as both a reader and writer. Analyze mentor texts for narrative craft, then create your own original short story.',
      icon: '📕',
      order: 1,
    },
  });
  console.log('✅ Unit 2 upserted');

  // ── Lesson definitions ──
  const lessonDefs = [
    { id: 'g6-ela-u2-l1', title: 'What Makes a Great Story?', subtitle: 'Analyze fiction to identify protagonist, antagonist, conflict, and plot elements.', order: 1, learningGoal: 'Identify and analyze elements of fiction including protagonist, antagonist, conflict types, and basic plot structure.', successCriteria: 'I can identify the protagonist and antagonist in a story.\nI can name the type of conflict (person vs person, person vs self, person vs nature, person vs society).\nI can describe the basic plot structure (exposition, rising action, climax, falling action, resolution).', reflectionPrompt: 'Think of your favorite story (book, movie, or game). What conflict drives the story? Why does it keep you engaged?' },
    { id: 'g6-ela-u2-l2', title: 'Story Structures', subtitle: 'Explore subplot, flashback, flash-forward, and story-within-a-story.', order: 2, learningGoal: 'Recognize and explain how authors use complex plot structures to engage readers.', successCriteria: 'I can identify a subplot and explain how it connects to the main plot.\nI can recognize flashback and flash-forward and explain their effect.\nI can describe how a story-within-a-story works.', reflectionPrompt: 'Why might an author choose to use a flashback instead of telling the story in order? When would this be effective?' },
    { id: 'g6-ela-u2-l3', title: 'Exploring Sub-Genres', subtitle: 'Compare fantasy, sci-fi, historical fiction, mystery, and comedy.', order: 3, learningGoal: 'Compare fiction sub-genres by identifying their defining features and categorizing texts.', successCriteria: 'I can name at least 4 fiction sub-genres and describe what makes each one distinct.\nI can categorize a text by its sub-genre using specific evidence.\nI can explain how genre shapes what a reader expects.', reflectionPrompt: 'What is your favorite fiction sub-genre? What specific features of that genre do you enjoy most?' },
    { id: 'g6-ela-u2-l4', title: 'The Writer\'s Toolbox', subtitle: 'Sensory detail, dialogue, figurative language, and show-don\'t-tell.', order: 4, learningGoal: 'Analyze and practice using writer\'s craft techniques: sensory detail, dialogue, figurative language, and show-don\'t-tell.', successCriteria: 'I can identify sensory detail and explain its effect on the reader.\nI can explain the difference between showing and telling.\nI can use dialogue and figurative language to create vivid writing.', reflectionPrompt: 'Which writer\'s tool do you find most powerful: dialogue, sensory detail, or figurative language? Explain with an example.' },
  ];

  for (const l of lessonDefs) {
    await prisma.lesson.upsert({
      where: { id: l.id },
      update: { title: l.title, subtitle: l.subtitle, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
      create: { id: l.id, unitId: 'g6-ela-u2', title: l.title, subtitle: l.subtitle, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
    });
  }
  console.log('✅ Lessons 1–4 upserted');

  // ── Clear existing blocks and questions ──
  for (const l of lessonDefs) {
    await prisma.lessonBlock.deleteMany({ where: { lessonId: l.id } });
    await prisma.quizQuestion.deleteMany({ where: { lessonId: l.id } });
  }

  // ════════════════════════════════════════
  // LESSON 1: What Makes a Great Story?
  // Target: ELA.6.TF.1 (fiction elements)
  // Review: ELA.6.RC.1 (inference from U1)
  // ════════════════════════════════════════
  const L1 = 'g6-ela-u2-l1';

  const l1Blocks = [
    { id: 'u2-l1-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>What Makes Fiction Powerful?</h3><p>Every great story has four essential elements working together:</p><ul><li><strong>Character:</strong> The people (or creatures) in the story. The <em>protagonist</em> is the main character. The <em>antagonist</em> is the force working against them.</li><li><strong>Conflict:</strong> The central problem or struggle that drives the plot forward.</li><li><strong>Plot:</strong> The sequence of events — how the story unfolds.</li><li><strong>Setting:</strong> Where and when the story takes place.</li></ul><p>Without conflict, there is no story. Conflict creates tension, and tension keeps readers turning pages.</p>' } },
    { id: 'u2-l1-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Types of Conflict</h3><table style="width:100%;border-collapse:collapse"><tr style="background:#f1f5f9"><th style="padding:8px;border:1px solid #e2e8f0;text-align:left">Type</th><th style="padding:8px;border:1px solid #e2e8f0;text-align:left">What It Means</th><th style="padding:8px;border:1px solid #e2e8f0;text-align:left">Example</th></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Person vs Person</strong></td><td style="padding:8px;border:1px solid #e2e8f0">A character struggles against another character</td><td style="padding:8px;border:1px solid #e2e8f0">Harry Potter vs Voldemort</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Person vs Self</strong></td><td style="padding:8px;border:1px solid #e2e8f0">A character wrestles with their own feelings, fears, or choices</td><td style="padding:8px;border:1px solid #e2e8f0">A student trying to decide whether to speak up about bullying</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Person vs Nature</strong></td><td style="padding:8px;border:1px solid #e2e8f0">A character faces a natural force</td><td style="padding:8px;border:1px solid #e2e8f0">Hatchet — surviving in the wilderness</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Person vs Society</strong></td><td style="padding:8px;border:1px solid #e2e8f0">A character challenges rules, traditions, or expectations</td><td style="padding:8px;border:1px solid #e2e8f0">The Giver — a society that controls everything</td></tr></table>' } },
    { id: 'u2-l1-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Plot Structure: The Story Arc</h3><p>Most stories follow a predictable pattern called the <em>story arc</em>:</p><ol><li><strong>Exposition:</strong> Introduces characters, setting, and the \"normal world\"</li><li><strong>Rising Action:</strong> Events that build tension and develop the conflict</li><li><strong>Climax:</strong> The turning point — the most intense moment</li><li><strong>Falling Action:</strong> Events after the climax that begin to resolve the conflict</li><li><strong>Resolution:</strong> The conflict is resolved and loose ends are tied up</li></ol>' } },
    { id: 'u2-l1-learn-4', section: 'LEARN', blockType: 'TEXT', order: 4, content: { html: '<h3>Anchor Text: "The Lighthouse Keeper\'s Daughter"</h3><blockquote style="border-left:3px solid #7c5cf5;padding:12px 16px;margin:12px 0;font-style:italic;color:#475569">"Mara pressed her face against the cold glass of the lighthouse window. Below, the sea churned and roared, swallowing the dock piece by piece. The storm had arrived three days early.<br><br>Her father should have been back by now.<br><br>She glanced at the emergency radio — dead. The backup batteries, still in their packaging on the mainland. Every choice she made from this moment would matter.<br><br>Mara pulled on her father\'s oilskin coat — far too big, smelling of salt and engine grease — and descended the spiral stairs. Thirty-seven steps. She had counted them a thousand times, playing. This time was not a game."<br><br>— Original anchor text</blockquote>' } },
    { id: 'u2-l1-learn-5', section: 'LEARN', blockType: 'MICRO_CHECK', order: 5, content: { question: 'What type of conflict is Mara facing in this passage?', options: [{ label: 'Person vs Person — she is fighting with someone', value: 'a' }, { label: 'Person vs Nature — she is battling the storm alone', value: 'b', correct: true }, { label: 'Person vs Society — she disagrees with rules', value: 'c' }], explanation: 'Mara is alone in a lighthouse during a dangerous storm with no way to communicate. The storm (nature) is the antagonistic force she must overcome.' } },
    { id: 'u2-l1-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Match each anchor text detail to its story element:', pairs: [{ left: 'Mara', right: 'Protagonist' }, { left: 'The storm', right: 'Antagonist / Conflict' }, { left: 'Lighthouse on a rocky coast', right: 'Setting' }, { left: 'The storm arrives early, father is missing, radio is dead', right: 'Rising Action' }, { left: '"Every choice she made from this moment would matter"', right: 'Foreshadowing / Tension' }] } },
    { id: 'u2-l1-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: 'Look at the anchor text about Mara.\n\n1. What can you INFER about Mara\'s character from the detail that she "counted the steps a thousand times, playing"?\n2. What does this tell us about her relationship with the lighthouse?\n3. Predict what might happen next in the story, based on what you know so far.', minLength: 40, rubricHint: 'Makes a valid inference about Mara\'s familiarity with the lighthouse. Connects the detail to her character. Makes a reasonable prediction based on evidence.' } },
    { id: 'u2-l1-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Think of your favorite story.\n\n1. Who is the protagonist? The antagonist?\n2. What type of conflict drives the story?\n3. Why does this conflict keep you engaged as a reader?', minLength: 30 } },
  ];

  for (const b of l1Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L1, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L1: ${l1Blocks.length} blocks`);

  // L1 Quiz — Target: ELA.6.TF.1, Review: ELA.6.RC.1
  const l1Qs = [
    { id: 'u2-l1-q1', questionText: 'The PROTAGONIST of a story is:', options: [{ label: 'The villain or enemy', value: 'a' }, { label: 'The main character the story follows', value: 'b', correct: true }, { label: 'The narrator', value: 'c' }, { label: 'A minor character', value: 'd' }], correctAnswer: 'b', explanation: 'The protagonist is the main character the reader follows through the story. They face the central conflict.', outcomeCode: 'ELA.6.TF.1', difficulty: 1 },
    { id: 'u2-l1-q2', questionText: 'A character who struggles with whether to tell the truth about a mistake is facing which type of conflict?', options: [{ label: 'Person vs Person', value: 'a' }, { label: 'Person vs Nature', value: 'b' }, { label: 'Person vs Self', value: 'c', correct: true }, { label: 'Person vs Society', value: 'd' }], correctAnswer: 'c', explanation: 'An internal struggle about a personal decision is Person vs Self — the character is in conflict with their own conscience.', outcomeCode: 'ELA.6.TF.1', difficulty: 1 },
    { id: 'u2-l1-q3', questionText: 'In a story arc, the CLIMAX is:', options: [{ label: 'The beginning where characters are introduced', value: 'a' }, { label: 'The turning point — the most intense moment of the story', value: 'b', correct: true }, { label: 'The final paragraph', value: 'c' }, { label: 'When the conflict is first introduced', value: 'd' }], correctAnswer: 'b', explanation: 'The climax is the peak of tension where the conflict reaches its most critical point. Everything before builds toward it.', outcomeCode: 'ELA.6.TF.1', difficulty: 1 },
    { id: 'u2-l1-q4', questionText: 'In Hatchet, Brian must survive alone in the Canadian wilderness after a plane crash. This is an example of:', options: [{ label: 'Person vs Person', value: 'a' }, { label: 'Person vs Nature', value: 'b', correct: true }, { label: 'Person vs Self', value: 'c' }, { label: 'Person vs Society', value: 'd' }], correctAnswer: 'b', explanation: 'Brian\'s main struggle is against the wilderness itself — cold, hunger, predators, and isolation. Nature is the antagonistic force.', outcomeCode: 'ELA.6.TF.1', difficulty: 1 },
    { id: 'u2-l1-q5', questionText: 'The EXPOSITION of a story introduces:', options: [{ label: 'The climax and resolution', value: 'a' }, { label: 'The characters, setting, and initial situation', value: 'b', correct: true }, { label: 'Only the conflict', value: 'c' }, { label: 'The moral of the story', value: 'd' }], correctAnswer: 'b', explanation: 'Exposition sets the stage — who the characters are, where/when the story takes place, and the "normal world" before the conflict begins.', outcomeCode: 'ELA.6.TF.1', difficulty: 1 },
    { id: 'u2-l1-q6', questionText: 'In the anchor text, Mara "pulled on her father\'s oilskin coat — far too big." What can you INFER from this detail?', options: [{ label: 'She is cold and needs a coat', value: 'a' }, { label: 'She is stepping into a role that feels too big for her, just like the coat', value: 'b', correct: true }, { label: 'She does not have her own coat', value: 'c' }, { label: 'Her father left his coat behind by accident', value: 'd' }], correctAnswer: 'b', explanation: 'The coat being "far too big" is symbolic — Mara is taking on her father\'s responsibility, which feels overwhelming. This is an inference based on the detail, not stated directly.', outcomeCode: 'ELA.6.RC.1', difficulty: 2 },
    { id: 'u2-l1-q7', questionText: 'Which of these correctly places events in a story arc order?', options: [{ label: 'Climax → Exposition → Rising Action → Resolution', value: 'a' }, { label: 'Exposition → Rising Action → Climax → Falling Action → Resolution', value: 'b', correct: true }, { label: 'Conflict → Climax → Exposition → Resolution', value: 'c' }, { label: 'Resolution → Climax → Rising Action → Exposition', value: 'd' }], correctAnswer: 'b', explanation: 'The story arc moves in order: Exposition (setup) → Rising Action (tension builds) → Climax (turning point) → Falling Action → Resolution.', outcomeCode: 'ELA.6.TF.1', difficulty: 2 },
    { id: 'u2-l1-q8', questionText: '"The sea churned and roared, swallowing the dock piece by piece." The word "swallowing" is used figuratively to mean:', options: [{ label: 'The sea is eating food', value: 'a' }, { label: 'The waves are gradually destroying the dock', value: 'b', correct: true }, { label: 'The dock is sinking underwater permanently', value: 'c' }, { label: 'A sea creature is attacking', value: 'd' }], correctAnswer: 'b', explanation: 'The sea cannot literally swallow — this is personification, giving the ocean a human action to show its destructive power. It means the waves are tearing the dock apart.', outcomeCode: 'ELA.6.VL.2', difficulty: 2 },
  ];

  for (const q of l1Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L1, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L1: ${l1Qs.length} questions (target: TF.1, review: RC.1, VL.2)`);

  // ════════════════════════════════════════
  // LESSON 2: Story Structures
  // Target: ELA.6.TF.1 (subplot, flashback, etc.)
  // Review: ELA.6.RC.3 (comprehension strategies)
  // ════════════════════════════════════════
  const L2 = 'g6-ela-u2-l2';

  const l2Blocks = [
    { id: 'u2-l2-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Beyond the Basic Arc</h3><p>While all stories follow a basic pattern (exposition → climax → resolution), skilled authors use <strong>structural techniques</strong> to make their stories more interesting:</p><ul><li><strong>Subplot:</strong> A secondary story that runs alongside and connects to the main plot</li><li><strong>Flashback:</strong> A scene that jumps BACK in time to show something that already happened</li><li><strong>Flash-forward:</strong> A scene that jumps FORWARD to show something that will happen later</li><li><strong>Story within a story:</strong> A character in the main story tells or reads another story — and both stories connect thematically</li></ul>' } },
    { id: 'u2-l2-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Why Do Authors Use These Techniques?</h3><table style="width:100%;border-collapse:collapse"><tr style="background:#f1f5f9"><th style="padding:8px;border:1px solid #e2e8f0">Technique</th><th style="padding:8px;border:1px solid #e2e8f0">Effect on the Reader</th></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Subplot</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Adds depth; shows different sides of characters; creates parallel conflicts</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Flashback</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Reveals backstory; explains WHY a character acts a certain way; creates mystery</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Flash-forward</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Creates suspense; makes the reader wonder "how did we get here?"</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Story within a story</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Mirrors the main theme; provides a different perspective on the same idea</td></tr></table>' } },
    { id: 'u2-l2-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Anchor Text: Flashback in Action</h3><blockquote style="border-left:3px solid #7c5cf5;padding:12px 16px;margin:12px 0;font-style:italic;color:#475569">"Kai stared at the trophy case. His name was not there.<br><br>Three months earlier, he had stood on that same gymnasium floor, heart hammering, the ball spinning from his fingertips. The crowd had gone silent. Then — the buzzer. The miss. His teammates\' faces falling like dominoes.<br><br>Now, looking at the empty space where his team\'s name should have been, Kai made a decision. He pulled out his phone and texted Coach Davis: <em>I want to try again.</em>"<br><br>— Original anchor text</blockquote><p><strong>Notice:</strong> The paragraph beginning "Three months earlier" is a <em>flashback</em>. It takes us back in time to explain why Kai is staring at the trophy case now.</p>' } },
    { id: 'u2-l2-learn-4', section: 'LEARN', blockType: 'MICRO_CHECK', order: 4, content: { question: 'What effect does the flashback have in Kai\'s story?', options: [{ label: 'It confuses the reader about when events happen', value: 'a' }, { label: 'It explains WHY Kai is motivated to try again — we understand his failure', value: 'b', correct: true }, { label: 'It introduces a new character', value: 'c' }], explanation: 'The flashback to the missed shot gives us context for Kai\'s determination. Without it, we wouldn\'t understand the significance of his decision to try again.' } },
    { id: 'u2-l2-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Match each scenario to the correct structural technique:', pairs: [{ left: 'In a story about a dog rescue, we also follow the family that will adopt the dog', right: 'Subplot' }, { left: '"Twenty years later, Maya would stand in this exact spot as the president"', right: 'Flash-forward' }, { left: 'A grandfather tells his granddaughter a fairy tale that mirrors their own family problem', right: 'Story within a story' }, { left: '"She remembered the day everything changed — the summer she was seven..."', right: 'Flashback' }] } },
    { id: 'u2-l2-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: 'Read the Kai anchor text again.\n\n1. If you were the author, what SUBPLOT could you add to make the story richer? (Think: another character with a connected problem)\n2. Where could a FLASH-FORWARD work in this story? What would it show?', minLength: 40 } },
    { id: 'u2-l2-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Why might an author choose to use a flashback instead of telling the story in order? When is this technique most effective?', minLength: 30 } },
  ];

  for (const b of l2Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L2, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L2: ${l2Blocks.length} blocks`);

  const l2Qs = [
    { id: 'u2-l2-q1', questionText: 'A SUBPLOT is:', options: [{ label: 'The main conflict of the story', value: 'a' }, { label: 'A secondary story that runs alongside and connects to the main plot', value: 'b', correct: true }, { label: 'The setting of the story', value: 'c' }, { label: 'The resolution', value: 'd' }], correctAnswer: 'b', explanation: 'A subplot is a side-story that adds depth. It connects to the main plot thematically but follows different characters or conflicts.', outcomeCode: 'ELA.6.TF.1', difficulty: 1 },
    { id: 'u2-l2-q2', questionText: 'A scene that begins "Fifteen years from now, she would regret this decision" is an example of:', options: [{ label: 'Flashback', value: 'a' }, { label: 'Flash-forward', value: 'b', correct: true }, { label: 'Subplot', value: 'c' }, { label: 'Exposition', value: 'd' }], correctAnswer: 'b', explanation: 'This jumps FORWARD in time — telling us something that will happen in the future. This creates suspense.', outcomeCode: 'ELA.6.TF.1', difficulty: 1 },
    { id: 'u2-l2-q3', questionText: 'In Kai\'s story, the flashback scene reveals:', options: [{ label: 'That Kai is a new student', value: 'a' }, { label: 'That Kai missed a crucial shot and lost a game — explaining his motivation now', value: 'b', correct: true }, { label: 'That the coach is new to the school', value: 'c' }, { label: 'That the trophy case is broken', value: 'd' }], correctAnswer: 'b', explanation: 'The flashback shows us Kai\'s missed shot and the team\'s loss. Without this backstory, his decision to "try again" would lack emotional weight.', outcomeCode: 'ELA.6.TF.1', difficulty: 1 },
    { id: 'u2-l2-q4', questionText: 'Which comprehension strategy would help you MOST when a story uses flashbacks?', options: [{ label: 'Visualizing — imagining what the scene looks like', value: 'a' }, { label: 'Questioning — asking "when is this happening? Is this the past or present?"', value: 'b', correct: true }, { label: 'Connecting — linking to your own life', value: 'c' }, { label: 'Predicting — guessing what happens next', value: 'd' }], correctAnswer: 'b', explanation: 'When a story jumps in time, actively questioning WHEN events are happening helps you track the timeline and understand the story\'s structure.', outcomeCode: 'ELA.6.RC.3', difficulty: 2 },
    { id: 'u2-l2-q5', questionText: 'A grandfather tells his granddaughter a fairy tale about a brave mouse who stands up to a cat. Meanwhile, the granddaughter needs to stand up to a bully. This is an example of:', options: [{ label: 'Flashback', value: 'a' }, { label: 'Story within a story', value: 'b', correct: true }, { label: 'Flash-forward', value: 'c' }, { label: 'Person vs Nature', value: 'd' }], correctAnswer: 'b', explanation: 'The fairy tale is a STORY WITHIN A STORY — an internal narrative that mirrors the main character\'s real-life situation, reinforcing the theme.', outcomeCode: 'ELA.6.TF.1', difficulty: 2 },
    { id: 'u2-l2-q6', questionText: '"His teammates\' faces falling like dominoes." This simile suggests:', options: [{ label: 'The teammates collapsed physically', value: 'a' }, { label: 'One by one, each teammate\'s expression changed to disappointment', value: 'b', correct: true }, { label: 'The teammates were playing dominoes', value: 'c' }, { label: 'The game was over quickly', value: 'd' }], correctAnswer: 'b', explanation: 'The simile "like dominoes" means one after another — each face falling (showing disappointment) in sequence, just like dominoes toppling.', outcomeCode: 'ELA.6.VL.2', difficulty: 2 },
    { id: 'u2-l2-q7', questionText: 'Why do authors use flashbacks?', options: [{ label: 'To confuse the reader', value: 'a' }, { label: 'To provide backstory, explain motivations, or create mystery', value: 'b', correct: true }, { label: 'To make the story shorter', value: 'c' }, { label: 'Because linear stories are boring', value: 'd' }], correctAnswer: 'b', explanation: 'Flashbacks serve a purpose: they reveal characters\' histories, explain why they act the way they do, and can create mystery by revealing information gradually.', outcomeCode: 'ELA.6.TF.1', difficulty: 1 },
    { id: 'u2-l2-q8', questionText: 'What is the relationship between a subplot and the main plot?', options: [{ label: 'They are completely unrelated stories', value: 'a' }, { label: 'The subplot connects to the main plot thematically or through shared characters', value: 'b', correct: true }, { label: 'The subplot always happens first', value: 'c' }, { label: 'The subplot replaces the main plot halfway through', value: 'd' }], correctAnswer: 'b', explanation: 'Subplots are connected — they might share characters, mirror the main theme, or show a different angle of the same conflict. They enrich the story.', outcomeCode: 'ELA.6.TF.1', difficulty: 2 },
  ];

  for (const q of l2Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L2, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L2: ${l2Qs.length} questions (target: TF.1, review: RC.3, VL.2)`);

  // ════════════════════════════════════════
  // LESSON 3: Exploring Sub-Genres
  // Target: ELA.6.TF.2 (fiction sub-genres)
  // Review: ELA.6.RC.2 (text connections)
  // ════════════════════════════════════════
  const L3 = 'g6-ela-u2-l3';

  const l3Blocks = [
    { id: 'u2-l3-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>What Is a Sub-Genre?</h3><p><em>Fiction</em> is a broad genre — it means any story that is made up. But within fiction, there are many <strong>sub-genres</strong>, each with its own conventions (rules and expectations).</p><p>Knowing sub-genres helps you as a reader (you know what to expect) and as a writer (you know which tools to use).</p>' } },
    { id: 'u2-l3-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Major Fiction Sub-Genres</h3><table style="width:100%;border-collapse:collapse"><tr style="background:#f1f5f9"><th style="padding:8px;border:1px solid #e2e8f0">Sub-Genre</th><th style="padding:8px;border:1px solid #e2e8f0">Key Features</th><th style="padding:8px;border:1px solid #e2e8f0">Example</th></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Fantasy</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Magic, mythical creatures, imaginary worlds</td><td style="padding:8px;border:1px solid #e2e8f0">Harry Potter, Percy Jackson</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Science Fiction</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Future technology, space, "what if" scenarios based on science</td><td style="padding:8px;border:1px solid #e2e8f0">The Giver, A Wrinkle in Time</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Historical Fiction</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Set in a real time period; blends real events with fictional characters</td><td style="padding:8px;border:1px solid #e2e8f0">Number the Stars</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Mystery</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Puzzle or crime to solve; clues, suspects, red herrings</td><td style="padding:8px;border:1px solid #e2e8f0">Westing Game, Enola Holmes</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Realistic Fiction</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Could happen in real life; deals with real-world problems</td><td style="padding:8px;border:1px solid #e2e8f0">Wonder, Bridge to Terabithia</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Comedy</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Humour drives the story; misunderstandings, exaggeration, wit</td><td style="padding:8px;border:1px solid #e2e8f0">Diary of a Wimpy Kid</td></tr></table>' } },
    { id: 'u2-l3-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: 'A story set in the year 2185 about teenagers discovering they are living in a computer simulation is MOST likely which sub-genre?', options: [{ label: 'Historical Fiction', value: 'a' }, { label: 'Science Fiction', value: 'b', correct: true }, { label: 'Fantasy', value: 'c' }], explanation: 'The future setting + technology (computer simulation) are hallmarks of science fiction. Fantasy uses magic, not technology, as the central "what if."' } },
    { id: 'u2-l3-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Categorize each story by its most likely sub-genre:', pairs: [{ left: 'A girl discovers a portal to a world where animals can talk and dragons guard ancient libraries', right: 'Fantasy' }, { left: 'A 12-year-old in 1940s Alberta works to save her family farm during a drought', right: 'Historical Fiction' }, { left: 'A boy finds a coded message in a library book and must solve clues to find a hidden treasure', right: 'Mystery' }, { left: 'In 2250, colonists on Mars discover that the planet\'s core contains alien technology', right: 'Science Fiction' }, { left: 'A student accidentally becomes class president after a series of hilarious misunderstandings', right: 'Comedy' }] } },
    { id: 'u2-l3-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: 'Choose TWO sub-genres from the chart above.\n\n1. Name the two sub-genres\n2. List at least 2 features that make each one distinct\n3. Could the SAME character or conflict appear in both sub-genres? Give an example of how the same basic story might work in each genre.', minLength: 50 } },
    { id: 'u2-l3-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'What is your favorite fiction sub-genre? What specific features of that genre do you enjoy most? Can you make a text-to-self connection about why you are drawn to this genre?', minLength: 30 } },
  ];

  for (const b of l3Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L3, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L3: ${l3Blocks.length} blocks`);

  const l3Qs = [
    { id: 'u2-l3-q1', questionText: 'Which feature defines FANTASY as a sub-genre?', options: [{ label: 'Future technology and space travel', value: 'a' }, { label: 'Magic, mythical creatures, and imaginary worlds', value: 'b', correct: true }, { label: 'A puzzle or crime to solve', value: 'c' }, { label: 'Humour and exaggeration', value: 'd' }], correctAnswer: 'b', explanation: 'Fantasy is defined by magical or supernatural elements: magic systems, mythical creatures, imaginary worlds, chosen-one prophecies, etc.', outcomeCode: 'ELA.6.TF.2', difficulty: 1 },
    { id: 'u2-l3-q2', questionText: 'Historical fiction differs from other fiction because it:', options: [{ label: 'Is always sad', value: 'a' }, { label: 'Is set in a real time period and blends real events with fictional characters', value: 'b', correct: true }, { label: 'Only tells true stories', value: 'c' }, { label: 'Has no conflict', value: 'd' }], correctAnswer: 'b', explanation: 'Historical fiction uses a real time period and often real events as its backdrop, but the main characters and their personal stories are fictional.', outcomeCode: 'ELA.6.TF.2', difficulty: 1 },
    { id: 'u2-l3-q3', questionText: 'A story where a student accidentally enters a cooking competition and chaos ensues because they can only make toast is MOST likely:', options: [{ label: 'Mystery', value: 'a' }, { label: 'Science Fiction', value: 'b' }, { label: 'Comedy', value: 'c', correct: true }, { label: 'Historical Fiction', value: 'd' }], correctAnswer: 'c', explanation: 'Humour, misunderstandings, and exaggeration (only making toast in a cooking competition) are features of comedy.', outcomeCode: 'ELA.6.TF.2', difficulty: 1 },
    { id: 'u2-l3-q4', questionText: 'What is a TEXT-TO-TEXT connection you could make between Harry Potter and Percy Jackson?', options: [{ label: 'Both are movies', value: 'a' }, { label: 'Both feature a young protagonist who discovers they have extraordinary powers in a hidden magical world', value: 'b', correct: true }, { label: 'Both are set in schools', value: 'c' }, { label: 'Both are nonfiction', value: 'd' }], correctAnswer: 'b', explanation: 'A strong text-to-text connection identifies shared themes, character types, or narrative structures — not just surface similarities.', outcomeCode: 'ELA.6.RC.2', difficulty: 2 },
    { id: 'u2-l3-q5', questionText: 'What distinguishes SCIENCE FICTION from FANTASY?', options: [{ label: 'Science fiction uses technology and scientific "what if" scenarios; fantasy uses magic', value: 'b', correct: true }, { label: 'Fantasy is for kids; science fiction is for adults', value: 'a' }, { label: 'They are the same thing', value: 'c' }, { label: 'Science fiction is always set in space', value: 'd' }], correctAnswer: 'b', explanation: 'The key distinction: sci-fi extrapolates from science/technology ("what if we could...?"), while fantasy uses magic/supernatural elements as its foundational logic.', outcomeCode: 'ELA.6.TF.2', difficulty: 2 },
    { id: 'u2-l3-q6', questionText: 'In a mystery, a "red herring" is:', options: [{ label: 'A type of fish in the story', value: 'a' }, { label: 'A clue that misleads the reader away from the real answer', value: 'b', correct: true }, { label: 'The detective\'s name', value: 'c' }, { label: 'The crime scene', value: 'd' }], correctAnswer: 'b', explanation: 'A red herring is a false clue that distracts. Authors use them to create suspense and surprise.', outcomeCode: 'ELA.6.TF.2', difficulty: 1 },
    { id: 'u2-l3-q7', questionText: 'Why do genre CONVENTIONS matter for readers?', options: [{ label: 'They don\'t — all stories are the same', value: 'a' }, { label: 'They set expectations, so readers know what type of experience to anticipate', value: 'b', correct: true }, { label: 'They restrict what authors can write', value: 'c' }, { label: 'They only matter for movie genres', value: 'd' }], correctAnswer: 'b', explanation: 'Genre conventions create a contract between writer and reader — fantasy readers expect magic, mystery readers expect clues. Understanding conventions helps you engage more deeply.', outcomeCode: 'ELA.6.TF.2', difficulty: 2 },
    { id: 'u2-l3-q8', questionText: 'A story set during WWII where a fictional girl helps real resistance fighters is:', options: [{ label: 'Science Fiction', value: 'a' }, { label: 'Historical Fiction', value: 'b', correct: true }, { label: 'Fantasy', value: 'c' }, { label: 'Comedy', value: 'd' }], correctAnswer: 'b', explanation: 'Real time period (WWII) + real events (resistance) + fictional characters (the girl) = historical fiction.', outcomeCode: 'ELA.6.TF.2', difficulty: 1 },
  ];

  for (const q of l3Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L3, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L3: ${l3Qs.length} questions (target: TF.2, review: RC.2)`);

  // ════════════════════════════════════════
  // LESSON 4: The Writer's Toolbox
  // Target: ELA.6.WC.4 (creative expression)
  // Review: ELA.6.VL.2 (figurative language)
  // ════════════════════════════════════════
  const L4 = 'g6-ela-u2-l4';

  const l4Blocks = [
    { id: 'u2-l4-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>The Writer\'s Toolbox</h3><p>Great fiction is not just about WHAT happens — it is about HOW the author makes you FEEL it. Writers use specific <strong>craft techniques</strong> to create vivid, engaging stories:</p>' } },
    { id: 'u2-l4-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Tool 1: Show, Don\'t Tell</h3><p>Instead of TELLING the reader how a character feels, SHOW it through actions, dialogue, and details.</p><table style="width:100%;border-collapse:collapse"><tr style="background:#f1f5f9"><th style="padding:8px;border:1px solid #e2e8f0">❌ Telling</th><th style="padding:8px;border:1px solid #e2e8f0">✅ Showing</th></tr><tr><td style="padding:8px;border:1px solid #e2e8f0">She was nervous.</td><td style="padding:8px;border:1px solid #e2e8f0">Her hands trembled as she gripped the edges of the podium. The microphone squealed, and every eye in the room turned toward her.</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0">He was happy to see his dog.</td><td style="padding:8px;border:1px solid #e2e8f0">The moment the front door opened, Max launched himself at Jamal\'s legs, tail a blur, tongue everywhere. Jamal dropped his backpack and sank to the floor, laughing.</td></tr></table>' } },
    { id: 'u2-l4-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Tool 2: Sensory Detail</h3><p>Sensory details use the <strong>five senses</strong> (sight, sound, smell, touch, taste) to make writing vivid.</p><blockquote style="border-left:3px solid #7c5cf5;padding:12px 16px;margin:12px 0;font-style:italic">"The kitchen smelled of cinnamon and burnt edges — Grandma\'s attempt at cookies. The floor was sticky underfoot, dusted with a fine layer of flour. From the counter, a timer shrieked."</blockquote><p>This uses <em>smell</em> (cinnamon, burnt edges), <em>touch</em> (sticky floor), <em>sight</em> (flour), and <em>sound</em> (shrieking timer).</p>' } },
    { id: 'u2-l4-learn-4', section: 'LEARN', blockType: 'TEXT', order: 4, content: { html: '<h3>Tool 3: Dialogue That Reveals Character</h3><p>Good dialogue does more than move the plot — it shows WHO the character is.</p><blockquote style="border-left:3px solid #7c5cf5;padding:12px 16px;margin:12px 0;font-style:italic">"I didn\'t want to come," Priya said, pulling her hood over her face.<br>"Nobody asked if you wanted to," her brother replied, already halfway up the trail. "You just had to show up."<br>Priya kicked a rock. "That\'s the problem."</blockquote><p>Notice: we learn Priya feels reluctant and unheard. Her brother is assertive and dismissive. Neither feeling is stated directly — it is all shown through dialogue and action.</p>' } },
    { id: 'u2-l4-learn-5', section: 'LEARN', blockType: 'MICRO_CHECK', order: 5, content: { question: '"Her hands trembled as she gripped the podium." This is an example of:', options: [{ label: 'Telling — it directly states she is nervous', value: 'a' }, { label: 'Showing — it describes physical actions that reveal nervousness', value: 'b', correct: true }, { label: 'Neither', value: 'c' }], explanation: 'The sentence never says "nervous" — it SHOWS the nervousness through trembling hands and gripping the podium. The reader infers the emotion.' } },
    { id: 'u2-l4-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Rewrite each TELLING sentence as a SHOWING passage using sensory details, actions, and/or dialogue:\n\n1. "He was scared of the dark."\n2. "The cafeteria was noisy."\n3. "She was excited about the snow day."\n\nFor each one, use at least 2 senses and avoid naming the emotion directly.', minLength: 60 } },
    { id: 'u2-l4-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Which writer\'s tool (show-don\'t-tell, sensory detail, or dialogue) do you find most powerful? Explain with a specific example from a book, movie, or your own experience.', minLength: 30 } },
  ];

  for (const b of l4Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L4, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L4: ${l4Blocks.length} blocks`);

  const l4Qs = [
    { id: 'u2-l4-q1', questionText: '"Show, don\'t tell" means:', options: [{ label: 'Use pictures instead of words', value: 'a' }, { label: 'Reveal emotions through actions, dialogue, and details instead of naming them directly', value: 'b', correct: true }, { label: 'Write longer sentences', value: 'c' }, { label: 'Always use first person', value: 'd' }], correctAnswer: 'b', explanation: 'Showing uses concrete actions, dialogue, and sensory details so the reader can FEEL the emotion rather than just being told about it.', outcomeCode: 'ELA.6.WC.4', difficulty: 1 },
    { id: 'u2-l4-q2', questionText: 'Which sentence uses SENSORY DETAIL most effectively?', options: [{ label: 'The room was dirty.', value: 'a' }, { label: 'The carpet squelched under her shoes, and the air tasted of rust and old newspapers.', value: 'b', correct: true }, { label: 'It was a bad room.', value: 'c' }, { label: 'She did not like the room.', value: 'd' }], correctAnswer: 'b', explanation: 'Option B uses touch (squelching carpet), taste (rust), and smell (old newspapers) to create a vivid picture. The others just tell.', outcomeCode: 'ELA.6.WC.4', difficulty: 1 },
    { id: 'u2-l4-q3', questionText: '"The floor was sticky underfoot, dusted with a fine layer of flour." Which TWO senses does this use?', options: [{ label: 'Sight and smell', value: 'a' }, { label: 'Touch and sight', value: 'b', correct: true }, { label: 'Sound and touch', value: 'c' }, { label: 'Taste and smell', value: 'd' }], correctAnswer: 'b', explanation: '"Sticky underfoot" = touch. "Dusted with flour" = sight. Two senses make the scene vivid.', outcomeCode: 'ELA.6.WC.4', difficulty: 1 },
    { id: 'u2-l4-q4', questionText: 'In the dialogue about Priya and her brother, what can you INFER about Priya\'s feelings?', options: [{ label: 'She is excited about the hike', value: 'a' }, { label: 'She feels unheard and forced into something she doesn\'t want', value: 'b', correct: true }, { label: 'She is angry at her parents', value: 'c' }, { label: 'She is cold', value: 'd' }], correctAnswer: 'b', explanation: '"I didn\'t want to come" + "That\'s the problem" (about nobody asking) reveals she feels unheard. The inference comes from her words and actions, not a direct statement.', outcomeCode: 'ELA.6.RC.1', difficulty: 2 },
    { id: 'u2-l4-q5', questionText: '"From the counter, a timer shrieked." The word "shrieked" is an example of:', options: [{ label: 'A simile', value: 'a' }, { label: 'Personification — giving a non-living thing a human action', value: 'b', correct: true }, { label: 'Hyperbole', value: 'c' }, { label: 'A metaphor', value: 'd' }], correctAnswer: 'b', explanation: 'Timers cannot shriek — that is a human sound. Describing the timer as shrieking gives it a human quality, making it more vivid and urgent.', outcomeCode: 'ELA.6.VL.2', difficulty: 2 },
    { id: 'u2-l4-q6', questionText: 'Good dialogue reveals character by:', options: [{ label: 'Having characters describe themselves', value: 'a' }, { label: 'Showing how characters speak, what they say, and how they interact — revealing personality and relationships', value: 'b', correct: true }, { label: 'Using very long speeches', value: 'c' }, { label: 'Always having characters agree', value: 'd' }], correctAnswer: 'b', explanation: 'Effective dialogue shows WHO a character is through their word choices, tone, and how they respond to others — not through self-description.', outcomeCode: 'ELA.6.WC.4', difficulty: 1 },
    { id: 'u2-l4-q7', questionText: 'Which is a TELLING sentence?', options: [{ label: '"His knees buckled and he grabbed the doorframe."', value: 'a' }, { label: '"She was sad about moving."', value: 'b', correct: true }, { label: '"Tears tracked through the dust on her cheeks."', value: 'c' }, { label: '"He whispered: I can\'t do this."', value: 'd' }], correctAnswer: 'b', explanation: '"She was sad" tells the emotion directly. The other options SHOW emotions through actions, physical details, and dialogue.', outcomeCode: 'ELA.6.WC.4', difficulty: 1 },
    { id: 'u2-l4-q8', questionText: '"Grandma\'s attempt at cookies" — what does the word "attempt" imply about the cookies?', options: [{ label: 'They were perfect', value: 'a' }, { label: 'They were a first try and probably didn\'t turn out well', value: 'b', correct: true }, { label: 'She made them professionally', value: 'c' }, { label: 'She didn\'t finish making them', value: 'd' }], correctAnswer: 'b', explanation: 'The word "attempt" implies trying but not quite succeeding. Combined with "burnt edges," we can infer the cookies were imperfect — the connotation of "attempt" suggests effort without full success.', outcomeCode: 'ELA.6.VL.3', difficulty: 2 },
  ];

  for (const q of l4Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L4, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L4: ${l4Qs.length} questions (target: WC.4, review: RC.1, VL.2, VL.3)`);

  // ── Summary ──
  console.log(`
╔═══════════════════════════════════════════════╗
║   ELA UNIT 2 (L1–L4) SEED COMPLETE          ║
╠═══════════════════════════════════════════════╣
║ Lessons:    4                                ║
║ Blocks:     ${String(l1Blocks.length + l2Blocks.length + l3Blocks.length + l4Blocks.length).padStart(2)}                               ║
║ Questions:  ${String(l1Qs.length + l2Qs.length + l3Qs.length + l4Qs.length).padStart(2)}                               ║
╚═══════════════════════════════════════════════╝`);
}

main()
  .catch((e) => { console.error('❌ Seed error:', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); pool.end(); });
