// ============================================
// Seed Science Unit D L4-L8 — Structures & Forces
// ============================================
// Run: npx tsx prisma/seed-sci-ud-l4-l8.ts

import { config } from 'dotenv';
config({ path: '.env.local' });
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function seed(ID: string, title: string, data: { lesson: Record<string, unknown>, blocks: Array<Record<string, unknown>>, questions: Array<Record<string, unknown>> }) {
  console.log(`\n🔩 Seeding ${title}...`);
  await prisma.lesson.update({ where: { id: ID }, data: data.lesson as any });
  await prisma.lessonBlock.deleteMany({ where: { lessonId: ID } });
  await prisma.quizQuestion.deleteMany({ where: { lessonId: ID } });
  for (const b of data.blocks) { await prisma.lessonBlock.create({ data: { ...b, lessonId: ID } as any }); }
  console.log(`  ✅ ${data.blocks.length} blocks`);
  for (const q of data.questions) { await prisma.quizQuestion.create({ data: { ...q, lessonId: ID } as any }); }
  console.log(`  ✅ ${data.questions.length} questions`);
}

const L4 = {
  lesson: { subjectMode: 'SCIENCE', estimatedMinutes: 45, learningGoal: 'Describe material properties (strength, flexibility, hardness, durability), compare natural and synthetic materials, and explain engineering material choices.', successCriteria: 'I can compare 4 material properties, explain composites, and select materials for specific purposes.', materials: 'Science notebook', reflectionPrompt: 'Look at the room you are in. What materials were used and why?', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
  blocks: [
    { id: 'ud-l4-learn-1', section: 'LEARN', blockType: 'VOCABULARY', order: 1, content: { terms: [{ term: 'Tensile Strength', definition: 'How well a material resists being pulled apart (stretched).', example: 'Steel cables have high tensile strength.' }, { term: 'Compressive Strength', definition: 'How well a material resists being crushed (squeezed).', example: 'Concrete has high compressive strength.' }, { term: 'Flexibility', definition: 'Ability to bend without breaking.', example: 'Rubber bands are highly flexible.' }, { term: 'Composite', definition: 'Material made from two or more substances combined for better properties.', example: 'Reinforced concrete (concrete + steel rebar).' }] } },
    { id: 'ud-l4-learn-2', section: 'LEARN', blockType: 'VIDEO', order: 2, content: { url: 'https://www.youtube.com/embed/UGKLZuSyVIE', title: 'Materials in Engineering', transcript: 'Video comparing material properties for engineering.' } },
    { id: 'ud-l4-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>🧪 Material Properties Compared</h3><table><thead><tr><th>Material</th><th>Strength</th><th>Flexibility</th><th>Best Used For</th></tr></thead><tbody><tr><td>Steel</td><td>Very high (both)</td><td>Moderate</td><td>Beams, bridges, skyscrapers</td></tr><tr><td>Concrete</td><td>High compression, weak tension</td><td>Very low</td><td>Foundations, dams, floors</td></tr><tr><td>Wood</td><td>Moderate</td><td>Moderate</td><td>Houses, furniture, fences</td></tr><tr><td>Carbon Fibre</td><td>Extremely high</td><td>Some</td><td>Aircraft, sports equipment</td></tr></tbody></table><p><strong>Composites:</strong> Reinforced concrete combines concrete\'s compression strength with steel\'s tension strength — stronger than either material alone.</p>' } },
    { id: 'ud-l4-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Pick the best material for each structural challenge:', pairs: [{ left: 'A bridge that flexes in wind and carries heavy traffic', right: 'Steel' }, { left: 'A foundation that resists enormous downward pressure', right: 'Concrete' }, { left: 'A residential house frame — light and affordable', right: 'Wood' }, { left: 'An aircraft wing — extremely strong but lightweight', right: 'Carbon Fibre' }] } },
    { id: 'ud-l4-reflect-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Why is reinforced concrete (concrete with steel rebar) stronger than plain concrete? Explain using tensile and compressive strength.', minLength: 60, rubricHint: 'Explains concrete is strong in compression but weak in tension. Steel adds tensile strength. Combined = composite stronger than either alone.', teacherReviewRequired: false } },
  ],
  questions: [
    { id: 'ud-l4-q1', questionText: 'Tensile strength measures how well a material resists:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Being squeezed', value: 'a' }, { label: 'Being pulled apart', value: 'b', correct: true }, { label: 'Being twisted', value: 'c' }, { label: 'Heat', value: 'd' }], correctAnswer: 'b', explanation: 'Tensile strength = resistance to pulling/stretching forces.', outcomeCode: 'SCI.7.D.3.1', difficulty: 1 },
    { id: 'ud-l4-q2', questionText: 'Reinforced concrete is a composite because:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'It uses only concrete', value: 'a' }, { label: 'It combines concrete (compression) with steel rebar (tension)', value: 'b', correct: true }, { label: 'It\'s painted', value: 'c' }, { label: 'It uses wood', value: 'd' }], correctAnswer: 'b', explanation: 'Composites combine two materials to get the best properties of both.', outcomeCode: 'SCI.7.D.3.1', difficulty: 2 },
    { id: 'ud-l4-q3', questionText: 'Carbon fibre is used in aircraft because it is:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Heavy and cheap', value: 'a' }, { label: 'Extremely strong yet lightweight', value: 'b', correct: true }, { label: 'Transparent', value: 'c' }, { label: 'Flexible like rubber', value: 'd' }], correctAnswer: 'b', explanation: 'Carbon fibre has an extremely high strength-to-weight ratio.', outcomeCode: 'SCI.7.D.3.1', difficulty: 1 },
    { id: 'ud-l4-q4', questionText: 'Concrete is weak in:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Compression', value: 'a' }, { label: 'Tension (pulling)', value: 'b', correct: true }, { label: 'Both equally', value: 'c' }, { label: 'Neither', value: 'd' }], correctAnswer: 'b', explanation: 'Concrete excels at compression but cracks easily under tension.', outcomeCode: 'SCI.7.D.3.1', difficulty: 1 },
    { id: 'ud-l4-q5', questionText: 'Flexibility in a material means:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'It breaks easily', value: 'a' }, { label: 'It can bend without breaking', value: 'b', correct: true }, { label: 'It\'s very heavy', value: 'c' }, { label: 'It resists all forces equally', value: 'd' }], correctAnswer: 'b', explanation: 'Flexible materials deform under stress and return to shape without breaking.', outcomeCode: 'SCI.7.D.3.1', difficulty: 1 },
    { id: 'ud-l4-q6', questionText: 'The best material for a dam foundation is:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Glass', value: 'a' }, { label: 'Reinforced concrete', value: 'b', correct: true }, { label: 'Plastic', value: 'c' }, { label: 'Wood', value: 'd' }], correctAnswer: 'b', explanation: 'Reinforced concrete handles the massive compression and is waterproof.', outcomeCode: 'SCI.7.D.3.1', difficulty: 1 },
    { id: 'ud-l4-q7', questionText: 'Wood is commonly used for houses because:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'It\'s fireproof', value: 'a' }, { label: 'It\'s light, easy to shape, and affordable', value: 'b', correct: true }, { label: 'It\'s stronger than steel', value: 'c' }, { label: 'It\'s waterproof', value: 'd' }], correctAnswer: 'b', explanation: 'Wood is lightweight, workable, and cost-effective for residential construction.', outcomeCode: 'SCI.7.D.3.1', difficulty: 1 },
    { id: 'ud-l4-q8', questionText: 'A material with high compressive strength can resist:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Being pulled apart', value: 'a' }, { label: 'Being crushed or squeezed', value: 'b', correct: true }, { label: 'Being twisted', value: 'c' }, { label: 'Being heated', value: 'd' }], correctAnswer: 'b', explanation: 'Compressive strength = resistance to crushing/squeezing forces.', outcomeCode: 'SCI.7.D.3.1', difficulty: 1 },
  ],
};

const L5 = {
  lesson: { subjectMode: 'SCIENCE', estimatedMinutes: 45, learningGoal: 'Compare fixed and flexible joints, identify different fasteners and their purposes, and explain how joints relate to structural integrity.', successCriteria: 'I can compare joint types, select appropriate fasteners, and explain why joints are common failure points.', materials: 'Science notebook', reflectionPrompt: 'Find a joint in the room. What type is it and why was it chosen?', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
  blocks: [
    { id: 'ud-l5-learn-1', section: 'LEARN', blockType: 'VOCABULARY', order: 1, content: { terms: [{ term: 'Fixed Joint', definition: 'Rigid connection that does not move — welding, rivets, glue.', example: 'Welded steel beams in a skyscraper.' }, { term: 'Flexible Joint', definition: 'Connection that allows movement — hinges, ball-and-socket, pivots.', example: 'Door hinge, knee joint.' }, { term: 'Gusset', definition: 'Triangular plate added to a joint to strengthen it.', example: 'Metal triangle at a beam junction.' }, { term: 'Fastener', definition: 'Device used to connect parts — nails, screws, bolts, rivets, adhesives.', example: 'Bolts holding a bridge together.' }] } },
    { id: 'ud-l5-learn-2', section: 'LEARN', blockType: 'VIDEO', order: 2, content: { url: 'https://www.youtube.com/embed/wQYJqLE73R0', title: 'Joints in Structures', transcript: 'Video explaining joint types in engineering.' } },
    { id: 'ud-l5-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>🔩 Fixed vs Flexible Joints</h3><table><thead><tr><th>Feature</th><th>Fixed Joint</th><th>Flexible Joint</th></tr></thead><tbody><tr><td>Movement</td><td>None — rigid</td><td>Allows rotation/pivoting</td></tr><tr><td>Examples</td><td>Welding, rivets, glue</td><td>Hinges, pivot pins, ball-and-socket</td></tr><tr><td>Strength</td><td>Very strong</td><td>Moderate but allows motion</td></tr><tr><td>Use case</td><td>Buildings, permanent structures</td><td>Doors, cranes, moving parts</td></tr></tbody></table><p><strong>Gussets</strong> are triangular plates added at joints to distribute force and prevent buckling. They are especially common in bridge and roof trusses.</p>' } },
    { id: 'ud-l5-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Choose the right joint type for each scenario:', pairs: [{ left: 'Steel beams in a permanent building — must never move', right: 'Fixed (welded)' }, { left: 'A door that needs to open and close', right: 'Flexible (hinge)' }, { left: 'A crane arm that rotates 360°', right: 'Flexible (pivot)' }, { left: 'A bridge truss joint needs extra strength', right: 'Fixed + gusset plate' }] } },
    { id: 'ud-l5-reflect-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Why do many structural failures happen at joints rather than in the middle of a beam? Use the concepts of stress concentration and force transfer.', minLength: 60, rubricHint: 'Explains stress concentrates at joints. Forces must transfer between members. Weakest point in a system.', teacherReviewRequired: false } },
  ],
  questions: [
    { id: 'ud-l5-q1', questionText: 'A fixed joint is one that:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Allows free movement', value: 'a' }, { label: 'Is rigid and does not move', value: 'b', correct: true }, { label: 'Uses no fasteners', value: 'c' }, { label: 'Is always temporary', value: 'd' }], correctAnswer: 'b', explanation: 'Fixed joints are rigid — welding, rivets, and adhesives create permanent connections.', outcomeCode: 'SCI.7.D.3.2', difficulty: 1 },
    { id: 'ud-l5-q2', questionText: 'A door hinge is an example of:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'A fixed joint', value: 'a' }, { label: 'A flexible joint', value: 'b', correct: true }, { label: 'A gusset', value: 'c' }, { label: 'Compression', value: 'd' }], correctAnswer: 'b', explanation: 'Hinges allow rotational movement — a flexible joint.', outcomeCode: 'SCI.7.D.3.2', difficulty: 1 },
    { id: 'ud-l5-q3', questionText: 'A gusset strengthens a joint by:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Adding weight', value: 'a' }, { label: 'Distributing force across a triangular plate', value: 'b', correct: true }, { label: 'Making it flexible', value: 'c' }, { label: 'Reducing material', value: 'd' }], correctAnswer: 'b', explanation: 'The triangular shape of a gusset spreads stress across a wider area.', outcomeCode: 'SCI.7.D.3.2', difficulty: 2 },
    { id: 'ud-l5-q4', questionText: 'Welding creates a:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Flexible joint', value: 'a' }, { label: 'Fixed (rigid) joint', value: 'b', correct: true }, { label: 'Temporary connection', value: 'c' }, { label: 'No connection', value: 'd' }], correctAnswer: 'b', explanation: 'Welding fuses metals together permanently — a rigid fixed joint.', outcomeCode: 'SCI.7.D.3.2', difficulty: 1 },
    { id: 'ud-l5-q5', questionText: 'Structures often fail at joints because:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Joints are decorative', value: 'a' }, { label: 'Forces concentrate at connection points', value: 'b', correct: true }, { label: 'Joints are always weak', value: 'c' }, { label: 'They use too much material', value: 'd' }], correctAnswer: 'b', explanation: 'Joints are stress concentration points where forces must transfer between members.', outcomeCode: 'SCI.7.D.3.2', difficulty: 2 },
    { id: 'ud-l5-q6', questionText: 'A ball-and-socket joint allows:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'No movement at all', value: 'a' }, { label: 'Movement in multiple directions', value: 'b', correct: true }, { label: 'Only compression', value: 'c' }, { label: 'Only one direction', value: 'd' }], correctAnswer: 'b', explanation: 'Ball-and-socket joints (like your shoulder) allow multi-directional rotation.', outcomeCode: 'SCI.7.D.3.2', difficulty: 1 },
    { id: 'ud-l5-q7', questionText: 'Bolts are used instead of nails when:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'A weaker connection is needed', value: 'a' }, { label: 'The joint needs to be stronger or removable', value: 'b', correct: true }, { label: 'The structure is temporary', value: 'c' }, { label: 'Cost is the only concern', value: 'd' }], correctAnswer: 'b', explanation: 'Bolts provide stronger connections than nails and can be removed for maintenance.', outcomeCode: 'SCI.7.D.3.2', difficulty: 1 },
    { id: 'ud-l5-q8', questionText: 'Triangular shapes in trusses are strong because:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'They use less material', value: 'a' }, { label: 'They can\'t be deformed without breaking a side', value: 'b', correct: true }, { label: 'They look modern', value: 'c' }, { label: 'They allow flexibility', value: 'd' }], correctAnswer: 'b', explanation: 'A triangle distributes forces across all three sides and maintains its shape under load.', outcomeCode: 'SCI.7.D.3.2', difficulty: 2 },
  ],
};

const L6 = {
  lesson: { subjectMode: 'SCIENCE', estimatedMinutes: 45, learningGoal: 'Describe the engineering design cycle, explain safety margins and testing, and identify points of failure before building.', successCriteria: 'I can list 7 design cycle steps, explain prototyping and safety margins, and spot potential failure points.', materials: 'Science notebook', reflectionPrompt: 'Think of something you redesigned or improved. How is that similar to the engineering design cycle?', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
  blocks: [
    { id: 'ud-l6-learn-1', section: 'LEARN', blockType: 'VOCABULARY', order: 1, content: { terms: [{ term: 'Design Cycle', definition: 'Identify need → Research → Design → Build → Test → Evaluate → Improve → Repeat.', example: 'Designing a new bridge for a community.' }, { term: 'Safety Margin', definition: 'Extra strength built into a structure beyond minimum requirements.', example: 'A bridge designed to hold 3x its expected maximum load.' }, { term: 'Prototype', definition: 'A test model built before the final version to identify problems.', example: 'A scale model of a building tested in a wind tunnel.' }, { term: 'Constraint', definition: 'Limitations on a design — budget, materials, size, regulations.', example: 'A $500,000 budget for a pedestrian bridge.' }] } },
    { id: 'ud-l6-learn-2', section: 'LEARN', blockType: 'VIDEO', order: 2, content: { url: 'https://www.youtube.com/embed/fxJWin195kU', title: 'The Engineering Design Process', transcript: 'Video explaining the engineering design cycle.' } },
    { id: 'ud-l6-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>📐 The Engineering Design Cycle</h3><ol><li><strong>Identify the Need</strong> — What problem needs solving?</li><li><strong>Research</strong> — Study existing solutions, materials, and constraints.</li><li><strong>Design</strong> — Create drawings, plans, and specifications.</li><li><strong>Build</strong> — Construct a prototype or model.</li><li><strong>Test</strong> — Apply forces and conditions to see how it performs.</li><li><strong>Evaluate</strong> — Did it meet requirements? What failed?</li><li><strong>Improve</strong> — Modify the design based on test results and repeat.</li></ol><p><strong>Safety Margins:</strong> Engineers always build structures stronger than the minimum requirement. A bridge designed for 1000 kg might actually hold 3000 kg — providing a 3x safety margin.</p>' } },
    { id: 'ud-l6-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Match each design concept to its purpose:', pairs: [{ left: 'Prototype', right: 'Test ideas before final construction' }, { left: 'Safety margin', right: 'Build stronger than minimum requirement' }, { left: 'Constraint', right: 'Limit on budget, size, or materials' }, { left: 'Evaluate step', right: 'Check if design meets requirements' }] } },
    { id: 'ud-l6-reflect-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Why do engineers build prototypes before constructing the real structure? Give at least two reasons and an example.', minLength: 60, rubricHint: 'Names 2+ reasons (find flaws, test materials, save money). Gives example. Uses vocabulary.', teacherReviewRequired: false } },
  ],
  questions: [
    { id: 'ud-l6-q1', questionText: 'The first step in the design cycle is:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Build', value: 'a' }, { label: 'Identify the need', value: 'b', correct: true }, { label: 'Test', value: 'c' }, { label: 'Improve', value: 'd' }], correctAnswer: 'b', explanation: 'The design cycle always starts with identifying what problem needs solving.', outcomeCode: 'SCI.7.D.4.1', difficulty: 1 },
    { id: 'ud-l6-q2', questionText: 'A safety margin means:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Building to exact minimum requirements', value: 'a' }, { label: 'Building extra strength beyond minimum — a built-in buffer', value: 'b', correct: true }, { label: 'Using the cheapest materials', value: 'c' }, { label: 'Not testing', value: 'd' }], correctAnswer: 'b', explanation: 'Safety margins provide a buffer — structures are designed stronger than the minimum needed.', outcomeCode: 'SCI.7.D.4.1', difficulty: 1 },
    { id: 'ud-l6-q3', questionText: 'A prototype is built to:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Be the final product', value: 'a' }, { label: 'Test ideas and identify problems before final construction', value: 'b', correct: true }, { label: 'Save materials', value: 'c' }, { label: 'Skip the design phase', value: 'd' }], correctAnswer: 'b', explanation: 'Prototypes catch flaws early — cheaper to fix a model than a full-scale structure.', outcomeCode: 'SCI.7.D.4.1', difficulty: 1 },
    { id: 'ud-l6-q4', questionText: 'A constraint on a design might include:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Unlimited budget', value: 'a' }, { label: 'Budget, materials, size, or regulations', value: 'b', correct: true }, { label: 'No limits at all', value: 'c' }, { label: 'Only colour choices', value: 'd' }], correctAnswer: 'b', explanation: 'Real designs always face practical limits — money, materials, space, and building codes.', outcomeCode: 'SCI.7.D.4.1', difficulty: 1 },
    { id: 'ud-l6-q5', questionText: 'After testing a prototype, the next step is:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Start over completely', value: 'a' }, { label: 'Evaluate results and improve the design', value: 'b', correct: true }, { label: 'Sell the prototype', value: 'c' }, { label: 'Skip to final construction', value: 'd' }], correctAnswer: 'b', explanation: 'Testing → evaluate → improve is the iterative heart of the design cycle.', outcomeCode: 'SCI.7.D.4.1', difficulty: 1 },
    { id: 'ud-l6-q6', questionText: 'Engineers test structures to ensure they:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Look good', value: 'a' }, { label: 'Can handle expected loads plus a safety margin', value: 'b', correct: true }, { label: 'Use the most materials', value: 'c' }, { label: 'Cost the most', value: 'd' }], correctAnswer: 'b', explanation: 'Testing verifies that the structure can handle all expected forces with extra safety margin.', outcomeCode: 'SCI.7.D.4.1', difficulty: 1 },
    { id: 'ud-l6-q7', questionText: 'The design cycle is called a "cycle" because:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'It only happens once', value: 'a' }, { label: 'The process repeats — you keep improving', value: 'b', correct: true }, { label: 'It goes in a straight line', value: 'c' }, { label: 'It\'s about bicycles', value: 'd' }], correctAnswer: 'b', explanation: 'The cycle repeats iteratively — each pass improves the design based on testing and evaluation.', outcomeCode: 'SCI.7.D.4.1', difficulty: 1 },
    { id: 'ud-l6-q8', questionText: 'A 3x safety margin on a bridge means:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'It can hold 3 cars', value: 'a' }, { label: 'It can support 3 times the expected maximum load', value: 'b', correct: true }, { label: 'It has 3 supports', value: 'c' }, { label: 'It cost 3x more', value: 'd' }], correctAnswer: 'b', explanation: 'A 3x safety margin means the bridge handles 3 times the expected maximum force.', outcomeCode: 'SCI.7.D.4.1', difficulty: 2 },
  ],
};

const L7 = {
  lesson: { subjectMode: 'SCIENCE', estimatedMinutes: 45, learningGoal: 'Analyze real-world structural failures, describe failure modes (fatigue, overload, corrosion, resonance), and explain prevention strategies.', successCriteria: 'I can explain 4 failure modes, analyze a real failure case, and describe prevention strategies.', materials: 'Science notebook', reflectionPrompt: 'Have you ever seen a structure that was damaged or failing? What do you think caused it?', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
  blocks: [
    { id: 'ud-l7-learn-1', section: 'LEARN', blockType: 'VOCABULARY', order: 1, content: { terms: [{ term: 'Fatigue', definition: 'Weakening caused by repeated stress cycles over time.', example: 'Bending a paper clip back and forth until it breaks.' }, { term: 'Overload', definition: 'When forces exceed what a structure was designed to handle.', example: 'Too many people on a balcony causing it to collapse.' }, { term: 'Corrosion', definition: 'Gradual chemical destruction of materials — rust on steel, acid rain on stone.', example: 'Rusted bridge supports weakening over decades.' }, { term: 'Resonance', definition: 'When vibrations match a structure\'s natural frequency, amplifying them dangerously.', example: 'Tacoma Narrows Bridge shaking apart in wind.' }] } },
    { id: 'ud-l7-learn-2', section: 'LEARN', blockType: 'VIDEO', order: 2, content: { url: 'https://www.youtube.com/embed/dMg4b6sAelg', title: 'Engineering Failures', transcript: 'Video analyzing famous structural failures.' } },
    { id: 'ud-l7-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>🚨 Why Structures Fail</h3><ul><li>🔧 <strong>Fatigue:</strong> Repeated stress weakens materials over time (like bending a paperclip)</li><li>📈 <strong>Overload:</strong> Too much weight or force beyond design limits</li><li>🌧️ <strong>Corrosion:</strong> Chemical breakdown — rust weakens steel, acid rain erodes stone</li><li>🌊 <strong>Resonance:</strong> Vibrations at the structure\'s natural frequency amplify dangerously (Tacoma Narrows Bridge, 1940)</li></ul><h3>Prevention Strategies</h3><ul><li>Regular inspection and maintenance</li><li>Anti-corrosion coatings (paint, galvanizing)</li><li>Safety margins exceeding minimum requirements</li><li>Dampeners to prevent resonance</li><li>Proper material selection for the environment</li></ul>' } },
    { id: 'ud-l7-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Match each prevention strategy to the failure type it addresses:', pairs: [{ left: 'Anti-rust paint on steel beams', right: 'Corrosion' }, { left: 'Building 3x stronger than minimum required', right: 'Overload' }, { left: 'Regular inspection for cracks', right: 'Fatigue' }, { left: 'Wind dampeners on tall buildings', right: 'Resonance' }] } },
    { id: 'ud-l7-reflect-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'The Tacoma Narrows Bridge collapsed in 1940 due to wind-induced resonance. Using your knowledge, explain what went wrong and how engineers could have prevented it.', minLength: 80, rubricHint: 'Explains resonance concept. Identifies wind as the cause. Suggests prevention methods (dampeners, design changes).', teacherReviewRequired: false } },
  ],
  questions: [
    { id: 'ud-l7-q1', questionText: 'Material fatigue occurs when:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'A structure is hit once very hard', value: 'a' }, { label: 'Repeated stress weakens a material over time', value: 'b', correct: true }, { label: 'A structure gets wet', value: 'c' }, { label: 'A material gets too hot', value: 'd' }], correctAnswer: 'b', explanation: 'Fatigue results from many cycles of stress, not a single event.', outcomeCode: 'SCI.7.D.4.2', difficulty: 1 },
    { id: 'ud-l7-q2', questionText: 'The Tacoma Narrows Bridge collapsed due to:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Too many cars', value: 'a' }, { label: 'Wind-induced resonance — vibrations matched the bridge\'s natural frequency', value: 'b', correct: true }, { label: 'Rust', value: 'c' }, { label: 'An earthquake', value: 'd' }], correctAnswer: 'b', explanation: 'Wind matched the bridge\'s natural frequency, causing vibrations to amplify uncontrollably.', outcomeCode: 'SCI.7.D.4.2', difficulty: 2 },
    { id: 'ud-l7-q3', questionText: 'Corrosion on steel structures is prevented by:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Loading more weight', value: 'a' }, { label: 'Anti-corrosion coatings like paint and galvanizing', value: 'b', correct: true }, { label: 'Adding more joints', value: 'c' }, { label: 'Using glass', value: 'd' }], correctAnswer: 'b', explanation: 'Protective coatings prevent water and oxygen from reaching the steel.', outcomeCode: 'SCI.7.D.4.2', difficulty: 1 },
    { id: 'ud-l7-q4', questionText: 'Overloading a structure means:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Painting it too many times', value: 'a' }, { label: 'Applying forces exceeding its design capacity', value: 'b', correct: true }, { label: 'Building it too tall', value: 'c' }, { label: 'Using too many fasteners', value: 'd' }], correctAnswer: 'b', explanation: 'Overloading occurs when forces exceed what the structure was designed to handle.', outcomeCode: 'SCI.7.D.4.2', difficulty: 1 },
    { id: 'ud-l7-q5', questionText: 'Regular structural inspections help prevent:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'All fires', value: 'a' }, { label: 'Failures from undetected fatigue cracks and corrosion', value: 'b', correct: true }, { label: 'Wind', value: 'c' }, { label: 'Snow', value: 'd' }], correctAnswer: 'b', explanation: 'Inspections catch developing problems (cracks, rust) before they cause failure.', outcomeCode: 'SCI.7.D.4.2', difficulty: 1 },
    { id: 'ud-l7-q6', questionText: 'Resonance is dangerous because:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'It makes structures quieter', value: 'a' }, { label: 'Vibrations at the natural frequency amplify until the structure fails', value: 'b', correct: true }, { label: 'It reduces load', value: 'c' }, { label: 'It only affects wood', value: 'd' }], correctAnswer: 'b', explanation: 'Resonance causes vibrations to grow larger and larger until structural failure.', outcomeCode: 'SCI.7.D.4.2', difficulty: 2 },
    { id: 'ud-l7-q7', questionText: 'Bending a paper clip back and forth demonstrates:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Compression', value: 'a' }, { label: 'Material fatigue', value: 'b', correct: true }, { label: 'Shear', value: 'c' }, { label: 'Resonance', value: 'd' }], correctAnswer: 'b', explanation: 'Each bend applies stress — repeated cycles weaken the metal until it breaks.', outcomeCode: 'SCI.7.D.4.2', difficulty: 1 },
    { id: 'ud-l7-q8', questionText: 'Wind dampeners on skyscrapers prevent:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Compression', value: 'a' }, { label: 'Resonance from wind vibrations', value: 'b', correct: true }, { label: 'Dead load', value: 'c' }, { label: 'Corrosion', value: 'd' }], correctAnswer: 'b', explanation: 'Dampeners absorb vibration energy, preventing resonance buildups from wind.', outcomeCode: 'SCI.7.D.4.2', difficulty: 2 },
  ],
};

const L8 = {
  lesson: { subjectMode: 'SCIENCE', estimatedMinutes: 60, learningGoal: 'Design a pedestrian bridge for an Alberta park, applying concepts of structure types, material selection, force analysis, joint design, and safety margins.', successCriteria: 'I can create a complete bridge design addressing structure type, materials, forces, joints, and safety.', materials: 'Science notebook, coloured pencils, ruler', reflectionPrompt: 'How does your bridge design demonstrate what you\'ve learned about structures throughout this unit?', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
  blocks: [
    { id: 'ud-l8-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h2>🏆 Structure Design & Analysis Report</h2><p>You are a structural engineer designing a new pedestrian bridge for a park in your Alberta community. Complete all 5 sections:</p><ol><li><strong>Structure Type & Form</strong> — Shell, frame, solid, or combination? How does form follow function?</li><li><strong>Materials & Properties</strong> — What materials and why? Reference specific properties.</li><li><strong>Force Analysis</strong> — What internal/external forces act on it? How does your design handle each?</li><li><strong>Joints & Connections</strong> — What joint types and fasteners? Why each choice?</li><li><strong>Safety & Improvement</strong> — Safety margin? Potential failure points? How to test and improve?</li></ol>' } },
    { id: 'ud-l8-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Part 1: Structure Type & Form — What type of structure will your bridge be? Explain how its form follows its function.', minLength: 80, rubricHint: 'Identifies structure type. Explains form-function relationship. Shows understanding of structural concepts.', teacherReviewRequired: true } },
    { id: 'ud-l8-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: 'Part 2: Materials — What materials will you use and why? Reference strength, flexibility, durability, cost.', minLength: 80, rubricHint: 'Names specific materials with properties. Justifies choices for the bridge context.', teacherReviewRequired: true } },
    { id: 'ud-l8-prac-3', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 3, content: { prompt: 'Part 3: Force Analysis — What internal and external forces act on your bridge? How does your design handle each?', minLength: 80, rubricHint: 'Identifies tension, compression, shear. Considers Alberta external forces (wind, snow). Explains design solutions.', teacherReviewRequired: true } },
    { id: 'ud-l8-prac-4', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 4, content: { prompt: 'Part 4: Joints & Safety — What joints, fasteners, and safety margins will you use? What failure points exist and how would you test and improve your design?', minLength: 80, rubricHint: 'Names joint types and fasteners. Defines safety margin. Identifies failure points. References design cycle.', teacherReviewRequired: true } },
    { id: 'ud-l8-reflect-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Reflect on the entire Structures & Forces unit. What was the most important concept you learned? How does engineering design help keep people safe?', minLength: 60, rubricHint: 'Makes personal connection. References unit content. Connects to real-world safety.', teacherReviewRequired: false } },
  ],
  questions: [
    { id: 'ud-l8-q1', questionText: 'The best bridge design for a park in Alberta should consider:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Only appearance', value: 'a' }, { label: 'Forces, materials, loads, environmental factors, and safety', value: 'b', correct: true }, { label: 'Only cost', value: 'c' }, { label: 'Only the material', value: 'd' }], correctAnswer: 'b', explanation: 'Good engineering considers all factors: forces, materials, loads, environment, safety, and cost.', outcomeCode: 'SCI.7.D.4.1', difficulty: 1 },
    { id: 'ud-l8-q2', questionText: 'A pedestrian bridge must resist at minimum:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Only dead load', value: 'a' }, { label: 'Dead load + live load (people, wind, snow)', value: 'b', correct: true }, { label: 'No forces', value: 'c' }, { label: 'Only live load', value: 'd' }], correctAnswer: 'b', explanation: 'All bridges must support their own weight plus all expected live loads.', outcomeCode: 'SCI.7.D.2.1', difficulty: 1 },
    { id: 'ud-l8-q3', questionText: 'A truss bridge uses triangular shapes to:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Save paint', value: 'a' }, { label: 'Distribute forces evenly — triangles resist deformation', value: 'b', correct: true }, { label: 'Look decorative', value: 'c' }, { label: 'Reduce dead load to zero', value: 'd' }], correctAnswer: 'b', explanation: 'Triangles can\'t change shape without breaking — they distribute forces across all sides.', outcomeCode: 'SCI.7.D.2.2', difficulty: 1 },
    { id: 'ud-l8-q4', questionText: 'For an Alberta park bridge, the most important external force to consider is:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Earthquakes', value: 'a' }, { label: 'Wind (Chinooks) and snow', value: 'b', correct: true }, { label: 'Tsunamis', value: 'c' }, { label: 'Volcanoes', value: 'd' }], correctAnswer: 'b', explanation: 'Alberta\'s main external forces are strong Chinook winds and heavy snow loads.', outcomeCode: 'SCI.7.D.2.3', difficulty: 1 },
    { id: 'ud-l8-q5', questionText: 'The design cycle helps engineers by:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Skipping testing', value: 'a' }, { label: 'Systematically identifying and solving problems through iteration', value: 'b', correct: true }, { label: 'Building once with no changes', value: 'c' }, { label: 'Only using one material', value: 'd' }], correctAnswer: 'b', explanation: 'The iterative design cycle systematically improves structures through test-evaluate-improve loops.', outcomeCode: 'SCI.7.D.4.1', difficulty: 1 },
    { id: 'ud-l8-q6', questionText: 'Anti-corrosion treatment on a steel bridge prevents:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Compression', value: 'a' }, { label: 'Rust weakening the steel over time', value: 'b', correct: true }, { label: 'Resonance', value: 'c' }, { label: 'Live loads', value: 'd' }], correctAnswer: 'b', explanation: 'Protective coatings prevent rust (corrosion) from weakening the steel structure.', outcomeCode: 'SCI.7.D.4.2', difficulty: 1 },
    { id: 'ud-l8-q7', questionText: 'Gusset plates at bridge joints help by:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Adding weight', value: 'a' }, { label: 'Distributing stress across a triangular plate', value: 'b', correct: true }, { label: 'Making the bridge flexible', value: 'c' }, { label: 'Reducing cost', value: 'd' }], correctAnswer: 'b', explanation: 'Gusset plates spread stress across a wider area, strengthening joints.', outcomeCode: 'SCI.7.D.3.2', difficulty: 2 },
    { id: 'ud-l8-q8', questionText: 'A well-designed bridge balances:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Only appearance', value: 'a' }, { label: 'Strength, safety, cost, materials, and environmental factors', value: 'b', correct: true }, { label: 'Only weight', value: 'c' }, { label: 'Only the budget', value: 'd' }], correctAnswer: 'b', explanation: 'Engineering excellence requires balancing multiple competing factors.', outcomeCode: 'SCI.7.D.4.1', difficulty: 1 },
  ],
};

async function main() {
  console.log('🏗️ ═══ SCIENCE UNIT D: L4-L8 ═══');
  await seed('g7-sci-ud-l4', 'UD L4: Properties of Materials', L4);
  await seed('g7-sci-ud-l5', 'UD L5: Joints & Connections', L5);
  await seed('g7-sci-ud-l6', 'UD L6: The Design Process', L6);
  await seed('g7-sci-ud-l7', 'UD L7: Structural Failure', L7);
  await seed('g7-sci-ud-l8', 'UD L8: Performance Task', L8);
  console.log('\n✅ Unit D L4-L8 complete!');
}
main().catch(console.error).finally(() => { pool.end(); });
