// ============================================
// Seed ELA Unit 6 — "Publish and Reflect" (Lessons 1–4)
// ============================================
// Portfolio building, revision mastery, reflection, literary analysis.
// Run: npx tsx prisma/seed-ela-u6-l1-l4.ts

import { config } from 'dotenv';
config({ path: '.env.local' });
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('Seeding ELA Unit 6 "Publish and Reflect" — L1–L4');

  const lessonDefs = [
    { id: 'g6-ela-u6-l1', title: 'Portfolio Builder', order: 1, learningGoal: 'Select and organize your strongest work from Units 1-5 into a portfolio that demonstrates growth and mastery.', successCriteria: 'I can select 3-5 pieces that represent my best work across different text types.\nI can explain WHY each piece was selected and what it demonstrates.\nI can organize my portfolio with a clear introduction and structure.', reflectionPrompt: 'What does your best work say about you as a learner? How do you decide what represents your growth?' },
    { id: 'g6-ela-u6-l2', title: 'Revision Mastery', order: 2, learningGoal: 'Apply advanced revision strategies to strengthen selected portfolio pieces for clarity, evidence, voice, and mechanics.', successCriteria: 'I can revise for content (ideas and evidence).\nI can revise for organization (flow and structure).\nI can revise for voice (tone, word choice, audience awareness).\nI can edit for conventions (spelling, grammar, punctuation).', reflectionPrompt: 'How has your revision process changed since Unit 1? What do you now do differently when you revise?' },
    { id: 'g6-ela-u6-l3', title: 'Growth Reflection', order: 3, learningGoal: 'Write a reflective essay analyzing your growth as a reader, writer, speaker, and thinker across Grade 6 ELA.', successCriteria: 'I can describe specific skills I have developed.\nI can provide evidence of growth using examples from my portfolio.\nI can set meaningful goals for Grade 7 ELA.\nI can use reflective language that shows metacognitive awareness.', reflectionPrompt: 'What has surprised you most about your own growth this year? What are you most proud of?' },
    { id: 'g6-ela-u6-l4', title: 'Literary Analysis Capstone', order: 4, learningGoal: 'Demonstrate reading comprehension, text analysis, and critical thinking by analyzing a new text using skills built across all 5 previous units.', successCriteria: 'I can identify theme, conflict, and character development in a new text.\nI can analyze figurative language and text features.\nI can make inferences supported by textual evidence.\nI can connect the text to other texts, personal experiences, and the world.', reflectionPrompt: 'How does analyzing literature help you understand the world and yourself better?' },
  ];

  for (const l of lessonDefs) {
    await prisma.lesson.upsert({
      where: { id: l.id },
      update: { title: l.title, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
      create: { id: l.id, unitId: 'g6-ela-u6', title: l.title, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
    });
  }
  console.log('Lessons 1-4 upserted');

  for (const l of lessonDefs) {
    await prisma.lessonBlock.deleteMany({ where: { lessonId: l.id } });
    await prisma.quizQuestion.deleteMany({ where: { lessonId: l.id } });
  }

  // L1: Portfolio Builder — WC.1, WC.3, Review: WC.4, RC.3
  const L1 = 'g6-ela-u6-l1';
  const l1Blocks = [
    { id: 'u6-l1-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>What Is a Portfolio?</h3><p>A <strong>portfolio</strong> is a curated collection of your best work that tells the story of your growth as a learner. It is NOT "everything you did" — it is a deliberate selection of pieces that demonstrate mastery, growth, and voice.</p><p><strong>A strong portfolio includes:</strong></p><ul><li>3-5 selected pieces from different units and text types (narrative, informational, argument, poetry, etc.)</li><li>A brief introduction explaining your selections</li><li>For each piece: a reflection on WHY you chose it and what it demonstrates about your learning</li></ul>' } },
    { id: 'u6-l1-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Selection Criteria</h3><p>When choosing portfolio pieces, ask yourself:</p><ul><li><strong>Does this show my GROWTH?</strong> It does not have to be perfect — it can show where you struggled and improved.</li><li><strong>Does this demonstrate a KEY SKILL?</strong> Reading comprehension, writing craft, oral communication, critical thinking.</li><li><strong>Am I PROUD of this?</strong> Does this piece represent me as a learner?</li><li><strong>Does my portfolio show RANGE?</strong> Include different types of writing and thinking, not just one kind.</li></ul>' } },
    { id: 'u6-l1-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: 'A portfolio is:', options: [{ label: 'Every assignment you completed this year', value: 'a' }, { label: 'A curated selection of your best or most meaningful work that demonstrates growth and mastery', value: 'b', correct: true }, { label: 'Only your highest graded work', value: 'c' }], explanation: 'Curation means choosing with purpose. A portfolio tells the story of your learning journey — including growth, not just perfection.' } },
    { id: 'u6-l1-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Build your portfolio:\n\n1. List 3-5 pieces you want to include (title, unit, type of writing)\n2. For EACH piece, write 2-3 sentences explaining WHY you chose it and what skill or growth it demonstrates\n3. Write a 4-6 sentence PORTFOLIO INTRODUCTION that explains what the collection shows about you as a learner', minLength: 60 } },
    { id: 'u6-l1-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'What does your best work say about you as a learner? How do you decide what represents your growth?', minLength: 30 } },
  ];
  for (const b of l1Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L1, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log('L1: ' + l1Blocks.length + ' blocks');

  const l1Qs = [
    { id: 'u6-l1-q1', questionText: 'A PORTFOLIO is:', options: [{ label: 'Every assignment you completed', value: 'a' }, { label: 'A curated collection of work that demonstrates growth, mastery, and voice', value: 'b', correct: true }, { label: 'Only your favourite assignment', value: 'c' }, { label: 'A folder of unfinished work', value: 'd' }], correctAnswer: 'b', explanation: 'Portfolios are curated — selected with purpose and intention to tell the story of your learning.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u6-l1-q2', questionText: '"Curated" means:', options: [{ label: 'Everything included', value: 'a' }, { label: 'Carefully selected with purpose and intention', value: 'b', correct: true }, { label: 'Random', value: 'c' }, { label: 'Only the newest work', value: 'd' }], correctAnswer: 'b', explanation: 'Curation is thoughtful selection. It requires evaluating your work and choosing pieces that best represent your learning journey.', outcomeCode: 'ELA.6.WC.3', difficulty: 1 },
    { id: 'u6-l1-q3', questionText: 'A strong portfolio should include:', options: [{ label: 'Only narrative writing', value: 'a' }, { label: 'A range of text types that demonstrate different skills', value: 'b', correct: true }, { label: 'Only perfect work with no mistakes', value: 'c' }, { label: 'Only work from one unit', value: 'd' }], correctAnswer: 'b', explanation: 'Range shows versatility. Including narrative, informational, argument, and creative writing demonstrates broad ELA skills.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u6-l1-q4', questionText: 'Including a piece that shows GROWTH (not perfection) is valuable because:', options: [{ label: 'It fills space', value: 'a' }, { label: 'It demonstrates learning from challenges, which is more meaningful than only showing easy successes', value: 'b', correct: true }, { label: 'It shows you struggled', value: 'c' }, { label: 'It is not valuable', value: 'd' }], correctAnswer: 'b', explanation: 'Growth pieces show resilience and metacognition. Explaining HOW you improved is powerful evidence of real learning.', outcomeCode: 'ELA.6.WC.1', difficulty: 2 },
    { id: 'u6-l1-q5', questionText: 'Writing a reflection for each portfolio piece requires:', options: [{ label: 'Just saying "I liked this one"', value: 'a' }, { label: 'Explaining WHY you chose it, what skill it demonstrates, and what it shows about your learning', value: 'b', correct: true }, { label: 'Copying the assignment instructions', value: 'c' }, { label: 'Only stating the grade you received', value: 'd' }], correctAnswer: 'b', explanation: 'Reflection is metacognition — thinking about your own thinking. Specific reasons and evidence show depth of self-awareness.', outcomeCode: 'ELA.6.RC.3', difficulty: 2 },
    { id: 'u6-l1-q6', questionText: 'Choosing pieces that represent your VOICE means:', options: [{ label: 'Picking the longest ones', value: 'a' }, { label: 'Selecting work where your unique perspective, writing style, and thinking come through', value: 'b', correct: true }, { label: 'Only choosing creative writing', value: 'c' }, { label: 'Choosing pieces written by others', value: 'd' }], correctAnswer: 'b', explanation: 'Voice is what makes your writing distinctly yours — your choices, your perspective, your way of communicating.', outcomeCode: 'ELA.6.WC.4', difficulty: 2 },
    { id: 'u6-l1-q7', questionText: 'A portfolio INTRODUCTION should:', options: [{ label: 'List every assignment title', value: 'a' }, { label: 'Explain what the collection shows about you as a learner and preview your selected pieces', value: 'b', correct: true }, { label: 'Apologize for mistakes', value: 'c' }, { label: 'Copy from someone else', value: 'd' }], correctAnswer: 'b', explanation: 'The introduction frames the portfolio — it helps the reader understand your purpose, your growth, and what to look for.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u6-l1-q8', questionText: 'The process of selecting portfolio pieces is itself a demonstration of:', options: [{ label: 'Nothing', value: 'a' }, { label: 'Self-assessment and metacognition — the ability to evaluate your own work honestly', value: 'b', correct: true }, { label: 'Only organizational skills', value: 'c' }, { label: 'Memory', value: 'd' }], correctAnswer: 'b', explanation: 'Portfolio curation requires honest self-evaluation: "What represents my best effort? Where did I grow? What am I proud of?" This IS metacognition.', outcomeCode: 'ELA.6.RC.3', difficulty: 2 },
  ];
  for (const q of l1Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L1, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log('L1: ' + l1Qs.length + ' questions');

  // L2: Revision Mastery — WC.3, WC.5, Review: WC.1, WC.2
  const L2 = 'g6-ela-u6-l2';
  const l2Blocks = [
    { id: 'u6-l2-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Revision: The Secret of Good Writing</h3><p><strong>"Writing is rewriting."</strong> — Every professional writer revises multiple times before publishing.</p><p>Revision is NOT just fixing spelling. It happens at multiple levels:</p><ol><li><strong>Content:</strong> Are my ideas clear? Is my evidence strong? Do I say what I mean?</li><li><strong>Organization:</strong> Does it flow logically? Are my transitions smooth? Does each paragraph have a purpose?</li><li><strong>Voice:</strong> Does this sound like ME? Is my tone appropriate for my audience?</li><li><strong>Conventions:</strong> Spelling, grammar, punctuation — the final polish.</li></ol>' } },
    { id: 'u6-l2-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Revision Checklist</h3><table style="width:100%;border-collapse:collapse"><tr style="background:#f1f5f9"><th style="padding:8px;border:1px solid #e2e8f0">Level</th><th style="padding:8px;border:1px solid #e2e8f0">Questions to Ask</th></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Content</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Is my main idea clear? Do I have enough evidence? Are there gaps in my reasoning?</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Organization</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Does my intro hook the reader? Do my paragraphs follow a logical order? Is my conclusion strong?</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Voice</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Does this sound like me? Is my tone right for the audience? Did I show, not tell?</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Conventions</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Spelling? Grammar? Punctuation? Capitalization?</td></tr></table>' } },
    { id: 'u6-l2-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: 'The FIRST level of revision should focus on:', options: [{ label: 'Spelling errors', value: 'a' }, { label: 'CONTENT — are the ideas clear and well-supported with evidence?', value: 'b', correct: true }, { label: 'Font choices', value: 'c' }], explanation: 'Content revision comes first because changing the ideas may require rewriting entire sections. Fixing spelling first wastes time if you rewrite later.' } },
    { id: 'u6-l2-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Choose ONE portfolio piece and revise it using all 4 levels:\n\n1. CONTENT: What ideas did you strengthen? What evidence did you add or improve?\n2. ORGANIZATION: What did you rearrange or restructure? Are transitions smooth?\n3. VOICE: Where did you improve word choice or tone?\n4. CONVENTIONS: What spelling, grammar, or punctuation errors did you fix?\n\nWrite 2-3 sentences about EACH level of revision you performed.', minLength: 60 } },
    { id: 'u6-l2-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'How has your revision process changed since Unit 1? What do you now do differently when you revise?', minLength: 30 } },
  ];
  for (const b of l2Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L2, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log('L2: ' + l2Blocks.length + ' blocks');

  const l2Qs = [
    { id: 'u6-l2-q1', questionText: 'The FIRST step of revision should focus on:', options: [{ label: 'Fixing commas', value: 'a' }, { label: 'Content — ensuring ideas are clear and evidence is strong', value: 'b', correct: true }, { label: 'Choosing a font', value: 'c' }, { label: 'Checking word count', value: 'd' }], correctAnswer: 'b', explanation: 'Start with the big picture (content/ideas) before the details (conventions). You may rewrite sections, making early editing wasted effort.', outcomeCode: 'ELA.6.WC.3', difficulty: 1 },
    { id: 'u6-l2-q2', questionText: '"Writing is rewriting" means:', options: [{ label: 'Copy your work twice', value: 'a' }, { label: 'Good writing comes from revision — the first draft is just the beginning', value: 'b', correct: true }, { label: 'Never change anything', value: 'c' }, { label: 'Only professionals revise', value: 'd' }], correctAnswer: 'b', explanation: 'First drafts capture ideas. Revision shapes them into clear, powerful writing. Professional writers revise many times.', outcomeCode: 'ELA.6.WC.3', difficulty: 1 },
    { id: 'u6-l2-q3', questionText: 'Revising for ORGANIZATION means:', options: [{ label: 'Only checking spelling', value: 'a' }, { label: 'Ensuring ideas flow logically, transitions are smooth, and each paragraph has a clear purpose', value: 'b', correct: true }, { label: 'Making it longer', value: 'c' }, { label: 'Changing the title', value: 'd' }], correctAnswer: 'b', explanation: 'Organization revision checks the STRUCTURE: Does the order make sense? Do transitions connect ideas? Does each paragraph earn its place?', outcomeCode: 'ELA.6.WC.3', difficulty: 1 },
    { id: 'u6-l2-q4', questionText: 'Revising for VOICE means:', options: [{ label: 'Speaking louder', value: 'a' }, { label: 'Ensuring your unique writing style, tone, and word choices come through authentically', value: 'b', correct: true }, { label: 'Using the biggest words possible', value: 'c' }, { label: 'Removing all personality', value: 'd' }], correctAnswer: 'b', explanation: 'Voice revision checks that your writing sounds like YOU — your perspective, your word choices, your way of communicating to your specific audience.', outcomeCode: 'ELA.6.WC.3', difficulty: 2 },
    { id: 'u6-l2-q5', questionText: 'CONVENTIONS (spelling, grammar, punctuation) should be checked:', options: [{ label: 'First, before anything else', value: 'a' }, { label: 'LAST — after content, organization, and voice revisions are complete', value: 'b', correct: true }, { label: 'Never', value: 'c' }, { label: 'Only by the teacher', value: 'd' }], correctAnswer: 'b', explanation: 'Conventions are the final polish. Fix them last because earlier revisions may add, remove, or rewrite sections.', outcomeCode: 'ELA.6.WC.5', difficulty: 1 },
    { id: 'u6-l2-q6', questionText: 'Peer feedback during revision is valuable because:', options: [{ label: 'It saves the writer time', value: 'a' }, { label: 'Another reader can identify unclear spots, missing evidence, and strengths the writer cannot see', value: 'b', correct: true }, { label: 'It replaces self-revision', value: 'c' }, { label: 'Only teachers can give good feedback', value: 'd' }], correctAnswer: 'b', explanation: 'Writers are often too close to their own work. A fresh reader catches gaps, confusion, and strengths that the writer may not notice.', outcomeCode: 'ELA.6.WC.1', difficulty: 2 },
    { id: 'u6-l2-q7', questionText: 'The four levels of revision in order are:', options: [{ label: 'Conventions, voice, organization, content', value: 'a' }, { label: 'Content, organization, voice, conventions', value: 'b', correct: true }, { label: 'Voice, content, conventions, organization', value: 'c' }, { label: 'There is no order', value: 'd' }], correctAnswer: 'b', explanation: 'Big picture first (content), then structure (organization), then style (voice), then details (conventions). This is the most efficient order.', outcomeCode: 'ELA.6.WC.3', difficulty: 1 },
    { id: 'u6-l2-q8', questionText: 'Strong multi-paragraph organization includes:', options: [{ label: 'One long paragraph', value: 'a' }, { label: 'Introduction, focused body paragraphs with transitions, and a conclusion', value: 'b', correct: true }, { label: 'Random order of ideas', value: 'c' }, { label: 'Only bullet points', value: 'd' }], correctAnswer: 'b', explanation: 'Clear structure helps the reader follow your thinking. Each body paragraph should have a focused idea that connects to the overall purpose.', outcomeCode: 'ELA.6.WC.2', difficulty: 1 },
  ];
  for (const q of l2Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L2, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log('L2: ' + l2Qs.length + ' questions');

  // L3: Growth Reflection — WC.4, RC.3, Review: WC.1, OC.3
  const L3 = 'g6-ela-u6-l3';
  const l3Blocks = [
    { id: 'u6-l3-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Reflecting on Your Learning Journey</h3><p>A <strong>reflective essay</strong> is different from other essays — it looks INWARD at your own growth, thinking, and development.</p><p><strong>Structure of a reflective essay:</strong></p><ol><li><strong>Where I started:</strong> What skills did you have at the beginning of Grade 6 ELA?</li><li><strong>What I learned:</strong> What specific skills have you developed? Use evidence from your portfolio.</li><li><strong>What challenged me:</strong> What was hard? How did you push through?</li><li><strong>Where I am now:</strong> How have you grown as a reader, writer, speaker, and thinker?</li><li><strong>Where I am going:</strong> What goals do you have for Grade 7?</li></ol>' } },
    { id: 'u6-l3-learn-2', section: 'LEARN', blockType: 'MICRO_CHECK', order: 2, content: { question: 'A reflective essay is different from other essays because it:', options: [{ label: 'Only uses outside sources', value: 'a' }, { label: 'Looks INWARD — analyzing your own growth, thinking, and development as a learner', value: 'b', correct: true }, { label: 'Has no structure', value: 'c' }], explanation: 'Reflective writing is metacognitive — it requires you to think about your own thinking and learning with honesty and specificity.' } },
    { id: 'u6-l3-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Write a reflective essay (at least 3 paragraphs) addressing:\n\n1. WHERE I STARTED: Describe your reading, writing, or communication skills at the beginning of Grade 6.\n2. WHAT I LEARNED: Identify 3-4 specific skills you developed (use evidence from your portfolio).\n3. WHAT CHALLENGED ME: Describe a specific challenge and how you worked through it.\n4. WHERE I AM NOW: How have you grown? What can you do now that you could not do before?\n5. WHERE I AM GOING: Set 2-3 goals for Grade 7 ELA.', minLength: 100 } },
    { id: 'u6-l3-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'What has surprised you most about your own growth this year? What are you most proud of?', minLength: 30 } },
  ];
  for (const b of l3Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L3, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log('L3: ' + l3Blocks.length + ' blocks');

  const l3Qs = [
    { id: 'u6-l3-q1', questionText: 'A REFLECTIVE ESSAY:', options: [{ label: 'Analyzes someone else work', value: 'a' }, { label: 'Looks inward — analyzing your own growth, thinking, and development', value: 'b', correct: true }, { label: 'Has no personal content', value: 'c' }, { label: 'Only describes events', value: 'd' }], correctAnswer: 'b', explanation: 'Reflective essays are personal and metacognitive. They require honest self-evaluation and specific evidence of growth.', outcomeCode: 'ELA.6.WC.4', difficulty: 1 },
    { id: 'u6-l3-q2', questionText: 'METACOGNITION means:', options: [{ label: 'A type of poem', value: 'a' }, { label: 'Thinking about your own thinking — understanding how you learn and process information', value: 'b', correct: true }, { label: 'A vocabulary word', value: 'c' }, { label: 'A reading strategy', value: 'd' }], correctAnswer: 'b', explanation: 'Meta = about, cognition = thinking. Metacognition is the ability to reflect on your own thought processes, strengths, and areas for growth.', outcomeCode: 'ELA.6.RC.3', difficulty: 1 },
    { id: 'u6-l3-q3', questionText: 'Setting GOALS for Grade 7 in a reflective essay demonstrates:', options: [{ label: 'That you are done learning', value: 'a' }, { label: 'Forward-thinking self-awareness and understanding that learning is ongoing', value: 'b', correct: true }, { label: 'Nothing important', value: 'c' }, { label: 'Only planning', value: 'd' }], correctAnswer: 'b', explanation: 'Goals show that you understand learning never stops. Specific, actionable goals ("I want to improve argument writing") show mature self-awareness.', outcomeCode: 'ELA.6.WC.4', difficulty: 2 },
    { id: 'u6-l3-q4', questionText: 'Using EVIDENCE FROM YOUR PORTFOLIO in a reflective essay:', options: [{ label: 'Is unnecessary', value: 'a' }, { label: 'Strengthens your reflection by showing specific, concrete proof of growth', value: 'b', correct: true }, { label: 'Makes it too long', value: 'c' }, { label: 'Only works for research essays', value: 'd' }], correctAnswer: 'b', explanation: '"I improved at argument writing" is a claim. "In my Unit 4 essay, I used counterarguments for the first time" is evidence. Evidence matters in all writing.', outcomeCode: 'ELA.6.WC.4', difficulty: 2 },
    { id: 'u6-l3-q5', questionText: 'Describing a CHALLENGE in your reflective essay shows:', options: [{ label: 'Weakness', value: 'a' }, { label: 'Resilience, honest self-assessment, and the ability to learn from difficulty', value: 'b', correct: true }, { label: 'That you did not try hard enough', value: 'c' }, { label: 'Nothing valuable', value: 'd' }], correctAnswer: 'b', explanation: 'Sharing challenges honestly shows self-awareness and growth mindset. HOW you overcame difficulty is more impressive than never struggling.', outcomeCode: 'ELA.6.WC.4', difficulty: 1 },
    { id: 'u6-l3-q6', questionText: 'The writing process applies to reflective writing because:', options: [{ label: 'It does not apply', value: 'a' }, { label: 'Reflective essays still need planning, drafting, revision, and editing', value: 'b', correct: true }, { label: 'Only the first draft matters', value: 'c' }, { label: 'Reflection is just stream of consciousness', value: 'd' }], correctAnswer: 'b', explanation: 'Even personal writing benefits from revision. Clarifying your thoughts, strengthening your evidence, and polishing your prose makes reflection more powerful.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u6-l3-q7', questionText: 'Discussing your growth as a READER, WRITER, SPEAKER, and THINKER shows:', options: [{ label: 'Too many topics', value: 'a' }, { label: 'A comprehensive understanding that ELA skills are interconnected', value: 'b', correct: true }, { label: 'You only focused on one area', value: 'c' }, { label: 'Nothing significant', value: 'd' }], correctAnswer: 'b', explanation: 'ELA is not just reading OR writing — all four areas work together. Reflecting on all of them shows holistic understanding.', outcomeCode: 'ELA.6.RC.3', difficulty: 2 },
    { id: 'u6-l3-q8', questionText: 'Giving AND receiving peer feedback throughout the year has helped you:', options: [{ label: 'Only helped others', value: 'a' }, { label: 'Develop critical reading skills, empathy, communication, and the ability to improve your own work', value: 'b', correct: true }, { label: 'Waste time', value: 'c' }, { label: 'Only with spelling', value: 'd' }], correctAnswer: 'b', explanation: 'Peer feedback is a two-way skill. Giving feedback builds critical thinking. Receiving feedback builds resilience and self-improvement.', outcomeCode: 'ELA.6.OC.3', difficulty: 1 },
  ];
  for (const q of l3Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L3, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log('L3: ' + l3Qs.length + ' questions');

  // L4: Literary Analysis Capstone — RC.1, TF.1, Review: VL.2, TR.2, RC.2
  const L4 = 'g6-ela-u6-l4';
  const l4Blocks = [
    { id: 'u6-l4-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Literary Analysis: The Full Toolkit</h3><p>Across Units 1-5, you built a complete set of literary analysis skills. Now you will apply ALL of them to a new text:</p><ul><li><strong>Unit 1:</strong> Genre, character development, plot structure, theme</li><li><strong>Unit 2:</strong> Narrative voice, creative writing, storytelling</li><li><strong>Unit 3:</strong> Non-fiction analysis, evidence, fact vs opinion, research</li><li><strong>Unit 4:</strong> Perspective, bias, argument, communication</li><li><strong>Unit 5:</strong> Poetry, figurative language, drama, rhetoric</li></ul>' } },
    { id: 'u6-l4-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Capstone Text: "The Last Leaf"</h3><blockquote style="border-left:3px solid #10b981;padding:12px 16px;margin:12px 0;color:#475569"><p>Mara pressed her face against the window, watching the last leaf cling stubbornly to the old oak. The doctors had said autumn would be hard. "When that leaf falls," Mara had whispered to her grandmother, "it will be time to say goodbye."</p><p>But the leaf held on. Through rain and wind and the first bitter frost, it held on. Each morning, Mara would check — and there it was, golden and defiant, trembling but refusing to let go.</p><p>On the seventieth day, Mara noticed something. The leaf was not golden anymore. It had been painted — fresh green paint, brushed carefully onto the bark where a real leaf had once grown.</p><p>She turned to her grandmother, who sat in a chair by the door, thin but smiling. "You painted it," Mara said, half laughing, half crying.</p><p>Her grandmother shrugged. "Sometimes hope needs a little help."</p></blockquote>' } },
    { id: 'u6-l4-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: 'The LEAF in this story is a SYMBOL for:', options: [{ label: 'Just a leaf on a tree', value: 'a' }, { label: 'Hope, persistence, and the will to hold on during difficult times', value: 'b', correct: true }, { label: 'The season of autumn', value: 'c' }], explanation: 'The leaf symbolizes hope. When the grandmother paints a new one, she is literally creating hope — refusing to let it fall. The symbol carries the entire emotional message.' } },
    { id: 'u6-l4-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Analyze "The Last Leaf" using skills from ALL 5 previous units:\n\n1. UNIT 1 (Genre/Plot/Theme): What genre is this? What is the central conflict? What is the THEME?\n2. UNIT 2 (Narrative Voice): What point of view is this told from? How does the narrator reveal emotion?\n3. UNIT 3 (Evidence): Find a TEXT-BASED inference. Quote the evidence and explain your reasoning.\n4. UNIT 4 (Perspective): How might the story be DIFFERENT if told from the grandmother perspective?\n5. UNIT 5 (Figurative Language): Identify ONE example of figurative language or symbolism. Explain its effect.\n6. CONNECTIONS: Make one text-to-self, text-to-text, or text-to-world connection.', minLength: 80 } },
    { id: 'u6-l4-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'How does analyzing literature help you understand the world and yourself better? Use a specific example from this analysis.', minLength: 30 } },
  ];
  for (const b of l4Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L4, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log('L4: ' + l4Blocks.length + ' blocks');

  const l4Qs = [
    { id: 'u6-l4-q1', questionText: 'The THEME of "The Last Leaf" is:', options: [{ label: 'Trees lose leaves in autumn', value: 'a' }, { label: 'Hope requires action — sometimes we must actively create and sustain hope, especially during difficult times', value: 'b', correct: true }, { label: 'Painting is fun', value: 'c' }, { label: 'Grandmothers are always right', value: 'd' }], correctAnswer: 'b', explanation: 'The grandmother does not passively wait for hope — she CREATES it by painting the leaf. The theme is that hope is an active choice.', outcomeCode: 'ELA.6.TF.1', difficulty: 2 },
    { id: 'u6-l4-q2', questionText: 'The LEAF in the story symbolizes:', options: [{ label: 'Nature', value: 'a' }, { label: 'Hope, persistence, and the will to hold on', value: 'b', correct: true }, { label: 'Autumn weather', value: 'c' }, { label: 'The colour green', value: 'd' }], correctAnswer: 'b', explanation: 'The leaf is not just a leaf — it represents hope. When it would have fallen (hope fading), the grandmother intervenes. The symbol carries emotional weight beyond the literal.', outcomeCode: 'ELA.6.VL.2', difficulty: 1 },
    { id: 'u6-l4-q3', questionText: '"Golden and defiant, trembling but refusing to let go" is an example of:', options: [{ label: 'Only description', value: 'a' }, { label: 'PERSONIFICATION — the leaf is given human qualities (defiance, refusal)', value: 'b', correct: true }, { label: 'A simile', value: 'c' }, { label: 'A fact statement', value: 'd' }], correctAnswer: 'b', explanation: 'Defiance and refusal are human qualities. Giving them to the leaf makes it a character — mirroring the grandmother resilience.', outcomeCode: 'ELA.6.VL.2', difficulty: 1 },
    { id: 'u6-l4-q4', questionText: 'The central CONFLICT in the story is:', options: [{ label: 'Person vs Person', value: 'a' }, { label: 'Person vs Nature/Mortality — Mara fears losing her grandmother as the seasons change', value: 'b', correct: true }, { label: 'Person vs Technology', value: 'c' }, { label: 'There is no conflict', value: 'd' }], correctAnswer: 'b', explanation: 'The deepest conflict is Mara facing the possibility of loss. The leaf becomes the physical marker of that emotional struggle.', outcomeCode: 'ELA.6.TF.1', difficulty: 2 },
    { id: 'u6-l4-q5', questionText: 'You can INFER from "thin but smiling" that the grandmother:', options: [{ label: 'Is perfectly healthy', value: 'a' }, { label: 'Is physically weakened by illness but remains emotionally strong and hopeful', value: 'b', correct: true }, { label: 'Has gained weight', value: 'c' }, { label: 'Is angry', value: 'd' }], correctAnswer: 'b', explanation: '"Thin" suggests illness has affected her body, but "smiling" shows her spirit is unbroken. The contrast reveals character depth.', outcomeCode: 'ELA.6.RC.1', difficulty: 1 },
    { id: 'u6-l4-q6', questionText: 'If this story were told from the GRANDMOTHER perspective, the reader would likely learn more about:', options: [{ label: 'Nothing new', value: 'a' }, { label: 'Her fears, her decision to paint the leaf, and her motivation to protect Mara emotionally', value: 'b', correct: true }, { label: 'Only weather patterns', value: 'c' }, { label: 'Her cooking recipes', value: 'd' }], correctAnswer: 'b', explanation: 'Perspective shift would reveal the grandmother inner world — her own fears, her love for Mara, and the moment she decided to act.', outcomeCode: 'ELA.6.TR.2', difficulty: 2 },
    { id: 'u6-l4-q7', questionText: '"Sometimes hope needs a little help" functions as:', options: [{ label: 'Just a sentence', value: 'a' }, { label: 'The RESOLUTION and thematic statement — the grandmother wisdom captures the story entire meaning', value: 'b', correct: true }, { label: 'Evidence from a study', value: 'c' }, { label: 'A stage direction', value: 'd' }], correctAnswer: 'b', explanation: 'This single line contains the theme, the resolution, and the grandmother character in one sentence. It is the emotional and thematic core.', outcomeCode: 'ELA.6.TF.1', difficulty: 2 },
    { id: 'u6-l4-q8', questionText: 'A TEXT-TO-WORLD connection to this story might be:', options: [{ label: 'I once saw a tree', value: 'a' }, { label: 'People around the world find creative ways to sustain hope during illness, hardship, and uncertainty', value: 'b', correct: true }, { label: 'Autumn is my favourite season', value: 'c' }, { label: 'I like painting', value: 'd' }], correctAnswer: 'b', explanation: 'Text-to-world connects the story themes to real-world patterns. Hope during illness is a universal human experience.', outcomeCode: 'ELA.6.RC.2', difficulty: 1 },
  ];
  for (const q of l4Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L4, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log('L4: ' + l4Qs.length + ' questions');

  console.log('\n=== ELA UNIT 6 (L1-L4) SEED COMPLETE ===');
  console.log('Lessons:   4');
  console.log('Blocks:    ' + (l1Blocks.length + l2Blocks.length + l3Blocks.length + l4Blocks.length));
  console.log('Questions: ' + (l1Qs.length + l2Qs.length + l3Qs.length + l4Qs.length));
}

main()
  .catch((e) => { console.error('Seed error:', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); pool.end(); });
