// ============================================
// Seed ELA Unit 3 — "Truth, Evidence, and Information" (Lessons 1–4)
// ============================================
// Non-fiction reading, word origins, academic vocabulary, fact vs opinion.
// Run: npx tsx prisma/seed-ela-u3-l1-l4.ts

import { config } from 'dotenv';
config({ path: '.env.local' });
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🔎 Seeding ELA Unit 3 "Truth, Evidence, and Information" — L1–L4');

  const lessonDefs = [
    { id: 'g6-ela-u3-l1', title: 'Reading Non-Fiction', order: 1, learningGoal: 'Identify and analyze text features and organizational structures in non-fiction texts to comprehend main ideas.', successCriteria: 'I can identify text features (headings, captions, glossaries, indexes) and explain how they help readers.\nI can determine the main idea and supporting details in a non-fiction text.\nI can explain how a text\'s organization supports its purpose.', reflectionPrompt: 'How is reading non-fiction different from reading fiction? What strategies help you most?' },
    { id: 'g6-ela-u3-l2', title: 'Word Roots & Origins', order: 2, learningGoal: 'Examine word origins including Greek/Latin roots, prefixes, and suffixes to unlock the meaning of unfamiliar words.', successCriteria: 'I can identify common Greek and Latin roots and explain their meanings.\nI can use prefixes and suffixes to determine the meaning of an unfamiliar word.\nI can trace a word\'s origin and explain how its meaning has changed.', reflectionPrompt: 'Why is understanding word roots like having a "master key" for vocabulary? Give an example.' },
    { id: 'g6-ela-u3-l3', title: 'Academic Vocabulary', order: 3, learningGoal: 'Distinguish between Tier 1, Tier 2, and Tier 3 vocabulary and apply Tier 2 words across subjects for precise communication.', successCriteria: 'I can explain the difference between Tier 1, 2, and 3 vocabulary.\nI can use Tier 2 words accurately in my own writing and speaking.\nI can identify Tier 3 subject-specific words and use them in context.', reflectionPrompt: 'Why is it important to use precise vocabulary instead of vague words like "thing" or "stuff"?' },
    { id: 'g6-ela-u3-l4', title: 'Fact vs Opinion', order: 4, learningGoal: 'Distinguish between fact and opinion, evaluate claims for evidence, and identify bias in non-fiction texts.', successCriteria: 'I can distinguish between facts and opinions in non-fiction texts.\nI can evaluate whether a claim is supported by evidence.\nI can identify signs of bias in a text and explain how bias affects reliability.', reflectionPrompt: 'Think of something you read online recently. How would you check whether the information was reliable?' },
  ];

  for (const l of lessonDefs) {
    await prisma.lesson.upsert({
      where: { id: l.id },
      update: { title: l.title, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
      create: { id: l.id, unitId: 'g6-ela-u3', title: l.title, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
    });
  }
  console.log('✅ Lessons 1–4 upserted');

  for (const l of lessonDefs) {
    await prisma.lessonBlock.deleteMany({ where: { lessonId: l.id } });
    await prisma.quizQuestion.deleteMany({ where: { lessonId: l.id } });
  }

  // ═══════════════════════════════════════
  // L1: Reading Non-Fiction
  // Target: RC.4 (text features), TF.3 (non-fiction analysis)
  // Review: RC.1 (inference), RC.3 (strategies)
  // ═══════════════════════════════════════
  const L1 = 'g6-ela-u3-l1';
  const l1Blocks = [
    { id: 'u3-l1-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>From Fiction to Non-Fiction</h3><p>In Units 1 and 2, you read and created <em>fiction</em> — made-up stories. Now we shift to <strong>non-fiction</strong> — texts that present real information about the real world.</p><p>Non-fiction includes: textbooks, articles, biographies, news reports, how-to guides, documentaries, and websites.</p><p>Reading non-fiction requires different strategies than reading fiction. You\'re not following a plot — you\'re <strong>extracting, evaluating, and organizing information</strong>.</p>' } },
    { id: 'u3-l1-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Non-Fiction Text Features</h3><p>Non-fiction texts use <strong>text features</strong> to help readers find and understand information:</p><table style="width:100%;border-collapse:collapse"><tr style="background:#f1f5f9"><th style="padding:8px;border:1px solid #e2e8f0">Feature</th><th style="padding:8px;border:1px solid #e2e8f0">Purpose</th></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Headings / Subheadings</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Organize content into sections; tell you what each section is about</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Bold / Italic text</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Highlights important terms or emphasis</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Captions</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Explain images, charts, or diagrams</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Glossary</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Defines key vocabulary at the end of the text</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Index</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Alphabetical list of topics with page numbers</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Charts / Graphs / Maps</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Present data visually to support the text</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Sidebar / Text box</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Provides additional facts or related information</td></tr></table>' } },
    { id: 'u3-l1-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Organizational Structures</h3><p>Authors organize non-fiction in specific ways depending on their purpose:</p><ul><li><strong>Chronological / Sequence:</strong> Events in time order (biographies, how-to guides)</li><li><strong>Cause and Effect:</strong> Explains why something happens and what results (science articles)</li><li><strong>Compare and Contrast:</strong> Shows similarities and differences (product reviews, analysis)</li><li><strong>Problem and Solution:</strong> Identifies a problem and proposes solutions (editorials, research)</li><li><strong>Description:</strong> Provides details about a topic using sensory language (travel writing, profiles)</li></ul>' } },
    { id: 'u3-l1-learn-4', section: 'LEARN', blockType: 'TEXT', order: 4, content: { html: '<h3>Anchor Text: "The Hidden World of Soil"</h3><blockquote style="border-left:3px solid #0ea5e9;padding:12px 16px;margin:12px 0;color:#475569"><strong>The Hidden World of Soil</strong><br><br>Beneath your feet lies one of Earth\'s most complex ecosystems. A single teaspoon of healthy soil contains more microorganisms than there are people on the planet — roughly 8 billion bacteria, fungi, and other microscopic life forms.<br><br><strong>Why Soil Matters</strong><br>Soil is not just "dirt." It is a living system that filters water, stores carbon, and provides nutrients for 95% of the world\'s food. Without healthy soil, crops fail, floods worsen, and ecosystems collapse.<br><br><strong>The Problem</strong><br>Scientists estimate that one-third of the world\'s topsoil has been degraded due to farming practices, deforestation, and pollution. At current rates, some regions could lose their productive soil within 60 years.<br><br><strong>What Can Be Done?</strong><br>Farmers are turning to regenerative techniques: cover cropping, no-till farming, and composting. These methods rebuild soil health while still producing food. "We need to stop treating soil like a factory floor," says Dr. Anika Patel, a soil scientist at the University of Alberta. "It\'s a living community."</blockquote>' } },
    { id: 'u3-l1-learn-5', section: 'LEARN', blockType: 'MICRO_CHECK', order: 5, content: { question: 'The anchor text "The Hidden World of Soil" uses which organizational structure?', options: [{ label: 'Chronological — events in time order', value: 'a' }, { label: 'Problem and Solution — identifies a problem and proposes solutions', value: 'b', correct: true }, { label: 'Compare and Contrast — shows similarities and differences', value: 'c' }], explanation: 'The text presents a problem (soil degradation) and then proposes solutions (regenerative farming techniques). The headings "The Problem" and "What Can Be Done?" signal this structure.' } },
    { id: 'u3-l1-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Match each text feature from the anchor text to its purpose:', pairs: [{ left: '"The Hidden World of Soil" (title)', right: 'Tells the reader what the text is about' }, { left: '"Why Soil Matters" (subheading)', right: 'Organizes the text into a focused section' }, { left: '"8 billion bacteria" (specific number)', right: 'Supports the claim with evidence / data' }, { left: '"says Dr. Anika Patel" (quote)', right: 'Adds credibility through expert authority' }, { left: '"one-third of topsoil has been degraded" (statistic)', right: 'Provides factual evidence for the problem' }] } },
    { id: 'u3-l1-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: 'Reread the anchor text.\n\n1. What is the MAIN IDEA of this text? (One sentence)\n2. List 3 SUPPORTING DETAILS the author uses to support this main idea.\n3. What TEXT FEATURES does the author use to help you navigate the information?\n4. What can you INFER about why the author chose to quote Dr. Patel at the end?', minLength: 50 } },
    { id: 'u3-l1-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'How is reading non-fiction different from reading fiction? What comprehension strategies (from Unit 1) do you find MOST useful when reading informational texts?', minLength: 30 } },
  ];
  for (const b of l1Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L1, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L1: ${l1Blocks.length} blocks`);

  const l1Qs = [
    { id: 'u3-l1-q1', questionText: 'The PURPOSE of headings and subheadings in non-fiction is to:', options: [{ label: 'Make the page look nice', value: 'a' }, { label: 'Organize content into sections and help readers find information', value: 'b', correct: true }, { label: 'Replace the need for paragraphs', value: 'c' }, { label: 'Show the author\'s opinion', value: 'd' }], correctAnswer: 'b', explanation: 'Headings organize information into scannable sections so readers can quickly find what they need.', outcomeCode: 'ELA.6.RC.4', difficulty: 1 },
    { id: 'u3-l1-q2', questionText: 'A GLOSSARY is found at the end of a text and provides:', options: [{ label: 'A list of chapters', value: 'a' }, { label: 'Definitions of key vocabulary used in the text', value: 'b', correct: true }, { label: 'The author\'s biography', value: 'c' }, { label: 'A summary of the text', value: 'd' }], correctAnswer: 'b', explanation: 'A glossary defines important or specialized terms used in the text, helping readers understand unfamiliar vocabulary.', outcomeCode: 'ELA.6.RC.4', difficulty: 1 },
    { id: 'u3-l1-q3', questionText: 'The anchor text states: "A single teaspoon of healthy soil contains more microorganisms than there are people on the planet." This detail serves to:', options: [{ label: 'Confuse the reader with large numbers', value: 'a' }, { label: 'Support the main idea by showing how complex and alive soil is', value: 'b', correct: true }, { label: 'Introduce a new topic', value: 'c' }, { label: 'Provide an opinion about soil', value: 'd' }], correctAnswer: 'b', explanation: 'This comparison makes the invisible world of soil tangible by connecting it to something the reader can understand (world population). It supports the claim that soil is a "complex ecosystem."', outcomeCode: 'ELA.6.TF.3', difficulty: 2 },
    { id: 'u3-l1-q4', questionText: 'Which organizational structure tells events in the order they happened?', options: [{ label: 'Compare and Contrast', value: 'a' }, { label: 'Problem and Solution', value: 'b' }, { label: 'Chronological / Sequence', value: 'c', correct: true }, { label: 'Description', value: 'd' }], correctAnswer: 'c', explanation: 'Chronological/sequence order presents events in the order they occurred — first, then, next, finally.', outcomeCode: 'ELA.6.TF.4', difficulty: 1 },
    { id: 'u3-l1-q5', questionText: 'The author quotes Dr. Anika Patel saying "It\'s a living community." You can INFER that:', options: [{ label: 'Dr. Patel is the author of the article', value: 'a' }, { label: 'The author is using an expert source to add credibility and emphasize the main message', value: 'b', correct: true }, { label: 'Dr. Patel disagrees with the article', value: 'c' }, { label: 'The quote is not important', value: 'd' }], correctAnswer: 'b', explanation: 'Including a quote from a scientist at a university adds authority. The quote also reinforces the text\'s central argument that soil is alive, not just "dirt."', outcomeCode: 'ELA.6.RC.1', difficulty: 2 },
    { id: 'u3-l1-q6', questionText: 'An INDEX helps readers by:', options: [{ label: 'Summarizing each chapter', value: 'a' }, { label: 'Providing an alphabetical list of topics with page numbers for quick reference', value: 'b', correct: true }, { label: 'Defining vocabulary words', value: 'c' }, { label: 'Showing pictures related to the text', value: 'd' }], correctAnswer: 'b', explanation: 'An index lists topics alphabetically with page numbers so readers can quickly locate specific information without reading the entire text.', outcomeCode: 'ELA.6.RC.4', difficulty: 1 },
    { id: 'u3-l1-q7', questionText: 'Which comprehension strategy is MOST useful for non-fiction reading?', options: [{ label: 'Only visualizing', value: 'a' }, { label: 'Questioning — asking "What is the author\'s purpose? Is this fact or opinion? What evidence supports this?"', value: 'b', correct: true }, { label: 'Only predicting what happens next', value: 'c' }, { label: 'Skimming without reading', value: 'd' }], correctAnswer: 'b', explanation: 'Active questioning helps you evaluate non-fiction critically. Asking about purpose, evidence, and fact vs opinion builds media literacy.', outcomeCode: 'ELA.6.RC.3', difficulty: 2 },
    { id: 'u3-l1-q8', questionText: '"Problem and Solution" organizational structure:', options: [{ label: 'Shows similarities between two things', value: 'a' }, { label: 'Identifies a problem and explains possible ways to address it', value: 'b', correct: true }, { label: 'Lists items in alphabetical order', value: 'c' }, { label: 'Tells a story in time order', value: 'd' }], correctAnswer: 'b', explanation: 'Problem-and-solution structure first describes a problem, then proposes one or more solutions. Signal words include "the problem is," "one solution," "as a result."', outcomeCode: 'ELA.6.TF.4', difficulty: 1 },
  ];
  for (const q of l1Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L1, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L1: ${l1Qs.length} questions`);

  // ═══════════════════════════════════════
  // L2: Word Roots & Origins
  // Target: VL.1 (word origins & morphology)
  // Review: VL.3 (context clues)
  // ═══════════════════════════════════════
  const L2 = 'g6-ela-u3-l2';
  const l2Blocks = [
    { id: 'u3-l2-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>The Secret Code of Words</h3><p>Did you know that over 60% of English words come from <strong>Latin</strong> and <strong>Greek</strong>? Learning roots, prefixes, and suffixes is like having a master key that unlocks thousands of words at once.</p><p>Instead of memorizing every word individually, you can <em>decode</em> unfamiliar words by recognizing their parts.</p>' } },
    { id: 'u3-l2-learn-2', section: 'LEARN', blockType: 'VOCABULARY', order: 2, content: { terms: [{ term: 'Root', definition: 'The base part of a word that carries the core meaning.', example: '"bio" (life) → biology, biography, biome' }, { term: 'Prefix', definition: 'A word part added to the BEGINNING that changes the meaning.', example: '"un-" (not) → unhappy, undo, unfair' }, { term: 'Suffix', definition: 'A word part added to the END that changes the meaning or part of speech.', example: '"-tion" (act of) → creation, education, pollution' }, { term: 'Morphology', definition: 'The study of word parts and how they combine to create meaning.', example: 'un + believe + able = unbelievable (not + trust + capable of)' }] } },
    { id: 'u3-l2-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Common Greek & Latin Roots</h3><table style="width:100%;border-collapse:collapse"><tr style="background:#f1f5f9"><th style="padding:8px;border:1px solid #e2e8f0">Root</th><th style="padding:8px;border:1px solid #e2e8f0">Origin</th><th style="padding:8px;border:1px solid #e2e8f0">Meaning</th><th style="padding:8px;border:1px solid #e2e8f0">Examples</th></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>bio</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Greek</td><td style="padding:8px;border:1px solid #e2e8f0">life</td><td style="padding:8px;border:1px solid #e2e8f0">biology, biography, antibiotic</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>geo</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Greek</td><td style="padding:8px;border:1px solid #e2e8f0">earth</td><td style="padding:8px;border:1px solid #e2e8f0">geography, geology, geothermal</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>port</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Latin</td><td style="padding:8px;border:1px solid #e2e8f0">carry</td><td style="padding:8px;border:1px solid #e2e8f0">transport, portable, export</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>struct</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Latin</td><td style="padding:8px;border:1px solid #e2e8f0">build</td><td style="padding:8px;border:1px solid #e2e8f0">structure, construct, instruct</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>rupt</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Latin</td><td style="padding:8px;border:1px solid #e2e8f0">break</td><td style="padding:8px;border:1px solid #e2e8f0">erupt, interrupt, disrupt</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>micro</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Greek</td><td style="padding:8px;border:1px solid #e2e8f0">small</td><td style="padding:8px;border:1px solid #e2e8f0">microscope, microorganism, microphone</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>tele</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Greek</td><td style="padding:8px;border:1px solid #e2e8f0">far</td><td style="padding:8px;border:1px solid #e2e8f0">telescope, telephone, television</td></tr></table>' } },
    { id: 'u3-l2-learn-4', section: 'LEARN', blockType: 'TEXT', order: 4, content: { html: '<h3>Prefixes That Change Meaning</h3><table style="width:100%;border-collapse:collapse"><tr style="background:#f1f5f9"><th style="padding:8px;border:1px solid #e2e8f0">Prefix</th><th style="padding:8px;border:1px solid #e2e8f0">Meaning</th><th style="padding:8px;border:1px solid #e2e8f0">Examples</th></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>un-, in-, im-, dis-</strong></td><td style="padding:8px;border:1px solid #e2e8f0">not / opposite</td><td style="padding:8px;border:1px solid #e2e8f0">unable, invisible, impossible, disagree</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>re-</strong></td><td style="padding:8px;border:1px solid #e2e8f0">again / back</td><td style="padding:8px;border:1px solid #e2e8f0">rebuild, rewrite, return</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>pre-</strong></td><td style="padding:8px;border:1px solid #e2e8f0">before</td><td style="padding:8px;border:1px solid #e2e8f0">preview, predict, prehistoric</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>trans-</strong></td><td style="padding:8px;border:1px solid #e2e8f0">across</td><td style="padding:8px;border:1px solid #e2e8f0">transport, transfer, transform</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>anti-</strong></td><td style="padding:8px;border:1px solid #e2e8f0">against</td><td style="padding:8px;border:1px solid #e2e8f0">antibiotic, antisocial, antivirus</td></tr></table>' } },
    { id: 'u3-l2-learn-5', section: 'LEARN', blockType: 'MICRO_CHECK', order: 5, content: { question: 'The word "microscope" combines "micro" (small) + "scope" (look at). So a microscope is:', options: [{ label: 'A tool that makes things far away look closer', value: 'a' }, { label: 'A tool that lets you look at very small things', value: 'b', correct: true }, { label: 'A type of small camera', value: 'c' }], explanation: 'micro = small, scope = to look at. A microscope is literally "a tool for looking at small things." Knowing roots lets you decode the meaning!' } },
    { id: 'u3-l2-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Break each word into its parts and match to the correct meaning:', pairs: [{ left: 'transport (trans + port)', right: 'carry across' }, { left: 'biology (bio + logy)', right: 'study of life' }, { left: 'prehistoric (pre + history + ic)', right: 'before recorded history' }, { left: 'reconstruct (re + construct)', right: 'build again' }, { left: 'geothermal (geo + thermal)', right: 'earth heat' }, { left: 'disrupt (dis + rupt)', right: 'break apart' }] } },
    { id: 'u3-l2-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: 'Use your word roots knowledge to decode these unfamiliar words:\n\n1. "autobiography" — Break it into parts (auto + bio + graphy). What does each part mean? What is the whole word?\n2. "telepathy" — Break it into parts (tele + pathy). What might this word mean?\n3. Find ONE word in the Unit 3 anchor text ("The Hidden World of Soil") that contains a Greek or Latin root. Identify the root and explain how knowing the root helps you understand the word.', minLength: 40 } },
    { id: 'u3-l2-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Why is understanding word roots like having a "master key" for vocabulary? Give an example of a time when knowing a word root helped (or could help) you figure out an unfamiliar word.', minLength: 30 } },
  ];
  for (const b of l2Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L2, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L2: ${l2Blocks.length} blocks`);

  const l2Qs = [
    { id: 'u3-l2-q1', questionText: 'The Greek root "bio" means:', options: [{ label: 'earth', value: 'a' }, { label: 'life', value: 'b', correct: true }, { label: 'water', value: 'c' }, { label: 'small', value: 'd' }], correctAnswer: 'b', explanation: '"Bio" means life. Biology = study of life, biography = writing about a life, antibiotic = against living bacteria.', outcomeCode: 'ELA.6.VL.1', difficulty: 1 },
    { id: 'u3-l2-q2', questionText: 'Adding the prefix "un-" to a word:', options: [{ label: 'Makes it plural', value: 'a' }, { label: 'Changes it to the opposite meaning', value: 'b', correct: true }, { label: 'Makes it past tense', value: 'c' }, { label: 'Makes it a noun', value: 'd' }], correctAnswer: 'b', explanation: '"Un-" means "not" or "opposite." Happy → unhappy. Fair → unfair. Do → undo.', outcomeCode: 'ELA.6.VL.1', difficulty: 1 },
    { id: 'u3-l2-q3', questionText: 'The word "geothermal" combines "geo" (earth) + "thermal" (heat). Based on these roots, "geothermal energy" is:', options: [{ label: 'Energy from the sun', value: 'a' }, { label: 'Energy from the heat inside the Earth', value: 'b', correct: true }, { label: 'Energy from water', value: 'c' }, { label: 'Energy from wind', value: 'd' }], correctAnswer: 'b', explanation: 'Geo = earth + thermal = heat. Geothermal = Earth-heat. Geothermal energy uses heat from within the Earth.', outcomeCode: 'ELA.6.VL.1', difficulty: 1 },
    { id: 'u3-l2-q4', questionText: '"Microorganism" — based on the roots "micro" (small) + "organism" (living thing), this word means:', options: [{ label: 'A large animal', value: 'a' }, { label: 'A very small living thing', value: 'b', correct: true }, { label: 'A type of machine', value: 'c' }, { label: 'A plant that grows in soil', value: 'd' }], correctAnswer: 'b', explanation: 'Micro = small, organism = living thing. Microorganisms are living things too small to see without a microscope, like bacteria and fungi.', outcomeCode: 'ELA.6.VL.1', difficulty: 1 },
    { id: 'u3-l2-q5', questionText: 'The prefix "trans-" means "across." Which word means "to carry across"?', options: [{ label: 'Transform', value: 'a' }, { label: 'Transport', value: 'b', correct: true }, { label: 'Translate', value: 'c' }, { label: 'Transparent', value: 'd' }], correctAnswer: 'b', explanation: 'Trans = across, port = carry. Transport literally means "to carry across" — moving something from one place to another.', outcomeCode: 'ELA.6.VL.1', difficulty: 2 },
    { id: 'u3-l2-q6', questionText: 'You encounter the unfamiliar word "indestructible." Using context and word parts (in + destruct + ible), you can determine it means:', options: [{ label: 'Easy to build', value: 'a' }, { label: 'Not able to be destroyed', value: 'b', correct: true }, { label: 'Very large', value: 'c' }, { label: 'Rebuilt again', value: 'd' }], correctAnswer: 'b', explanation: 'In- = not, destruct = destroy, -ible = able to be. Indestructible = not able to be destroyed. Word parts + context clues = powerful strategy.', outcomeCode: 'ELA.6.VL.3', difficulty: 2 },
    { id: 'u3-l2-q7', questionText: 'Which is a SUFFIX?', options: [{ label: 'un-', value: 'a' }, { label: 'pre-', value: 'b' }, { label: '-tion', value: 'c', correct: true }, { label: 'bio-', value: 'd' }], correctAnswer: 'c', explanation: 'A suffix is added to the END of a word. "-tion" goes at the end (creation, education). "Un-" and "pre-" are prefixes (beginning). "Bio" is a root.', outcomeCode: 'ELA.6.VL.1', difficulty: 1 },
    { id: 'u3-l2-q8', questionText: 'The Latin root "rupt" means "break." Which word means "to break into" (as in a conversation)?', options: [{ label: 'Erupt', value: 'a' }, { label: 'Interrupt', value: 'b', correct: true }, { label: 'Disrupt', value: 'c' }, { label: 'Corrupt', value: 'd' }], correctAnswer: 'b', explanation: 'Inter = between/into + rupt = break. Interrupt = to break into (a conversation, activity). Erupt = break out, disrupt = break apart.', outcomeCode: 'ELA.6.VL.1', difficulty: 2 },
  ];
  for (const q of l2Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L2, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L2: ${l2Qs.length} questions`);

  // ═══════════════════════════════════════
  // L3: Academic Vocabulary
  // Target: VL.4 (Tier 2/3 vocabulary)
  // Review: VL.1 (word origins)
  // ═══════════════════════════════════════
  const L3 = 'g6-ela-u3-l3';
  const l3Blocks = [
    { id: 'u3-l3-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Three Tiers of Vocabulary</h3><p>Not all words are created equal. Researchers divide vocabulary into three tiers based on how frequently and widely they are used:</p><ul><li><strong>Tier 1 — Everyday Words:</strong> Words most people already know (run, happy, house, eat). Rarely need instruction.</li><li><strong>Tier 2 — Academic Words:</strong> Used across many subjects to describe complex ideas (analyze, evidence, significant, contrast, evaluate). THESE are the words that unlock advanced reading and writing.</li><li><strong>Tier 3 — Domain-Specific Words:</strong> Technical words used only in specific subjects (photosynthesis, denominator, confederation, metaphor). Important, but narrowly used.</li></ul>' } },
    { id: 'u3-l3-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Why Tier 2 Words Matter Most</h3><p>Tier 2 words are the <strong>power words</strong> of school. They appear in textbooks, assessments, and professional writing across EVERY subject.</p><p>Compare these sentences:</p><ul><li>❌ "The thing <em>showed</em> that the stuff was <em>different</em>."</li><li>✅ "The <em>evidence demonstrated</em> that the <em>results were significant</em>."</li></ul><p>Same idea, but the second version is clearer, more precise, and more academic.</p>' } },
    { id: 'u3-l3-learn-3', section: 'LEARN', blockType: 'VOCABULARY', order: 3, content: { terms: [{ term: 'Analyze', definition: 'To examine something carefully by breaking it into parts.', example: '"Analyze the data to find patterns."' }, { term: 'Evidence', definition: 'Facts or information that support a claim or conclusion.', example: '"What evidence supports the author\'s argument?"' }, { term: 'Significant', definition: 'Important, meaningful, or large enough to matter.', example: '"There was a significant difference between the two groups."' }, { term: 'Contrast', definition: 'To compare in order to show differences.', example: '"Contrast the two characters\' reactions to the conflict."' }, { term: 'Evaluate', definition: 'To judge the quality, importance, or value of something.', example: '"Evaluate the reliability of the source."' }, { term: 'Infer', definition: 'To draw a conclusion based on evidence and reasoning.', example: '"What can you infer from the character\'s actions?"' }] } },
    { id: 'u3-l3-learn-4', section: 'LEARN', blockType: 'MICRO_CHECK', order: 4, content: { question: 'The word "evaluate" is a Tier 2 word because:', options: [{ label: 'It is only used in science class', value: 'a' }, { label: 'It is used across many subjects to mean "judge the quality or value of something"', value: 'b', correct: true }, { label: 'It is an everyday word everyone uses casually', value: 'c' }], explanation: '"Evaluate" is powerful because you use it in ELA (evaluate a text), Science (evaluate results), Social Studies (evaluate a decision), and Math (evaluate an expression). It works across all subjects.' } },
    { id: 'u3-l3-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Replace each vague word with the best Tier 2 academic word:', pairs: [{ left: '"The test showed that the medicine worked."', right: 'demonstrated' }, { left: '"Look at the differences between the two poems."', right: 'contrast' }, { left: '"The change was really big and important."', right: 'significant' }, { left: '"The facts back up the scientist\'s idea."', right: 'evidence supports' }, { left: '"Figure out what the character is feeling."', right: 'infer' }] } },
    { id: 'u3-l3-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: 'Rewrite this paragraph using at least 4 Tier 2 words from today\'s lesson (analyze, evidence, significant, contrast, evaluate, infer, demonstrate):\n\n"The science test showed that plants grow better with more light. The things we found were big. We looked at the difference between plants in the dark and plants in the sun. The results proved our guess was right."\n\nRewrite it in academic language below.', minLength: 40 } },
    { id: 'u3-l3-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Why is it important to use precise vocabulary instead of vague words like "thing," "stuff," or "showed"? How does word choice affect how seriously your writing is taken?', minLength: 30 } },
  ];
  for (const b of l3Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L3, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L3: ${l3Blocks.length} blocks`);

  const l3Qs = [
    { id: 'u3-l3-q1', questionText: 'Tier 2 vocabulary words are:', options: [{ label: 'Everyday words everyone knows', value: 'a' }, { label: 'Academic words used across many subjects', value: 'b', correct: true }, { label: 'Technical words used only in one subject', value: 'c' }, { label: 'Slang words', value: 'd' }], correctAnswer: 'b', explanation: 'Tier 2 words (analyze, evidence, contrast) appear across ELA, Science, Math, and Social Studies. They are the "power words" of academic language.', outcomeCode: 'ELA.6.VL.4', difficulty: 1 },
    { id: 'u3-l3-q2', questionText: '"Photosynthesis" is a Tier 3 word because:', options: [{ label: 'Everyone uses it daily', value: 'a' }, { label: 'It is a technical term specific to Science', value: 'b', correct: true }, { label: 'It works across all subjects', value: 'c' }, { label: 'It is a very common word', value: 'd' }], correctAnswer: 'b', explanation: 'Photosynthesis is domain-specific — you only need it in Science. It doesn\'t appear in math or ELA contexts, making it Tier 3.', outcomeCode: 'ELA.6.VL.4', difficulty: 1 },
    { id: 'u3-l3-q3', questionText: 'Which sentence uses "evidence" correctly?', options: [{ label: '"The evidence was really big and showed stuff."', value: 'a' }, { label: '"The evidence from the experiment supports the hypothesis that plants need light."', value: 'b', correct: true }, { label: '"I evidenced my homework."', value: 'c' }, { label: '"The evidence was nice."', value: 'd' }], correctAnswer: 'b', explanation: '"Evidence" is used precisely here — it refers to specific data from an experiment that supports a specific claim.', outcomeCode: 'ELA.6.VL.4', difficulty: 1 },
    { id: 'u3-l3-q4', questionText: '"Analyze the data to find patterns." The word "analyze" uses the Greek root "lyse" meaning:', options: [{ label: 'to build', value: 'a' }, { label: 'to break apart / loosen', value: 'b', correct: true }, { label: 'to count', value: 'c' }, { label: 'to measure', value: 'd' }], correctAnswer: 'b', explanation: 'The Greek root "lyse" means to break apart. To analyze something is to break it into parts for examination — exactly like what you do with word roots!', outcomeCode: 'ELA.6.VL.1', difficulty: 2 },
    { id: 'u3-l3-q5', questionText: 'Which revision replaces vague language with precise Tier 2 vocabulary? Original: "The test showed that the medicine worked."', options: [{ label: '"The test really showed that the medicine really worked."', value: 'a' }, { label: '"The clinical trial demonstrated that the medication was effective."', value: 'b', correct: true }, { label: '"The thing proved the stuff was good."', value: 'c' }, { label: '"The medicine worked because the test said so."', value: 'd' }], correctAnswer: 'b', explanation: '"Demonstrated" (Tier 2) replaces "showed." "Clinical trial" and "effective" add precision. This is how academic writing communicates clearly.', outcomeCode: 'ELA.6.VL.4', difficulty: 2 },
    { id: 'u3-l3-q6', questionText: 'To "evaluate" something means to:', options: [{ label: 'Copy it exactly', value: 'a' }, { label: 'Judge its quality, importance, or value', value: 'b', correct: true }, { label: 'Ignore it', value: 'c' }, { label: 'Memorize it', value: 'd' }], correctAnswer: 'b', explanation: 'Evaluate means to make a judgment. You evaluate sources (reliable?), evaluate arguments (convincing?), evaluate results (significant?).', outcomeCode: 'ELA.6.VL.4', difficulty: 1 },
    { id: 'u3-l3-q7', questionText: '"Contrast" means to:', options: [{ label: 'Find similarities', value: 'a' }, { label: 'Compare in order to show DIFFERENCES', value: 'b', correct: true }, { label: 'Summarize', value: 'c' }, { label: 'Quote directly', value: 'd' }], correctAnswer: 'b', explanation: 'Contrast focuses on differences (while compare can include both similarities and differences). "Contrast the two characters" = show how they are different.', outcomeCode: 'ELA.6.VL.4', difficulty: 1 },
    { id: 'u3-l3-q8', questionText: 'Why does using Tier 2 words improve your writing?', options: [{ label: 'They make your writing longer', value: 'a' }, { label: 'They communicate ideas more precisely, clearly, and with academic credibility', value: 'b', correct: true }, { label: 'Teachers require them for word counts', value: 'c' }, { label: 'They are easier to spell', value: 'd' }], correctAnswer: 'b', explanation: 'Precise vocabulary communicates exactly what you mean, shows depth of understanding, and matches the expectations of academic contexts.', outcomeCode: 'ELA.6.VL.4', difficulty: 2 },
  ];
  for (const q of l3Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L3, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L3: ${l3Qs.length} questions`);

  // ═══════════════════════════════════════
  // L4: Fact vs Opinion
  // Target: TF.3 (non-fiction analysis), TF.4 (text form)
  // Review: RC.1 (inference), TR.1 (evidence)
  // ═══════════════════════════════════════
  const L4 = 'g6-ela-u3-l4';
  const l4Blocks = [
    { id: 'u3-l4-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Fact, Opinion, and Everything in Between</h3><p>One of the most important skills in the information age is telling the difference between <strong>facts</strong> and <strong>opinions</strong>:</p><ul><li><strong>Fact:</strong> A statement that can be <em>verified</em> — proven true or false with evidence. "Alberta became a province in 1905."</li><li><strong>Opinion:</strong> A statement that expresses a <em>belief, judgment, or preference</em>. It cannot be proven true or false. "Alberta is the best province to live in."</li></ul><p>Some statements are tricky because they <em>sound</em> like facts but are actually opinions disguised with confident language.</p>' } },
    { id: 'u3-l4-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Spotting Bias</h3><p><strong>Bias</strong> is when an author presents information in a way that favors one side. Bias is not always bad — everyone has perspectives — but it becomes a problem when it hides information or manipulates the reader.</p><p><strong>Signs of bias:</strong></p><ul><li>Only presenting one side of an issue</li><li>Using emotional or loaded language ("devastating," "obviously")</li><li>Leaving out evidence that contradicts the argument</li><li>Attacking the person instead of the argument</li></ul><p><strong>Reliability test:</strong></p><ol><li>Who wrote this? Are they an expert?</li><li>When was it published? Is it current?</li><li>What sources do they cite? Can you verify them?</li><li>Does the author present multiple perspectives?</li><li>What is the author\'s PURPOSE? (inform, persuade, entertain, sell?)</li></ol>' } },
    { id: 'u3-l4-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Anchor Text: Two Articles About Screen Time</h3><blockquote style="border-left:3px solid #22c55e;padding:12px 16px;margin:12px 0;color:#475569"><strong>Article A: "Screen Time Is Harming Our Children"</strong><br>A recent survey found that 78% of parents are worried about their children\'s screen time. Obviously, screens are destroying childhood. Kids today can\'t even hold a conversation without checking their phones. We must act now before an entire generation is lost to addiction.</blockquote><blockquote style="border-left:3px solid #3b82f6;padding:12px 16px;margin:12px 0;color:#475569"><strong>Article B: "Understanding Screen Time: What Research Shows"</strong><br>A 2024 study published in the Journal of Pediatric Health found that screen time effects vary based on content type and context. Educational screen use (reading apps, research, creative tools) showed no negative effects on development. However, passive consumption exceeding 3 hours daily was associated with reduced sleep quality in 12–15 year olds. Researchers recommend a balanced approach rather than blanket restrictions.</blockquote>' } },
    { id: 'u3-l4-learn-4', section: 'LEARN', blockType: 'MICRO_CHECK', order: 4, content: { question: 'Which article shows MORE bias?', options: [{ label: 'Article B — it cites a specific study', value: 'a' }, { label: 'Article A — it uses emotional language like "destroying," "obviously," and "lost to addiction" without citing specific evidence', value: 'b', correct: true }, { label: 'Both are equally biased', value: 'c' }], explanation: 'Article A uses loaded emotional language ("destroying," "obviously," "addiction") and presents only one side. Article B cites a specific study, presents nuance, and acknowledges complexity. Article B is more reliable.' } },
    { id: 'u3-l4-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Classify each statement as FACT or OPINION:', pairs: [{ left: '"Alberta became a province in 1905."', right: 'Fact — verifiable' }, { left: '"Hockey is the most exciting sport."', right: 'Opinion — preference' }, { left: '"The average temperature in Edmonton in January is -11°C."', right: 'Fact — verifiable' }, { left: '"Obviously, winter is too long in Alberta."', right: 'Opinion — judgment with "obviously" bias signal' }, { left: '"78% of parents are worried about screen time."', right: 'Fact — survey data (verifiable)' }, { left: '"Screens are destroying childhood."', right: 'Opinion — emotional language, not verifiable' }] } },
    { id: 'u3-l4-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: 'Compare Article A and Article B:\n\n1. Which article is MORE RELIABLE? Explain using at least 2 criteria from the reliability test.\n2. Find ONE example of emotional/loaded language in Article A.\n3. Find ONE specific piece of evidence in Article B that makes it more trustworthy.\n4. What is the author\'s PURPOSE in each article? (inform? persuade? both?)', minLength: 50 } },
    { id: 'u3-l4-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Think of something you read online recently. How would you check whether the information was reliable? Which criteria from today\'s lesson would you use?', minLength: 30 } },
  ];
  for (const b of l4Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L4, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L4: ${l4Blocks.length} blocks`);

  const l4Qs = [
    { id: 'u3-l4-q1', questionText: 'A FACT is a statement that:', options: [{ label: 'Everyone agrees with', value: 'a' }, { label: 'Can be verified — proven true or false with evidence', value: 'b', correct: true }, { label: 'Sounds confident', value: 'c' }, { label: 'Is in a textbook', value: 'd' }], correctAnswer: 'b', explanation: 'Facts are verifiable — you can check them against evidence. "The Earth orbits the Sun" is a fact. "Sunsets are beautiful" is an opinion.', outcomeCode: 'ELA.6.TF.3', difficulty: 1 },
    { id: 'u3-l4-q2', questionText: '"Obviously, screens are destroying childhood." This is an example of:', options: [{ label: 'A verified fact', value: 'a' }, { label: 'An opinion disguised with emotional language and a bias signal word ("obviously")', value: 'b', correct: true }, { label: 'A research finding', value: 'c' }, { label: 'A neutral observation', value: 'd' }], correctAnswer: 'b', explanation: '"Obviously" is a bias signal — it makes an opinion sound like an undeniable truth. "Destroying" is emotional/loaded language. Neither word is supported by evidence.', outcomeCode: 'ELA.6.TF.3', difficulty: 1 },
    { id: 'u3-l4-q3', questionText: 'Article B cites "a 2024 study published in the Journal of Pediatric Health." This detail makes Article B more reliable because:', options: [{ label: 'It has a longer title', value: 'a' }, { label: 'It names a specific, verifiable source that experts can review', value: 'b', correct: true }, { label: 'It was written more recently', value: 'c' }, { label: 'It agrees with Article A', value: 'd' }], correctAnswer: 'b', explanation: 'Naming a specific journal and year allows readers to verify the claim independently. This is a hallmark of reliable non-fiction writing.', outcomeCode: 'ELA.6.TF.3', difficulty: 2 },
    { id: 'u3-l4-q4', questionText: 'BIAS in a text means:', options: [{ label: 'The text has no errors', value: 'a' }, { label: 'The author presents information in a way that favors one side, often hiding contradicting evidence', value: 'b', correct: true }, { label: 'The text is very long', value: 'c' }, { label: 'The text uses simple vocabulary', value: 'd' }], correctAnswer: 'b', explanation: 'Bias is one-sided presentation. A biased text highlights only supporting evidence and downplays or ignores anything that contradicts its position.', outcomeCode: 'ELA.6.TF.3', difficulty: 1 },
    { id: 'u3-l4-q5', questionText: 'The reliability test asks "What is the author\'s PURPOSE?" Why does this matter?', options: [{ label: 'It does not matter', value: 'a' }, { label: 'An author writing to persuade may be more biased than an author writing to inform', value: 'b', correct: true }, { label: 'Authors always have the same purpose', value: 'c' }, { label: 'Only fictional authors have purposes', value: 'd' }], correctAnswer: 'b', explanation: 'Purpose affects reliability. An author trying to sell you something or persuade you has motivation to be selective with evidence. Informational writing aims for balance.', outcomeCode: 'ELA.6.TR.1', difficulty: 2 },
    { id: 'u3-l4-q6', questionText: 'Which of these is a SIGN OF BIAS in a text?', options: [{ label: 'Using specific data from a named source', value: 'a' }, { label: 'Only presenting one side of an issue and using emotional language', value: 'b', correct: true }, { label: 'Including a bibliography', value: 'c' }, { label: 'Acknowledging the complexity of an issue', value: 'd' }], correctAnswer: 'b', explanation: 'One-sidedness + emotional language = bias signals. Reliable texts present complexity, acknowledge counter-arguments, and cite specific sources.', outcomeCode: 'ELA.6.TF.3', difficulty: 1 },
    { id: 'u3-l4-q7', questionText: 'In Article A, what can you INFER about the author\'s purpose?', options: [{ label: 'To inform the reader with balanced evidence', value: 'a' }, { label: 'To persuade the reader that screen time is harmful, using fear-based language', value: 'b', correct: true }, { label: 'To entertain the reader with a story', value: 'c' }, { label: 'To compare different viewpoints neutrally', value: 'd' }], correctAnswer: 'b', explanation: 'The emotional language ("destroying," "addiction," "lost"), urgency ("act now"), and one-sided presentation all indicate the author is trying to persuade, not inform.', outcomeCode: 'ELA.6.RC.1', difficulty: 2 },
    { id: 'u3-l4-q8', questionText: 'Which organizational structure does Article B primarily use?', options: [{ label: 'Chronological order', value: 'a' }, { label: 'Cause and Effect — explaining what causes screen time effects and what the results are', value: 'b', correct: true }, { label: 'Narrative — telling a story', value: 'c' }, { label: 'Description only', value: 'd' }], correctAnswer: 'b', explanation: 'Article B identifies causes (type of content, duration) and effects (no negative effects for educational use, reduced sleep for passive use). This is cause-and-effect structure.', outcomeCode: 'ELA.6.TF.4', difficulty: 2 },
  ];
  for (const q of l4Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L4, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L4: ${l4Qs.length} questions`);

  console.log(`\n╔═══════════════════════════════════════════════╗\n║   ELA UNIT 3 (L1–L4) SEED COMPLETE          ║\n╠═══════════════════════════════════════════════╣\n║ Lessons:    4                                ║\n║ Blocks:     ${String(l1Blocks.length + l2Blocks.length + l3Blocks.length + l4Blocks.length).padStart(2)}                               ║\n║ Questions:  ${String(l1Qs.length + l2Qs.length + l3Qs.length + l4Qs.length).padStart(2)}                               ║\n╚═══════════════════════════════════════════════╝`);
}

main()
  .catch((e) => { console.error('❌ Seed error:', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); pool.end(); });
