// ============================================
// Seed ELA Unit 3 — "Truth, Evidence, and Information" (Lessons 5–8)
// ============================================
// Research skills, evidence-based writing, spelling lab, research report.
// Run: npx tsx prisma/seed-ela-u3-l5-l8.ts

import { config } from 'dotenv';
config({ path: '.env.local' });
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🔎 Seeding ELA Unit 3 "Truth, Evidence, and Information" — L5–L8');

  const lessonDefs = [
    { id: 'g6-ela-u3-l5', title: 'Research Skills', order: 5, learningGoal: 'Narrow research questions, locate information from multiple sources, and take organized notes.', successCriteria: 'I can narrow a broad topic into a focused research question.\nI can find relevant information from at least 2 different sources.\nI can take organized notes that include key facts and source information.', reflectionPrompt: 'What makes a good research question? How is it different from a question you could answer with a single Google search?' },
    { id: 'g6-ela-u3-l6', title: 'Evidence-Based Writing', order: 6, learningGoal: 'Write multi-paragraph responses that support a main idea with evidence from sources.', successCriteria: 'I can write a clear topic sentence that states my main idea.\nI can support my main idea with evidence from at least 2 sources.\nI can explain HOW the evidence supports my point (not just include it).', reflectionPrompt: 'Why is it not enough to just include a quote or fact? Why do you need to explain how it supports your point?' },
    { id: 'g6-ela-u3-l7', title: 'Spelling Lab', order: 7, learningGoal: 'Apply spelling patterns, knowledge of bases and affixes, and derivational strategies to spell familiar and unfamiliar words correctly.', successCriteria: 'I can identify common spelling patterns and explain the rules behind them.\nI can use knowledge of prefixes and suffixes to spell complex words.\nI can apply strategies to spell unfamiliar words (say it, segment it, connect to known words).', reflectionPrompt: 'What strategies help you most when you encounter a word you don\'t know how to spell? Which spelling patterns trip you up most?' },
    { id: 'g6-ela-u3-l8', title: 'Research Report', order: 8, learningGoal: 'Draft, revise, and publish a complete research report that uses evidence from multiple sources and follows the writing process.', successCriteria: 'I can write a multi-paragraph research report with introduction, body, and conclusion.\nI can use evidence from multiple sources to support my main idea.\nI can cite my sources and use information ethically.\nI can revise for clarity and edit for conventions.', reflectionPrompt: 'Look back at your complete research journey. What is the most important thing you learned — about your topic, or about the research process itself?' },
  ];

  for (const l of lessonDefs) {
    await prisma.lesson.upsert({
      where: { id: l.id },
      update: { title: l.title, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
      create: { id: l.id, unitId: 'g6-ela-u3', title: l.title, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
    });
  }
  console.log('✅ Lessons 5–8 upserted');

  for (const l of lessonDefs) {
    await prisma.lessonBlock.deleteMany({ where: { lessonId: l.id } });
    await prisma.quizQuestion.deleteMany({ where: { lessonId: l.id } });
  }

  // ═══════════════════════════════════════
  // L5: Research Skills
  // Target: WC.6 (research & ethical info use)
  // Review: RC.4 (text features), TF.3 (non-fiction)
  // ═══════════════════════════════════════
  const L5 = 'g6-ela-u3-l5';
  const l5Blocks = [
    { id: 'u3-l5-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>From Curiosity to Research</h3><p>Great research starts with a great question. But not all questions are research-worthy:</p><ul><li>❌ <strong>Too broad:</strong> "What is climate change?" (could fill an encyclopedia)</li><li>❌ <strong>Too narrow:</strong> "What temperature was it in Edmonton on March 3, 2024?" (one Google search)</li><li>✅ <strong>Just right:</strong> "How is climate change affecting wildlife in the Canadian Rockies?" (focused, researchable, requires multiple sources)</li></ul><p>A strong research question is <strong>focused</strong> (not too broad), <strong>open-ended</strong> (not a yes/no answer), and <strong>researchable</strong> (you can find evidence).</p>' } },
    { id: 'u3-l5-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Finding and Evaluating Sources</h3><p>For a research report, you need <strong>at least 2 different sources</strong>. Types of sources:</p><ul><li><strong>Books/textbooks:</strong> In-depth, reviewed, but may not be current</li><li><strong>Websites:</strong> Accessible, but vary in reliability (.gov, .edu, .org are usually more reliable than .com)</li><li><strong>Articles/journals:</strong> Written by experts, peer-reviewed, very reliable</li><li><strong>Videos/documentaries:</strong> Can be informative but check who made them and why</li></ul><p>Always apply the <strong>reliability test</strong> from Lesson 4: Who? When? What sources? Multiple perspectives? Purpose?</p>' } },
    { id: 'u3-l5-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Ethical Information Use</h3><p>Using other people\'s ideas or words without giving credit is called <strong>plagiarism</strong>. Even if unintentional, it is unethical.</p><p><strong>Rules:</strong></p><ul><li>If you use someone\'s exact words, put them in <strong>quotation marks</strong> and name the source</li><li>If you use someone\'s ideas in your own words (<strong>paraphrasing</strong>), you still need to name the source</li><li>Always record where you found your information (author, title, website, date)</li></ul>' } },
    { id: 'u3-l5-learn-4', section: 'LEARN', blockType: 'MICRO_CHECK', order: 4, content: { question: 'Which research question is the BEST?', options: [{ label: '"What is soil?"', value: 'a' }, { label: '"How are regenerative farming practices helping Alberta farmers maintain soil health?"', value: 'b', correct: true }, { label: '"Is soil important? Yes or no?"', value: 'c' }], explanation: 'Option B is focused (Alberta farmers + regenerative farming), open-ended (not yes/no), and researchable (you can find evidence from multiple sources).' } },
    { id: 'u3-l5-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Choose ONE topic from the list below and narrow it into a strong research question:\n\nTopics: Water pollution | Endangered species in Alberta | The history of video games | How music affects the brain | Space exploration\n\n1. Write your BROAD topic\n2. Write your NARROWED research question (focused, open-ended, researchable)\n3. List 2 types of sources you would use to answer your question\n4. Explain HOW you would check if each source is reliable', minLength: 50 } },
    { id: 'u3-l5-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'What makes a good research question? How is it different from a question you could answer with a single Google search?', minLength: 30 } },
  ];
  for (const b of l5Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L5, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L5: ${l5Blocks.length} blocks`);

  const l5Qs = [
    { id: 'u3-l5-q1', questionText: 'A strong research question should be:', options: [{ label: 'Answerable with yes or no', value: 'a' }, { label: 'Focused, open-ended, and researchable using multiple sources', value: 'b', correct: true }, { label: 'As broad as possible', value: 'c' }, { label: 'About a topic you already know everything about', value: 'd' }], correctAnswer: 'b', explanation: 'Strong research questions require investigation, multiple sources, and produce substantial answers — not simple yes/no or one-fact responses.', outcomeCode: 'ELA.6.WC.6', difficulty: 1 },
    { id: 'u3-l5-q2', questionText: 'PLAGIARISM is:', options: [{ label: 'Using quotation marks', value: 'a' }, { label: 'Using someone else\'s words or ideas without giving them credit', value: 'b', correct: true }, { label: 'Paraphrasing with a source citation', value: 'c' }, { label: 'Writing your own original ideas', value: 'd' }], correctAnswer: 'b', explanation: 'Plagiarism means taking credit for someone else\'s work. Always cite your sources, whether quoting directly or paraphrasing.', outcomeCode: 'ELA.6.WC.6', difficulty: 1 },
    { id: 'u3-l5-q3', questionText: 'Which website domain is GENERALLY most reliable for research?', options: [{ label: '.com (commercial business)', value: 'a' }, { label: '.edu (educational institution)', value: 'b', correct: true }, { label: '.biz (business)', value: 'c' }, { label: 'Any domain is equally reliable', value: 'd' }], correctAnswer: 'b', explanation: '.edu sites belong to schools and universities, which typically have academic standards for accuracy. .gov (government) is also highly reliable. .com varies widely.', outcomeCode: 'ELA.6.WC.6', difficulty: 1 },
    { id: 'u3-l5-q4', questionText: 'PARAPHRASING means:', options: [{ label: 'Copying someone\'s exact words', value: 'a' }, { label: 'Restating someone\'s idea in YOUR OWN words while still citing the source', value: 'b', correct: true }, { label: 'Ignoring the source completely', value: 'c' }, { label: 'Making up new information', value: 'd' }], correctAnswer: 'b', explanation: 'Paraphrasing = same idea, your own words, still cite the source. It shows you understand the material well enough to restate it.', outcomeCode: 'ELA.6.WC.6', difficulty: 1 },
    { id: 'u3-l5-q5', questionText: '"What is soil?" is a WEAK research question because:', options: [{ label: 'It is about science', value: 'a' }, { label: 'It is too broad — it could fill an entire textbook and doesn\'t focus on a specific aspect', value: 'b', correct: true }, { label: 'Soil is not interesting', value: 'c' }, { label: 'It has too many words', value: 'd' }], correctAnswer: 'b', explanation: 'Too-broad questions lead to unfocused research. Narrowing it (e.g., "How does composting improve soil health in Alberta gardens?") gives direction.', outcomeCode: 'ELA.6.WC.6', difficulty: 2 },
    { id: 'u3-l5-q6', questionText: 'Using text features (headings, index, table of contents) when researching helps you:', options: [{ label: 'Read every page of the book', value: 'a' }, { label: 'Quickly find specific information relevant to your research question', value: 'b', correct: true }, { label: 'Avoid reading altogether', value: 'c' }, { label: 'Only look at pictures', value: 'd' }], correctAnswer: 'b', explanation: 'Text features help you navigate efficiently — you don\'t need to read an entire book to find the relevant section for your research.', outcomeCode: 'ELA.6.RC.4', difficulty: 1 },
    { id: 'u3-l5-q7', questionText: 'Why should you use MULTIPLE sources for a research report?', options: [{ label: 'To make the bibliography longer', value: 'a' }, { label: 'Multiple sources provide more complete information and allow you to verify claims across sources', value: 'b', correct: true }, { label: 'One source is always enough', value: 'c' }, { label: 'Teachers require it for grades', value: 'd' }], correctAnswer: 'b', explanation: 'Multiple sources let you cross-check information, get different perspectives, and build a more complete understanding of your topic.', outcomeCode: 'ELA.6.WC.6', difficulty: 2 },
    { id: 'u3-l5-q8', questionText: 'When evaluating a website\'s reliability, which question is MOST important?', options: [{ label: 'Does the website have colorful graphics?', value: 'a' }, { label: 'Who created the content, what sources do they cite, and what is their purpose?', value: 'b', correct: true }, { label: 'Is the website free?', value: 'c' }, { label: 'Does the website load quickly?', value: 'd' }], correctAnswer: 'b', explanation: 'Credibility depends on the author\'s expertise, the sources they cite, and whether their purpose is to inform or persuade. Design and speed do not determine reliability.', outcomeCode: 'ELA.6.TF.3', difficulty: 2 },
  ];
  for (const q of l5Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L5, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L5: ${l5Qs.length} questions`);

  // ═══════════════════════════════════════
  // L6: Evidence-Based Writing
  // Target: WC.2 (multi-paragraph), TR.1 (evidence)
  // Review: WC.1 (process)
  // ═══════════════════════════════════════
  const L6 = 'g6-ela-u3-l6';
  const l6Blocks = [
    { id: 'u3-l6-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Writing WITH Evidence</h3><p>In Unit 2, you learned to write multi-paragraph stories. Now you\'ll write multi-paragraph <strong>informational responses</strong> — where every claim must be backed up with evidence.</p><p>The formula:</p><ol><li><strong>Claim:</strong> What are you saying? (your main idea or topic sentence)</li><li><strong>Evidence:</strong> What proof do you have? (facts, data, quotes from sources)</li><li><strong>Explanation:</strong> Why does this evidence matter? HOW does it support your claim?</li></ol><p>This is called <strong>C-E-E</strong> (Claim-Evidence-Explanation).</p>' } },
    { id: 'u3-l6-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Example: C-E-E in Action</h3><blockquote style="border-left:3px solid #0ea5e9;padding:12px 16px;margin:12px 0;color:#475569"><strong>Claim:</strong> Healthy soil is essential for food production.<br><br><strong>Evidence:</strong> According to the article "The Hidden World of Soil," soil provides nutrients for 95% of the world\'s food supply.<br><br><strong>Explanation:</strong> This statistic demonstrates that nearly all food depends on soil health. If soil continues to degrade, food production could decline significantly, affecting millions of people worldwide.</blockquote><p>Notice: the explanation doesn\'t just repeat the evidence — it <em>analyzes</em> what the evidence means and <em>connects</em> it back to the claim.</p>' } },
    { id: 'u3-l6-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: 'In C-E-E writing, the EXPLANATION should:', options: [{ label: 'Just repeat the evidence in different words', value: 'a' }, { label: 'Analyze what the evidence means and connect it back to the claim', value: 'b', correct: true }, { label: 'Introduce a new topic', value: 'c' }], explanation: 'The explanation is where YOUR thinking lives. It shows the reader WHY the evidence matters and HOW it supports your claim. This is the most important part.' } },
    { id: 'u3-l6-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Using the anchor text "The Hidden World of Soil" from Lesson 1, write a C-E-E paragraph:\n\n1. CLAIM: Write one clear sentence stating a main idea about soil.\n2. EVIDENCE: Include a specific fact, statistic, or quote from the anchor text.\n3. EXPLANATION: Explain in 2–3 sentences WHY this evidence matters and HOW it supports your claim.\n\nYour paragraph should be at least 5 sentences total.', minLength: 60 } },
    { id: 'u3-l6-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Why is it not enough to just include a quote or fact in your writing? Why do you need to explain how the evidence supports your point?', minLength: 30 } },
  ];
  for (const b of l6Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L6, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L6: ${l6Blocks.length} blocks`);

  const l6Qs = [
    { id: 'u3-l6-q1', questionText: 'In the C-E-E model, "E-E" stands for:', options: [{ label: 'Example and Ending', value: 'a' }, { label: 'Evidence and Explanation', value: 'b', correct: true }, { label: 'Edit and Evaluate', value: 'c' }, { label: 'Evidence and Evidence', value: 'd' }], correctAnswer: 'b', explanation: 'C-E-E = Claim (what you\'re saying) + Evidence (proof) + Explanation (why the proof matters).', outcomeCode: 'ELA.6.TR.1', difficulty: 1 },
    { id: 'u3-l6-q2', questionText: 'A TOPIC SENTENCE should:', options: [{ label: 'Be a question', value: 'a' }, { label: 'Clearly state the main idea of the paragraph', value: 'b', correct: true }, { label: 'Include evidence', value: 'c' }, { label: 'Be the last sentence of the paragraph', value: 'd' }], correctAnswer: 'b', explanation: 'The topic sentence (your claim) tells the reader what the paragraph is about. Everything after it should support this claim.', outcomeCode: 'ELA.6.WC.2', difficulty: 1 },
    { id: 'u3-l6-q3', questionText: 'Which is the BEST explanation for this evidence? Claim: "Soil degradation is a serious problem." Evidence: "One-third of topsoil has been degraded."', options: [{ label: '"This shows soil is degraded."', value: 'a' }, { label: '"This means that a significant portion of the Earth\'s most productive land is losing its ability to grow food, threatening global food security."', value: 'b', correct: true }, { label: '"Soil is important."', value: 'c' }, { label: '"One-third is a lot."', value: 'd' }], correctAnswer: 'b', explanation: 'Option B actually analyzes the evidence — it explains WHAT the statistic means (land is losing productivity) and WHY it matters (threatens food security). The others just restate or oversimplify.', outcomeCode: 'ELA.6.TR.1', difficulty: 2 },
    { id: 'u3-l6-q4', questionText: 'Multi-paragraph informational writing should be organized with:', options: [{ label: 'Random paragraphs in any order', value: 'a' }, { label: 'An introduction, body paragraphs (each with a claim + evidence), and a conclusion', value: 'b', correct: true }, { label: 'Only one long paragraph', value: 'c' }, { label: 'Bullet points', value: 'd' }], correctAnswer: 'b', explanation: 'Clear organization (intro → body → conclusion) helps readers follow your argument. Each body paragraph should have its own focused claim.', outcomeCode: 'ELA.6.WC.2', difficulty: 1 },
    { id: 'u3-l6-q5', questionText: 'Why must you explain your evidence (the second E in C-E-E)?', options: [{ label: 'To make the paragraph longer', value: 'a' }, { label: 'Because evidence alone doesn\'t tell the reader WHY it matters or HOW it supports your point', value: 'b', correct: true }, { label: 'You don\'t need to explain evidence', value: 'c' }, { label: 'Because teachers require it', value: 'd' }], correctAnswer: 'b', explanation: 'Evidence without explanation is like showing someone a puzzle piece without showing where it fits. The explanation connects the evidence to your claim and shows YOUR thinking.', outcomeCode: 'ELA.6.TR.1', difficulty: 2 },
    { id: 'u3-l6-q6', questionText: 'Which sentence is the CLAIM in this paragraph? "Regenerative farming can restore soil health. According to Dr. Patel, techniques like composting rebuild soil communities. This means farmers can produce food while healing the land."', options: [{ label: 'The second sentence', value: 'a' }, { label: 'The first sentence — "Regenerative farming can restore soil health"', value: 'b', correct: true }, { label: 'The third sentence', value: 'c' }, { label: 'None of them', value: 'd' }], correctAnswer: 'b', explanation: 'The claim always states the main idea. The evidence (Dr. Patel\'s quote) and explanation (farmers can heal the land) support it.', outcomeCode: 'ELA.6.WC.2', difficulty: 1 },
    { id: 'u3-l6-q7', questionText: 'The writing process for a research report is:', options: [{ label: 'Write it once and submit', value: 'a' }, { label: 'Plan → Research → Draft → Revise → Edit → Publish', value: 'b', correct: true }, { label: 'Copy from one source', value: 'c' }, { label: 'Edit → Draft → Plan', value: 'd' }], correctAnswer: 'b', explanation: 'Research writing follows the same process as creative writing, with an added research step between planning and drafting.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u3-l6-q8', questionText: 'When including evidence from a source, which is CORRECT?', options: [{ label: 'Copy the sentence without quotation marks or source', value: 'a' }, { label: 'Put exact words in quotation marks and name the source, OR paraphrase and name the source', value: 'b', correct: true }, { label: 'Change one word and call it your own', value: 'c' }, { label: 'Never use evidence from sources', value: 'd' }], correctAnswer: 'b', explanation: 'Direct quotes need quotation marks + attribution. Paraphrases need attribution too. Both show ethical information use.', outcomeCode: 'ELA.6.WC.6', difficulty: 1 },
  ];
  for (const q of l6Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L6, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L6: ${l6Qs.length} questions`);

  // ═══════════════════════════════════════
  // L7: Spelling Lab
  // Target: CV.4 (spelling & derivations)
  // Review: VL.1 (word origins), CV.1 (capitalization)
  // ═══════════════════════════════════════
  const L7 = 'g6-ela-u3-l7';
  const l7Blocks = [
    { id: 'u3-l7-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Spelling Is Not Just Memory</h3><p>Spelling is not about memorizing random letter combinations. English spelling has <strong>patterns and rules</strong> — and when you know them, you can spell thousands of words correctly.</p><p>Three key strategies:</p><ol><li><strong>Sound it out:</strong> Break the word into syllables and spell each one</li><li><strong>Use what you know:</strong> Connect to root words, prefixes, and suffixes you already know</li><li><strong>Visualize:</strong> Picture the word in your mind — does it "look right"?</li></ol>' } },
    { id: 'u3-l7-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Key Spelling Patterns</h3><table style="width:100%;border-collapse:collapse"><tr style="background:#f1f5f9"><th style="padding:8px;border:1px solid #e2e8f0">Pattern</th><th style="padding:8px;border:1px solid #e2e8f0">Rule</th><th style="padding:8px;border:1px solid #e2e8f0">Examples</th></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Doubling rule</strong></td><td style="padding:8px;border:1px solid #e2e8f0">When adding -ing/-ed to a short vowel word, double the final consonant</td><td style="padding:8px;border:1px solid #e2e8f0">run → running, stop → stopped</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Drop the e</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Drop silent e before a suffix starting with a vowel</td><td style="padding:8px;border:1px solid #e2e8f0">make → making, hope → hoping</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Change y to i</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Change y to i before adding -es, -ed, -er, -est</td><td style="padding:8px;border:1px solid #e2e8f0">happy → happiness, carry → carried</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>i before e</strong></td><td style="padding:8px;border:1px solid #e2e8f0">i before e except after c (when it sounds like "ee")</td><td style="padding:8px;border:1px solid #e2e8f0">believe, receive, achieve, ceiling</td></tr></table>' } },
    { id: 'u3-l7-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Spelling with Affixes</h3><p>When you add prefixes and suffixes to base words, the spelling usually follows predictable rules:</p><ul><li><strong>Prefixes</strong> usually just attach: un + happy = unhappy, dis + agree = disagree</li><li><strong>Suffixes</strong> sometimes require changes: -tion, -sion, -ment, -ness, -ful, -less</li></ul><p><strong>Derivation families:</strong> Words from the same root share spelling patterns:</p><ul><li>construct → construction → constructive → reconstruct</li><li>educate → education → educational → educator</li></ul>' } },
    { id: 'u3-l7-learn-4', section: 'LEARN', blockType: 'MICRO_CHECK', order: 4, content: { question: 'When adding "-ing" to "hope," the correct spelling is:', options: [{ label: 'hopeing', value: 'a' }, { label: 'hoping — drop the silent e before adding -ing', value: 'b', correct: true }, { label: 'hopping', value: 'c' }], explanation: 'The "drop the e" rule: when a word ends in silent e and the suffix starts with a vowel, drop the e. hope → hoping. (Hopping = hop + doubling rule.)' } },
    { id: 'u3-l7-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Apply spelling rules to spell each word correctly:\n\n1. run + -ing = ?\n2. happy + -ness = ?\n3. believe or beleive?\n4. dis + appear = ?\n5. make + -ing = ?\n\nThen: Find 3 words in your research draft (from L5/L6) that you are unsure about. Use the strategies from today to check and correct them.', minLength: 30 } },
    { id: 'u3-l7-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'What strategies help you most when you encounter a word you don\'t know how to spell? Which spelling patterns trip you up most?', minLength: 25 } },
  ];
  for (const b of l7Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L7, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L7: ${l7Blocks.length} blocks`);

  const l7Qs = [
    { id: 'u3-l7-q1', questionText: 'When adding "-ing" to "run," the correct spelling is:', options: [{ label: 'runing', value: 'a' }, { label: 'running — double the final consonant', value: 'b', correct: true }, { label: 'runeing', value: 'c' }, { label: 'runnning', value: 'd' }], correctAnswer: 'b', explanation: 'Run has a short vowel + single consonant at the end. The doubling rule applies: run → running.', outcomeCode: 'ELA.6.CV.4', difficulty: 1 },
    { id: 'u3-l7-q2', questionText: 'Which follows the "drop the e" rule correctly?', options: [{ label: 'hope → hopeing', value: 'a' }, { label: 'make → making', value: 'b', correct: true }, { label: 'come → comeing', value: 'c' }, { label: 'write → writeing', value: 'd' }], correctAnswer: 'b', explanation: 'Drop the silent e before a suffix starting with a vowel: make → making. The others should be: hoping, coming, writing.', outcomeCode: 'ELA.6.CV.4', difficulty: 1 },
    { id: 'u3-l7-q3', questionText: '"Happy + -ness" = ', options: [{ label: 'happyness', value: 'a' }, { label: 'happiness — change y to i before adding -ness', value: 'b', correct: true }, { label: 'happness', value: 'c' }, { label: 'happienss', value: 'd' }], correctAnswer: 'b', explanation: 'When a word ends in consonant + y, change y to i before adding the suffix: happy → happiness, carry → carried.', outcomeCode: 'ELA.6.CV.4', difficulty: 1 },
    { id: 'u3-l7-q4', questionText: 'Which word is spelled correctly?', options: [{ label: 'beleive', value: 'a' }, { label: 'believe', value: 'b', correct: true }, { label: 'beleave', value: 'c' }, { label: 'beleeve', value: 'd' }], correctAnswer: 'b', explanation: 'I before e except after c (when it sounds like "ee"): believe, achieve. After c: receive, ceiling.', outcomeCode: 'ELA.6.CV.4', difficulty: 1 },
    { id: 'u3-l7-q5', questionText: 'Adding a PREFIX to a word usually:', options: [{ label: 'Requires dropping a letter', value: 'a' }, { label: 'Just attaches directly without changing the base word', value: 'b', correct: true }, { label: 'Always doubles a consonant', value: 'c' }, { label: 'Changes the vowel', value: 'd' }], correctAnswer: 'b', explanation: 'Prefixes simply attach: un + happy = unhappy, dis + agree = disagree, re + build = rebuild. No spelling changes needed.', outcomeCode: 'ELA.6.CV.4', difficulty: 1 },
    { id: 'u3-l7-q6', questionText: 'The words "construct, construction, constructive" are a DERIVATION FAMILY because:', options: [{ label: 'They start with the same letter', value: 'a' }, { label: 'They share the same root word and are related in meaning', value: 'b', correct: true }, { label: 'They are all nouns', value: 'c' }, { label: 'They have the same number of syllables', value: 'd' }], correctAnswer: 'b', explanation: 'Derivation families share a root (construct) and branch out through different suffixes to create related words with different parts of speech.', outcomeCode: 'ELA.6.VL.1', difficulty: 2 },
    { id: 'u3-l7-q7', questionText: 'Which is the correct spelling? "The scientist made a signif_____ discovery."', options: [{ label: 'significent', value: 'a' }, { label: 'significant', value: 'b', correct: true }, { label: 'signifacant', value: 'c' }, { label: 'significunt', value: 'd' }], correctAnswer: 'b', explanation: 'Significant — the suffix is "-ant" (not "-ent" or "-unt"). Connecting to related words (significance, significantly) can help you remember.', outcomeCode: 'ELA.6.CV.4', difficulty: 2 },
    { id: 'u3-l7-q8', questionText: 'Which spelling strategy is MOST effective for unfamiliar words?', options: [{ label: 'Guessing randomly', value: 'a' }, { label: 'Breaking the word into parts (prefix + root + suffix) and applying known patterns', value: 'b', correct: true }, { label: 'Spelling it as fast as possible', value: 'c' }, { label: 'Using only the first two letters', value: 'd' }], correctAnswer: 'b', explanation: 'Morphological strategy: break words into known parts. If you know "construct" and the suffix "-ion," you can spell "construction" confidently.', outcomeCode: 'ELA.6.CV.4', difficulty: 2 },
  ];
  for (const q of l7Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L7, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L7: ${l7Qs.length} questions`);

  // ═══════════════════════════════════════
  // L8: Research Report
  // Target: WC.6 (research), WC.1 (process)
  // Review: WC.3 (revision), OC.3 (collaboration)
  // ═══════════════════════════════════════
  const L8 = 'g6-ela-u3-l8';
  const l8Blocks = [
    { id: 'u3-l8-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Putting It All Together</h3><p>You\'ve learned to:</p><ul><li>Read non-fiction critically (L1)</li><li>Decode words with roots and affixes (L2)</li><li>Use precise academic vocabulary (L3)</li><li>Distinguish fact from opinion and evaluate sources (L4)</li><li>Narrow research questions and find reliable sources (L5)</li><li>Write with evidence using C-E-E (L6)</li><li>Spell with confidence using patterns (L7)</li></ul><p>Now you\'ll bring ALL of these skills together into a <strong>research report</strong>.</p>' } },
    { id: 'u3-l8-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Research Report Structure</h3><ol><li><strong>Introduction:</strong> Hook the reader, state your research question, and preview your main points</li><li><strong>Body Paragraphs (2–3):</strong> Each paragraph has one focused claim supported by evidence from your sources, with explanation</li><li><strong>Conclusion:</strong> Summarize your findings, explain why they matter, and suggest next steps or remaining questions</li><li><strong>Sources:</strong> List all sources you used (author, title, date, URL if applicable)</li></ol>' } },
    { id: 'u3-l8-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Revision Checklist for Research Reports</h3><ul><li>✅ <strong>Research question:</strong> Is it clear and focused?</li><li>✅ <strong>Evidence:</strong> Does every body paragraph include evidence from a source?</li><li>✅ <strong>Explanation:</strong> Does every piece of evidence have an explanation?</li><li>✅ <strong>Academic vocabulary:</strong> Have I used Tier 2 words instead of vague language?</li><li>✅ <strong>Sources:</strong> Have I cited all sources? No plagiarism?</li><li>✅ <strong>Conventions:</strong> Capitalization, punctuation, grammar, and spelling?</li><li>✅ <strong>Read aloud:</strong> Does it flow clearly?</li></ul>' } },
    { id: 'u3-l8-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Write your complete RESEARCH REPORT.\n\nRequirements:\n- At least 400 words\n- Introduction with research question and hook\n- 2–3 body paragraphs, each with C-E-E structure\n- Evidence from at least 2 sources\n- Academic vocabulary (Tier 2 words)\n- Conclusion with summary and reflection\n- Source list at the end\n- Correct spelling, capitalization, punctuation, and grammar', minLength: 400 } },
    { id: 'u3-l8-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Look back at your complete research journey (research question → sources → draft → revision → final report).\n\n1. What is the most important thing you learned — about your TOPIC or about the RESEARCH PROCESS itself?\n2. What would you do differently next time?\n3. How did peer feedback improve your report?', minLength: 40 } },
  ];
  for (const b of l8Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L8, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L8: ${l8Blocks.length} blocks`);

  const l8Qs = [
    { id: 'u3-l8-q1', questionText: 'A research report should include:', options: [{ label: 'Only your personal opinion', value: 'a' }, { label: 'An introduction, body paragraphs with evidence, a conclusion, and a source list', value: 'b', correct: true }, { label: 'Just a list of facts', value: 'c' }, { label: 'Only one paragraph', value: 'd' }], correctAnswer: 'b', explanation: 'A research report follows a clear structure: intro (question + preview) → body (claims + evidence + explanation) → conclusion (summary + significance) → sources.', outcomeCode: 'ELA.6.WC.6', difficulty: 1 },
    { id: 'u3-l8-q2', questionText: 'The CONCLUSION of a research report should:', options: [{ label: 'Introduce a completely new topic', value: 'a' }, { label: 'Summarize the findings, explain why they matter, and suggest next steps', value: 'b', correct: true }, { label: 'Copy the introduction word for word', value: 'c' }, { label: 'Just say "The End"', value: 'd' }], correctAnswer: 'b', explanation: 'A conclusion wraps up the report by connecting back to the research question, summarizing key findings, and reflecting on significance.', outcomeCode: 'ELA.6.WC.6', difficulty: 1 },
    { id: 'u3-l8-q3', questionText: 'Why is it important to LIST YOUR SOURCES at the end of a report?', options: [{ label: 'To make the report longer', value: 'a' }, { label: 'To give credit to the original authors and allow readers to verify your information', value: 'b', correct: true }, { label: 'It is not important', value: 'c' }, { label: 'Because it looks professional', value: 'd' }], correctAnswer: 'b', explanation: 'Citing sources is about honesty (giving credit), credibility (readers can check your evidence), and ethics (avoiding plagiarism).', outcomeCode: 'ELA.6.WC.6', difficulty: 1 },
    { id: 'u3-l8-q4', questionText: 'Peer feedback on a research report should FOCUS on:', options: [{ label: 'Whether you agree with the topic', value: 'a' }, { label: 'Clarity of the research question, strength of evidence, and quality of explanations', value: 'b', correct: true }, { label: 'How long the report is', value: 'c' }, { label: 'Only spelling errors', value: 'd' }], correctAnswer: 'b', explanation: 'Good peer feedback addresses the content and reasoning first (is the evidence strong? are explanations clear?) then conventions.', outcomeCode: 'ELA.6.OC.3', difficulty: 2 },
    { id: 'u3-l8-q5', questionText: 'The WRITING PROCESS for a research report is:', options: [{ label: 'Research → Plan → Draft → Revise → Edit → Publish', value: 'b', correct: true }, { label: 'Draft → Publish → Research', value: 'a' }, { label: 'Write it once, hand it in', value: 'c' }, { label: 'Copy from a website', value: 'd' }], correctAnswer: 'b', explanation: 'Research writing follows: choose topic → research → plan/organize → draft → revise content → edit conventions → publish/share.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u3-l8-q6', questionText: 'When revising a research report, you should check for:', options: [{ label: 'Only spelling', value: 'a' }, { label: 'Clear claims, strong evidence, thorough explanations, academic vocabulary, and logical organization', value: 'b', correct: true }, { label: 'Word count only', value: 'c' }, { label: 'Nothing — first drafts are perfect', value: 'd' }], correctAnswer: 'b', explanation: 'Revision is about BIG changes — improving your argument, adding stronger evidence, making explanations clearer. Editing (spelling, grammar) comes after.', outcomeCode: 'ELA.6.WC.3', difficulty: 1 },
    { id: 'u3-l8-q7', questionText: 'An INTRODUCTION to a research report should:', options: [{ label: 'Just state the research question', value: 'a' }, { label: 'Hook the reader, state the research question, and preview the main points', value: 'b', correct: true }, { label: 'Include all the evidence', value: 'c' }, { label: 'List all the sources', value: 'd' }], correctAnswer: 'b', explanation: 'A strong introduction draws the reader in (hook), establishes the topic (research question), and gives a road map (preview of main points).', outcomeCode: 'ELA.6.WC.2', difficulty: 1 },
    { id: 'u3-l8-q8', questionText: 'The MOST important part of evidence-based writing is:', options: [{ label: 'Using as many quotes as possible', value: 'a' }, { label: 'The EXPLANATION — showing WHY the evidence matters and HOW it supports your claim', value: 'b', correct: true }, { label: 'Making the font look nice', value: 'c' }, { label: 'Having a catchy title', value: 'd' }], correctAnswer: 'b', explanation: 'Evidence without explanation is just information. The explanation is where YOUR analysis lives — it\'s what makes the writing yours and shows critical thinking.', outcomeCode: 'ELA.6.TR.1', difficulty: 2 },
  ];
  for (const q of l8Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L8, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L8: ${l8Qs.length} questions`);

  console.log(`\n╔═══════════════════════════════════════════════╗\n║   ELA UNIT 3 (L5–L8) SEED COMPLETE          ║\n╠═══════════════════════════════════════════════╣\n║ Lessons:    4                                ║\n║ Blocks:     ${String(l5Blocks.length + l6Blocks.length + l7Blocks.length + l8Blocks.length).padStart(2)}                               ║\n║ Questions:  ${String(l5Qs.length + l6Qs.length + l7Qs.length + l8Qs.length).padStart(2)}                               ║\n╚═══════════════════════════════════════════════╝`);
}

main()
  .catch((e) => { console.error('❌ Seed error:', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); pool.end(); });
