// ============================================
// Seed ELA Unit 4 — "Perspectives and Justice" (Lessons 5–8)
// ============================================
// Persuasion, presentation planning, collaborative discussion, showcase.
// Run: npx tsx prisma/seed-ela-u4-l5-l8.ts

import { config } from 'dotenv';
config({ path: '.env.local' });
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('⚖️ Seeding ELA Unit 4 "Perspectives and Justice" — L5–L8');

  const lessonDefs = [
    { id: 'g6-ela-u4-l5', title: 'The Art of Persuasion', order: 5, learningGoal: 'Analyze persuasive techniques in texts and speeches, identifying ethos, pathos, and logos.', successCriteria: 'I can identify persuasive techniques (ethos, pathos, logos) in texts and speeches.\nI can explain how authors use emotional language, credibility, and logic to persuade.\nI can evaluate the effectiveness of a persuasive text.', reflectionPrompt: 'Which persuasive technique do you think is most powerful — ethos, pathos, or logos? Why? When might each be most effective?' },
    { id: 'g6-ela-u4-l6', title: 'Presentation Planning', order: 6, learningGoal: 'Plan an effective presentation with clear structure, audience awareness, and purposeful delivery.', successCriteria: 'I can organize a presentation with a clear introduction, body, and conclusion.\nI can adapt my language and tone for a specific audience.\nI can plan purposeful use of visual supports.', reflectionPrompt: 'What is the difference between reading your notes and truly presenting to an audience? What makes a presenter engaging?' },
    { id: 'g6-ela-u4-l7', title: 'Collaborative Discussion', order: 7, learningGoal: 'Practice structured discussion protocols including active listening, building on others\' ideas, and respectful disagreement.', successCriteria: 'I can use discussion protocols to build on another person\'s idea.\nI can respectfully disagree by using evidence and reasoning.\nI can actively listen and ask clarifying questions.', reflectionPrompt: 'What is the difference between a debate and a collaborative discussion? Which approach leads to deeper understanding?' },
    { id: 'g6-ela-u4-l8', title: 'Perspectives Showcase', order: 8, learningGoal: 'Present a persuasive argument to an audience, receive and give constructive peer feedback, and reflect on growth.', successCriteria: 'I can deliver a persuasive argument clearly and confidently.\nI can use non-verbal and paraverbal cues to strengthen my delivery.\nI can give specific, constructive peer feedback.\nI can reflect on my growth as a communicator.', reflectionPrompt: 'What is the most important thing you learned in this unit — about communication, about perspectives, or about yourself?' },
  ];

  for (const l of lessonDefs) {
    await prisma.lesson.upsert({
      where: { id: l.id },
      update: { title: l.title, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
      create: { id: l.id, unitId: 'g6-ela-u4', title: l.title, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
    });
  }
  console.log('✅ Lessons 5–8 upserted');

  for (const l of lessonDefs) {
    await prisma.lessonBlock.deleteMany({ where: { lessonId: l.id } });
    await prisma.quizQuestion.deleteMany({ where: { lessonId: l.id } });
  }

  // L5: The Art of Persuasion — TR.3, TF.3, Review: VL.2, RC.1
  const L5 = 'g6-ela-u4-l5';
  const l5Blocks = [
    { id: 'u4-l5-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>The Three Pillars of Persuasion</h3><p>Over 2,000 years ago, the Greek philosopher Aristotle identified three tools that persuasive speakers and writers use:</p><ul><li><strong>Ethos (Credibility):</strong> "Trust me because I am qualified." — Using expertise, authority, or moral character to build trust.</li><li><strong>Pathos (Emotion):</strong> "Feel this." — Using stories, emotional language, or vivid imagery to create an emotional response.</li><li><strong>Logos (Logic):</strong> "This makes sense." — Using facts, statistics, evidence, and logical reasoning.</li></ul><p>The strongest persuasive texts use a <em>combination</em> of all three.</p>' } },
    { id: 'u4-l5-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Persuasion in Action</h3><blockquote style="border-left:3px solid #f59e0b;padding:12px 16px;margin:12px 0;color:#475569"><strong>Speech Excerpt: "Every Child Deserves Recess"</strong><br><br>"I\'ve been a physical education teacher for 18 years <em>(ethos)</em>, and I\'ve watched what happens when schools cut recess. Kids don\'t just lose playtime — they lose the space to breathe, to process, to be human <em>(pathos)</em>. A 2023 study from the Canadian Paediatric Society found that children with daily unstructured outdoor time showed 22% better emotional regulation and 15% higher focus in afternoon classes <em>(logos)</em>. We don\'t give children recess because they\'ve earned it. We give them recess because their brains need it."</blockquote>' } },
    { id: 'u4-l5-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: '"A 2023 study found that children with daily outdoor time showed 22% better emotional regulation." This is an example of:', options: [{ label: 'Ethos — credibility', value: 'a' }, { label: 'Pathos — emotional appeal', value: 'b' }, { label: 'Logos — using evidence, statistics, and logic', value: 'c', correct: true }], explanation: 'Statistics and research findings are logos — they appeal to the reader\'s sense of logic and reason. Data makes the argument feel evidence-based and objective.' } },
    { id: 'u4-l5-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Reread the recess speech excerpt.\n\n1. Find and label ONE example of each: ethos, pathos, and logos.\n2. Which technique do you think is MOST effective in this speech? Why?\n3. Write 2–3 sentences using PATHOS to argue that schools should (or should not) have longer lunch breaks. Use emotional language and vivid imagery.', minLength: 50 } },
    { id: 'u4-l5-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Which persuasive technique do you think is most powerful — ethos, pathos, or logos? Why? When might each be most effective?', minLength: 30 } },
  ];
  for (const b of l5Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L5, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L5: ${l5Blocks.length} blocks`);

  const l5Qs = [
    { id: 'u4-l5-q1', questionText: 'ETHOS in persuasion refers to:', options: [{ label: 'Emotional appeal', value: 'a' }, { label: 'Credibility — trusting the speaker because of their qualifications or character', value: 'b', correct: true }, { label: 'Logical evidence', value: 'c' }, { label: 'The topic of the speech', value: 'd' }], correctAnswer: 'b', explanation: 'Ethos = credibility. "As a doctor..." or "In my 20 years of experience..." builds trust through authority.', outcomeCode: 'ELA.6.TR.3', difficulty: 1 },
    { id: 'u4-l5-q2', questionText: 'PATHOS appeals to:', options: [{ label: 'Logic and facts', value: 'a' }, { label: 'The audience\'s emotions — using stories, vivid language, or imagery to create feeling', value: 'b', correct: true }, { label: 'The author\'s reputation', value: 'c' }, { label: 'Grammar rules', value: 'd' }], correctAnswer: 'b', explanation: 'Pathos = emotion. Stories, descriptive language, and appeals to values (fairness, safety) create emotional engagement.', outcomeCode: 'ELA.6.TR.3', difficulty: 1 },
    { id: 'u4-l5-q3', questionText: '"They lose the space to breathe, to process, to be human." This uses:', options: [{ label: 'Logos — statistics', value: 'a' }, { label: 'Pathos — emotional language that makes the audience FEEL the loss', value: 'b', correct: true }, { label: 'Ethos — the speaker\'s credentials', value: 'c' }, { label: 'None of the above', value: 'd' }], correctAnswer: 'b', explanation: '"To breathe, to process, to be human" is emotional language that creates sympathy and urgency. This is pathos.', outcomeCode: 'ELA.6.TR.3', difficulty: 1 },
    { id: 'u4-l5-q4', questionText: '"I\'ve been a physical education teacher for 18 years" establishes:', options: [{ label: 'Pathos', value: 'a' }, { label: 'Logos', value: 'b' }, { label: 'Ethos — the speaker has experience and authority on the topic', value: 'c', correct: true }, { label: 'None', value: 'd' }], correctAnswer: 'c', explanation: 'Citing 18 years of experience makes the speaker credible on this topic. This is ethos.', outcomeCode: 'ELA.6.TR.3', difficulty: 1 },
    { id: 'u4-l5-q5', questionText: 'The STRONGEST persuasive texts:', options: [{ label: 'Use only pathos', value: 'a' }, { label: 'Use a combination of ethos, pathos, AND logos', value: 'b', correct: true }, { label: 'Use only logos', value: 'c' }, { label: 'Avoid persuasive techniques entirely', value: 'd' }], correctAnswer: 'b', explanation: 'The most persuasive arguments combine credibility (ethos), emotional connection (pathos), and evidence (logos). Each alone is weaker.', outcomeCode: 'ELA.6.TR.3', difficulty: 2 },
    { id: 'u4-l5-q6', questionText: 'Figurative language like metaphor and simile can serve as PATHOS in persuasion because:', options: [{ label: 'They are grammar techniques', value: 'a' }, { label: 'They create vivid images and emotional connections that make the argument more compelling', value: 'b', correct: true }, { label: 'They provide statistical evidence', value: 'c' }, { label: 'They prove the speaker is credible', value: 'd' }], correctAnswer: 'b', explanation: 'Figurative language creates imagery and emotional resonance. "Education is the passport to the future" (metaphor) is more powerful than "education is useful."', outcomeCode: 'ELA.6.VL.2', difficulty: 2 },
    { id: 'u4-l5-q7', questionText: 'When evaluating persuasive text, a critical reader asks:', options: [{ label: '"Is this text long?"', value: 'a' }, { label: '"What techniques is the author using? Are the claims supported by evidence? Is there bias?"', value: 'b', correct: true }, { label: '"Do I agree with the author?"', value: 'c' }, { label: '"Is the font nice?"', value: 'd' }], correctAnswer: 'b', explanation: 'Critical evaluation means analyzing HOW the author is trying to persuade you, not just WHETHER you agree. Identify the techniques and check the evidence.', outcomeCode: 'ELA.6.TF.3', difficulty: 2 },
    { id: 'u4-l5-q8', questionText: 'An inference you can make about the recess speech author is:', options: [{ label: 'They don\'t like children', value: 'a' }, { label: 'They believe strongly that recess matters and have seen the consequences of cutting it firsthand', value: 'b', correct: true }, { label: 'They have never been a teacher', value: 'c' }, { label: 'They are neutral on the topic', value: 'd' }], correctAnswer: 'b', explanation: 'The author cites personal experience (18 years) and says "I\'ve watched what happens" — inferring they have firsthand evidence of the negative effects.', outcomeCode: 'ELA.6.RC.1', difficulty: 2 },
  ];
  for (const q of l5Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L5, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L5: ${l5Qs.length} questions`);

  // L6: Presentation Planning — OC.4, Review: WC.1, OC.2
  const L6 = 'g6-ela-u4-l6';
  const l6Blocks = [
    { id: 'u4-l6-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>From Writing to Speaking</h3><p>Writing an argument is one thing. <em>Presenting</em> it is another. A great presentation is NOT reading your paper out loud — it is an <strong>act of communication</strong> where you connect with your audience.</p><p><strong>Presentation structure:</strong></p><ol><li><strong>Hook:</strong> Start with something that grabs attention — a question, a surprising fact, or a short story</li><li><strong>Claim:</strong> State your position clearly</li><li><strong>Key points:</strong> 2–3 main arguments with evidence</li><li><strong>Conclusion:</strong> Restate your position and leave the audience thinking</li></ol>' } },
    { id: 'u4-l6-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Delivery Tips</h3><ul><li><strong>Eye contact:</strong> Look at your audience, not your notes</li><li><strong>Pacing:</strong> Speak slowly enough to be understood. Pause after key points.</li><li><strong>Volume:</strong> Project your voice — speak to the back of the room</li><li><strong>Body language:</strong> Stand tall, use natural gestures, avoid fidgeting</li><li><strong>Visual supports:</strong> Use slides, images, or props that ADD to your message (not replace it)</li><li><strong>Practice:</strong> Rehearse at least 2–3 times before presenting</li></ul>' } },
    { id: 'u4-l6-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: 'The BIGGEST mistake in a presentation is:', options: [{ label: 'Using eye contact', value: 'a' }, { label: 'Reading your entire paper word for word without looking at the audience', value: 'b', correct: true }, { label: 'Speaking clearly', value: 'c' }], explanation: 'Reading word-for-word disconnects you from the audience. A presentation should feel like a conversation — use notes as reminders, not a script.' } },
    { id: 'u4-l6-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Plan your persuasive presentation:\n\n1. Write your HOOK (1–2 sentences that grab attention)\n2. State your CLAIM (1 clear sentence)\n3. List your 2–3 KEY POINTS with evidence\n4. Write your CONCLUSION (1–2 sentences)\n5. Describe how you will use DELIVERY SKILLS (eye contact, pacing, body language)\n6. Will you use any visual supports? What and why?', minLength: 60 } },
    { id: 'u4-l6-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'What is the difference between reading your notes and truly presenting to an audience? What makes a presenter engaging?', minLength: 30 } },
  ];
  for (const b of l6Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L6, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L6: ${l6Blocks.length} blocks`);

  const l6Qs = [
    { id: 'u4-l6-q1', questionText: 'A presentation HOOK should:', options: [{ label: 'Start with "Today I will talk about..."', value: 'a' }, { label: 'Grab the audience\'s attention with a question, surprising fact, or short story', value: 'b', correct: true }, { label: 'Apologize for being nervous', value: 'c' }, { label: 'List all your sources first', value: 'd' }], correctAnswer: 'b', explanation: 'A hook draws the audience in immediately. A question makes them think, a fact surprises them, a story creates connection.', outcomeCode: 'ELA.6.OC.4', difficulty: 1 },
    { id: 'u4-l6-q2', questionText: 'Reading your paper word-for-word during a presentation:', options: [{ label: 'Shows preparation', value: 'a' }, { label: 'Disconnects you from the audience and makes the delivery flat and impersonal', value: 'b', correct: true }, { label: 'Is the best approach', value: 'c' }, { label: 'Saves time', value: 'd' }], correctAnswer: 'b', explanation: 'Presentations are about CONNECTION. Reading word-for-word prevents eye contact, natural pacing, and genuine engagement.', outcomeCode: 'ELA.6.OC.4', difficulty: 1 },
    { id: 'u4-l6-q3', questionText: 'PACING in a presentation means:', options: [{ label: 'Walking around the room', value: 'a' }, { label: 'Controlling your speed — speaking slowly enough to be understood and pausing after key points', value: 'b', correct: true }, { label: 'Speaking as fast as possible', value: 'c' }, { label: 'Reading the clock', value: 'd' }], correctAnswer: 'b', explanation: 'Pacing is about tempo and rhythm. Slow down for important points. Pause to let ideas sink in. This is paraverbal awareness in action.', outcomeCode: 'ELA.6.OC.4', difficulty: 1 },
    { id: 'u4-l6-q4', questionText: 'Visual supports in a presentation should:', options: [{ label: 'Replace what you say entirely', value: 'a' }, { label: 'ADD to your message — supporting your words with images, data, or key points', value: 'b', correct: true }, { label: 'Have as much text as possible', value: 'c' }, { label: 'Be confusing to create interest', value: 'd' }], correctAnswer: 'b', explanation: 'Visuals support — not replace — your words. A powerful image or key statistic reinforces what you\'re saying and helps the audience remember.', outcomeCode: 'ELA.6.OC.4', difficulty: 1 },
    { id: 'u4-l6-q5', questionText: 'Adapting your language for your AUDIENCE means:', options: [{ label: 'Using the same language for everyone', value: 'a' }, { label: 'Choosing words, tone, and examples that match who you are speaking to', value: 'b', correct: true }, { label: 'Using the biggest words possible', value: 'c' }, { label: 'Whispering', value: 'd' }], correctAnswer: 'b', explanation: 'Audience awareness means adjusting your language, examples, and tone. You speak differently to classmates vs the principal vs younger students.', outcomeCode: 'ELA.6.OC.4', difficulty: 2 },
    { id: 'u4-l6-q6', questionText: 'The writing process skill that applies to presentations is:', options: [{ label: 'There is no connection', value: 'a' }, { label: 'Planning, drafting, and revising your content BEFORE presenting it', value: 'b', correct: true }, { label: 'Only the publishing step', value: 'c' }, { label: 'Only editing for commas', value: 'd' }], correctAnswer: 'b', explanation: 'Great presentations are planned (structure), drafted (key points), and revised (practiced and improved). The writing process applies to oral communication too.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u4-l6-q7', questionText: 'Which body language strengthens a presentation?', options: [{ label: 'Looking at the floor, crossing your arms', value: 'a' }, { label: 'Standing tall, making eye contact, using natural gestures', value: 'b', correct: true }, { label: 'Turning your back to the audience', value: 'c' }, { label: 'Sitting with your hands in your pockets', value: 'd' }], correctAnswer: 'b', explanation: 'Open posture, eye contact, and purposeful gestures show confidence and help the audience connect with your message.', outcomeCode: 'ELA.6.OC.2', difficulty: 1 },
    { id: 'u4-l6-q8', questionText: 'Rehearsing a presentation 2–3 times before delivering it helps you:', options: [{ label: 'Memorize every word', value: 'a' }, { label: 'Feel more confident, improve pacing, and catch problems before the real presentation', value: 'b', correct: true }, { label: 'Waste time', value: 'c' }, { label: 'Make it sound robotic', value: 'd' }], correctAnswer: 'b', explanation: 'Practice builds confidence and fluency. It helps you internalize your content so you can present naturally instead of reading.', outcomeCode: 'ELA.6.OC.4', difficulty: 1 },
  ];
  for (const q of l6Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L6, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L6: ${l6Qs.length} questions`);

  // L7: Collaborative Discussion — OC.3, TR.2, Review: OC.2, RC.3
  const L7 = 'g6-ela-u4-l7';
  const l7Blocks = [
    { id: 'u4-l7-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Discussion vs Debate</h3><p>In a <strong>debate</strong>, two sides try to WIN. In a <strong>collaborative discussion</strong>, participants try to UNDERSTAND — building on each other\'s ideas to reach deeper thinking.</p><p><strong>Discussion sentence starters:</strong></p><ul><li>"I agree with ___ because..."</li><li>"I\'d like to build on what ___ said..."</li><li>"I see it differently because..."</li><li>"Can you explain what you mean by...?"</li><li>"That makes me think about..."</li></ul>' } },
    { id: 'u4-l7-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Active Listening Protocol</h3><ol><li><strong>Focus:</strong> Give the speaker your full attention</li><li><strong>Show:</strong> Use non-verbal cues (eye contact, nodding)</li><li><strong>Reflect:</strong> Before responding, summarize what you heard ("So you\'re saying...")</li><li><strong>Build:</strong> Connect your idea TO theirs, don\'t just change the topic</li><li><strong>Question:</strong> Ask clarifying or probing questions</li></ol>' } },
    { id: 'u4-l7-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: 'The main difference between a debate and a collaborative discussion is:', options: [{ label: 'They are the same thing', value: 'a' }, { label: 'A debate tries to WIN; a collaborative discussion tries to UNDERSTAND and build shared meaning', value: 'b', correct: true }, { label: 'Discussions are louder', value: 'c' }], explanation: 'Debates are competitive. Collaborative discussions are cooperative — the goal is deeper understanding, not victory.' } },
    { id: 'u4-l7-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Return to the Jade and Malik anchor text from L1.\n\n1. Write a response BUILDING ON Jade\'s perspective: "I\'d like to build on what Jade said by adding..."\n2. Write a RESPECTFUL DISAGREEMENT with Jade: "I see it differently because..."\n3. Write a CLARIFYING QUESTION for Malik: "Can you explain what you mean by..."\n4. How does collaborative discussion help us reach a DEEPER understanding than if only one person spoke?', minLength: 50 } },
    { id: 'u4-l7-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'What is the difference between a debate and a collaborative discussion? Which approach leads to deeper understanding? Which is harder for you, and why?', minLength: 30 } },
  ];
  for (const b of l7Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L7, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L7: ${l7Blocks.length} blocks`);

  const l7Qs = [
    { id: 'u4-l7-q1', questionText: 'In collaborative discussion, the goal is to:', options: [{ label: 'Win the argument', value: 'a' }, { label: 'Understand different perspectives and build shared meaning through dialogue', value: 'b', correct: true }, { label: 'Be the loudest speaker', value: 'c' }, { label: 'Avoid sharing your opinion', value: 'd' }], correctAnswer: 'b', explanation: 'Collaborative discussion is about collective understanding — building on each other\'s ideas, not competing.', outcomeCode: 'ELA.6.OC.3', difficulty: 1 },
    { id: 'u4-l7-q2', questionText: '"I\'d like to build on what Sarah said..." is an example of:', options: [{ label: 'Changing the topic', value: 'a' }, { label: 'Building on another person\'s idea — a key collaborative discussion skill', value: 'b', correct: true }, { label: 'Disagreeing', value: 'c' }, { label: 'Starting a debate', value: 'd' }], correctAnswer: 'b', explanation: 'Building on others\' ideas shows active listening and creates deeper discussion. It connects ideas instead of creating isolated opinions.', outcomeCode: 'ELA.6.OC.3', difficulty: 1 },
    { id: 'u4-l7-q3', questionText: 'RESPECTFUL DISAGREEMENT sounds like:', options: [{ label: '"You\'re wrong."', value: 'a' }, { label: '"I see it differently because... the evidence suggests that..."', value: 'b', correct: true }, { label: '"That\'s a dumb idea."', value: 'c' }, { label: 'Not saying anything', value: 'd' }], correctAnswer: 'b', explanation: 'Respectful disagreement uses reasoning ("I see it differently because...") and evidence, not personal attacks or dismissives.', outcomeCode: 'ELA.6.OC.3', difficulty: 1 },
    { id: 'u4-l7-q4', questionText: 'Active listening requires:', options: [{ label: 'Thinking about what to say next while someone else talks', value: 'a' }, { label: 'Giving full attention, using non-verbal cues, summarizing before responding, and asking questions', value: 'b', correct: true }, { label: 'Just being quiet', value: 'c' }, { label: 'Interrupting with better ideas', value: 'd' }], correctAnswer: 'b', explanation: 'Active listening is a FULL skill set: attention + non-verbal engagement + reflection + questions. It\'s far more than silence.', outcomeCode: 'ELA.6.OC.3', difficulty: 1 },
    { id: 'u4-l7-q5', questionText: 'Understanding BOTH Jade\'s AND Malik\'s perspectives helps us:', options: [{ label: 'Pick the "right" side', value: 'a' }, { label: 'Develop empathy and recognize that complex situations have multiple valid viewpoints', value: 'b', correct: true }, { label: 'Decide neither matters', value: 'c' }, { label: 'Avoid the issue entirely', value: 'd' }], correctAnswer: 'b', explanation: 'Multiple perspectives reveal complexity. Empathy grows when we understand WHY people feel differently, even in disagreement.', outcomeCode: 'ELA.6.TR.2', difficulty: 2 },
    { id: 'u4-l7-q6', questionText: '"So you\'re saying..." before responding is an example of:', options: [{ label: 'Ignoring what was said', value: 'a' }, { label: 'REFLECTING — summarizing what you heard to ensure you understood correctly', value: 'b', correct: true }, { label: 'Changing the subject', value: 'c' }, { label: 'Being sarcastic', value: 'd' }], correctAnswer: 'b', explanation: 'Reflecting back shows the speaker you were listening and gives them a chance to clarify before you respond. This deepens communication.', outcomeCode: 'ELA.6.OC.3', difficulty: 1 },
    { id: 'u4-l7-q7', questionText: 'Which NON-VERBAL CUE shows you are actively listening?', options: [{ label: 'Looking at your phone', value: 'a' }, { label: 'Making eye contact and nodding to show you\'re engaged', value: 'b', correct: true }, { label: 'Crossing your arms and looking away', value: 'c' }, { label: 'Tapping your fingers', value: 'd' }], correctAnswer: 'b', explanation: 'Eye contact and nodding are non-verbal signals that say "I\'m paying attention and I value what you\'re saying."', outcomeCode: 'ELA.6.OC.2', difficulty: 1 },
    { id: 'u4-l7-q8', questionText: 'Which comprehension strategy is MOST important during collaborative discussion?', options: [{ label: 'Visualizing', value: 'a' }, { label: 'QUESTIONING — asking clarifying and probing questions to deepen understanding', value: 'b', correct: true }, { label: 'Predicting', value: 'c' }, { label: 'Skimming', value: 'd' }], correctAnswer: 'b', explanation: 'Questioning drives deeper discussion. "Can you explain what you mean by...?" and "Why do you think that?" push thinking beyond surface-level responses.', outcomeCode: 'ELA.6.RC.3', difficulty: 2 },
  ];
  for (const q of l7Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L7, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L7: ${l7Qs.length} questions`);

  // L8: Perspectives Showcase — OC.4, WC.1, Review: WC.3, OC.3
  const L8 = 'g6-ela-u4-l8';
  const l8Blocks = [
    { id: 'u4-l8-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Showtime: Putting It All Together</h3><p>You have learned to:</p><ul><li>Take on different perspectives and practice empathy (L1)</li><li>Identify missing voices and analyze representation (L2)</li><li>Build structured arguments with evidence (L3)</li><li>Communicate effectively with verbal, non-verbal, and paraverbal awareness (L4)</li><li>Analyze persuasive techniques — ethos, pathos, logos (L5)</li><li>Plan engaging presentations (L6)</li><li>Practice collaborative discussion protocols (L7)</li></ul><p>Now it\'s time to <strong>present your persuasive argument</strong> and <strong>receive peer feedback</strong>.</p>' } },
    { id: 'u4-l8-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Peer Feedback Protocol: Glow, Grow, Question</h3><ol><li><strong>Glow:</strong> Name 2 SPECIFIC strengths. "Your use of the statistic about outdoor time was really convincing because..."</li><li><strong>Grow:</strong> Suggest 1 SPECIFIC area for improvement. "I think your conclusion could be stronger if you restated your claim with a powerful final sentence."</li><li><strong>Question:</strong> Ask 1 question the presentation made you think about. "I wonder what would happen if schools tried a compromise instead of a full ban?"</li></ol>' } },
    { id: 'u4-l8-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Deliver your persuasive presentation (record yourself if possible, or write out your delivery notes below).\n\nThen, after receiving peer feedback, write:\n\n1. What were your 2 STRONGEST elements? (What did you do well?)\n2. What is 1 SPECIFIC thing you would improve for next time?\n3. What did you learn from listening to OTHER presentations?', minLength: 50 } },
    { id: 'u4-l8-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'What is the most important thing you learned in this unit — about communication, about perspectives, or about yourself as a thinker and speaker?', minLength: 30 } },
  ];
  for (const b of l8Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L8, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L8: ${l8Blocks.length} blocks`);

  const l8Qs = [
    { id: 'u4-l8-q1', questionText: 'The "Glow, Grow, Question" feedback protocol requires:', options: [{ label: 'Only positive comments', value: 'a' }, { label: '2 specific strengths, 1 specific area for improvement, and 1 question', value: 'b', correct: true }, { label: 'General comments like "good job"', value: 'c' }, { label: 'Rewriting the presenter\'s argument', value: 'd' }], correctAnswer: 'b', explanation: 'The protocol ensures feedback is balanced (strengths + growth), specific (not vague), and thought-provoking (question).', outcomeCode: 'ELA.6.OC.3', difficulty: 1 },
    { id: 'u4-l8-q2', questionText: 'After giving a presentation, the BEST way to improve is:', options: [{ label: 'Ignore all feedback', value: 'a' }, { label: 'Reflect on peer feedback, identify specific areas to strengthen, and practice again', value: 'b', correct: true }, { label: 'Blame the audience', value: 'c' }, { label: 'Never present again', value: 'd' }], correctAnswer: 'b', explanation: 'Growth comes from honest reflection + targeted practice. Peer feedback gives you perspective on how your message was received.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u4-l8-q3', questionText: 'SPECIFIC feedback is more helpful than VAGUE feedback because:', options: [{ label: 'It takes longer to write', value: 'a' }, { label: 'It tells the writer/speaker exactly WHAT worked and WHAT to change', value: 'b', correct: true }, { label: 'It is always negative', value: 'c' }, { label: 'It uses bigger words', value: 'd' }], correctAnswer: 'b', explanation: '"Your opening question hooked me because I was curious about the answer" is actionable. "Good job" tells the presenter nothing useful.', outcomeCode: 'ELA.6.OC.3', difficulty: 1 },
    { id: 'u4-l8-q4', questionText: 'Revising a presentation based on feedback is part of:', options: [{ label: 'The writing process — plan, draft, revise, edit, publish applies to presentations too', value: 'b', correct: true }, { label: 'Wasting time', value: 'a' }, { label: 'Copying someone else\'s work', value: 'c' }, { label: 'Nothing — presentations can\'t be revised', value: 'd' }], correctAnswer: 'b', explanation: 'The writing process is universal. Presenting is "publishing" — revision before that step strengthens the final product.', outcomeCode: 'ELA.6.WC.1', difficulty: 1 },
    { id: 'u4-l8-q5', questionText: 'Effective communicators ALIGN their verbal, non-verbal, and paraverbal cues. This means:', options: [{ label: 'Using the loudest voice possible', value: 'a' }, { label: 'Making sure words, body language, and tone all send the SAME message', value: 'b', correct: true }, { label: 'Only using words', value: 'c' }, { label: 'Ignoring body language', value: 'd' }], correctAnswer: 'b', explanation: 'Alignment = consistency. If your words say "I\'m confident" but your body says "I\'m scared," the message is mixed. Alignment builds trust.', outcomeCode: 'ELA.6.OC.2', difficulty: 2 },
    { id: 'u4-l8-q6', questionText: 'Which combines ETHOS, PATHOS, and LOGOS in one statement?', options: [{ label: '"I think recess is fun."', value: 'a' }, { label: '"As a PE teacher for 18 years, I\'ve seen the heartbreak of kids losing recess — and research confirms that daily outdoor play improves focus by 15%."', value: 'b', correct: true }, { label: '"Everyone should have recess."', value: 'c' }, { label: '"Recess is at 10:30."', value: 'd' }], correctAnswer: 'b', explanation: 'Ethos ("as a PE teacher for 18 years") + Pathos ("heartbreak") + Logos ("research confirms... 15%") — all three in one powerful sentence.', outcomeCode: 'ELA.6.TR.3', difficulty: 2 },
    { id: 'u4-l8-q7', questionText: 'Revising for CLARITY means:', options: [{ label: 'Adding more words', value: 'a' }, { label: 'Making sure your ideas are easy to understand, well-organized, and free of confusion', value: 'b', correct: true }, { label: 'Removing all evidence', value: 'c' }, { label: 'Using longer sentences', value: 'd' }], correctAnswer: 'b', explanation: 'Clarity revision asks: "Will the audience understand what I mean? Is this organized logically? Are there confusing parts?"', outcomeCode: 'ELA.6.WC.3', difficulty: 1 },
    { id: 'u4-l8-q8', questionText: 'Listening to OTHER people\'s presentations helps you because:', options: [{ label: 'It wastes class time', value: 'a' }, { label: 'You learn new persuasive techniques, hear different perspectives, and identify what makes delivery effective', value: 'b', correct: true }, { label: 'It only helps the presenter', value: 'c' }, { label: 'You can copy their ideas', value: 'd' }], correctAnswer: 'b', explanation: 'Being an audience member is active learning. You analyze what works (and what doesn\'t), encounter new perspectives, and build your own skills.', outcomeCode: 'ELA.6.OC.3', difficulty: 1 },
  ];
  for (const q of l8Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L8, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L8: ${l8Qs.length} questions`);

  console.log(`\n╔═══════════════════════════════════════════════╗\n║   ELA UNIT 4 (L5–L8) SEED COMPLETE          ║\n╠═══════════════════════════════════════════════╣\n║ Lessons:    4                                ║\n║ Blocks:     ${String(l5Blocks.length + l6Blocks.length + l7Blocks.length + l8Blocks.length).padStart(2)}                               ║\n║ Questions:  ${String(l5Qs.length + l6Qs.length + l7Qs.length + l8Qs.length).padStart(2)}                               ║\n╚═══════════════════════════════════════════════╝`);
}

main()
  .catch((e) => { console.error('❌ Seed error:', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); pool.end(); });
