// ============================================
// Seed ELA Unit 5 — "Wonder, Discovery, and Imagination" (Lessons 1–4)
// ============================================
// Poetry, figurative language, drama, FNMI land literacy.
// Run: npx tsx prisma/seed-ela-u5-l1-l4.ts

import { config } from 'dotenv';
config({ path: '.env.local' });
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🌿 Seeding ELA Unit 5 "Wonder, Discovery, and Imagination" — L1–L4');

  const lessonDefs = [
    { id: 'g6-ela-u5-l1', title: 'The Power of Poetry', order: 1, learningGoal: 'Identify and analyze poetic structures including stanza, rhythm, rhyme scheme, and free verse.', successCriteria: 'I can identify basic poetic structures (stanza, line, rhyme scheme).\nI can distinguish between structured poems (sonnets, haiku) and free verse.\nI can explain how a poem\'s structure contributes to its meaning.', reflectionPrompt: 'Why do poets choose certain structures? How does the way a poem looks on the page affect how you read and feel it?' },
    { id: 'g6-ela-u5-l2', title: 'Figurative Language Deep Dive', order: 2, learningGoal: 'Analyze figurative language including extended metaphor, symbolism, imagery, and sound devices in poetry and prose.', successCriteria: 'I can identify and explain metaphor, simile, personification, and symbolism.\nI can analyze how imagery appeals to the five senses.\nI can identify sound devices (alliteration, onomatopoeia, repetition) and explain their effect.', reflectionPrompt: 'Why do writers use figurative language instead of just saying things literally? What does figurative language add to a text?' },
    { id: 'g6-ela-u5-l3', title: 'Drama & Performance', order: 3, learningGoal: 'Read, analyze, and appreciate dramatic works including comedy and tragedy, understanding the unique features of plays as a literary form.', successCriteria: 'I can identify features unique to drama (stage directions, dialogue, acts/scenes).\nI can explain the difference between comedy and tragedy.\nI can analyze how a playwright conveys character and conflict through dialogue.', reflectionPrompt: 'How is reading a play different from reading a story? What extra skills do you need to "see" a play in your mind while reading?' },
    { id: 'g6-ela-u5-l4', title: 'Land as Text', order: 4, learningGoal: 'Explore FNMI perspectives on land literacy — understanding how land carries meaning, story, and knowledge through Indigenous ways of knowing.', successCriteria: 'I can explain what "land as text" means in Indigenous perspectives.\nI can describe how structures of land carry meaning and teach.\nI can respectfully engage with Indigenous communication protocols and oral traditions.', reflectionPrompt: 'How does thinking about "land as text" change the way you see the natural world around you? What can we learn from the land that we can\'t learn from books?' },
  ];

  for (const l of lessonDefs) {
    await prisma.lesson.upsert({
      where: { id: l.id },
      update: { title: l.title, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
      create: { id: l.id, unitId: 'g6-ela-u5', title: l.title, order: l.order, subjectMode: 'ELA', estimatedMinutes: 40, learningGoal: l.learningGoal, successCriteria: l.successCriteria, reflectionPrompt: l.reflectionPrompt, masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
    });
  }
  console.log('✅ Lessons 1–4 upserted');

  for (const l of lessonDefs) {
    await prisma.lessonBlock.deleteMany({ where: { lessonId: l.id } });
    await prisma.quizQuestion.deleteMany({ where: { lessonId: l.id } });
  }

  // L1: The Power of Poetry — TF.5, Review: VL.2, RC.1
  const L1 = 'g6-ela-u5-l1';
  const l1Blocks = [
    { id: 'u5-l1-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>What Makes Poetry Different?</h3><p>Poetry is language at its most concentrated and musical. Unlike prose (paragraphs), poetry uses <strong>line breaks, stanzas, rhythm, and sound</strong> to create meaning and feeling.</p><p>A poet chooses every single word with care — and even the <em>spaces</em> and <em>silences</em> between words matter.</p>' } },
    { id: 'u5-l1-learn-2', section: 'LEARN', blockType: 'VOCABULARY', order: 2, content: { terms: [{ term: 'Stanza', definition: 'A group of lines in a poem, similar to a paragraph in prose.', example: 'A poem with 4 stanzas of 4 lines each has 16 lines total.' }, { term: 'Rhyme Scheme', definition: 'The pattern of rhymes at the end of each line, labeled with letters (ABAB, AABB, etc.).', example: '"Roses are red (A) / Violets are blue (B) / Sugar is sweet (A) / And so are you (B)" = ABAB' }, { term: 'Free Verse', definition: 'Poetry that does NOT follow a regular rhyme scheme or meter. It still uses poetic techniques.', example: 'Most modern poetry is free verse — it sounds like natural speech but uses imagery and line breaks for effect.' }, { term: 'Meter', definition: 'The rhythmic pattern of stressed and unstressed syllables in a line of poetry.', example: '"Shall I comPARE thee TO a SUMmer\'s DAY?" has a regular da-DUM da-DUM beat.' }] } },
    { id: 'u5-l1-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Anchor Poem: "Where I\'m From"</h3><blockquote style="border-left:3px solid #10b981;padding:12px 16px;margin:12px 0;color:#475569;font-style:italic">I am from clotheslines,<br>from Clorox and carbon-tetrachloride.<br>I am from the dirt under the back porch.<br>(Black, glistening,<br>it tasted like beets.)<br><br>I am from the forsythia bush<br>the Dutch elm<br>whose long gone limbs I remember<br>as if they were my own.<br><br>— George Ella Lyon</blockquote><p>This poem uses <strong>free verse</strong> — no rhyme scheme, no regular meter. But it uses powerful <strong>imagery</strong> (dirt that "tasted like beets"), <strong>repetition</strong> ("I am from"), and <strong>metaphor</strong> (tree limbs = her own limbs) to create deep meaning.</p>' } },
    { id: 'u5-l1-learn-4', section: 'LEARN', blockType: 'MICRO_CHECK', order: 4, content: { question: '"Where I\'m From" is an example of:', options: [{ label: 'A sonnet with strict rhyme scheme', value: 'a' }, { label: 'Free verse — no regular rhyme or meter, but uses imagery, repetition, and metaphor', value: 'b', correct: true }, { label: 'A haiku', value: 'c' }], explanation: 'Free verse poems like this one don\'t follow rhyme rules but still use poetic techniques. The repetition of "I am from" creates structure and rhythm without rhyme.' } },
    { id: 'u5-l1-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: '1. Read the anchor poem again. Identify ONE example of IMAGERY and explain which sense it appeals to.\n2. Why does the poet repeat "I am from"? What effect does this repetition create?\n3. Write your own "Where I\'m From" stanza (4–6 lines). Start each line with "I am from" and include at least one vivid image.', minLength: 40 } },
    { id: 'u5-l1-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Why do poets choose certain structures? How does the way a poem looks on the page affect how you read and feel it?', minLength: 30 } },
  ];
  for (const b of l1Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L1, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L1: ${l1Blocks.length} blocks`);

  const l1Qs = [
    { id: 'u5-l1-q1', questionText: 'A STANZA in a poem is:', options: [{ label: 'A single word', value: 'a' }, { label: 'A group of lines, similar to a paragraph in prose', value: 'b', correct: true }, { label: 'The title', value: 'c' }, { label: 'The last line', value: 'd' }], correctAnswer: 'b', explanation: 'Stanzas organize poems into sections. A 4-line stanza is a quatrain, a 2-line stanza is a couplet.', outcomeCode: 'ELA.6.TF.5', difficulty: 1 },
    { id: 'u5-l1-q2', questionText: 'FREE VERSE poetry:', options: [{ label: 'Must rhyme', value: 'a' }, { label: 'Does NOT follow a regular rhyme scheme or meter, but still uses poetic techniques', value: 'b', correct: true }, { label: 'Has exactly 14 lines', value: 'c' }, { label: 'Is written in paragraphs', value: 'd' }], correctAnswer: 'b', explanation: 'Free verse is "free" from rhyme and meter rules. It still uses imagery, metaphor, repetition, and line breaks to create meaning.', outcomeCode: 'ELA.6.TF.5', difficulty: 1 },
    { id: 'u5-l1-q3', questionText: 'In "Where I\'m From," the phrase "it tasted like beets" is an example of:', options: [{ label: 'Rhyme scheme', value: 'a' }, { label: 'IMAGERY — a vivid sensory detail (taste) that helps the reader experience the poem', value: 'b', correct: true }, { label: 'Meter', value: 'c' }, { label: 'A stanza break', value: 'd' }], correctAnswer: 'b', explanation: 'Imagery creates sensory experiences. "Tasted like beets" appeals to taste, making the dirt feel real and specific.', outcomeCode: 'ELA.6.VL.2', difficulty: 1 },
    { id: 'u5-l1-q4', questionText: 'RHYME SCHEME is labeled using:', options: [{ label: 'Numbers (1, 2, 3)', value: 'a' }, { label: 'Letters — matching letters for matching end sounds (ABAB, AABB)', value: 'b', correct: true }, { label: 'Colors', value: 'c' }, { label: 'Symbols', value: 'd' }], correctAnswer: 'b', explanation: 'Each new end sound gets a new letter. Lines that rhyme share the same letter: A rhymes with A, B rhymes with B.', outcomeCode: 'ELA.6.TF.5', difficulty: 1 },
    { id: 'u5-l1-q5', questionText: 'The REPETITION of "I am from" in the anchor poem creates:', options: [{ label: 'Confusion', value: 'a' }, { label: 'A rhythmic structure that unifies the poem and builds emotional momentum', value: 'b', correct: true }, { label: 'A rhyme scheme', value: 'c' }, { label: 'Nothing significant', value: 'd' }], correctAnswer: 'b', explanation: 'Repetition in poetry creates rhythm, emphasis, and emotional build. Each "I am from" adds a new layer of identity while keeping the poem unified.', outcomeCode: 'ELA.6.TF.5', difficulty: 2 },
    { id: 'u5-l1-q6', questionText: '"Whose long gone limbs I remember as if they were my own" is an example of:', options: [{ label: 'A literal description', value: 'a' }, { label: 'METAPHOR — comparing tree limbs to human limbs to express deep personal connection', value: 'b', correct: true }, { label: 'A fact', value: 'c' }, { label: 'Rhyme', value: 'd' }], correctAnswer: 'b', explanation: 'The poet compares tree branches ("limbs") to her own arms/legs — creating a metaphor that shows how deeply connected she feels to this place.', outcomeCode: 'ELA.6.VL.2', difficulty: 2 },
    { id: 'u5-l1-q7', questionText: 'You can INFER from the "Where I\'m From" poem that the speaker:', options: [{ label: 'Dislikes their childhood home', value: 'a' }, { label: 'Has deep, sensory memories of their childhood environment and feels emotionally connected to it', value: 'b', correct: true }, { label: 'Has never lived anywhere', value: 'c' }, { label: 'Is writing a science report', value: 'd' }], correctAnswer: 'b', explanation: 'The specific sensory details (taste, sight, texture) and emotional language ("as if they were my own") show deep attachment and vivid memory.', outcomeCode: 'ELA.6.RC.1', difficulty: 2 },
    { id: 'u5-l1-q8', questionText: 'METER in poetry refers to:', options: [{ label: 'How long the poem is', value: 'a' }, { label: 'The rhythmic pattern of stressed and unstressed syllables', value: 'b', correct: true }, { label: 'The number of stanzas', value: 'c' }, { label: 'The topic of the poem', value: 'd' }], correctAnswer: 'b', explanation: 'Meter is the "beat" of a poem — the pattern of stressed (strong) and unstressed (soft) syllables. Free verse doesn\'t use regular meter.', outcomeCode: 'ELA.6.TF.5', difficulty: 1 },
  ];
  for (const q of l1Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L1, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L1: ${l1Qs.length} questions`);

  // L2: Figurative Language Deep Dive — VL.2, TF.5, Review: VL.1, VL.3
  const L2 = 'g6-ela-u5-l2';
  const l2Blocks = [
    { id: 'u5-l2-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>The Tools of the Poet</h3><p>Figurative language is when words are used in non-literal ways to create vivid pictures, emotions, and connections. It is the poet\'s toolkit.</p>' } },
    { id: 'u5-l2-learn-2', section: 'LEARN', blockType: 'VOCABULARY', order: 2, content: { terms: [{ term: 'Metaphor', definition: 'A direct comparison saying one thing IS another (no "like" or "as").', example: '"Life is a journey." "Time is money." "Her voice was velvet."' }, { term: 'Simile', definition: 'A comparison using "like" or "as."', example: '"Fast as lightning." "Her smile was like sunshine."' }, { term: 'Personification', definition: 'Giving human qualities to non-human things.', example: '"The wind whispered." "The stars danced." "Time waits for no one."' }, { term: 'Symbolism', definition: 'Using an object or image to represent a bigger idea.', example: 'A dove = peace. A storm = conflict. A road = life choices.' }, { term: 'Alliteration', definition: 'Repeating the same consonant sound at the beginning of nearby words.', example: '"Peter Piper picked a peck of pickled peppers."' }, { term: 'Onomatopoeia', definition: 'Words that sound like what they describe.', example: '"Buzz, crash, sizzle, whisper, bang."' }] } },
    { id: 'u5-l2-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Extended Metaphor</h3><p>An <strong>extended metaphor</strong> carries a comparison throughout an entire poem or passage — not just one line.</p><blockquote style="border-left:3px solid #10b981;padding:12px 16px;margin:12px 0;color:#475569;font-style:italic">"Hope is the thing with feathers<br>That perches in the soul,<br>And sings the tune without the words,<br>And never stops at all."<br><br>— Emily Dickinson</blockquote><p>The entire poem compares hope to a bird: it has feathers, perches, sings, and endures. This is an extended metaphor.</p>' } },
    { id: 'u5-l2-learn-4', section: 'LEARN', blockType: 'MICRO_CHECK', order: 4, content: { question: '"The stars danced across the sky" is an example of:', options: [{ label: 'Simile — uses "like" or "as"', value: 'a' }, { label: 'Personification — giving human quality (dancing) to non-human things (stars)', value: 'b', correct: true }, { label: 'Onomatopoeia', value: 'c' }], explanation: 'Stars can\'t literally dance — that\'s a human action. Giving human qualities to non-human things is personification.' } },
    { id: 'u5-l2-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Identify the figurative language technique in each example:', pairs: [{ left: '"Her laughter was music to my ears"', right: 'Metaphor' }, { left: '"The tree groaned in the wind"', right: 'Personification' }, { left: '"He ran like a cheetah"', right: 'Simile' }, { left: '"The buzz of the bees filled the garden"', right: 'Onomatopoeia' }, { left: '"Sally sells seashells by the seashore"', right: 'Alliteration' }, { left: '"The broken mirror represented their shattered friendship"', right: 'Symbolism' }] } },
    { id: 'u5-l2-prac-2', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 2, content: { prompt: '1. Read Emily Dickinson\'s poem above. Explain how "hope" is compared to a bird. What does the extended metaphor help you understand about hope?\n2. Write your OWN extended metaphor: Choose an emotion (fear, joy, loneliness, curiosity) and compare it to an animal or natural force. Write 4–6 lines developing the comparison.', minLength: 40 } },
    { id: 'u5-l2-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Why do writers use figurative language instead of just saying things literally? What does figurative language add to a text that plain language cannot?', minLength: 30 } },
  ];
  for (const b of l2Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L2, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L2: ${l2Blocks.length} blocks`);

  const l2Qs = [
    { id: 'u5-l2-q1', questionText: 'A METAPHOR is:', options: [{ label: 'A comparison using "like" or "as"', value: 'a' }, { label: 'A direct comparison saying one thing IS another, without "like" or "as"', value: 'b', correct: true }, { label: 'A word that sounds like what it describes', value: 'c' }, { label: 'The pattern of rhymes', value: 'd' }], correctAnswer: 'b', explanation: 'Metaphor: "Life IS a journey." Simile: "Life is LIKE a journey." The difference is directness.', outcomeCode: 'ELA.6.VL.2', difficulty: 1 },
    { id: 'u5-l2-q2', questionText: '"The wind whispered through the trees" is an example of:', options: [{ label: 'Simile', value: 'a' }, { label: 'Personification — the wind is given the human ability to whisper', value: 'b', correct: true }, { label: 'Alliteration', value: 'c' }, { label: 'Symbolism', value: 'd' }], correctAnswer: 'b', explanation: 'Wind can\'t literally whisper. Giving it a human voice is personification — making the natural world feel alive and expressive.', outcomeCode: 'ELA.6.VL.2', difficulty: 1 },
    { id: 'u5-l2-q3', questionText: 'An EXTENDED METAPHOR:', options: [{ label: 'Uses "like" in every line', value: 'a' }, { label: 'Carries one comparison throughout an entire poem or passage', value: 'b', correct: true }, { label: 'Is only one line long', value: 'c' }, { label: 'Never uses imagery', value: 'd' }], correctAnswer: 'b', explanation: 'Dickinson compares hope to a bird across the ENTIRE poem — it perches, sings, and endures. That sustained comparison is an extended metaphor.', outcomeCode: 'ELA.6.TF.5', difficulty: 2 },
    { id: 'u5-l2-q4', questionText: '"Buzz, crash, sizzle" are examples of:', options: [{ label: 'Metaphor', value: 'a' }, { label: 'ONOMATOPOEIA — words that sound like what they describe', value: 'b', correct: true }, { label: 'Simile', value: 'c' }, { label: 'Symbolism', value: 'd' }], correctAnswer: 'b', explanation: 'Onomatopoeia = words whose pronunciation imitates the sound they describe. Buzz sounds like buzzing.', outcomeCode: 'ELA.6.VL.2', difficulty: 1 },
    { id: 'u5-l2-q5', questionText: 'SYMBOLISM is:', options: [{ label: 'Saying something is "like" something else', value: 'a' }, { label: 'Using a concrete object or image to represent a bigger, abstract idea', value: 'b', correct: true }, { label: 'Repeating a consonant sound', value: 'c' }, { label: 'Using words that sound like sounds', value: 'd' }], correctAnswer: 'b', explanation: 'A dove symbolizes peace. A storm symbolizes conflict. The concrete object represents something abstract that\'s harder to show directly.', outcomeCode: 'ELA.6.VL.2', difficulty: 1 },
    { id: 'u5-l2-q6', questionText: 'ALLITERATION is:', options: [{ label: 'Words from Latin roots', value: 'a' }, { label: 'Repeating the same consonant sound at the beginning of nearby words', value: 'b', correct: true }, { label: 'A type of rhyme scheme', value: 'c' }, { label: 'A comparison', value: 'd' }], correctAnswer: 'b', explanation: '"Sally sells seashells" = repeated "s" sound. Alliteration creates musicality and draws attention to key phrases.', outcomeCode: 'ELA.6.VL.2', difficulty: 1 },
    { id: 'u5-l2-q7', questionText: 'The Latin root "similis" means "similar." This connects to which figurative language technique?', options: [{ label: 'Metaphor', value: 'a' }, { label: 'SIMILE — a comparison using "like" or "as" (showing similarity)', value: 'b', correct: true }, { label: 'Onomatopoeia', value: 'c' }, { label: 'Personification', value: 'd' }], correctAnswer: 'b', explanation: 'Simile comes from Latin "similis" (similar). Similes show similarity between two things using "like" or "as."', outcomeCode: 'ELA.6.VL.1', difficulty: 2 },
    { id: 'u5-l2-q8', questionText: 'Figurative language makes writing more effective because:', options: [{ label: 'It adds word count', value: 'a' }, { label: 'It creates vivid images, emotional connections, and deeper meaning beyond literal words', value: 'b', correct: true }, { label: 'It confuses readers', value: 'c' }, { label: 'It only works in poetry', value: 'd' }], correctAnswer: 'b', explanation: 'Figurative language engages the reader\'s imagination and emotions. "Her voice was velvet" creates a sensation that "her voice was pleasant" cannot.', outcomeCode: 'ELA.6.VL.2', difficulty: 2 },
  ];
  for (const q of l2Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L2, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L2: ${l2Qs.length} questions`);

  // L3: Drama & Performance — TF.6, Review: TF.1, WC.4
  const L3 = 'g6-ela-u5-l3';
  const l3Blocks = [
    { id: 'u5-l3-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Drama: Literature for the Stage</h3><p>A <strong>play</strong> (drama) is a story written to be <em>performed</em>, not just read. Plays have unique features:</p><ul><li><strong>Dialogue:</strong> Characters speak directly — there is no narrator telling you what they think or feel</li><li><strong>Stage Directions:</strong> Instructions in [brackets] or (parentheses) that describe actions, setting, or tone</li><li><strong>Acts and Scenes:</strong> Plays are divided into acts (major sections) and scenes (smaller segments)</li></ul>' } },
    { id: 'u5-l3-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Comedy vs Tragedy</h3><table style="width:100%;border-collapse:collapse"><tr style="background:#f1f5f9"><th style="padding:8px;border:1px solid #e2e8f0">Feature</th><th style="padding:8px;border:1px solid #e2e8f0">Comedy</th><th style="padding:8px;border:1px solid #e2e8f0">Tragedy</th></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Tone</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Light, humorous, hopeful</td><td style="padding:8px;border:1px solid #e2e8f0">Serious, dark, sorrowful</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Ending</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Happy resolution, often marriage or reunion</td><td style="padding:8px;border:1px solid #e2e8f0">Downfall or death of the main character</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Hero</strong></td><td style="padding:8px;border:1px solid #e2e8f0">Ordinary person overcoming obstacles</td><td style="padding:8px;border:1px solid #e2e8f0">Noble character with a fatal flaw</td></tr><tr><td style="padding:8px;border:1px solid #e2e8f0"><strong>Purpose</strong></td><td style="padding:8px;border:1px solid #e2e8f0">To entertain and celebrate</td><td style="padding:8px;border:1px solid #e2e8f0">To evoke pity and reflection</td></tr></table>' } },
    { id: 'u5-l3-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>Anchor Scene</h3><blockquote style="border-left:3px solid #10b981;padding:12px 16px;margin:12px 0;color:#475569"><em>[A school hallway. ALEX stands nervously outside the principal\'s office, holding a crumpled paper.]</em><br><br><strong>ALEX:</strong> (to self, pacing) Okay, okay. You can do this. It\'s just... one speech. In front of the whole school. No big deal. <em>(laughs nervously)</em> Who am I kidding?<br><br><em>[JORDAN enters, carrying a stack of books.]</em><br><br><strong>JORDAN:</strong> Alex? What are you doing out here? You look like you\'ve seen a ghost.<br><br><strong>ALEX:</strong> Worse. I volunteered to give the assembly speech. <em>(holds up paper)</em> I have notes. But my hands are shaking so much I can barely read them.<br><br><strong>JORDAN:</strong> <em>(sets down books, faces Alex)</em> Hey. Look at me. You KNOW this stuff. Forget the paper. Just talk like you\'re talking to me right now.</blockquote>' } },
    { id: 'u5-l3-learn-4', section: 'LEARN', blockType: 'MICRO_CHECK', order: 4, content: { question: 'The bracketed text "[A school hallway. ALEX stands nervously...]" is an example of:', options: [{ label: 'Dialogue', value: 'a' }, { label: 'STAGE DIRECTIONS — instructions describing the setting, character actions, and tone', value: 'b', correct: true }, { label: 'The character\'s thoughts', value: 'c' }], explanation: 'Stage directions tell actors, directors, and readers what is happening physically — setting, movement, expression, tone. They appear in brackets or italics.' } },
    { id: 'u5-l3-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: '1. In the anchor scene, what can you tell about Alex\'s personality from dialogue alone (without the stage directions)?\n2. How do the STAGE DIRECTIONS add information that the dialogue doesn\'t?\n3. Is this scene leaning toward comedy or tragedy? Use specific evidence.\n4. Write a CONTINUATION of this scene (6–8 lines of dialogue with stage directions). What happens next?', minLength: 50 } },
    { id: 'u5-l3-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'How is reading a play different from reading a story? What extra skills do you need to "see" and "hear" a play in your mind while reading?', minLength: 30 } },
  ];
  for (const b of l3Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L3, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L3: ${l3Blocks.length} blocks`);

  const l3Qs = [
    { id: 'u5-l3-q1', questionText: 'STAGE DIRECTIONS in a play:', options: [{ label: 'Are spoken by the characters', value: 'a' }, { label: 'Describe the setting, character actions, and delivery cues — not spoken aloud', value: 'b', correct: true }, { label: 'Are always at the end', value: 'c' }, { label: 'Are optional', value: 'd' }], correctAnswer: 'b', explanation: 'Stage directions are instructions for actors, directors, and readers. They appear in brackets or italics and describe what is happening physically.', outcomeCode: 'ELA.6.TF.6', difficulty: 1 },
    { id: 'u5-l3-q2', questionText: 'In drama, the story is told primarily through:', options: [{ label: 'A narrator describing events', value: 'a' }, { label: 'DIALOGUE — characters speaking directly to each other', value: 'b', correct: true }, { label: 'Author commentary', value: 'c' }, { label: 'Only stage directions', value: 'd' }], correctAnswer: 'b', explanation: 'Unlike prose, plays have no narrator. Everything the audience learns comes through what characters SAY and DO.', outcomeCode: 'ELA.6.TF.6', difficulty: 1 },
    { id: 'u5-l3-q3', questionText: 'A TRAGEDY typically ends with:', options: [{ label: 'A happy wedding', value: 'a' }, { label: 'The downfall or death of the main character', value: 'b', correct: true }, { label: 'A comedy show', value: 'c' }, { label: 'Nothing happening', value: 'd' }], correctAnswer: 'b', explanation: 'Tragedies follow a noble character whose fatal flaw leads to their downfall, creating pity and reflection in the audience.', outcomeCode: 'ELA.6.TF.6', difficulty: 1 },
    { id: 'u5-l3-q4', questionText: 'Plays are divided into:', options: [{ label: 'Chapters and paragraphs', value: 'a' }, { label: 'Acts (major sections) and scenes (smaller segments)', value: 'b', correct: true }, { label: 'Stanzas', value: 'c' }, { label: 'Only one section', value: 'd' }], correctAnswer: 'b', explanation: 'Acts are like the big chapters of a play. Scenes are smaller divisions within acts, often marked by a change in time or location.', outcomeCode: 'ELA.6.TF.6', difficulty: 1 },
    { id: 'u5-l3-q5', questionText: 'In the anchor scene, Jordan says "Forget the paper. Just talk like you\'re talking to me." This reveals Jordan\'s character as:', options: [{ label: 'Unhelpful', value: 'a' }, { label: 'Supportive, calm, and encouraging — a good friend who builds confidence', value: 'b', correct: true }, { label: 'Nervous', value: 'c' }, { label: 'Angry', value: 'd' }], correctAnswer: 'b', explanation: 'Jordan puts down their books (non-verbal care), faces Alex, and gives practical advice. All through dialogue and action — no narrator needed.', outcomeCode: 'ELA.6.TF.1', difficulty: 2 },
    { id: 'u5-l3-q6', questionText: 'In drama, how do we learn what a character is THINKING?', options: [{ label: 'The narrator tells us', value: 'a' }, { label: 'Through what they SAY (dialogue), what they DO (stage directions), and how they interact with others', value: 'b', correct: true }, { label: 'Through thought bubbles', value: 'c' }, { label: 'It\'s impossible in drama', value: 'd' }], correctAnswer: 'b', explanation: 'Drama shows character through ACTION and SPEECH. Alex pacing and talking to himself reveals nervousness without anyone narrating it.', outcomeCode: 'ELA.6.TF.6', difficulty: 2 },
    { id: 'u5-l3-q7', questionText: 'Writing a scene continuation requires:', options: [{ label: 'Only dialogue, no stage directions', value: 'a' }, { label: 'Dialogue that reveals character AND stage directions that show action and tone', value: 'b', correct: true }, { label: 'A narrator to explain everything', value: 'c' }, { label: 'Only description', value: 'd' }], correctAnswer: 'b', explanation: 'Drama writing needs both: dialogue carries the story, stage directions create the visual and emotional world around the words.', outcomeCode: 'ELA.6.WC.4', difficulty: 2 },
    { id: 'u5-l3-q8', questionText: 'A COMEDY typically features:', options: [{ label: 'Only serious themes', value: 'a' }, { label: 'A lighthearted tone, humorous situations, and a happy resolution', value: 'b', correct: true }, { label: 'The death of the main character', value: 'c' }, { label: 'Only tragedies', value: 'd' }], correctAnswer: 'b', explanation: 'Comedies use humor, misunderstandings, and lightheartedness, ending with resolution and celebration.', outcomeCode: 'ELA.6.TF.6', difficulty: 1 },
  ];
  for (const q of l3Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L3, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L3: ${l3Qs.length} questions`);

  // L4: Land as Text (FNMI) — TF.7, OC.1, Review: TR.2, RC.2
  const L4 = 'g6-ela-u5-l4';
  const l4Blocks = [
    { id: 'u5-l4-learn-1', section: 'LEARN', blockType: 'TEXT', order: 1, content: { html: '<h3>Land as Text: Indigenous Ways of Knowing</h3><p>In many Indigenous cultures, <strong>land is not just a setting — it is a teacher, a text, a library.</strong> The land holds stories, knowledge, history, and relationships.</p><p>"Land as text" means reading the natural world the way you would read a book — observing patterns, listening to changes, and understanding what the land communicates.</p><p>This is called <strong>land literacy</strong> — the ability to read, understand, and learn from the land.</p>' } },
    { id: 'u5-l4-learn-2', section: 'LEARN', blockType: 'TEXT', order: 2, content: { html: '<h3>Oral Tradition and Communication Protocols</h3><p>Many Indigenous peoples use <strong>oral tradition</strong> — passing knowledge through spoken stories, songs, and ceremonies rather than written text.</p><p><strong>Communication protocols</strong> in Indigenous contexts include:</p><ul><li><strong>Listening first:</strong> Respectful silence and deep listening before responding</li><li><strong>Storytelling as teaching:</strong> Stories carry lessons, laws, and values</li><li><strong>Reciprocity:</strong> Communication is a relationship — you give and receive</li><li><strong>Connection to place:</strong> Stories are connected to specific places and seasons</li></ul><p>These protocols remind us that communication is not just about <em>words</em> — it is about <em>relationships</em> with people, land, and knowledge.</p>' } },
    { id: 'u5-l4-learn-3', section: 'LEARN', blockType: 'MICRO_CHECK', order: 3, content: { question: '"Land as text" means:', options: [{ label: 'Writing words on the ground', value: 'a' }, { label: 'Understanding land as a source of knowledge, story, and meaning — reading the natural world like a text', value: 'b', correct: true }, { label: 'Only studying geography', value: 'c' }], explanation: 'Land literacy sees the natural world as a teacher. The changing seasons, animal patterns, plant growth, and waterways all carry information and meaning.' } },
    { id: 'u5-l4-prac-1', section: 'PRACTICE', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: '1. What does "land as text" mean? Explain in your own words.\n2. How is oral tradition SIMILAR to and DIFFERENT from written tradition?\n3. Go outside (or look out a window). Describe what the land is "telling" you right now — what season, what weather patterns, what living things are active? Write 4–6 sentences practicing "reading" the land.\n4. Why is it important to learn about Indigenous communication protocols even if they are different from your own?', minLength: 50 } },
    { id: 'u5-l4-refl-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'How does thinking about "land as text" change the way you see the natural world around you? What can we learn from the land that we cannot learn from books?', minLength: 30 } },
  ];
  for (const b of l4Blocks) { await prisma.lessonBlock.create({ data: { id: b.id, lessonId: L4, section: b.section, blockType: b.blockType, content: b.content, order: b.order } }); }
  console.log(`L4: ${l4Blocks.length} blocks`);

  const l4Qs = [
    { id: 'u5-l4-q1', questionText: '"Land as text" means:', options: [{ label: 'Writing on the land', value: 'a' }, { label: 'Understanding the natural world as a source of knowledge, story, and meaning', value: 'b', correct: true }, { label: 'Only studying maps', value: 'c' }, { label: 'Ignoring the natural world', value: 'd' }], correctAnswer: 'b', explanation: 'Land literacy means reading the land the way you read a book — observing, interpreting, and learning from the natural world.', outcomeCode: 'ELA.6.TF.7', difficulty: 1 },
    { id: 'u5-l4-q2', questionText: 'ORAL TRADITION is:', options: [{ label: 'Writing stories down', value: 'a' }, { label: 'Passing knowledge through spoken stories, songs, and ceremonies across generations', value: 'b', correct: true }, { label: 'Reading textbooks', value: 'c' }, { label: 'Email communication', value: 'd' }], correctAnswer: 'b', explanation: 'Oral tradition transmits knowledge, history, laws, and values through spoken word and ceremony — passed from generation to generation.', outcomeCode: 'ELA.6.OC.1', difficulty: 1 },
    { id: 'u5-l4-q3', questionText: 'Indigenous communication protocols include:', options: [{ label: 'Speaking as quickly as possible', value: 'a' }, { label: 'Listening first, storytelling as teaching, reciprocity, and connection to place', value: 'b', correct: true }, { label: 'Only writing', value: 'c' }, { label: 'Ignoring the speaker', value: 'd' }], correctAnswer: 'b', explanation: 'These protocols emphasize respectful relationships, deep listening, and the understanding that communication connects people to each other and to the land.', outcomeCode: 'ELA.6.OC.1', difficulty: 1 },
    { id: 'u5-l4-q4', questionText: 'Storytelling in Indigenous oral tradition serves to:', options: [{ label: 'Only entertain children', value: 'a' }, { label: 'Carry lessons, laws, values, and history from one generation to the next', value: 'b', correct: true }, { label: 'Replace written texts', value: 'c' }, { label: 'Tell jokes', value: 'd' }], correctAnswer: 'b', explanation: 'Stories are pedagogy — they teach. Each story carries layered meanings that unfold as the listener grows and returns to the story.', outcomeCode: 'ELA.6.OC.1', difficulty: 2 },
    { id: 'u5-l4-q5', questionText: 'Learning about Indigenous ways of knowing helps us:', options: [{ label: 'Ignore our own perspectives', value: 'a' }, { label: 'Understand different perspectives on knowledge, communication, and our relationship with the land', value: 'b', correct: true }, { label: 'Replace all other learning', value: 'c' }, { label: 'Only study history', value: 'd' }], correctAnswer: 'b', explanation: 'Understanding different ways of knowing broadens our perspective and develops empathy — core skills from Unit 4.', outcomeCode: 'ELA.6.TR.2', difficulty: 1 },
    { id: 'u5-l4-q6', questionText: 'A text-to-world connection between "land as text" and your own life might be:', options: [{ label: 'Memorizing facts about geography', value: 'a' }, { label: 'Noticing how changing seasons affect the world around you and recognizing that as a form of reading', value: 'b', correct: true }, { label: 'Ignoring nature', value: 'c' }, { label: 'Only reading books indoors', value: 'd' }], correctAnswer: 'b', explanation: 'Text-to-world connections link concepts to your lived experience. Noticing seasonal change is a form of "reading" the land.', outcomeCode: 'ELA.6.RC.2', difficulty: 2 },
    { id: 'u5-l4-q7', questionText: 'RECIPROCITY in communication means:', options: [{ label: 'Only one person speaks', value: 'a' }, { label: 'Communication is a relationship — you give AND receive', value: 'b', correct: true }, { label: 'Repeating what someone says', value: 'c' }, { label: 'Speaking louder', value: 'd' }], correctAnswer: 'b', explanation: 'Reciprocity means the relationship goes both ways. In communication, this means genuine exchange — not just one person talking and another passively listening.', outcomeCode: 'ELA.6.OC.1', difficulty: 1 },
    { id: 'u5-l4-q8', questionText: 'LAND LITERACY is:', options: [{ label: 'The ability to read maps', value: 'a' }, { label: 'The ability to read, understand, and learn from the natural world', value: 'b', correct: true }, { label: 'Spelling words correctly', value: 'c' }, { label: 'Only used in science class', value: 'd' }], correctAnswer: 'b', explanation: 'Land literacy is a holistic ability to observe, interpret, and learn from the land — reading ecosystems, seasons, and natural patterns as sources of knowledge.', outcomeCode: 'ELA.6.TF.7', difficulty: 1 },
  ];
  for (const q of l4Qs) { await prisma.quizQuestion.create({ data: { id: q.id, lessonId: L4, questionText: q.questionText, questionType: 'MULTIPLE_CHOICE', options: q.options, correctAnswer: q.correctAnswer, explanation: q.explanation, outcomeCode: q.outcomeCode, difficulty: q.difficulty } }); }
  console.log(`L4: ${l4Qs.length} questions`);

  console.log(`\n╔═══════════════════════════════════════════════╗\n║   ELA UNIT 5 (L1–L4) SEED COMPLETE          ║\n╠═══════════════════════════════════════════════╣\n║ Lessons:    4                                ║\n║ Blocks:     ${String(l1Blocks.length + l2Blocks.length + l3Blocks.length + l4Blocks.length).padStart(2)}                               ║\n║ Questions:  ${String(l1Qs.length + l2Qs.length + l3Qs.length + l4Qs.length).padStart(2)}                               ║\n╚═══════════════════════════════════════════════╝`);
}

main()
  .catch((e) => { console.error('❌ Seed error:', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); pool.end(); });
