// ============================================
// Seed Science Unit E L1-L3 — Planet Earth
// ============================================
// Run: npx tsx prisma/seed-sci-ue-l1-l3.ts

import { config } from 'dotenv';
config({ path: '.env.local' });
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function seed(ID: string, title: string, data: { lesson: Record<string, unknown>, blocks: Array<Record<string, unknown>>, questions: Array<Record<string, unknown>> }) {
  console.log(`\n🌍 Seeding ${title}...`);
  await prisma.lesson.update({ where: { id: ID }, data: data.lesson as any });
  await prisma.lessonBlock.deleteMany({ where: { lessonId: ID } });
  await prisma.quizQuestion.deleteMany({ where: { lessonId: ID } });
  for (const b of data.blocks) { await prisma.lessonBlock.create({ data: { ...b, lessonId: ID } as any }); }
  console.log(`  ✅ ${data.blocks.length} blocks`);
  for (const q of data.questions) { await prisma.quizQuestion.create({ data: { ...q, lessonId: ID } as any }); }
  console.log(`  ✅ ${data.questions.length} questions`);
}

const L1 = {
  lesson: { subjectMode: 'SCIENCE', estimatedMinutes: 45, learningGoal: 'Describe Earth\'s 4 layers, explain how scientists study the interior, classify rocks as igneous/sedimentary/metamorphic, and describe the rock cycle.', successCriteria: 'I can order Earth\'s layers, distinguish rock types, tell rocks from minerals, and draw the rock cycle.', materials: 'Science notebook', reflectionPrompt: 'What was the most interesting thing you learned about Earth\'s interior or rocks?', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
  blocks: [
    { id: 'ue-l1-learn-1', section: 'LEARN', blockType: 'VOCABULARY', order: 1, content: { terms: [{ term: 'Mineral', definition: 'A naturally occurring, non-living solid with a specific chemical makeup and crystal structure.', example: 'Quartz, feldspar, calcite.' }, { term: 'Rock', definition: 'A solid made of one or more minerals.', example: 'Granite (quartz + feldspar + mica).' }, { term: 'Igneous Rock', definition: 'Formed when molten rock (magma/lava) cools and hardens.', example: 'Granite (slow cool), basalt (fast cool).' }, { term: 'Sedimentary Rock', definition: 'Formed when sediment is compressed and cemented over time.', example: 'Sandstone, limestone.' }, { term: 'Metamorphic Rock', definition: 'Formed when existing rocks are changed by extreme heat and pressure.', example: 'Marble (from limestone), slate (from shale).' }, { term: 'Rock Cycle', definition: 'The continuous process by which rocks change from one type to another.', example: 'Granite → weathering → sandstone → heat/pressure → gneiss.' }, { term: 'Crust', definition: 'Earth\'s thin, solid outermost layer (5-70 km thick).', example: 'Continental and oceanic crust.' }, { term: 'Mantle', definition: 'Thick, hot layer beneath the crust (~2,900 km thick).', example: 'Semi-solid rock that flows slowly.' }] } },
    { id: 'ue-l1-learn-2', section: 'LEARN', blockType: 'VIDEO', order: 2, content: { url: 'https://www.youtube.com/embed/eXiVGEEPQ6c', title: 'What\'s Inside Earth?', transcript: 'Video exploring Earth\'s layers.' } },
    { id: 'ue-l1-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>🌍 Earth\'s Layers</h3><ul><li>🥚 <strong>Crust:</strong> 5-70 km thick. Thin rocky surface we live on. Thinnest under oceans.</li><li>🔥 <strong>Mantle:</strong> ~2,900 km. Hot semi-solid rock. Convection currents drive plate movement.</li><li>💧 <strong>Outer Core:</strong> ~2,200 km. Liquid iron and nickel. Creates Earth\'s magnetic field.</li><li>⚡ <strong>Inner Core:</strong> ~1,200 km radius. Solid iron/nickel at ~5,400°C — kept solid by extreme pressure.</li></ul><p><strong>Alberta:</strong> The Canadian Rockies formed when plates collided, pushing crust upward. Banff and Jasper rocks contain fossils of ancient sea creatures!</p>' } },
    { id: 'ue-l1-learn-4', section: 'LEARN', blockType: 'TEXT', order: 4, content: { html: '<h3>🪨 Three Rock Types</h3><table><thead><tr><th>Type</th><th>How It Forms</th><th>Examples</th></tr></thead><tbody><tr><td>🌋 Igneous</td><td>Cooled magma/lava. Fast=small crystals, slow=large</td><td>Granite, basalt</td></tr><tr><td>🏖️ Sedimentary</td><td>Compressed sediment layers. Often has fossils</td><td>Sandstone, limestone, shale</td></tr><tr><td>♨️ Metamorphic</td><td>Changed by heat & pressure</td><td>Marble, slate, gneiss</td></tr></tbody></table><p><strong>Rock Cycle:</strong> Melting→cooling creates igneous. Weathering→compaction creates sedimentary. Heat+pressure creates metamorphic. The cycle has no beginning or end.</p><p><strong>Alberta:</strong> Drumheller hoodoos are sedimentary rock — layers of sand/silt/clay with dinosaur bones!</p>' } },
    { id: 'ue-l1-learn-5', section: 'LEARN', blockType: 'VIDEO', order: 5, content: { url: 'https://www.youtube.com/embed/TbHB7xUjMIk', title: 'The Rock Cycle', transcript: 'Video explaining how rocks transform.' } },
    { id: 'ue-l1-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Match each rock to its type:', pairs: [{ left: 'Granite (large crystals, cooled slowly underground)', right: 'Igneous' }, { left: 'Sandstone (visible layers, gritty, may have fossils)', right: 'Sedimentary' }, { left: 'Marble (smooth, swirled, formed from limestone under pressure)', right: 'Metamorphic' }, { left: 'Basalt (dark, fine-grained, cooled from lava)', right: 'Igneous' }, { left: 'Limestone (contains shell fossils, layered)', right: 'Sedimentary' }, { left: 'Slate (flat/flaky, formed from shale under pressure)', right: 'Metamorphic' }] } },
    { id: 'ue-l1-reflect-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Explain how one type of rock can become a completely different type. Use at least two vocabulary words and mention a specific example (like limestone → marble).', minLength: 60, rubricHint: 'Names specific transformation (e.g., limestone→marble). Uses vocabulary correctly. Explains the process.', teacherReviewRequired: false } },
  ],
  questions: [
    { id: 'ue-l1-q1', questionText: 'Earth\'s layers from surface to centre are:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Mantle, crust, outer core, inner core', value: 'a' }, { label: 'Crust, mantle, outer core, inner core', value: 'b', correct: true }, { label: 'Inner core, outer core, mantle, crust', value: 'c' }, { label: 'Crust, outer core, mantle, inner core', value: 'd' }], correctAnswer: 'b', explanation: 'The correct order is crust → mantle → outer core → inner core.', outcomeCode: 'SCI.7.E.1.1', difficulty: 1 },
    { id: 'ue-l1-q2', questionText: 'The thinnest layer of Earth is the:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Mantle', value: 'a' }, { label: 'Inner core', value: 'b' }, { label: 'Crust', value: 'c', correct: true }, { label: 'Outer core', value: 'd' }], correctAnswer: 'c', explanation: 'Earth\'s crust is only 5-70 km thick — the thinnest layer.', outcomeCode: 'SCI.7.E.1.1', difficulty: 1 },
    { id: 'ue-l1-q3', questionText: 'Which rock type forms when magma cools and hardens?', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Sedimentary', value: 'a' }, { label: 'Metamorphic', value: 'b' }, { label: 'Igneous', value: 'c', correct: true }, { label: 'Mineral', value: 'd' }], correctAnswer: 'c', explanation: 'Igneous rocks form from cooled and solidified magma or lava.', outcomeCode: 'SCI.7.E.1.2', difficulty: 1 },
    { id: 'ue-l1-q4', questionText: 'A rock contains visible layers and a fossil. It is most likely:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Igneous', value: 'a' }, { label: 'Sedimentary', value: 'b', correct: true }, { label: 'Metamorphic', value: 'c' }, { label: 'A mineral', value: 'd' }], correctAnswer: 'b', explanation: 'Sedimentary rocks form in layers and often contain fossils.', outcomeCode: 'SCI.7.E.1.2', difficulty: 1 },
    { id: 'ue-l1-q5', questionText: 'Scientists learn about Earth\'s interior primarily by studying:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Digging to the core', value: 'a' }, { label: 'Seismic waves from earthquakes', value: 'b', correct: true }, { label: 'Satellite photos', value: 'c' }, { label: 'Ocean currents', value: 'd' }], correctAnswer: 'b', explanation: 'Seismic waves change speed and direction through different layers, revealing composition.', outcomeCode: 'SCI.7.E.1.1', difficulty: 1 },
    { id: 'ue-l1-q6', questionText: 'The difference between a rock and a mineral is:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Rocks are bigger', value: 'a' }, { label: 'A mineral is a single substance; a rock is made of minerals', value: 'b', correct: true }, { label: 'No difference', value: 'c' }, { label: 'Minerals are man-made', value: 'd' }], correctAnswer: 'b', explanation: 'Minerals are single substances (like ingredients); rocks combine them (like a cake).', outcomeCode: 'SCI.7.E.1.2', difficulty: 1 },
    { id: 'ue-l1-q7', questionText: 'Limestone changed by heat and pressure becomes:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Granite', value: 'a' }, { label: 'Sandstone', value: 'b' }, { label: 'Marble', value: 'c', correct: true }, { label: 'Basalt', value: 'd' }], correctAnswer: 'c', explanation: 'Marble is the metamorphic version of limestone.', outcomeCode: 'SCI.7.E.1.2', difficulty: 2 },
    { id: 'ue-l1-q8', questionText: 'In the rock cycle, sedimentary rock can become igneous by:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Compaction', value: 'a' }, { label: 'Weathering only', value: 'b' }, { label: 'Melting into magma, then cooling', value: 'c', correct: true }, { label: 'Adding fossils', value: 'd' }], correctAnswer: 'c', explanation: 'Any rock can melt into magma; when magma cools, it forms igneous rock.', outcomeCode: 'SCI.7.E.1.2', difficulty: 2 },
  ],
};

const L2 = {
  lesson: { subjectMode: 'SCIENCE', estimatedMinutes: 45, learningGoal: 'Explain plate tectonics and convection currents, describe 3 boundary types and their geological effects, and explain evidence for continental drift.', successCriteria: 'I can classify boundary types, predict geological events, explain Wegener\'s evidence, and connect the Rockies to plate tectonics.', materials: 'Science notebook', reflectionPrompt: 'What do you think Earth will look like in 250 million years?', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
  blocks: [
    { id: 'ue-l2-learn-1', section: 'LEARN', blockType: 'VOCABULARY', order: 1, content: { terms: [{ term: 'Tectonic Plate', definition: 'A massive slab of Earth\'s lithosphere floating on the mantle. About 15 major plates.', example: 'North American Plate, Pacific Plate.' }, { term: 'Convergent Boundary', definition: 'Where plates push toward each other. Can form mountains, volcanoes, or trenches.', example: 'The Rockies, Himalayas, Mariana Trench.' }, { term: 'Divergent Boundary', definition: 'Where plates pull apart. Magma fills the gap, creating new crust.', example: 'Mid-Atlantic Ridge, East African Rift.' }, { term: 'Transform Boundary', definition: 'Where plates slide past each other, causing earthquakes.', example: 'San Andreas Fault.' }, { term: 'Subduction', definition: 'When a denser plate dives under a lighter plate, often causing volcanoes.', example: 'Pacific plate subducting under North American plate.' }, { term: 'Convection Current', definition: 'Circular flow in the mantle driven by heat — the engine of plate movement.', example: 'Hot mantle rises, cools near surface, sinks back.' }] } },
    { id: 'ue-l2-learn-2', section: 'LEARN', blockType: 'VIDEO', order: 2, content: { url: 'https://www.youtube.com/embed/kwfNGatxUJI', title: 'How Earth\'s Plates Move', transcript: 'Video explaining plate tectonics.' } },
    { id: 'ue-l2-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>🗺️ Three Types of Plate Boundaries</h3><table><thead><tr><th>Type</th><th>Motion</th><th>Result</th></tr></thead><tbody><tr><td>⬆️ Convergent</td><td>Plates push together</td><td>Mountains, volcanoes, trenches, subduction</td></tr><tr><td>⬇️ Divergent</td><td>Plates pull apart</td><td>New crust, mid-ocean ridges, rift valleys</td></tr><tr><td>↔️ Transform</td><td>Plates slide past</td><td>Earthquakes along fault lines</td></tr></tbody></table><p><strong>Alberta:</strong> The Rocky Mountains formed millions of years ago when the Pacific and North American plates collided. The immense pressure crumpled Earth\'s crust upward!</p>' } },
    { id: 'ue-l2-learn-4', section: 'LEARN', blockType: 'TEXT', order: 4, content: { html: '<h3>🧩 Evidence for Continental Drift (Wegener, 1912)</h3><ul><li>🧩 <strong>Puzzle Fit:</strong> Continents fit together like puzzle pieces (Africa + South America)</li><li>🦕 <strong>Matching Fossils:</strong> Same species found on now-separated continents</li><li>🪨 <strong>Rock Matches:</strong> Same rock types and mountain chains line up across continents</li><li>❄️ <strong>Glacial Evidence:</strong> Glacial scratches found in now-tropical areas that were once near the poles</li></ul><p><strong>Pangaea</strong> was the supercontinent where all land was joined ~300 million years ago.</p>' } },
    { id: 'ue-l2-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Classify each scenario by plate boundary type:', pairs: [{ left: 'Two continental plates collide, forming mountains', right: 'Convergent' }, { left: 'New ocean floor forms at a mid-ocean ridge', right: 'Divergent' }, { left: 'San Andreas Fault causes earthquakes', right: 'Transform' }, { left: 'Pacific plate slides under the North American plate', right: 'Convergent (subduction)' }, { left: 'Iceland sits on a spreading ridge', right: 'Divergent' }] } },
    { id: 'ue-l2-reflect-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'A student asks: "If continents move so slowly, how do we know they\'ve moved at all?" Explain the evidence for continental drift. Mention the Rocky Mountains. Use at least 3 vocabulary words.', minLength: 80, rubricHint: 'Names 3+ evidence types. Uses vocabulary. Connects Rockies to convergent boundary.', teacherReviewRequired: false } },
  ],
  questions: [
    { id: 'ue-l2-q1', questionText: 'Tectonic plates move because of:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Gravity pulling them', value: 'a' }, { label: 'Convection currents in the mantle', value: 'b', correct: true }, { label: 'Wind on the surface', value: 'c' }, { label: 'Ocean tides', value: 'd' }], correctAnswer: 'b', explanation: 'Hot mantle rock rises, cools, and sinks — this convection drags plates along.', outcomeCode: 'SCI.7.E.2.1', difficulty: 1 },
    { id: 'ue-l2-q2', questionText: 'At a convergent boundary, plates:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Pull apart', value: 'a' }, { label: 'Slide past each other', value: 'b' }, { label: 'Push toward each other', value: 'c', correct: true }, { label: 'Don\'t move', value: 'd' }], correctAnswer: 'c', explanation: 'Convergent = coming together. Can form mountains, volcanoes, or trenches.', outcomeCode: 'SCI.7.E.2.1', difficulty: 1 },
    { id: 'ue-l2-q3', questionText: 'The Rocky Mountains formed from:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Erosion', value: 'a' }, { label: 'Divergent boundary', value: 'b' }, { label: 'Convergent boundary (plate collision)', value: 'c', correct: true }, { label: 'A meteorite', value: 'd' }], correctAnswer: 'c', explanation: 'Plate collision crumpled the crust upward, forming the Rockies.', outcomeCode: 'SCI.7.E.2.1', difficulty: 1 },
    { id: 'ue-l2-q4', questionText: 'Pangaea was:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'An ancient ocean', value: 'a' }, { label: 'A supercontinent where all land was joined', value: 'b', correct: true }, { label: 'A type of rock', value: 'c' }, { label: 'A volcano', value: 'd' }], correctAnswer: 'b', explanation: 'Pangaea was the single supercontinent ~300 million years ago.', outcomeCode: 'SCI.7.E.2.2', difficulty: 1 },
    { id: 'ue-l2-q5', questionText: 'Matching fossils on different continents suggest:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Animals could fly', value: 'a' }, { label: 'The continents were once connected', value: 'b', correct: true }, { label: 'Fossils can swim', value: 'c' }, { label: 'Coincidence', value: 'd' }], correctAnswer: 'b', explanation: 'Same species on separated continents = they were once connected before drifting.', outcomeCode: 'SCI.7.E.2.2', difficulty: 1 },
    { id: 'ue-l2-q6', questionText: 'At a divergent boundary:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Mountains form', value: 'a' }, { label: 'New crust is created as plates pull apart', value: 'b', correct: true }, { label: 'Plates slide sideways', value: 'c' }, { label: 'Nothing happens', value: 'd' }], correctAnswer: 'b', explanation: 'Divergent boundaries create new crust as magma rises to fill the gap.', outcomeCode: 'SCI.7.E.2.1', difficulty: 1 },
    { id: 'ue-l2-q7', questionText: 'Transform boundaries mainly cause:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Volcanoes', value: 'a' }, { label: 'Mountains', value: 'b' }, { label: 'Earthquakes', value: 'c', correct: true }, { label: 'New crust', value: 'd' }], correctAnswer: 'c', explanation: 'Plates grind past each other, building pressure that releases as earthquakes.', outcomeCode: 'SCI.7.E.2.1', difficulty: 1 },
    { id: 'ue-l2-q8', questionText: 'Subduction occurs when:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'A plate rises', value: 'a' }, { label: 'A denser plate dives under a lighter one', value: 'b', correct: true }, { label: 'Plates move sideways', value: 'c' }, { label: 'Nothing happens', value: 'd' }], correctAnswer: 'b', explanation: 'Subduction = a denser oceanic plate sinks beneath a lighter continental plate.', outcomeCode: 'SCI.7.E.2.1', difficulty: 2 },
  ],
};

const L3 = {
  lesson: { subjectMode: 'SCIENCE', estimatedMinutes: 45, learningGoal: 'Describe how rocks transform between igneous, sedimentary, and metamorphic; identify processes driving the rock cycle; connect the rock cycle to plate tectonics.', successCriteria: 'I can trace a rock through all 3 types, name the process for each transformation, and connect the cycle to tectonic forces.', materials: 'Science notebook', reflectionPrompt: 'Have you ever seen a rock with visible layers? That could be sedimentary! What rocks have you noticed in Alberta?', masteryConfig: { passPercent: 80, maxRetries: 5, reteachEnabled: true, immediateCorrectiveFeedback: false } },
  blocks: [
    { id: 'ue-l3-learn-1', section: 'LEARN', blockType: 'VOCABULARY', order: 1, content: { terms: [{ term: 'Rock Cycle', definition: 'The continuous process of rocks transforming between igneous, sedimentary, and metamorphic.', example: 'Granite → weathering → sandstone → pressure → quartzite.' }, { term: 'Magma/Lava', definition: 'Molten rock. Underground = magma, on surface = lava. Cools to form igneous rock.', example: 'Hawaiian lava flows cool into basalt.' }, { term: 'Compaction', definition: 'When layers of sediment are squeezed together by weight above, forming sedimentary rock.', example: 'Sand compressed into sandstone over millions of years.' }, { term: 'Metamorphism', definition: 'Change in rock caused by extreme heat and pressure without melting.', example: 'Shale becomes slate; limestone becomes marble.' }] } },
    { id: 'ue-l3-learn-2', section: 'LEARN', blockType: 'VIDEO', order: 2, content: { url: 'https://www.youtube.com/embed/VByCLpj-I_s', title: 'The Rock Cycle', transcript: 'Video explaining rock cycle processes.' } },
    { id: 'ue-l3-learn-3', section: 'LEARN', blockType: 'TEXT', order: 3, content: { html: '<h3>🔄 Rock Cycle Processes</h3><ul><li>🌋 <strong>Melting → Cooling:</strong> Any rock can melt into magma. Cooled magma = <strong>igneous</strong> rock.</li><li>🌧️ <strong>Weathering → Compaction:</strong> Rocks break into sediment. Layers compress = <strong>sedimentary</strong> rock.</li><li>♨️ <strong>Heat + Pressure:</strong> Any rock deep underground can change into <strong>metamorphic</strong> rock.</li></ul><p>The rock cycle has <strong>no beginning or end</strong> — rocks can enter at any point and change into any type. Plate tectonics drives these processes by moving rock between surface and deep Earth.</p>' } },
    { id: 'ue-l3-prac-1', section: 'PRACTICE', blockType: 'MATCHING', order: 1, content: { instruction: 'Match each rock transformation to its process:', pairs: [{ left: 'Igneous → Sedimentary', right: 'Weathering & erosion → compaction' }, { left: 'Sedimentary → Metamorphic', right: 'Heat & pressure' }, { left: 'Metamorphic → Igneous', right: 'Melting → cooling' }, { left: 'Igneous → Metamorphic', right: 'Heat & pressure' }, { left: 'Any rock → Igneous', right: 'Melting into magma → cooling' }] } },
    { id: 'ue-l3-reflect-1', section: 'REFLECT', blockType: 'CONSTRUCTED_RESPONSE', order: 1, content: { prompt: 'Trace the journey of a granite rock (igneous) as it transforms through ALL three rock types. Describe every process.', minLength: 80, rubricHint: 'Traces granite through all 3 types. Names each process (weathering, compaction, heat/pressure, melting). Uses vocabulary.', teacherReviewRequired: false } },
  ],
  questions: [
    { id: 'ue-l3-q1', questionText: 'The rock cycle shows that:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Rocks never change', value: 'a' }, { label: 'Only igneous rocks exist', value: 'b' }, { label: 'Rocks continuously change from one type to another', value: 'c', correct: true }, { label: 'Rocks only form underground', value: 'd' }], correctAnswer: 'c', explanation: 'The rock cycle is a continuous loop — rocks can become any other type.', outcomeCode: 'SCI.7.E.1.3', difficulty: 1 },
    { id: 'ue-l3-q2', questionText: 'Sedimentary rock becomes metamorphic through:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Melting', value: 'a' }, { label: 'Weathering', value: 'b' }, { label: 'Heat and pressure', value: 'c', correct: true }, { label: 'Cooling', value: 'd' }], correctAnswer: 'c', explanation: 'Heat and pressure deep underground transform sedimentary rock into metamorphic.', outcomeCode: 'SCI.7.E.1.3', difficulty: 1 },
    { id: 'ue-l3-q3', questionText: 'Magma that cools underground forms:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Sedimentary rock', value: 'a' }, { label: 'Metamorphic rock', value: 'b' }, { label: 'Igneous rock with large crystals', value: 'c', correct: true }, { label: 'Fossils', value: 'd' }], correctAnswer: 'c', explanation: 'Slow cooling underground allows large crystals to form (like granite).', outcomeCode: 'SCI.7.E.1.3', difficulty: 1 },
    { id: 'ue-l3-q4', questionText: 'Compaction and cementation create:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Igneous rock', value: 'a' }, { label: 'Sedimentary rock', value: 'b', correct: true }, { label: 'Metamorphic rock', value: 'c' }, { label: 'Minerals', value: 'd' }], correctAnswer: 'b', explanation: 'Layers of sediment pressed and cemented together form sedimentary rock.', outcomeCode: 'SCI.7.E.1.3', difficulty: 1 },
    { id: 'ue-l3-q5', questionText: 'Plate tectonics is connected to the rock cycle because:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'It has nothing to do with rocks', value: 'a' }, { label: 'Plate movement moves rocks between surface and deep Earth', value: 'b', correct: true }, { label: 'Only igneous rocks are affected', value: 'c' }, { label: 'It only creates earthquakes', value: 'd' }], correctAnswer: 'b', explanation: 'Subduction drags rocks deep; volcanoes bring them up — powering the cycle.', outcomeCode: 'SCI.7.E.1.3', difficulty: 2 },
    { id: 'ue-l3-q6', questionText: 'Shale becomes slate through:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Melting', value: 'a' }, { label: 'Weathering', value: 'b' }, { label: 'Heat and pressure (metamorphism)', value: 'c', correct: true }, { label: 'Cooling', value: 'd' }], correctAnswer: 'c', explanation: 'Shale undergoes metamorphism (heat + pressure without melting) to become slate.', outcomeCode: 'SCI.7.E.1.3', difficulty: 1 },
    { id: 'ue-l3-q7', questionText: 'Lava cooling quickly on Earth\'s surface creates:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'Rock with large crystals', value: 'a' }, { label: 'Rock with small crystals or glassy texture', value: 'b', correct: true }, { label: 'Sedimentary rock', value: 'c' }, { label: 'Metamorphic rock', value: 'd' }], correctAnswer: 'b', explanation: 'Fast cooling gives crystals less time to grow — producing fine-grained rocks like basalt.', outcomeCode: 'SCI.7.E.1.3', difficulty: 2 },
    { id: 'ue-l3-q8', questionText: 'The rock cycle has:', questionType: 'MULTIPLE_CHOICE', options: [{ label: 'A definite start and end', value: 'a' }, { label: 'No beginning or end — it\'s continuous', value: 'b', correct: true }, { label: 'Only one direction', value: 'c' }, { label: 'Nothing to do with Earth\'s energy', value: 'd' }], correctAnswer: 'b', explanation: 'The rock cycle is ongoing — rocks can enter at any point and transform in any direction.', outcomeCode: 'SCI.7.E.1.3', difficulty: 1 },
  ],
};

async function main() {
  console.log('🌍 ═══ SCIENCE UNIT E: L1-L3 ═══');
  await seed('g7-sci-ue-l1', 'UE L1: Earth\'s Layers, Rocks & Minerals', L1);
  await seed('g7-sci-ue-l2', 'UE L2: Plate Tectonics', L2);
  await seed('g7-sci-ue-l3', 'UE L3: The Rock Cycle', L3);
  console.log('\n✅ Unit E L1-L3 complete!');
}
main().catch(console.error).finally(() => { pool.end(); });
