// ============================================
// ELA Child Skills — Hybrid Skill Tree
// ============================================
// Normalized child skills mapped to legacy parent codes.
// Legacy parents (ELA.6.1–.5) are preserved for backward compatibility.
// Children use the new normalized scheme (ELA.6.RC.*, ELA.6.VL.*, etc.)

import { ChildSkillDef } from './skill-data-children-science';

export const elaChildSkills: ChildSkillDef[] = [
  // ══════════════════════════════════════════
  // Parent: ELA.6.1 → Reading Comprehension (RC)
  // ══════════════════════════════════════════
  { id: 'skill-ela6-rc1', code: 'ELA.6.RC.1', parentCode: 'ELA.6.1', title: 'Comprehension & Inference', description: 'Independently read and demonstrate comprehension of increasingly complex texts by making inferences, distinguishing explicit from implicit information, and identifying author\'s purpose', iCanStatement: 'I can make inferences and distinguish between explicit and implicit information in a text', subject: 'ELA', gradeLevel: 6, strand: 'Reading & Comprehension', curriculumOutcomeCode: 'ELA.6.RC.1' },
  { id: 'skill-ela6-rc2', code: 'ELA.6.RC.2', parentCode: 'ELA.6.1', title: 'Text Connections', description: 'Make connections between texts and personal experiences (text-to-self), between multiple texts (text-to-text), and between texts and the broader world (text-to-world)', iCanStatement: 'I can make text-to-self, text-to-text, and text-to-world connections while reading', subject: 'ELA', gradeLevel: 6, strand: 'Reading & Comprehension', curriculumOutcomeCode: 'ELA.6.RC.2' },
  { id: 'skill-ela6-rc3', code: 'ELA.6.RC.3', parentCode: 'ELA.6.1', title: 'Comprehension Strategies', description: 'Apply comprehension strategies (predicting, questioning, inferring, summarizing, visualizing) to understand a variety of fiction and non-fiction texts', iCanStatement: 'I can use comprehension strategies like predicting, questioning, and summarizing to understand texts', subject: 'ELA', gradeLevel: 6, strand: 'Reading & Comprehension', curriculumOutcomeCode: 'ELA.6.RC.3' },
  { id: 'skill-ela6-rc4', code: 'ELA.6.RC.4', parentCode: 'ELA.6.1', title: 'Text Features', description: 'Identify and analyze how text structures and features (headings, subheadings, captions, glossaries, indexes) support comprehension of non-fiction texts', iCanStatement: 'I can use text features to find and organize information in non-fiction texts', subject: 'ELA', gradeLevel: 6, strand: 'Reading & Comprehension', curriculumOutcomeCode: 'ELA.6.RC.4' },

  // ══════════════════════════════════════════
  // Parent: ELA.6.2 → Vocabulary & Language (VL)
  // ══════════════════════════════════════════
  { id: 'skill-ela6-vl1', code: 'ELA.6.VL.1', parentCode: 'ELA.6.2', title: 'Word Origins & Morphology', description: 'Examine historical origins of words; research Greek/Latin roots; study FNMI and French origins; analyze how adding affixes changes meaning', iCanStatement: 'I can figure out the meaning of unknown words using context clues, word roots, prefixes, and suffixes', subject: 'ELA', gradeLevel: 6, strand: 'Vocabulary & Language', curriculumOutcomeCode: 'ELA.6.VL.1' },
  { id: 'skill-ela6-vl2', code: 'ELA.6.VL.2', parentCode: 'ELA.6.2', title: 'Figurative Language', description: 'Use similes, metaphors, and analogies to compare words or clarify meanings; analyze the meanings of words or phrases expressed figuratively', iCanStatement: 'I can recognize and explain figurative language including simile, metaphor, and personification', subject: 'ELA', gradeLevel: 6, strand: 'Vocabulary & Language', curriculumOutcomeCode: 'ELA.6.VL.2' },
  { id: 'skill-ela6-vl3', code: 'ELA.6.VL.3', parentCode: 'ELA.6.2', title: 'Word Study & Context', description: 'Categorize words and phrases of personal interest; analyze word parts and cross-check with context clues to determine the meaning of unknown words', iCanStatement: 'I can explain how a word\'s connotation affects meaning and choose words purposefully', subject: 'ELA', gradeLevel: 6, strand: 'Vocabulary & Language', curriculumOutcomeCode: 'ELA.6.VL.3' },
  { id: 'skill-ela6-vl4', code: 'ELA.6.VL.4', parentCode: 'ELA.6.2', title: 'Tier 2/3 Vocabulary', description: 'Apply tier 2 words across subjects to enhance precise communication; apply tier 3 words in subject-specific contexts', iCanStatement: 'I can use tier 2 academic words accurately across different subjects', subject: 'ELA', gradeLevel: 6, strand: 'Vocabulary & Language', curriculumOutcomeCode: 'ELA.6.VL.4' },

  // ══════════════════════════════════════════
  // Parent: ELA.6.3 → Text Forms & Literary Analysis (TF)
  // ══════════════════════════════════════════
  { id: 'skill-ela6-tf1', code: 'ELA.6.TF.1', parentCode: 'ELA.6.3', title: 'Fiction Elements & Plot', description: 'Examine elements of fiction including conflict, character types, plot structures (subplot, flashback, flash-forward, story within a story), and point of view', iCanStatement: 'I can identify and analyze theme, character, plot structure, and point of view in fiction', subject: 'ELA', gradeLevel: 6, strand: 'Literary Analysis', curriculumOutcomeCode: 'ELA.6.TF.1' },
  { id: 'skill-ela6-tf2', code: 'ELA.6.TF.2', parentCode: 'ELA.6.3', title: 'Fiction Sub-Genres', description: 'Examine mentor texts to deepen understandings of fiction sub-genres including comedy; categorize texts by sub-genre', iCanStatement: 'I can compare fiction sub-genres and explain what makes each one distinct', subject: 'ELA', gradeLevel: 6, strand: 'Literary Analysis', curriculumOutcomeCode: 'ELA.6.TF.2' },
  { id: 'skill-ela6-tf3', code: 'ELA.6.TF.3', parentCode: 'ELA.6.3', title: 'Non-Fiction Analysis', description: 'Investigate ways non-fiction texts can be organized to enhance factual information; confirm accuracy of information', iCanStatement: 'I can analyze non-fiction texts to identify fact vs opinion and evaluate reliability', subject: 'ELA', gradeLevel: 6, strand: 'Literary Analysis', curriculumOutcomeCode: 'ELA.6.TF.3' },
  { id: 'skill-ela6-tf4', code: 'ELA.6.TF.4', parentCode: 'ELA.6.3', title: 'Text Form & Structure', description: 'Analyze how text form and structure clarify information and support connecting with self, others, and the world', iCanStatement: 'I can explain how a text\'s form and structure influence how ideas are communicated', subject: 'ELA', gradeLevel: 6, strand: 'Literary Analysis', curriculumOutcomeCode: 'ELA.6.TF.4' },
  { id: 'skill-ela6-tf5', code: 'ELA.6.TF.5', parentCode: 'ELA.6.3', title: 'Poetry', description: 'Listen to, recite, or sing poetry; analyze figurative language; investigate poetic structures including ballads', iCanStatement: 'I can analyze and create poetry using different structures and figurative language', subject: 'ELA', gradeLevel: 6, strand: 'Literary Analysis', curriculumOutcomeCode: 'ELA.6.TF.5' },
  { id: 'skill-ela6-tf6', code: 'ELA.6.TF.6', parentCode: 'ELA.6.3', title: 'Drama', description: 'Listen to, read, or view dramatic works including comedy and tragedy; examine narrative structures in dramatic works', iCanStatement: 'I can analyze dramatic works and explain how they use narrative structures', subject: 'ELA', gradeLevel: 6, strand: 'Literary Analysis', curriculumOutcomeCode: 'ELA.6.TF.6' },
  { id: 'skill-ela6-tf7', code: 'ELA.6.TF.7', parentCode: 'ELA.6.3', title: 'Land Literacy (FNMI)', description: 'Describe how meaning is conveyed through human-made structures of land by First Nations, Métis, or Inuit and peoples from other parts of the world', iCanStatement: 'I can describe how land structures carry meaning for FNMI and other peoples', subject: 'ELA', gradeLevel: 6, strand: 'Literary Analysis', curriculumOutcomeCode: 'ELA.6.TF.7' },

  // ══════════════════════════════════════════
  // Parent: ELA.6.4 → Writing Craft (WC) + Conventions (CV)
  // ══════════════════════════════════════════
  { id: 'skill-ela6-wc1', code: 'ELA.6.WC.1', parentCode: 'ELA.6.4', title: 'Writing Process', description: 'Create written texts for a variety of audiences and purposes using writing processes (planning, drafting, revising, editing, publishing)', iCanStatement: 'I can plan, draft, revise, edit, and share written texts for specific audiences', subject: 'ELA', gradeLevel: 6, strand: 'Writing & Conventions', curriculumOutcomeCode: 'ELA.6.WC.1' },
  { id: 'skill-ela6-wc2', code: 'ELA.6.WC.2', parentCode: 'ELA.6.4', title: 'Multi-Paragraph Writing', description: 'Express personal ideas through multiple paragraphs; organize writing around clear ideas or positions supported by examples or relevant evidence', iCanStatement: 'I can write focused drafts with varied sentences and audience-appropriate detail', subject: 'ELA', gradeLevel: 6, strand: 'Writing & Conventions', curriculumOutcomeCode: 'ELA.6.WC.2' },
  { id: 'skill-ela6-wc3', code: 'ELA.6.WC.3', parentCode: 'ELA.6.4', title: 'Revision & Editing', description: 'Revise text for clarity, focus, and audience; edit writing for spelling, punctuation, and grammar', iCanStatement: 'I can revise my writing for clarity and read it aloud to check fluency', subject: 'ELA', gradeLevel: 6, strand: 'Writing & Conventions', curriculumOutcomeCode: 'ELA.6.WC.3' },
  { id: 'skill-ela6-wc4', code: 'ELA.6.WC.4', parentCode: 'ELA.6.4', title: 'Creative Expression', description: 'Apply creative-thinking processes; create narratives using setting, plot, character, suspense, figurative language, and dialogue; enhance personal style and voice', iCanStatement: 'I can use creative expression in my writing including voice, dialogue, and figurative language', subject: 'ELA', gradeLevel: 6, strand: 'Writing & Conventions', curriculumOutcomeCode: 'ELA.6.WC.4' },
  { id: 'skill-ela6-wc5', code: 'ELA.6.WC.5', parentCode: 'ELA.6.4', title: 'Publishing & Text Features', description: 'Express ideas using organizational structures that enhance writing; publish selected writing incorporating graphics, captions, charts', iCanStatement: 'I can organize and publish my writing with text features like graphics and captions', subject: 'ELA', gradeLevel: 6, strand: 'Writing & Conventions', curriculumOutcomeCode: 'ELA.6.WC.5' },
  { id: 'skill-ela6-wc6', code: 'ELA.6.WC.6', parentCode: 'ELA.6.4', title: 'Research & Ethical Info Use', description: 'Write to inform, explain, describe, or report; narrow research questions; support main idea with relevant facts from multiple sources; use information ethically', iCanStatement: 'I can research topics using multiple sources and present information ethically', subject: 'ELA', gradeLevel: 6, strand: 'Writing & Conventions', curriculumOutcomeCode: 'ELA.6.WC.6' },
  { id: 'skill-ela6-cv1', code: 'ELA.6.CV.1', parentCode: 'ELA.6.4', title: 'Capitalization', description: 'Apply capitalization appropriately in written communication; experiment with capitalization to create effects', iCanStatement: 'I can capitalize words correctly in different contexts', subject: 'ELA', gradeLevel: 6, strand: 'Writing & Conventions', curriculumOutcomeCode: 'ELA.6.CV.1' },
  { id: 'skill-ela6-cv2', code: 'ELA.6.CV.2', parentCode: 'ELA.6.4', title: 'Punctuation', description: 'Apply punctuation appropriately including colons; experiment with punctuation to create effects', iCanStatement: 'I can use commas, quotation marks, apostrophes, semicolons, and colons correctly', subject: 'ELA', gradeLevel: 6, strand: 'Writing & Conventions', curriculumOutcomeCode: 'ELA.6.CV.2' },
  { id: 'skill-ela6-cv3', code: 'ELA.6.CV.3', parentCode: 'ELA.6.4', title: 'Grammar & Sentence Structure', description: 'Maintain consistent use of tense; use subject-verb agreement; use independent and dependent clauses; differentiate between simple and compound sentences', iCanStatement: 'I can write complete sentences with correct grammar and varied sentence types', subject: 'ELA', gradeLevel: 6, strand: 'Writing & Conventions', curriculumOutcomeCode: 'ELA.6.CV.3' },
  { id: 'skill-ela6-cv4', code: 'ELA.6.CV.4', parentCode: 'ELA.6.4', title: 'Spelling & Derivations', description: 'Apply spelling patterns within and across known and unfamiliar words; apply knowledge of bases and affixes to spell words', iCanStatement: 'I can spell grade-level words correctly and use strategies for unfamiliar words', subject: 'ELA', gradeLevel: 6, strand: 'Writing & Conventions', curriculumOutcomeCode: 'ELA.6.CV.4' },

  // ══════════════════════════════════════════
  // Parent: ELA.6.5 → Oral Communication (OC) + Text Response (TR)
  // ══════════════════════════════════════════
  { id: 'skill-ela6-oc1', code: 'ELA.6.OC.1', parentCode: 'ELA.6.5', title: 'FNMI Communication Protocols', description: 'Reflect on how oral communication processes or protocols can enhance the quality of personal relationships; examine FNMI communication protocols', iCanStatement: 'I can listen actively and respond constructively to others\' ideas', subject: 'ELA', gradeLevel: 6, strand: 'Oral Communication', curriculumOutcomeCode: 'ELA.6.OC.1' },
  { id: 'skill-ela6-oc2', code: 'ELA.6.OC.2', parentCode: 'ELA.6.5', title: 'Verbal/Non-verbal/Paraverbal', description: 'Analyze the effectiveness of verbal, non-verbal, and paraverbal language used in oral communications', iCanStatement: 'I can present information clearly and confidently to an audience', subject: 'ELA', gradeLevel: 6, strand: 'Oral Communication', curriculumOutcomeCode: 'ELA.6.OC.2' },
  { id: 'skill-ela6-oc3', code: 'ELA.6.OC.3', parentCode: 'ELA.6.5', title: 'Collaborative Dialogue', description: 'Offer relevant information and logical reasoning to enhance collaborative dialogue; consider varied perspectives', iCanStatement: 'I can participate in collaborative discussions by contributing ideas and asking questions', subject: 'ELA', gradeLevel: 6, strand: 'Oral Communication', curriculumOutcomeCode: 'ELA.6.OC.3' },
  { id: 'skill-ela6-oc4', code: 'ELA.6.OC.4', parentCode: 'ELA.6.5', title: 'Presentations', description: 'Develop and deliver presentations for specific purposes and audiences; reflect on preparation, content, and delivery', iCanStatement: 'I can develop and deliver presentations for specific purposes and audiences', subject: 'ELA', gradeLevel: 6, strand: 'Oral Communication', curriculumOutcomeCode: 'ELA.6.OC.4' },
  { id: 'skill-ela6-oc5', code: 'ELA.6.OC.5', parentCode: 'ELA.6.5', title: 'Rhetoric & Public Speaking', description: 'Describe how effective speaking can impact daily life; examine speeches for their ability to persuade; apply elements of public speaking', iCanStatement: 'I can analyze speeches and apply elements of effective public speaking', subject: 'ELA', gradeLevel: 6, strand: 'Oral Communication', curriculumOutcomeCode: 'ELA.6.OC.5' },
  { id: 'skill-ela6-tr1', code: 'ELA.6.TR.1', parentCode: 'ELA.6.5', title: 'Summarize & Supporting Evidence', description: 'Respond to texts by summarizing main ideas and providing supporting evidence; synthesize ideas to confirm or expand understandings', iCanStatement: 'I can support my responses with evidence from the text', subject: 'ELA', gradeLevel: 6, strand: 'Oral Communication', curriculumOutcomeCode: 'ELA.6.TR.1' },
  { id: 'skill-ela6-tr2', code: 'ELA.6.TR.2', parentCode: 'ELA.6.5', title: 'Perspectives & Empathy', description: 'Connect perspectives reflected in texts to personal experiences; analyze factors that cause characters to change perspectives; develop empathy', iCanStatement: 'I can compare and contrast perspectives across multiple texts', subject: 'ELA', gradeLevel: 6, strand: 'Oral Communication', curriculumOutcomeCode: 'ELA.6.TR.2' },
  { id: 'skill-ela6-tr3', code: 'ELA.6.TR.3', parentCode: 'ELA.6.5', title: 'Context & Audience Influence', description: 'Analyze texts to determine contextual information; consider how information may be presented to influence an audience', iCanStatement: 'I can evaluate information by identifying bias and checking source reliability', subject: 'ELA', gradeLevel: 6, strand: 'Oral Communication', curriculumOutcomeCode: 'ELA.6.TR.3' },
];
