// ============================================
// Science Child Skills — Hybrid Skill Tree
// ============================================
// These are the assessable instructional targets.
// They power lesson tagging, question tagging, mastery evidence,
// retrieval targeting, review scheduling, and interleaving.
//
// Each child has a parentCode that maps to a parent skill.
// The seeder resolves parentCode → parentSkillId at runtime.

import { SkillDef } from './skill-data-parents';

export interface ChildSkillDef extends Omit<SkillDef, 'isCorePrerequisite'> {
  parentCode: string;
  iCanStatement: string; // Student-facing mastery label
}

export const scienceChildSkills: ChildSkillDef[] = [
  // ── Unit A: Interactions & Ecosystems ──

  // Parent: SCI.7.A.1
  { id: 'skill-sci7-a1-1', code: 'SCI.7.A.1.1', parentCode: 'SCI.7.A.1', title: 'Needs of Living Things', description: 'Illustrate how life-supporting environments meet the needs of living things for nutrients, energy sources, moisture, suitable habitat, and exchange of gases', iCanStatement: 'I can explain how environments meet the needs of living things', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.1.1' },
  { id: 'skill-sci7-a1-2', code: 'SCI.7.A.1.2', parentCode: 'SCI.7.A.1', title: 'Interactions & Interdependency', description: 'Describe examples of interaction and interdependency within an ecosystem', iCanStatement: 'I can describe how species depend on each other in an ecosystem', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.1.2' },
  { id: 'skill-sci7-a1-3', code: 'SCI.7.A.1.3', parentCode: 'SCI.7.A.1', title: 'Human Impacts', description: 'Identify examples of human impacts on ecosystems, and analyze the link between these impacts and human wants and needs', iCanStatement: 'I can explain how human activities affect ecosystems', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.1.3' },
  { id: 'skill-sci7-a1-4', code: 'SCI.7.A.1.4', parentCode: 'SCI.7.A.1', title: 'Decision Making', description: 'Analyze personal and public decisions that involve consideration of environmental impacts', iCanStatement: 'I can analyze decisions that affect the environment', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.1.4' },

  // Parent: SCI.7.A.2
  { id: 'skill-sci7-a2-1', code: 'SCI.7.A.2.1', parentCode: 'SCI.7.A.2', title: 'Biotic & Abiotic', description: 'Analyze an ecosystem to identify biotic and abiotic components, and describe interactions among these components', iCanStatement: 'I can identify living and non-living parts of an ecosystem', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.2.1' },
  { id: 'skill-sci7-a2-2', code: 'SCI.7.A.2.2', parentCode: 'SCI.7.A.2', title: 'Food Webs & Energy Flow', description: 'Analyze ecosystems to identify producers, consumers and decomposers; describe energy flow through food webs', iCanStatement: 'I can trace energy flow through a food web', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.2.2' },
  { id: 'skill-sci7-a2-3', code: 'SCI.7.A.2.3', parentCode: 'SCI.7.A.2', title: 'Nutrient Cycles', description: 'Describe the process of cycling carbon and water through an ecosystem', iCanStatement: 'I can describe how carbon and water cycle through ecosystems', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.2.3' },
  { id: 'skill-sci7-a2-4', code: 'SCI.7.A.2.4', parentCode: 'SCI.7.A.2', title: 'Pollutant Movement', description: 'Identify mechanisms by which pollutants enter and move through the environment and can become concentrated in organisms (bioaccumulation)', iCanStatement: 'I can explain how pollutants move through food chains', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.2.4' },

  // Parent: SCI.7.A.3
  { id: 'skill-sci7-a3-1', code: 'SCI.7.A.3.1', parentCode: 'SCI.7.A.3', title: 'Habitat Distribution', description: 'Investigate habitats, and describe and interpret distribution patterns of living things found in those habitats', iCanStatement: 'I can describe why organisms live where they do', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.3.1' },
  { id: 'skill-sci7-a3-2', code: 'SCI.7.A.3.2', parentCode: 'SCI.7.A.3', title: 'Population Change', description: 'Investigate and interpret evidence of interaction and change (population fluctuations, weather changes, food availability, introduction of new species)', iCanStatement: 'I can explain what causes populations to change', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.3.2' },
  { id: 'skill-sci7-a3-3', code: 'SCI.7.A.3.3', parentCode: 'SCI.7.A.3', title: 'Ecological Succession', description: 'Identify signs of ecological succession in local ecosystems', iCanStatement: 'I can identify signs that an ecosystem is changing over time', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.3.3' },

  // Parent: SCI.7.A.4
  { id: 'skill-sci7-a4-1', code: 'SCI.7.A.4.1', parentCode: 'SCI.7.A.4', title: 'Consequences', description: 'Identify intended and unintended consequences of human activities within local and global environments', iCanStatement: 'I can identify consequences of human activity on environments', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.4.1' },
  { id: 'skill-sci7-a4-2', code: 'SCI.7.A.4.2', parentCode: 'SCI.7.A.4', title: 'Science & Decisions', description: 'Describe and interpret examples of scientific investigations that serve to inform environmental decision making', iCanStatement: 'I can explain how science helps us make environmental decisions', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.4.2' },
  { id: 'skill-sci7-a4-3', code: 'SCI.7.A.4.3', parentCode: 'SCI.7.A.4', title: 'Limits of Science', description: 'Illustrate the limits of scientific and technological knowledge in making decisions about life-supporting environments', iCanStatement: 'I can explain why science alone cannot solve all environmental problems', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.4.3' },
  { id: 'skill-sci7-a4-4', code: 'SCI.7.A.4.4', parentCode: 'SCI.7.A.4', title: 'Local Issues', description: 'Analyze a local environmental issue based on evidence from a variety of sources, and identify possible actions and consequences', iCanStatement: 'I can analyze a local environmental issue using evidence', subject: 'Science', gradeLevel: 7, strand: 'Interactions & Ecosystems', curriculumOutcomeCode: 'SCI.7.A.4.4' },

  // ── Unit B: Plants for Food & Fibre ──

  // Parent: SCI.7.B.1
  { id: 'skill-sci7-b1-1', code: 'SCI.7.B.1.1', parentCode: 'SCI.7.B.1', title: 'Role of Plants', description: 'Illustrate and explain the essential role of plants within the environment', iCanStatement: 'I can explain why plants are essential to the environment', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.1.1' },
  { id: 'skill-sci7-b1-2', code: 'SCI.7.B.1.2', parentCode: 'SCI.7.B.1', title: 'Human Uses', description: 'Describe human uses of plants as sources of food and raw materials', iCanStatement: 'I can describe how humans use plants for food, materials, and medicine', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.1.2' },
  { id: 'skill-sci7-b1-3', code: 'SCI.7.B.1.3', parentCode: 'SCI.7.B.1', title: 'Land Use', description: 'Investigate trends in land use from natural to managed environments and describe changes', iCanStatement: 'I can describe how land use has changed from natural to managed', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.1.3' },
  { id: 'skill-sci7-b1-4', code: 'SCI.7.B.1.4', parentCode: 'SCI.7.B.1', title: 'Sustainability', description: 'Investigate practical problems in maintaining productive plants within sustainable environments', iCanStatement: 'I can explain challenges of growing plants sustainably', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.1.4' },

  // Parent: SCI.7.B.2
  { id: 'skill-sci7-b2-1', code: 'SCI.7.B.2.1', parentCode: 'SCI.7.B.2', title: 'Plant Structures', description: 'Describe the general structure and functions of seed plants (roots, stem, leaves, flower)', iCanStatement: 'I can describe how the parts of a plant work together', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.2.1' },
  { id: 'skill-sci7-b2-2', code: 'SCI.7.B.2.2', parentCode: 'SCI.7.B.2', title: 'Plant Adaptations', description: 'Investigate and interpret variations in plant structure, and relate these to different adaptations', iCanStatement: 'I can explain how plants are adapted to their environments', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.2.2' },
  { id: 'skill-sci7-b2-3', code: 'SCI.7.B.2.3', parentCode: 'SCI.7.B.2', title: 'Growing Conditions', description: 'Investigate and interpret variations in needs and tolerance for different growing conditions', iCanStatement: 'I can explain what plants need to grow in different conditions', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.2.3' },
  { id: 'skill-sci7-b2-4', code: 'SCI.7.B.2.4', parentCode: 'SCI.7.B.2', title: 'Plant Processes', description: 'Describe processes of diffusion, osmosis, conduction of fluids, transpiration, photosynthesis and gas exchange in plants', iCanStatement: 'I can explain photosynthesis, transpiration, and how plants move water', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.2.4' },
  { id: 'skill-sci7-b2-5', code: 'SCI.7.B.2.5', parentCode: 'SCI.7.B.2', title: 'Life Cycles', description: 'Describe life cycles of seed plants, and identify methods used to ensure germination, growth and reproduction', iCanStatement: 'I can describe the life cycle of a seed plant', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.2.5' },

  // Parent: SCI.7.B.3
  { id: 'skill-sci7-b3-1', code: 'SCI.7.B.3.1', parentCode: 'SCI.7.B.3', title: 'Yield Methods', description: 'Describe methods used to increase yields through modifying the environment and creating artificial environments', iCanStatement: 'I can describe ways people increase crop yields', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.3.1' },
  { id: 'skill-sci7-b3-2', code: 'SCI.7.B.3.2', parentCode: 'SCI.7.B.3', title: 'Soil Properties', description: 'Investigate and describe characteristics of different soils and their major components', iCanStatement: 'I can compare different soil types and explain their properties', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.3.2' },
  { id: 'skill-sci7-b3-3', code: 'SCI.7.B.3.3', parentCode: 'SCI.7.B.3', title: 'Soil Practices', description: 'Identify practices that may enhance or degrade soils', iCanStatement: 'I can identify what helps or harms soil quality', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.3.3' },
  { id: 'skill-sci7-b3-4', code: 'SCI.7.B.3.4', parentCode: 'SCI.7.B.3', title: 'Pest Control', description: 'Describe and interpret consequences of using herbicides, pesticides and biological controls', iCanStatement: 'I can evaluate different methods of pest control', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.3.4' },

  // Parent: SCI.7.B.4
  { id: 'skill-sci7-b4-1', code: 'SCI.7.B.4.1', parentCode: 'SCI.7.B.4', title: 'Selective Breeding', description: 'Investigate the development of plant varieties through selective breeding, and identify related needs and problems', iCanStatement: 'I can explain how selective breeding creates new plant varieties', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.4.1' },
  { id: 'skill-sci7-b4-2', code: 'SCI.7.B.4.2', parentCode: 'SCI.7.B.4', title: 'Management Consequences', description: 'Investigate intended and unintended consequences of environmental management practices (monoculture, pest management)', iCanStatement: 'I can explain consequences of farming practices like monoculture', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.4.2' },
  { id: 'skill-sci7-b4-3', code: 'SCI.7.B.4.3', parentCode: 'SCI.7.B.4', title: 'Sustainability Practices', description: 'Identify the effects of different practices on the sustainability of agriculture and environmental resources', iCanStatement: 'I can evaluate whether a farming practice is sustainable', subject: 'Science', gradeLevel: 7, strand: 'Plants for Food & Fibre', curriculumOutcomeCode: 'SCI.7.B.4.3' },

  // ── Unit C: Heat & Temperature ──

  // Parent: SCI.7.C.1
  { id: 'skill-sci7-c1-1', code: 'SCI.7.C.1.1', parentCode: 'SCI.7.C.1', title: 'Historical Heat Tech', description: 'Investigate and interpret examples of heat-related technologies and energy use in the past', iCanStatement: 'I can describe how people used heat technology in the past', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.1.1' },
  { id: 'skill-sci7-c1-2', code: 'SCI.7.C.1.2', parentCode: 'SCI.7.C.1', title: 'Purpose & Tech', description: 'Trace linkages between human purposes and the development of heat-related materials and technologies', iCanStatement: 'I can explain why humans developed heat technologies', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.1.2' },
  { id: 'skill-sci7-c1-3', code: 'SCI.7.C.1.3', parentCode: 'SCI.7.C.1', title: 'Heat Devices', description: 'Identify and explain uses of devices and systems to generate, transfer, control or remove thermal energy', iCanStatement: 'I can explain how devices generate and control heat', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.1.3' },
  { id: 'skill-sci7-c1-4', code: 'SCI.7.C.1.4', parentCode: 'SCI.7.C.1', title: 'Energy Choices', description: 'Identify examples of personal and societal choices in using energy resources and technology', iCanStatement: 'I can describe choices people make about energy use', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.1.4' },

  // Parent: SCI.7.C.2
  { id: 'skill-sci7-c2-1', code: 'SCI.7.C.2.1', parentCode: 'SCI.7.C.2', title: 'Heat Transmission', description: 'Compare heat transmission in different materials (conduction in solids, absorption of radiant heat)', iCanStatement: 'I can compare how different materials transmit heat', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.2.1' },
  { id: 'skill-sci7-c2-2', code: 'SCI.7.C.2.2', parentCode: 'SCI.7.C.2', title: 'Transfer Methods', description: 'Explain how heat is transmitted by conduction, convection and radiation in solids, liquids and gases', iCanStatement: 'I can explain conduction, convection, and radiation', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.2.2' },
  { id: 'skill-sci7-c2-3', code: 'SCI.7.C.2.3', parentCode: 'SCI.7.C.2', title: 'Particle Model', description: 'Describe the effect of heat on the motion of particles; explain changes of state using the particle model of matter', iCanStatement: 'I can use the particle model to explain heating and changes of state', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.2.3' },
  { id: 'skill-sci7-c2-4', code: 'SCI.7.C.2.4', parentCode: 'SCI.7.C.2', title: 'Heat vs Temperature', description: 'Distinguish between heat and temperature; explain temperature using kinetic energy and particle model', iCanStatement: 'I can explain the difference between heat and temperature', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.2.4' },
  { id: 'skill-sci7-c2-5', code: 'SCI.7.C.2.5', parentCode: 'SCI.7.C.2', title: 'Thermal Expansion', description: 'Investigate and describe effects of heating and cooling on volume, and identify applications (expansion joints)', iCanStatement: 'I can explain thermal expansion and give real-world examples', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.2.5' },

  // Parent: SCI.7.C.3
  { id: 'skill-sci7-c3-1', code: 'SCI.7.C.3.1', parentCode: 'SCI.7.C.3', title: 'Natural Heat Sources', description: 'Describe ways thermal energy is produced naturally (solar, combustion, living things, geothermal, composting)', iCanStatement: 'I can describe natural sources of thermal energy', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.3.1' },
  { id: 'skill-sci7-c3-2', code: 'SCI.7.C.3.2', parentCode: 'SCI.7.C.3', title: 'Solar Heating', description: 'Describe examples of passive and active solar heating and explain principles', iCanStatement: 'I can compare passive and active solar heating', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.3.2' },
  { id: 'skill-sci7-c3-3', code: 'SCI.7.C.3.3', parentCode: 'SCI.7.C.3', title: 'Insulation & Design', description: 'Compare and evaluate materials and designs that maximize or minimize heat energy transfer', iCanStatement: 'I can evaluate materials for insulation and heat control', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.3.3' },
  { id: 'skill-sci7-c3-4', code: 'SCI.7.C.3.4', parentCode: 'SCI.7.C.3', title: 'Temperature Devices', description: 'Explain the operation of technological devices that respond to temperature change (thermometers, bimetallic strips, thermostats)', iCanStatement: 'I can explain how thermometers and thermostats work', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.3.4' },
  { id: 'skill-sci7-c3-5', code: 'SCI.7.C.3.5', parentCode: 'SCI.7.C.3', title: 'Household Systems', description: 'Describe and interpret function of household devices for generating, transferring, controlling or removing thermal energy', iCanStatement: 'I can explain how home heating and cooling systems work', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.3.5' },
  { id: 'skill-sci7-c3-6', code: 'SCI.7.C.3.6', parentCode: 'SCI.7.C.3', title: 'Practical Problems', description: 'Investigate and describe practical problems in controlling and using thermal energy (heat losses, excess consumption, fire risk)', iCanStatement: 'I can describe problems with controlling heat in homes and industry', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.3.6' },

  // Parent: SCI.7.C.4
  { id: 'skill-sci7-c4-1', code: 'SCI.7.C.4.1', parentCode: 'SCI.7.C.4', title: 'Energy Sources', description: 'Identify and evaluate different sources of heat and environmental impacts of their use', iCanStatement: 'I can evaluate energy sources for environmental impact', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.4.1' },
  { id: 'skill-sci7-c4-2', code: 'SCI.7.C.4.2', parentCode: 'SCI.7.C.4', title: 'Energy Comparison', description: 'Compare energy consumption of alternative technologies for heat production and use', iCanStatement: 'I can compare how much energy different technologies use', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.4.2' },
  { id: 'skill-sci7-c4-3', code: 'SCI.7.C.4.3', parentCode: 'SCI.7.C.4', title: 'Conservation', description: 'Identify positive and negative consequences of energy use, and describe examples of energy conservation', iCanStatement: 'I can describe ways to conserve energy and why it matters', subject: 'Science', gradeLevel: 7, strand: 'Heat & Temperature', curriculumOutcomeCode: 'SCI.7.C.4.3' },

  // ── Unit D: Structures & Forces ──

  // Parent: SCI.7.D.1
  { id: 'skill-sci7-d1-1', code: 'SCI.7.D.1.1', parentCode: 'SCI.7.D.1', title: 'Classifying Structures', description: 'Recognize and classify structural forms and materials (frame, shell, frame-and-shell)', iCanStatement: 'I can classify structures as frame, shell, or frame-and-shell', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.1.1' },
  { id: 'skill-sci7-d1-2', code: 'SCI.7.D.1.2', parentCode: 'SCI.7.D.1', title: 'Design Variation', description: 'Interpret variation in design of structures sharing a common function, and evaluate effectiveness', iCanStatement: 'I can compare different designs for the same type of structure', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.1.2' },
  { id: 'skill-sci7-d1-3', code: 'SCI.7.D.1.3', parentCode: 'SCI.7.D.1', title: 'Cultural Structures', description: 'Describe and compare structures developed by different cultures and at different times', iCanStatement: 'I can compare structures from different cultures and time periods', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.1.3' },
  { id: 'skill-sci7-d1-4', code: 'SCI.7.D.1.4', parentCode: 'SCI.7.D.1', title: 'Natural Structures', description: 'Describe and interpret natural structures, including structures of living things and structures created by animals', iCanStatement: 'I can describe structures found in nature', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.1.4' },
  { id: 'skill-sci7-d1-5', code: 'SCI.7.D.1.5', parentCode: 'SCI.7.D.1', title: 'Failure Points', description: 'Identify points of failure and modes of failure in natural and built structures', iCanStatement: 'I can identify where and how structures can fail', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.1.5' },

  // Parent: SCI.7.D.2
  { id: 'skill-sci7-d2-1', code: 'SCI.7.D.2.1', parentCode: 'SCI.7.D.2', title: 'Measuring Forces', description: 'Recognize and use units of force and mass, and identify and measure forces and loads', iCanStatement: 'I can measure and describe forces acting on structures', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.2.1' },
  { id: 'skill-sci7-d2-2', code: 'SCI.7.D.2.2', parentCode: 'SCI.7.D.2', title: 'Friction', description: 'Identify examples of frictional forces and their use in structures', iCanStatement: 'I can explain how friction is used in structures', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.2.2' },
  { id: 'skill-sci7-d2-3', code: 'SCI.7.D.2.3', parentCode: 'SCI.7.D.2', title: 'Internal Forces', description: 'Identify tension, compression, shearing and bending forces within a structure; describe how these can cause failure', iCanStatement: 'I can identify tension, compression, shearing, and bending in a structure', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.2.3' },
  { id: 'skill-sci7-d2-4', code: 'SCI.7.D.2.4', parentCode: 'SCI.7.D.2', title: 'Material Properties', description: 'Analyze a design and identify properties of materials important to individual parts of the structure', iCanStatement: 'I can explain why specific materials are chosen for parts of a structure', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.2.4' },
  { id: 'skill-sci7-d2-5', code: 'SCI.7.D.2.5', parentCode: 'SCI.7.D.2', title: 'Stability', description: 'Infer how stability will be affected by changes in mass distribution and foundation design', iCanStatement: 'I can predict how changing mass or foundation affects stability', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.2.5' },

  // Parent: SCI.7.D.3
  { id: 'skill-sci7-d3-1', code: 'SCI.7.D.3.1', parentCode: 'SCI.7.D.3', title: 'Strength Testing', description: 'Devise and use methods of testing the strength and flexibility of materials', iCanStatement: 'I can design a test to compare material strength', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.3.1' },
  { id: 'skill-sci7-d3-2', code: 'SCI.7.D.3.2', parentCode: 'SCI.7.D.3', title: 'Joint Types', description: 'Identify where flexible or fixed joints are required, and evaluate appropriateness of different joint types', iCanStatement: 'I can explain where fixed and flexible joints are needed', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.3.2' },
  { id: 'skill-sci7-d3-3', code: 'SCI.7.D.3.3', parentCode: 'SCI.7.D.3', title: 'Material Comparison', description: 'Compare structural properties of different materials, including natural and synthetic', iCanStatement: 'I can compare natural and synthetic materials for building', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.3.3' },
  { id: 'skill-sci7-d3-4', code: 'SCI.7.D.3.4', parentCode: 'SCI.7.D.3', title: 'Biological Materials', description: 'Investigate the role of different materials found in plant and animal structures (bone, cartilage, ligaments, plant layers)', iCanStatement: 'I can describe structural materials in plants and animals', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.3.4' },

  // Parent: SCI.7.D.4
  { id: 'skill-sci7-d4-1', code: 'SCI.7.D.4.1', parentCode: 'SCI.7.D.4', title: 'Strengthening Methods', description: 'Demonstrate methods to increase strength through design changes (corrugation, lamination, shape changes, fastening methods)', iCanStatement: 'I can demonstrate ways to make structures stronger', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.4.1' },
  { id: 'skill-sci7-d4-2', code: 'SCI.7.D.4.2', parentCode: 'SCI.7.D.4', title: 'Environmental Factors', description: 'Identify environmental factors affecting stability and safety, and describe how they are accounted for', iCanStatement: 'I can explain how weather and environment affect structural safety', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.4.2' },
  { id: 'skill-sci7-d4-3', code: 'SCI.7.D.4.3', parentCode: 'SCI.7.D.4', title: 'Design Evaluation', description: 'Analyze and evaluate a technological design on the basis of costs, benefits, safety and environmental impact', iCanStatement: 'I can evaluate a design based on cost, safety, and environmental impact', subject: 'Science', gradeLevel: 7, strand: 'Structures & Forces', curriculumOutcomeCode: 'SCI.7.D.4.3' },

  // ── Unit E: Planet Earth ──

  // Parent: SCI.7.E.1
  { id: 'skill-sci7-e1-1', code: 'SCI.7.E.1.1', parentCode: 'SCI.7.E.1', title: 'Surface Change', description: 'Investigate and interpret evidence that Earth\'s surface undergoes both gradual and sudden change', iCanStatement: 'I can describe gradual and sudden changes to Earth\'s surface', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.1.1' },
  { id: 'skill-sci7-e1-2', code: 'SCI.7.E.1.2', parentCode: 'SCI.7.E.1', title: 'Earth\'s Layers', description: 'Interpret models that show a layered structure for Earth\'s interior; describe evidence for such models', iCanStatement: 'I can describe the layers of Earth and the evidence for them', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.1.2' },
  { id: 'skill-sci7-e1-3', code: 'SCI.7.E.1.3', parentCode: 'SCI.7.E.1', title: 'Earth Science Tools', description: 'Identify and explain the purpose of different tools and techniques used in the study of Earth', iCanStatement: 'I can explain tools scientists use to study Earth', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.1.3' },
  { id: 'skill-sci7-e1-4', code: 'SCI.7.E.1.4', parentCode: 'SCI.7.E.1', title: 'Rock/Mineral Description', description: 'Explain the need for common terminology in describing rocks and minerals, and apply suitable terms', iCanStatement: 'I can describe rocks and minerals using proper scientific terms', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.1.4' },

  // Parent: SCI.7.E.2
  { id: 'skill-sci7-e2-1', code: 'SCI.7.E.2.1', parentCode: 'SCI.7.E.2', title: 'Rocks vs Minerals', description: 'Distinguish between rocks and minerals', iCanStatement: 'I can explain the difference between rocks and minerals', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.2.1' },
  { id: 'skill-sci7-e2-2', code: 'SCI.7.E.2.2', parentCode: 'SCI.7.E.2', title: 'Rock Classification', description: 'Describe characteristics of igneous, sedimentary and metamorphic rocks, and describe evidence of their formation', iCanStatement: 'I can classify rocks and explain how each type forms', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.2.2' },
  { id: 'skill-sci7-e2-3', code: 'SCI.7.E.2.3', parentCode: 'SCI.7.E.2', title: 'Local Rocks', description: 'Describe local rocks and sediments, and interpret ways they may have formed', iCanStatement: 'I can describe rocks found locally and explain how they formed', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.2.3' },
  { id: 'skill-sci7-e2-4', code: 'SCI.7.E.2.4', parentCode: 'SCI.7.E.2', title: 'Weathering & Erosion', description: 'Investigate and interpret examples of weathering, erosion and sedimentation', iCanStatement: 'I can explain weathering, erosion, and sedimentation', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.2.4' },

  // Parent: SCI.7.E.3
  { id: 'skill-sci7-e3-1', code: 'SCI.7.E.3.1', parentCode: 'SCI.7.E.3', title: 'Mountain Formation', description: 'Investigate and interpret patterns in the structure and distribution of mountain formations', iCanStatement: 'I can describe how mountains form and where they are found', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.3.1' },
  { id: 'skill-sci7-e3-2', code: 'SCI.7.E.3.2', parentCode: 'SCI.7.E.3', title: 'Fold & Fault Mountains', description: 'Interpret the structure and development of fold and fault mountains', iCanStatement: 'I can compare fold and fault mountains', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.3.2' },
  { id: 'skill-sci7-e3-3', code: 'SCI.7.E.3.3', parentCode: 'SCI.7.E.3', title: 'Plate Tectonics', description: 'Describe evidence for crustal movement and identify patterns (earthquakes, volcanic action along Pacific Rim, plate movement)', iCanStatement: 'I can describe evidence that Earth\'s plates are moving', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.3.3' },
  { id: 'skill-sci7-e3-4', code: 'SCI.7.E.3.4', parentCode: 'SCI.7.E.3', title: 'Gradual Change', description: 'Identify examples of gradual/incremental change, and predict results over extended periods of time', iCanStatement: 'I can predict what happens when geological changes continue over time', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.3.4' },

  // Parent: SCI.7.E.4
  { id: 'skill-sci7-e4-1', code: 'SCI.7.E.4.1', parentCode: 'SCI.7.E.4', title: 'Fossil Types', description: 'Describe the nature of different kinds of fossils, and identify hypotheses about their formation', iCanStatement: 'I can describe different types of fossils and how they form', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.4.1' },
  { id: 'skill-sci7-e4-2', code: 'SCI.7.E.4.2', parentCode: 'SCI.7.E.4', title: 'Fossil Interpretation', description: 'Explain and apply methods used to interpret fossils (reconstruction, comparison to living things)', iCanStatement: 'I can explain how scientists interpret fossils', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.4.2' },
  { id: 'skill-sci7-e4-3', code: 'SCI.7.E.4.3', parentCode: 'SCI.7.E.4', title: 'Geological Time', description: 'Describe patterns in the appearance of different life forms as indicated by the fossil record; construct and interpret a geological time scale', iCanStatement: 'I can use the fossil record to understand Earth\'s history', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.4.3' },
  { id: 'skill-sci7-e4-4', code: 'SCI.7.E.4.4', parentCode: 'SCI.7.E.4', title: 'Evidence & Uncertainty', description: 'Identify uncertainties in interpreting individual fossil evidence; explain the role of accumulated evidence in developing accepted scientific ideas', iCanStatement: 'I can explain why many fossils together are more reliable than one', subject: 'Science', gradeLevel: 7, strand: 'Planet Earth', curriculumOutcomeCode: 'SCI.7.E.4.4' },
];
